esl/MongooseIM

doc/modules/mod_stream_management.md
src/config/mongoose_config_parser_toml.erl
src/config/mongoose_config_validator_toml.erl
src/mod_stream_management.erl
test/config_parser_SUITE.erl

This PR removes `int_or_infinity_or_atom` option type from TOML config spec. The idea is to introduce additional boolean options to the config of the module. 
|  Before                                | After               |
| -------------------------- | -------------- |
| buffer_max = "no_buffer"  | buffer = false  |
| ack_freq = "never"             | ack = false      |

Remove int_or_inf_or_atom from mod_stream_management

---

src/config/mongoose_config_parser_toml.erl
src/config/mongoose_config_spec.erl
src/config/mongoose_config_validator_toml.erl
test/config_parser_SUITE.erl

The goal of this pull request is to:
- Extend the declarative spec to the whole config tree.
- Remove code that handled the imperative part of the parser.
- Simplify and optimize declarative parsing.
See commit messages for details.

TOML config cleanup - parser simplification

---

.github/workflows/ci.yml
rebar.config
rebar.config.script
tools/gh-actions-configure-preset.sh
tools/test_runner/presets_to_dbs.erl

Basic implementation of GH CI workflow for MongooseIM.
Implements CI testing similar to Travis except report uploading, this functionality will be added in the following PR.

Gh actions

---

big_tests/tests/mod_http_upload_SUITE.erl
doc/migrations/4.0.1_4.x.x.md
doc/modules/mod_http_upload.md
include/mongoose_ns.hrl
src/http_upload/mod_http_upload.erl

This PR removes support for the outdated 0.2.5 specification of HTTP File Upload.

Remove HTTP File Upload 0.2.5 support

---

.github/workflows/ci.yml
rebar.config
rebar.config.script

Use [Coveralls GH action](https://github.com/marketplace/actions/coveralls-github-action) for reporting coverage

report lcov file to coveralls using gh action

---

big_tests/tests/accounts_SUITE.erl
include/mongoose_config_spec.hrl
src/config/mongoose_config_parser_toml.erl
src/config/mongoose_config_spec.erl
src/config/mongoose_config_validator.erl
src/gen_mod.erl
src/mod_register.erl

Add missing type specs, comments and exports.
Also: remove some obsolete code.
See the commit messages for more information.

TOML config cleanup: type specs

---

big_tests/tests/ejabberdctl_SUITE.erl
big_tests/tests/mod_http_upload_SUITE.erl
big_tests/tests/mongoose_helper.erl

Big tests are checking if minio should be running, that is, if the preset in the ct specs says it should, and not if it is _actually_ running. And the way this was checked wasn't correct, the keyword to check for was changed and also some nesting was added, during the toml epic.
We can see that minio wasn't being tested here: https://circleci-mim-results.s3.eu-central-1.amazonaws.com/branch/master/42088/internal_mnesia.23.0.3-1/big/ct_run.test@default-85d626ba-85ec-463e-892e-37d6f216922c.2021-01-05_15.00.49/big_tests.tests.mod_http_upload_SUITE.logs/run.2021-01-05_15.08.13/suite.log.html

Correctly detect minio in CI

---

src/config/mongoose_config_validator.erl
src/event_pusher/mod_event_pusher_push.erl
src/mod_vcard.erl
test/config_parser_SUITE.erl

In case of `@HOSTS@` wildcard usage, there were validation errors reported. For more details, please see [MIM-1330](https://erlangsolutions.atlassian.net/browse/MIM-1330) description.

validate mod_event_pusher_push.virtual_pubsub_hosts properly

---

big_tests/tests/muc_light_SUITE.erl
src/admin_extra/service_admin_extra_roster.erl
src/ejabberd_c2s.erl
src/ejabberd_sm.erl
src/mam/mod_mam_utils.erl
src/metrics/mongoose_metrics_hooks.erl
src/mod_commands.erl
src/mod_disco.erl
src/mod_last.erl
src/mod_privacy.erl
src/mod_roster.erl
src/mod_shared_roster_ldap.erl
src/mongoose_hooks.erl
src/muc_light/mod_muc_light.erl
src/pubsub/mod_pubsub.erl
test/roster_SUITE.erl

This PR, like several others I've done in the past, aim to reduce the redundancy of stringprepping again and again different blocks of a jid all over the MIM code, and instead taking advantage of the `jid` record. More type-safety, less code, and a tiny slightly bit more performance.

Less stringprepping in roster hooks

---

doc/authentication-methods/anonymous.md

Fixed the name of the ``protocol`` variable in the example.

Fixed the name of the protocol variable

---

src/ejabberd_c2s.erl
src/ejabberd_sm.erl
src/metrics/mongoose_metrics_hooks.erl
src/mod_last.erl
src/mod_privacy.erl
src/mongoose_hooks.erl
src/mongoose_privacy.erl
test/privacy_SUITE.erl

A few less stringprepps in another module that comes up on every once in a while, like on opening sessions, when the privacy lists is queried the first time (then it's cached) for a message delivery, or when the privacy list is modified and then broadcasted.

Less stringprepping in privacy modules

---

big_tests/tests/mongoose_cassandra_SUITE.erl
src/cassandra/mongoose_cassandra_worker.erl
src/wpool/mongoose_wpool_cassandra.erl

Three main changes:
- The fix in MongooseIM makes it reconnect after the cqerl supervision (sub)tree including `cqerl_cluster` is restarted.
- The fix in cqerl (https://github.com/esl/cqerl/pull/8) prevents escalation of the crash and bringing down the whole node when the fix mentioned above enabled cqerl to reconnect many times in a row and the network remains unreliable.
- The fix in tests prevents them from failing randomly (even though it's less likely after the two fixes listed above). Now the failures are simulated in a more predictable way. It's still possible to run the full stress test manually.

Fix the Cassandra connections

---

doc/modules/mod_pubsub.md

This PR adds to the documentation some hits on how to setup OMEMO with PEP pubsub plugin.

doc update config access_model for PEP plugin

---

doc/migrations/4.0.1_4.x.x.md
mkdocs.yml

Basically I went through the output of `git diff master toml-config doc/` command and wrote it down, already excluding couple of type alignments. I also added missing link to the newest migration guide's chapter.

Update migration guide with TOML changes

---

big_tests/tests/ejabberdctl_SUITE.erl
src/ejabberd_c2s.erl
src/mongoose_hooks.erl
src/offline/mod_offline.erl
src/offline/mod_offline_chatmarkers.erl
src/offline/mod_offline_mnesia.erl
src/offline/mod_offline_rdbms.erl
src/offline/mod_offline_riak.erl

get_max_user_messages gets its parameters from the #offline_msg record,
which when created took the jid:to_lus/1 from a full jid, hence its
arguments are already stringprepped.
resend_offline_message_packet will forward the server parameter down the
stack up to the timestamp function, which needs the stringprepped
parameter, but this was stringprepped already before, so this processed
version can be passed instead.

Reduce stringprepping in mod_offline

---

src/ejabberd_c2s.erl
src/mam/mod_mam_utils.erl
src/mod_muc_room.erl
src/mod_privacy.erl
src/offline/mod_offline.erl

And `list_to_integer` or `binary_to_integer` have the same API, throwing the same errors and so on.
Also, `try-of-catch` is better than `case catch`, errors are clearer and it doesn't build a stacktrace.

integer_to_binary/2 is available since OTP17

---

doc/modules/mod_pubsub.md

I added one concise table documenting these options and their default values for each node plugin.

document default_node_config options

---

doc/modules/mod_mam.md
src/mam/mod_mam.erl

The warning has been removed altogether with its mention in documentation.

Remove archive_groupchats warning

---

big_tests/tests/mam_SUITE.erl
src/metrics/mongoose_metrics_definitions.hrl
src/metrics/mongoose_metrics_mam_hooks.erl

This PR addresses "modMucMamFlushed is updated but not created".
* modMucMamFlushed is created now

Fix modMucMamFlushed metric

---

src/auth/ejabberd_auth_http.erl
src/mod_muc_room.erl

http_uri was deprecated since OTP21. This is in general to clean-up code for ejabberd_auth_http.

Simplify some deprecated uses of http_uri

---

priv/azuresql.sql
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
rebar.lock
src/mod_privacy_rdbms.erl

This PR addresses "Deadlock occurring in MySQL from time to time in the prepared queries branch".
* Insert only a diff of privacy_data
* Retry privacy update transaction
* Update eodbc. Return bigints as numbers, not binaries now
* Also NUMERIC type is overkill in pgsql, it's at least 10 bytes variable encoding. New installations would benefit from a smaller data type.

Insert only a diff of privacy_data

---

mkdocs.yml

Like all sites, it needs a sitemap, and mkdocs needs the site_url to be given to build so.
Also, add some links to general pages like our dockerhub or github.

Mkdocs needs this to build the sitemap

---

src/offline/mod_offline_rdbms.erl
src/rdbms/rdbms_queries.erl
src/rdbms/rdbms_queries_mssql.erl

Prepared queries for mod_offline - rebased

---

big_tests/tests/connect_SUITE.erl
big_tests/tests/mongoose_helper.erl
big_tests/tests/muc_light_SUITE.erl
big_tests/tests/push_SUITE.erl
big_tests/tests/push_integration_SUITE.erl
src/admin_extra/service_admin_extra_sessions.erl
src/auth/ejabberd_auth_anonymous.erl
src/ejabberd_c2s.erl
src/ejabberd_gen_sm.erl
src/ejabberd_local.erl
src/ejabberd_sm.erl
src/ejabberd_sm_mnesia.erl
src/ejabberd_sm_redis.erl
src/event_pusher/mod_event_pusher_push.erl
src/mod_carboncopy.erl
src/mod_commands.erl
src/mongoose_client_api/mongoose_client_api_sse.erl
src/mongoose_session.erl
src/pubsub/mod_pubsub.erl
test/ejabberd_sm_SUITE.erl

Plenty of explanations and profiling and details and whatnot, in the commit messages 😁

Mongoose session

---

big_tests/tests/rdbms_SUITE.erl
src/rdbms/mongoose_rdbms_odbc.erl

This PR addresses allows to specify arguments from the multiple table. Which is needed for pubsub queries.
* Allow to pass `table.column` as a field name into the `prepare` call
* `column` still works.

Allow to specify arguments from the multiple tables for prepared queries

---

big_tests/tests/sm_SUITE.erl
src/ejabberd_c2s.erl
src/p1_fsm_old.erl
test/ejabberd_c2s_SUITE.erl

This PR addresses #2933.
It contains a fix to the issue as well as a related testcase.

Fix handover crash

---

big_tests/tests/accounts_SUITE.erl
big_tests/tests/rdbms_SUITE.erl
doc/advanced-configuration/auth.md
doc/advanced-configuration/general.md
doc/advanced-configuration/host_config.md
doc/authentication-methods/rdbms.md
doc/migrations/4.1.0_4.x.x.md
mkdocs.yml
src/auth/ejabberd_auth_internal.erl
src/auth/ejabberd_auth_rdbms.erl
src/config/mongoose_config_spec.erl
src/rdbms/mongoose_rdbms.erl
src/rdbms/rdbms_queries.erl
test/config_parser_SUITE.erl
test/config_parser_SUITE_data/miscellaneous.options
test/config_parser_SUITE_data/miscellaneous.toml

**This PR includes the following changes:**
- Replace all plain queries in `ejabberd_auth_rdbms.erl` with their prepared equivalents
- Refactor code as it is already changed
- Improve and test Erlang-shell-only utilities for obtaining list and number of registered users.
- New tests revealed the following issues:
- There were bugs in the corresponding functions in `ejabberd_auth_internal`- this is fixed now.
- Prepared statements with `LIKE` were missing escaping. This is fixed and tested now.
- The option `pgsql_users_number_estimate` was working for Postgres, but for MySQL an estimate was used by default, causing confusion and test failures. This is unified now and a new option `auth.rdbms.users_number_estimate` supports both Postgres and MySQL.
**Out of scope:**
- Change error handling …

Use prepared queries in ejabberd_auth_rdbms

---

doc/modules/mod_offline.md

This PR adds documentation for mod_offline, regarding the option store_groupchat_messages. [#2879](https://github.com/esl/MongooseIM/issues/2879)

[skip ci] Reference about store_groupchat_messages option in mod_offline added

---

include/mod_muc_light.hrl

In case I’m mixing up some type, I’m sharing this error dialyzer should have complained about:
https://github.com/esl/MongooseIM/blob/3ce2355ed0dc8b217dacdbfaf9e1cc1ce30177f0/src/muc_light/mod_muc_light_codec.erl#L32 says that encode’s first parameter is a muc_light_encode_request()
https://github.com/esl/MongooseIM/blob/3ce2355ed0dc8b217dacdbfaf9e1cc1ce30177f0/src/muc_light/mod_muc_light_codec_modern.erl#L50 the first head of encode in the actual implementation takes a {msg(), aff_users()}
https://github.com/esl/MongooseIM/blob/3ce2355ed0dc8b217dacdbfaf9e1cc1ce30177f0/include/mod_muc_light.hrl#L115-L122 does not define {msg(), aff_users()} as any of the possibilities for this type
This arose when writing a custom codec for a client that would modify a couple of requests but just forward …

[OS] fix type declaration

---

big_tests/tests/push_SUITE.erl
src/event_pusher/mod_event_pusher_push.erl
src/event_pusher/mod_event_pusher_push_mnesia.erl
src/event_pusher/mod_event_pusher_push_rdbms.erl

- Introduce prepared queries
- Update the backend API to remove an unused case that would require a separate prepared query

Use prepared queries in mod_event_pusher_push

---

big_tests/tests/service_domain_db_SUITE.erl
doc/developers-guide/domain_management.md
rel/files/mongooseim.toml
src/admin_extra/service_admin_extra.erl
src/domain/mongoose_domain_api.erl
src/domain/mongoose_domain_h.erl
src/domain/mongoose_domain_handler.erl
src/domain/service_admin_extra_domain.erl

This PR addresses "REST and CLI API for domains".
* insert_domain
* enable/disable
* select_domain over REST.

REST and CLI API for domains

---

big_tests/tests/dynamic_domains_pm_SUITE.erl
big_tests/tests/service_domain_db_SUITE.erl
doc/developers-guide/domain_management.md
rel/files/mongooseim.toml
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
src/domain/mongoose_domain_api.erl
src/domain/mongoose_domain_core.erl
src/domain/mongoose_domain_db_cleaner.erl
src/domain/mongoose_domain_loader.erl
src/domain/mongoose_domain_sql.erl
src/domain/mongoose_domain_utils.erl
src/domain/service_domain_db.erl
src/ejabberd_app.erl
src/ejabberd_config.erl
test/mongoose_domain_core_SUITE.erl

this PR introduces the next changes:
- solves race condition at `check_for_updates/2` function
- eliminates the need to restart `mongoose_domain_core` if `service_domain_db` crashes on initial loading
- eliminates the need to halt the node if `service_domain_db` goes out of sync
- ensures proper init of the mongoose_domain_core
- introduces 2 dummy test suites for the future development.
Also now it's possible to implement "hooks" for domains adding/removing if there's such a need

Multi tenancy init

---

big_tests/default.spec
big_tests/tests/domain_isolation_SUITE.erl
doc/modules/mod_domain_isolation.md
mkdocs.yml
src/config/mongoose_config_spec.erl
src/mod_domain_isolation.erl

This PR addresses isolation.
* isolation

Added mod_domain_isolation

---

src/mod_smart_markers.erl

This module was doing one non-optimal check, that is, it was checking if the user has rights to access a room using the `can_access_room` hook, _before_ checking that the message being processed actually has any marker to begin with. This is non-optimal, as `can_access_room` requires another hook call and a DB query to verify affiliations, and will usually return true unless misbehaving clients, while checking whether a message has actually any marker is an in-place check with higher chances to return false.

Improve pipeline for mod_smart_markers

---

big_tests/default.spec
big_tests/tests/domain_isolation_SUITE.erl
doc/modules/mod_domain_isolation.md
mkdocs.yml
src/config/mongoose_config_spec.erl
src/mod_domain_isolation.erl

it's a variant of https://github.com/esl/MongooseIM/pull/3064 but to master.
* there is no code or solution for multi-tenancy.
* the code would probably change, once we add dynamic domains.
* could be merged to master, but multi-tenancy would have to be rebased on master to continue work on this feature. Routing would also have to be working.

Host isolation

---

big_tests/default.spec

This PR addresses "it's not running on CI"
* running on CI now

Enable service_domain_db_SUITE for CI

---

doc/user-guide/Features-and-supported-standards.md

There was no mention of retraction nor inbox in this page.

Update documentation about supported extensions and features

---

src/inbox/mod_inbox_utils.erl
src/mam/mod_mam_utils.erl
src/mod_smart_markers.erl
src/mongoose_chat_markers.erl

Currently checking if a stanza contains a chat markers is triplicated in
three different modules. Implement all of it in mod_smart_markers and
make the other two places simply call this one.

Unify checks for chat markers

---

src/mam/mod_mam.erl

* Set archive_groupchats to false by default
* **Syntax:** boolean
* **Default:** `false` (yes, now)
* **Example:** `modules.mod_mam_meta.pm.archive_groupchats = true`

Set archive_groupchats to false by default

---

doc/developers-guide/Testing-MongooseIM.md
doc/index.md
doc/operation-and-maintenance/known-issues.md

This PR updates the documentation of test runner. The main changes include correct examples (using existing presets) and rewording the ODBC parts in the documentation. It also includes fixes for small issues I noticed while reading the docs.

Update test runner documentation

---

big_tests/tests/bosh_SUITE.erl
big_tests/tests/ejabberdctl_SUITE.erl
big_tests/tests/mod_global_distrib_SUITE.erl
big_tests/tests/sm_SUITE.erl
src/ejabberd_admin.erl
src/ejabberd_c2s.erl
src/gen_mod.erl
src/mod_bosh.erl
src/mod_bosh_socket.erl
src/mod_extdisco.erl
src/mod_stream_management.erl
src/mod_vcard_ldap.erl
src/mongoose_cluster_id.erl
src/rdbms/mongoose_rdbms.erl
src/stream_management/stream_management_stale_h.erl

Remove all occurences of `?MYNAME` except stream errors and the initial value in `ejabberd_c2s`. These are the only expected uses of this macro.

Remove ?MYNAME macros

---

big_tests/default.spec
big_tests/tests/domain_removal_SUITE.erl
priv/mysql.sql
src/auth/ejabberd_auth.erl
src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_rdbms_arch.erl
src/mongoose_hooks.erl

This PR addresses "Ensure efficient indexing and removal of persistent data by domain name".
MAM already have proper indexes in the mam_server_user table. We should just LEFT JOIN it. OK, we can't LEFT JOIN in DELETEs. But we can use `WHERE IN` instead.
* remove_domain/3 handler for MAM/MUC MAM.
* nobody runs this hook in this PR. @DenysGonchar will code that part.
* a tip in schema. Because we use the same table to track MAM archive IDs for both MAM and MUC MAM.

Add remove_domain handler for MAM

---

src/inbox/mod_inbox.erl
src/inbox/mod_inbox_muc.erl
src/inbox/mod_inbox_muclight.erl
src/inbox/mod_inbox_one2one.erl
src/inbox/mod_inbox_utils.erl

There could be more important data in this, like the mam-id, that we
might prefer rather than the message's attribute id.
For MUC, well, inbox with regular muc is not the most common use case.

Pass the accumulator along

---

big_tests/default.spec
big_tests/tests/mam_send_message_SUITE.erl
big_tests/tests/mam_send_message_SUITE_data/mam_send_message_example.erl
doc/modules/mod_mam.md
src/mam/mam_decoder.erl
src/mam/mam_iq.erl
src/mam/mam_lookup.erl
src/mam/mam_send_message.erl
src/mam/mod_mam.erl
src/mam/mod_mam_cassandra_arch.erl
src/mam/mod_mam_elasticsearch_arch.erl
src/mam/mod_mam_meta.erl
src/mam/mod_mam_muc.erl
src/mam/mod_mam_muc_cassandra_arch.erl
src/mam/mod_mam_muc_elasticsearch_arch.erl
src/mam/mod_mam_params.erl
src/mam/mod_mam_rdbms_arch.erl
src/mam/mod_mam_riak_timed_arch_yz.erl
src/mam/mod_mam_utils.erl
src/mod_commands.erl
src/mod_muc_room.erl
src/mongoose_client_api/mongoose_client_api_messages.erl
src/mongoose_client_api/mongoose_client_api_rooms_messages.erl
src/xml.erl

This PR addresses "what if we use map, will tests still pass?"
* map
* Allow to override mod_mam_utils:send_message/4 callback. 
* Pass caller_jid into lookup_messages hook as a part of params (useful for MUC MAM).
As a dev, I want to extract some extra fields from MAM (or during MAM lookup).
I am currently only allowed to return message-id, source-jid and stanza packet. But sometimes I need to return more fields, so I can format them later (to build a proper forwarded message). Maps allows to attach some meta info to each message.
_Also, it's really hard to track what is what in 3 fields tuple :trollface:_

Use map for mod_mam:message_row()

---

src/mongoose_cluster_id.erl

Prepare queries in mongoose_cluster_id

---

big_tests/tests/domain_removal_SUITE.erl
doc/developers-guide/Testing-MongooseIM.md
doc/migrations/4.2.0_4.3.0.md
mkdocs.yml
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
src/domain/mongoose_domain_api.erl
src/inbox/mod_inbox.erl
src/inbox/mod_inbox_rdbms.erl
src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_rdbms_arch.erl
src/mongoose_hooks.erl
src/mongooseim.erl
tools/open-test-database-shell.sh

This PR addresses "tenant removal epic".
* Reorder indexes in the inbox table
* Add a prepared query for removal
* Add host_type type

Handle remove_domain in mod_inbox

---

doc/rest-api/Administration-backend.md
doc/rest-api/Client-frontend.md

My first front-end PR. The Swagger part was obscured on the left side and could not even be scrolled to see the content. Affected places: https://esl.github.io/MongooseDocs/latest/rest-api/Client-frontend/ and https://esl.github.io/MongooseDocs/latest/rest-api/Administration-backend/. I think this should be the fix but I have no idea what I am doing.
Before:
After:

Fix Swagger docs rendering

---

.circleci/config.yml
big_tests/dynamic_domains.config
big_tests/dynamic_domains.spec
big_tests/run_common_test.erl
big_tests/src/ct_mongoose_hook.erl
big_tests/tests/domain_helper.erl
big_tests/tests/dynamic_domains_pm_SUITE.erl
tools/test-runner-complete.sh
tools/test-runner.sh
tools/test_runner/selected-tests-to-test-spec.sh

Initial test configuration for dynamic domains. The plan is to extend them in subsequent PR's.
See individual commits for more details.

Multi tenancy tests

---

big_tests/tests/domain_isolation_SUITE.erl
src/mod_domain_isolation.erl

This PR addresses MIM-1395.
* Fixes "Domain isolation causes an infinite loop".
* A test.
**Description:**
Step to reproduce:
Enable domain isolation for two domains, e.g.: `localhost`, `localhost.bis`
Send any message between the two domains, e.g. from `alice@localhost.bis` (A) to `bob@localhost` (B)
`mod_domain_isolation` handles message from A to B by sending an error reply from B to A, which in turn results in an error reply etc... error elements are accumulating forever in the packet (actually: until the hook timeout passes), eating memory and time.
Add test to `domain_isolation_SUITE`, fix the issue by not bouncing the error message back.

Prevent infinite loop when domain isolation is on on both domains

---

CHANGELOG.md
doc/developers-guide/hooks_description.md
doc/developers-guide/mod_muc_light_developers_guide.md
doc/migrations/4.2.0_4.3.0.md
src/mam/mod_mam_muc.erl
src/mod_muc.erl
src/mod_muc_room.erl
src/mongoose_hooks.erl
src/muc_light/mod_muc_light_codec_legacy.erl
src/muc_light/mod_muc_light_codec_modern.erl

This PR addresses "some tech debt".
* room_event_data is now map (was a proplist)
* Remove room_send_packet hook

Room EventData is map now

---

src/domain/mongoose_domain_core.erl
src/domain/mongoose_subdomain_core.erl
src/domain/mongoose_subdomain_utils.erl
src/mongoose_hooks.erl
test/mongoose_subdomain_core_SUITE.erl

Initial implementation of subdomains management subsystem.
Note that it detects but doesn't solve subdomains or domain/subdomain names collisions:
for more information see comment in the corresponding test cases:
* [subdomain names collissions](https://github.com/esl/MongooseIM/pull/3116/files#diff-903da31c5ca7d77683c10c87e043e34f12c76d0bb06e1ff86317b96092f8ea54R293)
* [domain/subdomain names collisions](https://github.com/esl/MongooseIM/pull/3116/files#diff-903da31c5ca7d77683c10c87e043e34f12c76d0bb06e1ff86317b96092f8ea54R386)

adding mongoose_subdomain_core

---

src/mongoose_cluster_id.erl

This PR addresses "MIM-1396 Prepared query in mongoose_cluster_id causes errors on startup"
* Don't insert, if not needed.
* Insert only when we generate a new ID.
Basically, we implement "select and just use it. If not found, create new and insert" logic.
It is a bit less robust: 
- if a cluster got started without RDBMS, but after it got a new node with RDBMS, we would not get an update in DB.
- but this use case is _pretty weird_
There is still a race condition possible, when we try to insert, but someone has already inserted a ClusterID. we could handle it and retry, but it makes logic less clean. And I am pretty sure it's a rare case when two nodes go live for the first time. Could be avoided by adding retries, but nothing bad would happen anyway (we would …

Don't set cluster_id if not needed

---

src/logger/mongoose_log_filter.erl

This PR addresses ugly stacktraces.
Before:
```
"stacktrace":"ets:lookup/[prepared_statements,auth_list_users]:0 mongoose_rdbms:query_name_to_string/1:225 mongoose_rdbms:execute_successfully/3:217 ejabberd_auth_rdbms:get_vh_registered_users/2:206 lists:flatmap/2:1250 lists:flatmap/2:1250 rpc:'-handle_call_call/6-fun-0-'/5:197"
```
After:
```
"stacktrace_args":"[prepared_statements,auth_list_users]",
"stacktrace":"ets:lookup/2:0 mongoose_rdbms:query_name_to_string/1:225 mongoose_rdbms:execute_successfully/3:217 ejabberd_auth_rdbms:get_vh_registered_users/2:206 lists:flatmap/2:1250 lists:flatmap/2:1250 rpc:'-handle_call_call/6-fun-0-'/5:197"
```

Format stacktrace args properly

---

src/domain/mongoose_lazy_routing.erl
src/domain/mongoose_subdomain_core.erl
test/mongoose_domain_core_SUITE.erl
test/mongoose_lazy_routing_SUITE.erl
test/mongoose_subdomain_core_SUITE.erl

This PR introduces unit tests for mongoose_lazy_routing module

unit tests for mongoose_lazy_routing module

---

big_tests/dynamic_domains.spec
rel/mim1.vars-toml.config
src/ejabberd_app.erl
src/mod_carboncopy.erl

This PR introduces dynamic domains support for mod_carboncopy.
Service discovery doesn't work for dynamic domains (as mod_disco doesn't support it yet), but still works correctly for statically configured domains
for a local testing you can use this command:
```
test-runner.sh --skip-small-tests --skip-cover --spec dynamic_domains.spec --preset pgsql_mnesia -- carboncopy
test-runner.sh --skip-small-tests --skip-cover --preset pgsql_mnesia -- carboncopy
```

adding multitenancy support for mod_carboncopy

---

big_tests/src/ct_mongoose_log_hook.erl
big_tests/src/ct_tty_hook.erl

When I was testing suites, I was generating errors from all/0 and groups/0 callbacks. And CT works really strange and not informative.
Two problems:
- it does not print the error, just "location is unknown"
- it passes that error to CT hooks, and that's why this PR.
Before CTH was crashing when handling SUITE crash during the init:
```
*** CT 2021-05-24 12:32:43.391 *** Suite Hook
Call to CTH failed: error:{{test_case_failed,
{open_file_failed,'test@Mikhails-MacBook-Pro',
"/Users/mikhailuvarov/erlang/esl/MongooseIM/big_tests/ct_report/ct_run.test@Mikhails-MacBook-Pro.2021-05-24_12.32.42/undefined/../../../mongooseim@localhost.log.html",
{error,enoent}}},
[{ct_mongoose_log_hook,ensure_initialized,2,
[{file,
"/Users/mikhailuvarov/erlang/esl/MongooseIM/big_tests/src/ct_mongoose_log_hook.erl"} …
```

Safer CT hook error handling

---

doc/authentication-methods/dummy.md
rel/mim1.vars-toml.config
src/auth/ejabberd_auth_dummy.erl
src/config/mongoose_config_spec.erl
test/auth_dummy_SUITE.erl

This makes the delays configurable, which by default are too long and that's something that can be noticed in CI.

Make dummy auth delays configurable

---

big_tests/src/ct_mongoose_hook.erl

This PR removes the `Suite ... finished dirty.` messages appearing when running the tests. They appeared because of a failing common test hook.
This hook is a leftover from when `mod_carboncopy` was using its own mnesia table. See commit e0b1d9d8746e2de3ef137a21772f4bacf20d85f3 in which it was removed for details. It is safe to remove this hook, as other hooks like `check_sessions` or `check_registered_users` together with using escalus fresh stories should already ensure that no user configuration leaks between the test groups.

Remove check_carboncopy CT hook

---

big_tests/tests/metrics_api_SUITE.erl
big_tests/tests/metrics_helper.erl
doc/migrations/4.2.0_4.3.0.md
doc/operation-and-maintenance/MongooseIM-metrics.md
doc/rest-api/Metrics-backend.md
src/ejabberd_local.erl
src/global_distrib/mod_global_distrib_utils.erl
src/metrics/mongoose_api_metrics.erl
src/metrics/mongoose_metrics.erl
src/metrics/mongoose_metrics_hooks.erl
test/carbon_cache_server.erl
test/mongooseim_metrics_SUITE.erl
tools/summarise-ct-results

This PR updates the metrics to use host types instead of hosts. There are still some places left that use host types and should be updated when the modules are updated (for example `mongoose_wpool_rdbms`).
Because the host type may be any string, the spaces `" "` are changed to underscores `"_"` in the metrics modules in a simple manner on every call. Because of that, when calling functions like `mongoose_metrics:get_metric_value/1`, which expect the _metric name_, one has to provide a sanitized name - this is not needed when calling the metrics API expecting host types.
There are also some small fixes, like a bugfix for a test suite that occurred seemingly only on my computer, and getting rid of the "Failing the test due failed rerun groups" message that was printed even if the tests …

Metrics per host type

---

src/ejabberd_local.erl
src/mongoose_hooks.erl

It was registered per domain, not per host type, what caused exometer to create one metric per domain.
It can be removed as 'ejabberd_local' was the only module handling it.
This unexpected type of stanza shouldn't be handled by modules as well.

Remove 'local_send_to_resource' hook

---

big_tests/tests/rest_client_SUITE.erl
big_tests/tests/rest_helper.erl
doc/operation-and-maintenance/Logging-fields.md
rel/files/app.config
src/domain/mongoose_lazy_routing.erl
src/ejabberd_c2s.erl
src/ejabberd_local.erl
src/ejabberd_s2s_out.erl
src/ejabberd_sm.erl
src/logger/mongoose_log_filter.erl
src/logger/mongoose_record_pp.erl
src/mam/mod_mam_muc.erl
src/mod_muc.erl
src/mod_muc_room.erl
src/mongoose_api_common.erl
src/mongoose_client_api/mongoose_client_api.erl
src/mongoose_client_api/mongoose_client_api_rooms.erl

This PR addresses "We have too many places that can return 503 error".
* Add text to errors, so we can know where it comes from.
* REST API logs the errors. We are not concerned with cleaning up creds from cowboy_req in this PR, it's a big task on its own and can be done in one log filter.
* debugging helpers for gen_mod.

Better error reporting

---

big_tests/dynamic_domains.spec
big_tests/tests/mam_SUITE.erl

This should fix the tests using metrics. Because we allow any string to be a host type, and in testing its `<<"test type">>` one has to ensure that the metrics are checked against a sanitised host type prefix, because metrics cannot contain spaces in their names.

Fix metrics in mam suite

---

big_tests/tests/gdpr_SUITE.erl
doc/migrations/4.2.0_4.3.0.md
src/inbox/mod_inbox.erl
src/mam/mod_mam.erl
src/mam/mod_mam_muc.erl
src/mod_muc.erl
src/mod_muc_room.erl
src/mod_private.erl
src/mod_roster.erl
src/mod_vcard.erl
src/mongoose_hooks.erl
src/offline/mod_offline.erl
src/pubsub/mod_pubsub.erl

This will be needed in order to correctly query the correct pools where is needed. We can see that it was already done for `mod_mam` in #3123, which in-place queries the host_type. We can just use it as a parameter to the function.

GDPR get data takes host type as a parameter

---

big_tests/tests/carboncopy_SUITE.erl

fixing race condition in unavailable_resources_dont_get_carbons test case of carboncopy_SUITE

fixing race condition in carboncopy_SUITE

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/dynamic_modules.erl
big_tests/tests/offline_stub_SUITE.erl
src/ejabberd_sm.erl
src/offline/mod_offline_stub.erl
test/ejabberd_sm_SUITE.erl

mod_offline_stub doesn't require any conversion to support dynamic domains. Just added some simple offline_stub_SUITE to ensure that it's working correctly w/o any changes.

adding offline_stub_SUITE

---

big_tests/dynamic_domains.spec
big_tests/tests/ct_helper.erl
big_tests/tests/sm_SUITE.erl
rel/mim1.vars-toml.config
src/ejabberd_c2s.erl
src/mod_stream_management.erl

This PR introduces dynamic domains support for `mod_stream_management`.
Some tests in sm_SUITE are disabled for dynamic domains because they depend on another modules that do not support dynamic domains yet.

updating mod_stream_management module

---

big_tests/tests/adhoc_SUITE.erl
big_tests/tests/disco_and_caps_SUITE.erl
big_tests/tests/mod_http_upload_SUITE.erl
big_tests/tests/offline_SUITE.erl
big_tests/tests/pep_SUITE.erl
big_tests/tests/pubsub_SUITE.erl
src/http_upload/mod_http_upload.erl
src/mod_adhoc.erl
src/mod_disco.erl
src/mongoose_disco.erl
src/mongoose_hooks.erl
src/offline/mod_offline.erl
src/pubsub/mod_pubsub.erl

Further preparation and cleanup of disco-related code.
Some functionality was untested (and even broken). Tests added, bugs fixed. This will help assure that after introducing host types everything is still working.
Planned for the next PR: introduce host types to `mod_disco` and all the hooks to support dynamic domains.
Skipped for now: unit tests for `mongoose_disco`. It is a simple module covered by multiple functional tests.
Not sure: more pubsub tests. It's a deep rabbit hole, so I needed to stop at some point. A few lines I touched remain untested, just as before.

Further mod_disco rework

---

big_tests/dynamic_domains.spec
big_tests/tests/rest_client_SUITE.erl
big_tests/tests/rest_helper.erl
src/mongoose_client_api/mongoose_client_api_messages.erl
src/mongoose_client_api/mongoose_client_api_rooms.erl
src/muc_light/mod_muc_light_commands.erl
src/muc_light/mod_muc_light_utils.erl

This PR addresses "Multitenancy for the Client REST API for MAM and MUC-light".
* rooms and messages endpoints
* roster not included, because roster does not support MT yet.
* We also log more in rest_helper in tests now (similar to the way we log stanzas).

Multitenancy for the Client REST API for MAM and MUC-light

---

doc/migrations/4.2.0_4.3.0.md
src/mam/ejabberd_gen_mam_archive.erl
src/mam/mam_decoder.erl
src/mam/mam_lookup_sql.erl
src/mam/mod_mam_cassandra_arch.erl
src/mam/mod_mam_elasticsearch_arch.erl
src/mam/mod_mam_muc_cassandra_arch.erl
src/mam/mod_mam_muc_elasticsearch_arch.erl
src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
src/mam/mod_mam_rdbms_arch.erl
src/mam/mod_mam_rdbms_async_pool_writer.erl
src/mam/mod_mam_riak_timed_arch_yz.erl
src/mam/mod_mam_utils.erl
src/mongoose_hooks.erl

This PR addresses "more pretty".
* Use host_type/HostType names in mod_mam_rdbms_arch/mod_mam_muc_rdbms_arch
* No functional changes (it's just about variable names)
* mod_mam_rdbms_prefs is untouched to make the PR small (ok, it also fixes GDPR message extraction)

Use host_type/HostType names in mod_mam_rdbms_arch/mod_mam_muc_rdbms_arch

---

big_tests/dynamic_domains.spec
src/mam/mod_mam.erl
src/mam/mod_mam_muc.erl
src/mam/mod_mam_utils.erl

This PR addresses MIM-1412 "not working disco for mod_mam".
* just use HostType.

Fix disco for MAM MIM-1412

---

big_tests/dynamic_domains.spec
src/ejabberd_c2s.erl
src/ejabberd_c2s_state.erl
src/mod_amp.erl
src/mod_caps.erl
src/mod_csi.erl
src/mod_register.erl
src/mod_stream_management.erl
src/mongoose_hooks.erl
src/pubsub/mod_pubsub.erl

Add support for dynamic domains to mod_caps.
Hooks handled or triggered by `mod_caps` are refactored according to the following rule:
- If c2s state or `mongoose_acc:t()` is passed as an argument, do not add host type to the hook and handlers.
- Otherwise, add host type to the hook and its handlers.
Some lines remain untested as they are quite difficult to hit in the tests. Caps are mostly needed for PEP and it does not support dynamic domains, so the coverage for `dynamic_domains` is even lower. It could be increased in the future with the conversion of PubSub and PEP.
See individual commits for more details.

Support dynamic domains in mod_caps

---

src/gen_mod.erl
src/mam/mod_mam.erl
src/mam/mod_mam_cache_user.erl
src/mam/mod_mam_rdbms_prefs.erl
src/mam/mod_mam_rdbms_user.erl
src/mam/mod_mam_utils.erl

This PR addresses MIM-1412 (kinda)
* prefs/user and utils modules use HostType variable and host_type type where needed.
* no functional changes.
* ah, and I've refactored hooks there.

Use HostType variable in mod_mam_rdbms_prefs/user

---

big_tests/dynamic_domains.spec
doc/modules/mod_domain_isolation.md
include/mongoose.hrl
src/gen_mod.erl
src/mam/mod_mam.erl
src/mam/mod_mam_cache_user.erl
src/mam/mod_mam_meta.erl
src/mam/mod_mam_mnesia_prefs.erl
src/mam/mod_mam_muc.erl
src/mam/mod_mam_muc_cache_user.erl
src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
src/mam/mod_mam_rdbms_arch.erl
src/mam/mod_mam_rdbms_async_pool_writer.erl
src/mam/mod_mam_rdbms_prefs.erl
src/mam/mod_mam_rdbms_user.erl
src/mod_commands.erl
src/mod_domain_isolation.erl
src/mod_muc.erl
src/mod_muc_log.erl
src/muc_light/mod_muc_light.erl
src/muc_light/mod_muc_light_commands.erl
test/gen_mod_SUITE.erl
test/mod_global_distrib_SUITE.erl
test/mongoose_service_SUITE.erl
test/mongoose_wpool_SUITE.erl
test/roster_SUITE.erl
tools/travis-setup-db.sh

this PR introduces the following changes:
1. add verification of `dynamic_domains` feature support at gen_mod
2. Add dynamic_domains support declaration for the modules tested with dynamic_domains.spec. Please note that these modules are dynamically enabled during the integration tests, there is no warranty that they are fully converted and tested properly with the current dynamic_domains.spec. We must create a follow-up ticket to recheck all of that modules, here is the list of them:
* mod_mam
* mod_mam_cache_user
* mod_mam_meta - this one is not tested, but it's required for a normal MAM configuration through the TOML file
* mod_mam_mnesia_prefs
* mod_mam_muc
* mod_mam_muc_cache_user
* mod_mam_muc_rdbms_arch
* mod_mam_muc_rdbms_async_pool_writer
* mod_mam_rdbms_arch
* …

cleaning up some issues with multitenancy support

---

big_tests/tests/rest_helper.erl
big_tests/tests/service_domain_db_SUITE.erl
doc/developers-guide/domain_management.md
rel/files/mongooseim.toml
src/config/mongoose_config_spec.erl
src/domain/mongoose_domain_handler.erl
test/config_parser_SUITE.erl

Add auth for mongoose_domain_handler

---

src/mongoose_users.erl

As the tables are created per-host-type, a table can have more than one
domain within, and so there's no unique key properly defined,
considering that the same namepart can be used in two different domains,
and the same domain contains many nameparts.
The cache was broken because, as a set where the domain is the key, inserted users would always override previous. If namepart is the key, two users with the same namepart in different domains would also override each other. So the whole pair needed to be made the key as a 1-tuple.

Fix user cache

---

big_tests/tests/inbox_SUITE.erl
big_tests/tests/inbox_helper.erl
big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl
src/inbox/mod_inbox.erl
src/mam/mod_mam_utils.erl

If inbox is nothing more than a low-cost summary of mam, we can expect inbox to store pretty much what is stored in mam, and nothing else.
This is currently not true, as inbox is not taking into account `no-store` hints for example, and it is storing body-less messages, like for example it would store carbon copies.
Additionally, make both take the `<store>` hint as enforcing storage.

Mam inbox unification

---

doc/developers-guide/domain_management.md

mkdocs-material loses the table of contents if we start from the top index (single #).

Fix rendering of domain management docs, note table of contents

---

src/mod_cache_users.erl

TL;DR: it looks like in more or less all cases, the ets implementation is 2.8x slower and uses 1.6x more memory.
---
Using the following scenarios:
```elixir
:mod_cache_users.start("ets", [ttl: 1, number_of_segments: 5])
:mod_cache_users_pt.start("pt", [ttl: 1, number_of_segments: 5])
Benchee.run(
%{
"ets cache" => fn num -> :bench_erl.fun_ets(num) end,
"persistent term" => fn num -> :bench_erl.fun_pt(num) end
},
inputs: %{
"some" => :rand.uniform(4096)
},
parallel: 12,
time: 10,
memory_time: 10
)
:mod_cache_users.stop("ets")
:mod_cache_users_pt.stop("pt")
:mod_cache_users.start("ets", [ttl: 60, number_of_segments: 5])
:mod_cache_users_pt.start("pt", [ttl: 60, number_of_segments: 5])
Benchee.run(
%{
"ets cache" => fn num -> :bench_erl.fun_ets(num) end,
"persistent term" => fn num -> …
```

Reimplement cache using persistent_terms

---

.circleci/config.yml
tools/circle-publish-github-comment.sh

This PR brings back commenter.
* It post a comment, just like this one: https://github.com/esl/MongooseIM/pull/3173#issuecomment-874059779

Publish a comment from CircleCI to Github

---

big_tests/dynamic_domains.spec
big_tests/test.config
big_tests/tests/amp_big_SUITE.erl
big_tests/tests/ejabberdctl_SUITE.erl
big_tests/tests/gdpr_SUITE.erl
big_tests/tests/mam_helper.erl
big_tests/tests/mongoose_helper.erl
big_tests/tests/offline_SUITE.erl
rel/files/mongooseim.toml
rel/mim1.vars-toml.config
rel/vars-toml.config.in
src/ejabberd_admin.erl
src/ejabberd_c2s.erl
src/mongoose_hooks.erl
src/offline/mod_offline.erl
src/offline/mod_offline_mnesia.erl
src/offline/mod_offline_rdbms.erl
src/offline/mod_offline_riak.erl

**Main changes:**
- Support host types in `mod_offline` and its backends.
- Enable offline-related tests for dynamic domains.
- Change module templating to make the template and the resulting config readable at the same time. There are some whitespace manipulations, but they don't change the functionality. This can be still improved, I have ideas (e.g. mustache lists), but it would be a separate story. Right now the resulting config file always has a single empty line separating module sections. All module templates should be unified in the near future.
**Side changes:**
- Unify the implementation of `remove_*_messages` to only remove messages for the domain that was provided. The backends were behaving inconsistently before (it worked as expected only for Riak).
**Not included in this …

Support dynamic domains in mod_offline

---

src/auth/ejabberd_auth_ldap.erl
src/auth/mongoose_gen_auth.erl
src/eldap_pool.erl
src/eldap_utils.erl
src/mod_shared_roster_ldap.erl
src/mod_vcard_ldap.erl

Also, made some ldap types in eldap_utils
```erlang
===> Analyzing 405 files with "/Users/mikhailuvarov/erlang/esl/MongooseIM/_build/default/rebar3_22.3.4.10_plt"...                                                                                  [14/2732]
src/auth/ejabberd_auth_ldap.erl
150: Invalid type specification for function ejabberd_auth_ldap:set_password/4. The success typing is (binary(),binary(),binary(),_) -> {'error','user_not_found'}
155: The inferred return type of set_password/4 ({'error','user_not_found'}) has nothing in common with 'ok' | {'error','invalid_jid' | 'not_allowed'}, which is the expected return type for the callback
of mongoose_gen_auth behaviour
159: The variable DN can never match since previous clauses completely covered the type 'false'
168: Function …
```

Tag should be an atom, it's binary in ldap types

---

big_tests/tests/service_domain_db_SUITE.erl

For parallel tests, init/end should be done per group, not per TC.

Fix randomly failing service_domain_db tests

---

src/event_pusher/mod_event_pusher_push.erl
src/event_pusher/mod_event_pusher_sns.erl
src/mod_push_service_mongoosepush.erl
src/wpool/mongoose_wpool.erl
src/wpool/mongoose_wpool_cassandra.erl
src/wpool/mongoose_wpool_elastic.erl
src/wpool/mongoose_wpool_generic.erl
src/wpool/mongoose_wpool_http.erl
src/wpool/mongoose_wpool_ldap.erl
src/wpool/mongoose_wpool_mgr.erl
src/wpool/mongoose_wpool_rdbms.erl
src/wpool/mongoose_wpool_redis.erl
src/wpool/mongoose_wpool_riak.erl
src/wpool/mongoose_wpool_sup.erl
src/wpool/mongoose_wpool_type_sup.erl
test/mongoose_wpool_SUITE.erl

* HostTypes in wpool
* Better specs in wpool

Hosttypyfy wpool

---

src/mod_amp.erl
src/mongoose_hooks.erl
src/mongoose_local_delivery.erl

Fix error:
```erlang
when=2021-07-13T11:29:28.721597+00:00 level=error what=hook_failed reason="{function_clause,[{mongoose_acc,host_type, 
[ok],[{file,/src/mongoose_acc.erl"},{line,161}]},{mongoose_metrics_hooks,xmpp_stanza_dropped,4,[{file,"/src/metrics  
/mongoose_metrics_hooks.erl"},{line,131}]},{safely,apply,3,[{file,"/src/safely.erl"},{line,19}]},  
{ejabberd_hooks,run_hook,4,
```

Put accumulator instead of atom ok for xmpp_stanza_dropped

---

big_tests/dynamic_domains.spec
big_tests/test.config
big_tests/tests/ejabberdctl_SUITE.erl
big_tests/tests/mongoose_helper.erl
big_tests/tests/rdbms_SUITE.erl
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
rel/files/mongooseim.toml
rel/mim1.vars-toml.config
rel/vars-toml.config.in
src/admin_extra/service_admin_extra_accounts.erl
src/admin_extra/service_admin_extra_last.erl
src/auth/ejabberd_auth_external.erl
src/mod_last.erl
src/mod_last_mnesia.erl
src/mod_last_rdbms.erl
src/mod_last_riak.erl
src/mongoose_hooks.erl
test/mongoose_cleanup_SUITE.erl

Add support for dynamic domains to `mod_last` and its backends.
Side changes:
- Fix error handling when updating last info. Previously the error tuple would result in `badmatch` as `Acc` was expected in both hooks.
This PR does **not** include:
- Supporting `remove_domain`.
- Migration guide.
Both tasks will be done separately.

Support dynamic domains in mod_last

---

big_tests/dynamic_domains.config
big_tests/dynamic_domains.spec
big_tests/test.config
big_tests/tests/mod_blocking_SUITE.erl
big_tests/tests/mod_global_distrib_SUITE.erl
rel/files/mongooseim.toml
rel/mim1.vars-toml.config
rel/vars-toml.config.in
src/mod_blocking.erl

This PR makes `mod_blocking` depend on `mod_privacy` on the `gen_mod` level, as it should have been. As such, `mod_privacy` is removed from the default config, as the privacy xep is deprecated, and instead the blocking xep is promoted: hence we leave `mod_blocking` enabled.
I also had a few changes to the test suite. Users are created fresh, and we don't need websockets users to test blocking functionality, so `geralt` and `carol` are changed in favour of `kate` and `john`. Also a few sleeps are removed, and some answers are now asserted. This makes the test-suite run in half the time, and also asserts more tightly.

Implement multitenancy for mod_blocking

---

big_tests/rebar.config
rebar.config

Related also to https://github.com/esl/MongooseIM/pull/2760,

Remove rebar_faster_deps

---

doc/developers-guide/domain_management.md
src/domain/mongoose_domain_sql.erl
src/domain/service_domain_db.erl

This PR addresses MIM-1451
* Use global as a default pool
* Make this option configurable

Make pool_name configurable for service_domain_db

---

big_tests/rebar.config
big_tests/rebar.lock
big_tests/src/ejabberd_tests.app.src

The `fusco` is used from `escalus` but not used in `escalus`.

Declare fusco obviously in big tests

---

src/domain/mongoose_domain_gaps.erl
src/domain/mongoose_domain_loader.erl
src/domain/mongoose_domain_sql.erl
src/domain/service_domain_db.erl
test/mongoose_domain_core_SUITE.erl

This PR addresses MIM-1459 "Inconsistent values in mongoose_domain_core".
* Fix for a race condition in PgSQL when allocating IDs.
Node mim:
```erlang
f().
recon_trace:calls({mongoose_domain_sql, select_updates_from, fun(_) -> return_trace() end}, 5000, [{scope, local}]).
From = 20000.
timer:sleep(6000).
[spawn(fun() -> mongoose_domain_api:insert_domain(<<"test", (integer_to_binary(N))/binary>>, <<"test type">>) end) || N <- lists:seq(From, From + 2000, 2)].
```
Node mim2:
```erlang
f().
recon_trace:calls({mongoose_domain_sql, select_updates_from, fun(_) -> return_trace() end}, 5000, [{scope, local}]).
From = 20000.
timer:sleep(4000).
[spawn(fun() -> mongoose_domain_api:insert_domain(<<"test", (integer_to_binary(N))/binary>>, <<"test type">>) end) || N <- …
```

Fix race condition when inserting into domain_event table

---

doc/modules/mod_mam.md
src/mam/mod_mam.erl
src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
src/mam/mod_mam_rdbms_async_pool_writer.erl

This PR addresses "some old ugly code is a bit prettier now".
* No message_queue_len call on each archived message
* Just do cast
* Store messages off the heap
* Remove modMamDropped2 metric

Refactor async writer for MAM

---

c_src/ejabberd_zlib_drv.c

This PR addresses the master branch and also #2921.

Fix FTBFS on implicit declaration of function 'erts_exit'

---

src/domain/service_domain_db.erl

This PR addresses MIM-1472
* Typo in check_for_updates_tref

Ensure that check_for_updates_tref is set

---

big_tests/tests/service_domain_db_SUITE.erl
src/domain/mongoose_domain_core.erl

This tells to the service, that it needs to read the complete database.
But it assumes that the service process is down, so it would not
overwrite the last_event_id we set here.
To ensure that the service is down if the core is down,
the core and service processes should be supervised with rest_for_one strategy.
Which should be done in a separate PR. Though, it does not required to fix the "join cluster" issue.
This PR addresses MIM-1470

Reset last_event_id once mongoose_domain_core starts

---

big_tests/tests/inbox_SUITE.erl
big_tests/tests/inbox_helper.erl
big_tests/tests/muc_light_helper.erl
big_tests/tests/pubsub_tools.erl

Locally the suite goes from 7-8s to 4-5s. I'm too impatient, if I'm going to be running this suite even more 😬

Parallelise more inbox tests

---

big_tests/tests/inbox_SUITE.erl
src/inbox/mod_inbox.erl
src/inbox/mod_inbox_muclight.erl
src/muc_light/mod_muc_light.erl

This solution seems to be too simple to be true, but this is how I understand system messages in muclight. The other option is matching on them having a `<x>` subelement.

Inbox-muclight: fix system messages

---

big_tests/tests/mam_helper.erl
big_tests/tests/service_domain_db_SUITE.erl
src/domain/mongoose_domain_api.erl
src/mam/mod_mam.erl

This PR addresses "[JIRA] (MIM-1453) Start calling remove_domain hook"
* Add a call
* Add a test
* Also yeah, lserver_to_host_type is crashes now if host_type is not found.

Call remove_domain hook

---

big_tests/tests/rest_client_SUITE.erl
big_tests/tests/rest_helper.erl
doc/rest-api/Client-frontend.md
doc/rest-api/Client-frontend_swagger.yml
src/mongoose_client_api/mongoose_client_api_messages.erl
src/swagger_docs/mongoose_client_api_messages_doc.erl

Add support XEP-0201 https://xmpp.org/extensions/xep-0201.html to client api for message
Proposed changes include: 
Add thread and thread parent to client api messages
added test for message with thread and parent field will be encoded correctly
added test for messages without thread and parent field will be encoded correctly
Added sample field in mongooseim client rest api
Github action:
https://github.com/imcyee/MongooseIM/actions/runs/1179387019
This pr is to fix the messy git of #3233

Add thread and thread parent to client api messages

---

src/ejabberd_c2s.erl
test/ejabberd_c2s_SUITE.erl

When hook runs for an undefined host type, which causes the following error:
```erlang
when=2021-08-10T08:10:43.253721+00:00 level=error what=undefined_host_type pid=<0.18221.0> at=mongoose_hooks:run_hook_for_host_type/4:1465 text="Running hook for an undefined host type" hook_name=xmpp_send_element hook_args="[{xmlel,<<\"stream:error\">>,[],[{xmlel,<<\"host-unknown\">>,[{<<\"xmlns\">>,<<\"urn:ietf:params:xml:ns:xmpp-streams\">>}],[]}]}]" hook_acc_timestamp=1628583043253572 hook_acc_stanza_type=undefined hook_acc_stanza_to_jid=undefined hook_acc_stanza_ref=#Ref<0.2319972469.246677507.66886> hook_acc_stanza_name=stream:error hook_acc_stanza_from_jid="{jid,<<>>,<<\"test-domain-50005\">>,<<>>,<<>>,<<\"test-domain-50005\">>,<<>>}" hook_acc_stanza_element="{xmlel,<<\"stream:error\">>,[],[{xmlel …
```

Fix run hook(xmpp_send_element) with undefined host_type for c2s

---

big_tests/test.config
big_tests/tests/domain_helper.erl
big_tests/tests/dynamic_modules.erl
big_tests/tests/mongoose_helper.erl
big_tests/tests/private_SUITE.erl
big_tests/tests/vcard_SUITE.erl
big_tests/tests/vcard_simple_SUITE.erl
rel/files/mongooseim.toml
rel/mim1.vars-toml.config
rel/vars-toml.config.in

Improve the consistency of the module config templates used for tests.
Use `test.config` options for static and dynamic domains and do not repeat the same configuration in test suites.
This applies to two modules recently converted to use dynamic domains: `mod_private` and `mod_vcard`.

Unify big test config templating for modules

---

src/ejabberd_c2s.erl
src/ejabberd_router.erl
src/ejabberd_s2s.erl
src/ejabberd_service.erl
src/mod_dynamic_domains_test.erl
src/mod_muc.erl
src/mod_vcard.erl
src/mongoose_local_delivery.erl
src/mongoose_packet_handler.erl
src/mongoose_router_dynamic_domains.erl
src/mongoose_router_external.erl
src/mongoose_router_external_localnode.erl
src/mongoose_router_global.erl
src/mongoose_router_localdomain.erl
src/muc_light/mod_muc_light.erl
src/muc_light/mod_muc_light_codec.erl
src/muc_light/mod_muc_light_codec_legacy.erl
src/muc_light/mod_muc_light_codec_modern.erl
src/muc_light/mod_muc_light_room.erl
src/pubsub/mod_pubsub.erl
src/xmpp_router.erl
test/router_SUITE.erl

I'd like all routing to pass the accumulator along, with whatever modifications are needed like stripping it or updating the routed element. This will help with tracing the routing mechanism from start to end, if at all times the accumulator is preserved. It will also for example give me at the caller site, information about the packet handler's handling, like what muclight or pubsub did with the package. Then it is up to the caller to inspect the accumulator.

Route accumulator

---

big_tests/dynamic_domains.spec
big_tests/tests/dynamic_domains_SUITE.erl
big_tests/tests/rest_SUITE.erl
big_tests/tests/service_domain_db_SUITE.erl
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
src/mod_commands.erl

- Enable tests for `mod_commands` (`rest_SUITE`)
- Fix a bug discovered by the tests
- Use the configured auth backend with `rest_SUITE` - this is required by the tests
- Change the tests relying on the dummy auth to use a separate host type for now 
- Disable test repetition in `rest_SUITE` - we are moving away from this practice and this is in line with the recent changes in other test suites

Test commands with dynamic domains

---

doc/Differentiators.md
doc/advanced-configuration/Modules.md
doc/advanced-configuration/Services.md
doc/advanced-configuration/configuration-files.md
doc/advanced-configuration/general.md
doc/advanced-configuration/host_config.md
doc/advanced-configuration/listen.md
doc/advanced-configuration/outgoing-connections.md
doc/developers-guide/Basic-iq-handler.md
doc/developers-guide/Hooks-and-handlers.md
doc/developers-guide/domain_management.md
doc/modules/mod_domain_isolation.md
doc/modules/mod_mam.md
doc/modules/mod_ping.md
doc/rest-api/Administration-backend_swagger.yml
doc/rest-api/Dynamic-domains.md
doc/rest-api/Dynamic-domains_swagger.yml
doc/swagger/index.html
doc/user-guide/ABCs-of-MongooseIM.md
mkdocs.yml
src/config/mongoose_config_spec.erl

This PR documents the changes made for multi-tenancy.
- The REST API page is updated with a Swagger example, however I am not so familiar with Swagger so it's rather rudimentary. It was not automatically generated as I wasn't sure how to do it (it seemed to require Trails which the domains handler didn't use).
- `mod_domain_isolation` is documented.
- Domain management file in the developers guide is updated as it has some information (like the CLI) that is useful. Some of the parts have been moved to more relevant sections of the documentation.
- Outside the scope of this PR: Hooks documentation has to be updated not only to reflect multi-tenancy but also their recent updates (Hooks-and-handlers.md, hooks_description.md) - a ticket was created.
- General changes everywhere in the …

Document dynamic domains

---

big_tests/dynamic_domains.spec
src/mod_smart_markers.erl
src/mod_smart_markers_rdbms.erl
src/offline/mod_offline_chatmarkers.erl
src/offline/mod_offline_chatmarkers_rdbms.erl

Mainly makes smart_markers multitenancy ready. This also moves around some formatting like removing variable names in spec declarations or reordering some variables.

Make smart_markers multitenancy ready

---

doc/rest-api/Dynamic-domains_swagger.yml

This PR adds tags to the dynamic domains Swagger file, so that the operations are grouped under a "Dynamic domains" header, rather than a "default" one.

Update Swagger dynamic domains doc

---

big_tests/dynamic_domains.spec
big_tests/tests/muc_light_http_api_SUITE.erl
rel/mim1.vars-toml.config
src/mod_commands.erl
src/muc_light/mod_muc_light_commands.erl

Adapt and enable `muc_light_http_api` tests for dynamic domains.
Also: fix a stale TODO in `mod_commands`

Test MUC Light commands for dynamic domains

---

src/mod_muc.erl
src/mongoose_hooks.erl
src/muc_light/mod_muc_light.erl
src/muc_light/mod_muc_light_room.erl

As explained in the first commit:
Very often, the affiliations of a room will need to be checked many
times. Imagine a room of a thousand people, and one sending a message:
if any handler on user_send_packet needs to know the affiliations, they
would be then queried again when the router triggers the process_packet
callback for muclight.
Such a handler happens often when we're checking if we can access the
room, like in the case of smart_markers: then we could be introducing a
race condition, when a user can react in a certain way in his
user_send_packet hook, but then muclight finds out the user has just
been kicked out.
This can also be used as an optimisation: inbox is making a DB query for
each user when muc_light routes the package to them, but we could be
making a single DB call in …

Acc muc affs

---

src/muc_light/mod_muc_light.erl
src/muc_light/mod_muc_light_codec.erl
src/muc_light/mod_muc_light_codec_legacy.erl
src/muc_light/mod_muc_light_codec_modern.erl
src/muc_light/mod_muc_light_commands.erl
src/muc_light/mod_muc_light_room.erl
src/muc_light/mod_muc_light_utils.erl
test/muc_light_SUITE.erl

The biggest benefit is in the codec modules, I think so many jid formats is a bad and very confusing design.
Also routing handlers can reuse the already available accumulators, hence preserving the original timestamps and unique references -> again, better tracing.

Use more full jids and avoid to_lus conversions

---

big_tests/dynamic_domains.config
big_tests/dynamic_domains.spec
big_tests/tests/bosh_SUITE.erl
rel/mim1.vars-toml.config
src/mod_bosh.erl
src/mod_bosh_socket.erl
src/system_metrics/mongoose_module_metrics.erl

Update `mod_bosh` and the corresponding big tests to work with dynamic domains.
Also: fix some type specs related to system metrics.

BOSH with dynamic domains

---

big_tests/dynamic_domains.config
big_tests/dynamic_domains.spec
big_tests/tests/anonymous_SUITE.erl
big_tests/tests/domain_helper.erl
rel/mim1.vars-toml.config
src/auth/ejabberd_auth_anonymous.erl
test/mongoose_cleanup_SUITE.erl

- Fix two bugs in one function (!) that completely disabled anonymous connection registration
- Add tests for the fixed function
- Test anonymous login with dynamic domains. To do so, a separate host type needed to be added.

Fix anonymous login and test it for dynamic domains

---

big_tests/dynamic_domains.spec
big_tests/tests/mod_time_SUITE.erl
src/mod_last.erl
src/mod_time.erl

As in the title, this was a very simple PR.

Make mod_time multitenancy ready

---

big_tests/dynamic_domains.spec
big_tests/tests/adhoc_SUITE.erl
rel/mim1.vars-toml.config
src/mod_adhoc.erl
src/mongoose_hooks.erl

This PR adds support for dynamic domains in mod_adhoc and adapts tests.

Support dynamic domains in mod_adhoc

---

big_tests/dynamic_domains.spec
big_tests/tests/mod_version_SUITE.erl
src/mod_version.erl

Make mod_version multitenancy ready

---

big_tests/dynamic_domains.spec
big_tests/tests/sic_SUITE.erl
rel/mim1.vars-toml.config
src/mod_sic.erl

This PR adds support for dynamic domains in mod_sic and adapts tests.

Support dynamic domains in mod_sic

---

big_tests/dynamic_domains.spec
big_tests/tests/amp_big_SUITE.erl
rel/mim1.vars-toml.config
src/mod_amp.erl
src/mongoose_hooks.erl

- Support dynamic domains in `mod_amp`, add relevant tests for dynamic domains.
- Update one test case which was supposed to have a malformed jid, while it contained a blacklisted domain. Now it has an unknown domain.
- Remove mim1 host config for "test type" - this is possible because all enabled modules support dynamic domains now.

AMP with dynamic domains

---

big_tests/dynamic_domains.spec
big_tests/tests/mongoose_helper.erl
big_tests/tests/oauth_SUITE.erl
src/mod_auth_token.erl
src/mod_auth_token_rdbms.erl
src/mod_keystore.erl
src/mod_keystore_mnesia.erl
src/sasl/cyrsasl_oauth.erl
test/auth_tokens_SUITE.erl

Make mod_auth_token and mod_keystore multitenancy ready

---

big_tests/dynamic_domains.spec
big_tests/tests/mod_http_upload_SUITE.erl
src/admin_extra/service_admin_extra_upload.erl
src/http_upload/mod_http_upload.erl

This PR adds missing support for dynamic domains in `mod_http_upload` and adapts tests. It also replaces `host` with `host_type` in `service_admin_extra_upload`.

Support dynamic domains in mod_http_upload

---

big_tests/dynamic_domains.config
big_tests/dynamic_domains.spec

Enable connect_SUITE for dynamic domains

Enable connect_SUITE for dynamic domains

---

big_tests/tests/ejabberdctl_SUITE.erl
big_tests/tests/ejabberdctl_SUITE_data/roster.template
big_tests/tests/ejabberdctl_SUITE_data/roster.template.in
big_tests/tests/mongoose_helper.erl
src/admin_extra/service_admin_extra_private.erl
src/admin_extra/service_admin_extra_stats.erl
src/admin_extra/service_admin_extra_upload.erl

Enable the CLI tests for dynamic domains. Some bugs were discovered and fixed along the way:
- There was a faulty check if `mod_private` was running (per domain, not per host type)
- Total number of users was calculated only for static domains.
- HTTP upload URLs were supposed to be created domain, but the domain was interpreted as a host type.
Some tests were also skipped for RDBMS, but they shouldn't be.

Test mongooseimctl with dynamic domains

---

big_tests/dynamic_domains.spec
big_tests/tests/metrics_register_SUITE.erl

Enable metrics_register_SUITE for dynamic domains

Enable metrics_register_SUITE for dynamic domains

---

big_tests/dynamic_domains.spec
big_tests/tests/sasl_SUITE.erl
big_tests/tests/sasl_external_SUITE.erl

Enable sasl_SUITE and sasl_external_SUITE for dynamic domains.

Add `sasl_SUITE` and `sasl_external_SUITE` to dynamic domains testing 

---

big_tests/dynamic_domains.spec
big_tests/tests/mam_send_message_SUITE.erl
big_tests/tests/mam_send_message_SUITE_data/mam_send_message_example.erl

Adapt and enable `mam_send_message_SUITE`

Test mam_send_message with dynamic domains

---

big_tests/dynamic_domains.spec
big_tests/tests/metrics_session_SUITE.erl

Enable metrics_session_SUITE for dynamic domains.

Enable metrics_session_SUITE for dynamic domains

---

big_tests/dynamic_domains.spec
big_tests/tests/metrics_c2s_SUITE.erl

Enable metrics_c2s_SUITE for dynamic domains.

Enable metrics_c2s_SUITE for dynamic domains

---

big_tests/tests/metrics_register_SUITE.erl

Related to this [PR](https://github.com/esl/MongooseIM/pull/3275#pullrequestreview-756270786) and adds the suggestions from Paweł to use `host_type` instead of `domain`.

Use host_type instead of domain in metrics_register_SUITE

---

big_tests/dynamic_domains.spec
big_tests/tests/gdpr_SUITE.erl

Enable `gdpr_SUITE`, skip pubsub-related tests (`mod_pubsub` not supported for dynamic domains).

Test GDPR with dynamic domains

---

big_tests/dynamic_domains.config
big_tests/dynamic_domains.spec
big_tests/tests/login_SUITE.erl
big_tests/tests/mongoose_helper.erl

Enable login_SUITE for dynamic domains.

Enable login_SUITE for dynamic domains

---

big_tests/dynamic_domains.spec
big_tests/tests/metrics_roster_SUITE.erl
src/metrics/mongoose_metrics_hooks.erl
src/mod_roster.erl
src/mongoose_hooks.erl

- Bug fix: call roster_push hook for host type (not for domain)
- Adapt and enable `roster_push_SUITE`

Test roster metrics with dynamic domains

---

big_tests/dynamic_domains.spec
big_tests/tests/mongoose_helper.erl
big_tests/tests/persistent_cluster_id_SUITE.erl
big_tests/tests/rdbms_SUITE.erl
src/rdbms/mongoose_rdbms.erl

This PR:
-  adapts and enables rdbms_SUITE and persistent_cluster_id_SUITE for dynamic domains. 
- replaces `host` with `host_type` in mongoose_rdbms and mongoose_helper

Enable `rdbms_SUITE` and `persistent_cluster_id_SUITE` for dynamic domains

---

doc/index.md
doc/migrations/3.6.0_3.7.0.md
doc/migrations/3.7.0_4.0.0.md
doc/migrations/4.0.0_4.0.1.md
doc/migrations/4.0.1_4.1.0.md
doc/migrations/4.1.0_4.2.0.md

This is a follow up for #3259. The links to images in the index.md file got broken while moving files around, but worked locally for me for some reason, so I didn't notice. This fixes the issue.

Fix broken link

---

doc/tutorials/How-to-build.md

This PR addresses MIM-1503. If there are headers inside tabbed content in the documentation, they will not work if the tab containing them is not chosen by the user. The best solution is just not to use headers inside tabs.

Fix headers inside tabbed content

---

big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/presence_SUITE.erl
big_tests/tests/roster_helper.erl
src/auth/mongoose_gen_auth.erl
src/backend_module.erl
src/mod_roster.erl
src/mod_roster_rdbms.erl

This PR implements domain removal in mod_roster (only rdbms).
* extracting some functions to allow reuse,
* handling domain removal in mod_roster_rdbms,
* implementation of domain_removal hook in the mod_roster,
* adding a test case to the domain_removal_SUITE.

Implement domain removal in mod_roster

---

big_tests/tests/domain_removal_SUITE.erl
src/auth/ejabberd_auth.erl
src/auth/ejabberd_auth_rdbms.erl

Implement callback, add tests.
Also: export all functions from the test suite for easier debugging. We are doing this for most test suites.

Support domain removal in the RDBMS auth backend

---

big_tests/tests/domain_removal_SUITE.erl
src/offline/mod_offline.erl
src/offline/mod_offline_rdbms.erl

This PR implements domain removal in mod_roster (only RDBMS). It adds domain removal hook, domain removal callback in the RDBMS module, and test case.
Also: Beautify tests for domain removal from mod_roster.

Implement domain removal in mod_offline

---

big_tests/tests/domain_helper.erl
big_tests/tests/domain_removal_SUITE.erl

This module caches the users for quicker MAM and Inbox operations. It implements `remove_domain`, but a test was missing.
The test calls an API function for host types of two different domains, which have different host type configurations in different test specs:
- One host type in `dynamic_domains.spec`
- Two host types in `default.spec`
This required determining the host type dynamically, so a helper function was added with this functionality.
**Note:** we might want to eventually redesign the test suite to always use dynamic domains, because it is counter-intuitive to test domain removal hooks for static domains, which are never removed. This might require adding more users to `default.spec` and `dynamic_domain.spec`. Alternatively, we might just enable `dynamic_domains` for more DB …

Test domain removal in mod_cache_users

---

big_tests/tests/domain_removal_SUITE.erl
src/mod_vcard.erl
src/mod_vcard_rdbms.erl

This PR adds domain removal to the `mod_vcard` and implements the` remove_domain` callback in the RDBMS backend.  It also adds a test case to the 'domain_removal_SUITE'.

Implement domain removal in mod_vcard

---

doc/Contributions.md
doc/developers-guide/Testing-MongooseIM.md
doc/developers-guide/domain_management.md
doc/modules/mod_event_pusher_push.md
doc/modules/mod_inbox.md
doc/open-extensions/inbox.md
doc/rest-api/Dynamic-domains_swagger.yml
doc/tutorials/push-notifications/Push-notifications.md
doc/user-guide/Features.md

This PR addresses removes duplicates from docs, removes Tide mentions for now, adds links to `mod_inbox` and removes `@HOSTS@` mentions.

Fix small documentation issues

---

big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/muc_SUITE.erl
big_tests/tests/muc_helper.erl
src/mod_muc.erl
src/mod_muc_db.erl
src/mod_muc_db_rdbms.erl

* Add `remove_domain` callback to mod_muc_db behavior.
* Support `remove_domain` hook in mod_muc.
* Implement  `remove_domain` callback for RDBMS backend.
* Extract some helper functions from muc_SUITE to muc_helper module to make them available for reuse from domain_removal_SUITE.
* Add test case for mod_muc domain removal.

Implement domain removal in mod_muc

---

src/config/mongoose_config_parser.erl

Remove unused override-related functions

---

src/mod_carboncopy.erl
src/mod_commands.erl

Again, those accs might contain useful data we don't want to calculate again. In the case of carbons for example, hostypes, lservers, and timestamps, are the same for all copies, no need to recalculate again.

Routing shouldnt create new accs if ones are already available

---

.circleci/config.yml
big_tests/test.config
src/ejabberd_sm.erl
src/ejabberd_sm_mnesia.erl
src/ejabberd_sm_redis.erl

Enable jobs for dynamic domains with all SQL databases for Erlang 24, leave one with Erlang 23 to keep the number of jobs in control.

Test dynamic domains on CircleCI with MySQL and MSSQL

---

src/config/mongoose_config_parser.erl
src/ejabberd_config.erl

Required files are checked in `mongoose_config_validator` now, `required_files` are obsolete and unused in the code.

Remove the unused check for required_files

---

src/admin_extra/service_admin_extra_node.erl

As described, this feature is not supported and reloading the TOML file at runtime does not make sense.

Remove the leftovers of the config reload feature

---

src/config/mongoose_config_parser.erl
src/ejabberd_s2s_out.erl

The previous type got out of date and caused dialyzer to discard some success paths and miss the issue with the s2s option.
Moreover, dialyzer started failing for me when reworking the config options because of this outdated type.

Fix config key type definition and an s2s option

---

big_tests/tests/distributed_helper.erl
big_tests/tests/sm_SUITE.erl
rebar.config
src/ejabberd_sm.erl
test/ejabberd_sm_SUITE.erl

* Also fix acl:match_rule call to use hosttypes
* Because we support only one global backend, we don't need to pass HostTypes (that could be done later, if needed, but would have to have tests and rewriting API a bit)

Use persistent terms to store backend_module in ejabberd_sm

---

rebar.config
src/mod_keystore.erl
src/mod_keystore_backend.erl
src/mod_keystore_mnesia.erl
src/mongoose_hooks.erl
test/keystore_SUITE.erl

Removing dynamically compiled modules froem mod_keystore

Removing dynamically compiled modules from mod_keystore

---

big_tests/tests/mam_SUITE.erl
src/mam/mam_decoder.erl
src/mam/mod_mam_utils.erl

A lack of origin-id wasn't expressed using an empty binary, but rather a null. What we actually care is to drop the case when the origin-id is not there, not how its absence is expressed. My bug 😅

Fix correctly detecting no origin-id

---

big_tests/tests/rest_SUITE.erl
src/mongoose_api_admin.erl

This PR addresses MIM-1536
* This is already done for POST commands
* This is kinda different from `non_existent_command_returns404` testcase :) 
This command:
`curl -v "http://localhost:8088/api/contacts/"`
should return error 404, not 500.
This command is a valid working command fyi:
`curl -v "http://localhost:8088/api/contacts/alice@localhost"`
It's already done for POST commands.

MIM-1536 Return error 404 instead of 500 if GET command not found

---

.circleci/config.yml
rebar.config
tools/test-runner.sh
tools/test.sh

This PR addresses "small tests are slooow while on dev machine".
* --skip-cover flag works now
* no changes in how CI works
That is finally fast:
```
./tools/test-runner.sh --skip-big-tests --skip-cover --verbose router:routing
```
How to test the change:
```
./tools/test-runner.sh --skip-big-tests --skip-cover --verbose router:routing
./tools/test-runner.sh --skip-big-tests --verbose router:routing
```

Allow to skip cover compilation for small tests

---

src/ejabberd_gen_sm.erl
src/ejabberd_sm.erl
src/ejabberd_sm_backend.erl
src/ejabberd_sm_mnesia.erl
src/ejabberd_sm_redis.erl
src/event_pusher/mod_event_pusher_push_backend.erl
src/http_upload/mod_http_upload_backend.erl
src/inbox/mod_inbox_backend.erl
src/mod_auth_token_backend.erl
src/mod_keystore_backend.erl
src/mod_last_backend.erl
src/mod_muc_backend.erl
src/mod_private_backend.erl
src/mod_roster_backend.erl
src/mongoose_backend.erl
src/mongooseim.erl
src/muc_light/mod_muc_light_codec_backend.erl
src/muc_light/mod_muc_light_db_backend.erl
src/offline/mod_offline_backend.erl
src/offline/mod_offline_chatmarkers_backend.erl
src/privacy/mod_privacy_backend.erl
src/pubsub/mod_pubsub_cache_backend.erl
src/smart_markers/mod_smart_markers_backend.erl
src/vcard/mod_vcard_backend.erl
src/wpool/mongoose_wpool.erl
src/wpool/mongoose_wpool_http.erl

This PR addresses MIM-1539
* Removed behaviour_info, idk why it is commented out.
* Renamed init_per_host_type (so many files to change).

MIM-1539 Allow global to be passed into mongoose_backend as an arg

---

rebar.config
src/mam/mod_mam_rdbms_prefs.erl
src/rdbms/mongoose_rdbms.erl
src/rdbms/mongoose_rdbms_backend.erl
src/rdbms/mongoose_rdbms_mysql.erl
src/rdbms/mongoose_rdbms_odbc.erl
src/rdbms/mongoose_rdbms_pgsql.erl
src/wpool/mongoose_wpool_rdbms.erl
test/mongoose_rdbms_SUITE.erl

With the changes done in #3386, this turned out to be really easy. Before that, I tried to make `mongoose_rdbms_backend` expose its API with `HostType`s, but it was a bit messy. I think it's better to do it in a separate PR (after the whole `without-dynamic-backend-modules` branch is merged), to keep this already big diff smaller and more focused.
Other issue is that `mongoose_rdbms` has many functions exported, which seem to be not used, mainly for escaping different types. This could be revisited, but, in similar fashion, I left this as is for now.
What's left to do is remove dynamic `mongoose_rdbms_type`, but it will be done in a separate PR.

Add mongoose_rdbms_backend

---

src/ejabberd_sm.erl

When we arrive at this point, it is because the user we're sending a
message to has not been found to be online, so here the routing mech
needs to verify if the user actually exists, to know if it should go
the 'offline_message_hook' or the 'service_unavailable' way. But, it
would actually be incorrect to verify for anonymous users at this point:
first, we have already verified that the receiver is not online, and
anonymous accounts are ephemeral, they only exist as long as the user is
online, so checking for anonymous accounts is unnecessary and redundant.
To make things worse, there's then a race condition here, where the
anonymous account that wasn't connected before, is connected by the time
we check again, and then this code takes the wrong path!
This fix not only curates all that …

Identify only stored users on offline routing

---

big_tests/tests/rest_SUITE.erl
big_tests/tests/rest_helper.erl
doc/rest-api/Administration-backend.md
src/ejabberd_cowboy.erl
src/mod_commands.erl
src/mongoose_api_common.erl
test/mongoose_api_common_SUITE.erl

This PR addresses MIM-1535
* New fields `path`, `method`, `args`
* Sort commands by path
* Add a test
* Replace ct:pal with ct:log to reduce noise to the shell

MIM-1535 Extend /commands endpoint with more information

---

big_tests/test.config
rel/files/mongooseim.toml
rel/mim1.vars-toml.config
rel/vars-toml.config.in

The resulting config for prod, dev nodes and all test presets should have a single newline between modules in `mongooseim.toml`. Previously some newlines were missing if there was at least one option as each option is in its separate line and there was no newline after the last option. Maybe for tests it's not that important but for `prod` it affects the initial configuration file, which had a bit broken layout, leading to worse initial impression.
I chose to use '\n' as literal newlines could make the config spec less readable.
I checked the result manually for `mim1`, `prod` and finally for `mim1` with the `pgsql_mnesia` preset enabled.

Add a newline after module options to improve config readability

---

big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/mam_SUITE.erl
big_tests/tests/presence_SUITE.erl
big_tests/tests/roster_helper.erl

This PR addresses [MIM-1547](https://erlangsolutions.atlassian.net/browse/MIM-1547) and removes usage of gen_mod:set_module_opt(s) in modules:
- mam_SUITE
- roster_helper(presence_SUITE and domain_removal_SUITE)

Do not use gen_mod:set_module_opt(s) in big tests

---

src/inbox/mod_inbox_entries.erl

Just do one single time conversion here.

Simplify time-unit convertions

---

src/config/mongoose_config.erl
src/config/mongoose_config_parser_toml.erl
test/config_parser_SUITE.erl

The goal of this PR is to simplify the config processing so that no temporary functions are inserted into the option list.
This makes it easier to rework the internal structure (e.g. using maps) and to maintain and understand the unit tests.
It also simplifies the subsequent unit test rework needed to support config defaults.
Another advantage of the new unit test macros is that we could rework the config not to unfold the global options and most of the unit tests would stay the same.

Unfold global options without the temporary functions

---

src/config/mongoose_config_parser_toml.erl
src/config/mongoose_config_spec.erl
test/config_parser_SUITE.erl
test/config_parser_SUITE_data/s2s_only.options

The goal of this PR is to make config parser test cases independent of:
- any defaults that might be added to the resulting config structure
- the resulting structure itself, e.g. `local_config` records.
This is achieved by introducing a new macro `cfg` that checks only the value of the tested options instead of comparing the complete config lists. Regarding the possible presence of unwanted options, this is still checked by the file tests, which parse complete predefined TOML files and compare the contents against the expected option list.
An interesting fact is that the updated test suite executes much faster on my machine. I broke a few randomly chosen tests on purpose to sanity-check it and it looks that everything works properly, just faster.
Running dialyzer for the test suite after …

Prepare tests for config defaults

---

big_tests/test.config
big_tests/tests/last_SUITE.erl
big_tests/tests/mongooseimctl_SUITE.erl
rel/fed1.vars-toml.config
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
rel/mim3.vars-toml.config
rel/reg1.vars-toml.config

This module triggers an rdbms query every time a user disconnects, which in some suites that generate lots of fresh users in parallel, can mean lots of rdbms queries being triggered, when they are not needed. I've seen this deadlocking on MSSQL for the carboncopies suite:
https://app.circleci.com/pipelines/github/esl/MongooseIM/6374/workflows/ddf85703-70fe-456f-a55d-6834979f998f/jobs/88946
https://app.circleci.com/pipelines/github/esl/MongooseIM/6078/workflows/35ac57e9-75ee-45af-8f4b-ac3d974a3c96/jobs/83656
https://app.circleci.com/pipelines/github/esl/MongooseIM/6417/workflows/4416466d-9882-464e-8e83-f49ba455f53f/jobs/89920
https://app.circleci.com/pipelines/github/esl/MongooseIM/6411/workflows/2e7f8cd1-8414-40f2-8d6f-67ba8be8b7b7/jobs/89790

Flaky tests: enable mod_last only on its test suite

---

src/mam/mod_mam_muc.erl
src/mod_muc.erl
src/mongoose_hooks.erl
src/muc_light/mod_muc_light.erl
src/muc_light/mod_muc_light_room.erl
src/smart_markers/mod_smart_markers.erl

This allows to have the accumulator in hooks like is_muc_room_owner and
can_access_room, so that if affiliations where already fetched, they
will be present in the accumulator, and we then move forwards in
preserving the consistency of a message processing pipeline: we want to
avoid the case when, during this pipeline, a subsystem fetches the
affiliations, take some action, and before the next subsystem acts, a
concurrent process modifies the affiliations: then the following
subsystem may find out that the user has been removed from the room and
reject the request, therefore getting into an inconsistent state.
This also helps preventing more duplicate, and usually idempotent, DB
queries.
This also gives more fine-grained control over other new handlers to this hook that I can implement, …

Take the accumulator in the room hooks

---

src/wpool/mongoose_wpool_http.erl

The options are not used currently, which is critical when configuring TLS for HTTP auth.
Fusco did not complain, as the wpool library did not call the exported start/start_link functions, which verified options (https://github.com/inaka/worker_pool/blob/main/src/wpool_process.erl#L45, https://github.com/esl/fusco/blob/master/src/fusco.erl#L84).
Tested manually, without the patch, TLS is silently not verified and connection (if the MIM client certs are not rejected by the auth service) is established. With the patch, errors appear in logs when connecting to a service which has incorrect certificate.

Correctly pass connection options to Fusco

---

big_tests/tests/pubsub_SUITE.erl

* Run tests in pubsub:basic in parallel
* We do repeat_all_until_all_ok anyway, so if there is a race condition, it would be good to see it
* Typos
The main motivation is that it has one test that sleeps 5 seconds (i.e. subscribe_options_deliver_option_test). But I probably need to read some pubsub to ensure we can check that notification would not come without sleeping :)  - that would come separately

Run tests in pubsub:basic in parallel

---

src/auth/ejabberd_auth.erl
src/auth/ejabberd_auth_anonymous.erl
src/auth/ejabberd_auth_dummy.erl
src/auth/ejabberd_auth_external.erl
src/auth/ejabberd_auth_http.erl
src/auth/ejabberd_auth_jwt.erl
src/auth/ejabberd_auth_ldap.erl
src/auth/ejabberd_auth_rdbms.erl
src/auth/ejabberd_auth_riak.erl
src/auth/mongoose_gen_auth.erl
src/config/mongoose_config_spec.erl
src/mongoose_ldap_config.erl
src/vcard/mod_vcard.erl

Just like for modules and services, this keeps it more organized and simplifies future changes of auth handling, e.g. introducing defaults.

Move auth config spec to auth backend modules

---

big_tests/tests/mongoose_helper.erl
big_tests/tests/sm_SUITE.erl

* **Wait for resume_session state in resend_unacked_on_reconnection** - we basically could fail otherwise by suspending c2s before a receiver process gets down.
* Log messages if wait_for_queue_length fails
* A separate stop_client_and_wait_for_termination function for easy reading
*   Fix loglevel in sm_SUITE

Fix sm_SUITE

---

src/inbox/mod_inbox_entries.erl
src/inbox/mod_inbox_muclight.erl
src/jlib.erl
src/xmpp_router.erl

Just removing dead ignore_xref's and code, low hanging fruit here 👌🏽

Quick xref unneeded ignore

---

big_tests/tests/sm_SUITE.erl

This PR addresses MIM-1537 (investigate flaky tests)
* msg-1 arrives usually before we do stop
* And that stanza is buffered on the escalus side
* Unless we manage to hit a race condition by stopping c2s before msg-1 gets routed (and it gets stuck on the c2s process side and we get a receive stanza timeout)
Fix for the timeout https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3443/93940/riak_mnesia.24.0.5/big/ct_run.test%408fd9df8d5854.2021-12-10_11.01.05/big_tests.tests.sm_SUITE.logs/run.2021-12-10_11.16.03/sm_suite.resume_session_state_stop_c2s.62339.html#end

Avoid a race condition in sm_SUITE:resume_session_state_stop_c2s

---

big_tests/tests/offline_SUITE.erl

This PR addresses MIM-1537 (investigate flaky tests)
Failing test https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3443/93940/riak_mnesia.24.0.5/big/ct_run.test%408fd9df8d5854.2021-12-10_11.01.05/big_tests.tests.offline_SUITE.logs/run.2021-12-10_11.11.17/offline_suite.max_offline_messages_reached.62338.html
* Bob receives timeout instead of resource-contstraint error
* It is because Riak is eventually consistent and max_offline count not reached yet (we have to wait for the count)
```
%% Bob sends max limit of offline messages
...
%% Bob sends one more and waits for an error:
Packet = escalus:wait_for_stanza(B1),
escalus:assert(is_error, [<<"wait">>, <<"resource-constraint">>], Packet),
```
results in (no error)
```
=== === Reason: …
```

Fix offline_SUITE:max_offline_messages_reached

---

Makefile

Please get my certificates to rebuild automatically when they expire, please

Fix automatic certs rebuild

---

big_tests/tests/inbox_SUITE.erl
big_tests/tests/inbox_extensions_SUITE.erl
big_tests/tests/inbox_helper.erl
big_tests/tests/mongoose_helper.erl

Just cleaning up inbox tests to reuse code between inbox_SUITE and inbox_extensions_SUITE

Inbox refactor tests

---

src/mam/mod_mam_utils.erl
test/mam_misc_SUITE.erl

Just some property based tests for MAM's `is_archivable_message/4`, seems like a perfect candidate for this and there was no specific tests for it.

Mam filter property tests

---

priv/graphql/schemas/admin/admin_schema.gql
priv/graphql/schemas/global/jid.gql
priv/graphql/schemas/global/protected_dir.gql
priv/graphql/schemas/user/user_schema.gql
src/mongoose_graphql.erl
test/mongoose_graphql_SUITE.erl

This PR addresses [MIM-1559](https://erlangsolutions.atlassian.net/browse/MIM-1559) and adds support for global types.
In addition, it moves the `protected` directive to a global directory and adds the `JID` global type.

GraphQL - Support global types

---

tools/setup-db.sh

This should fix an error on Linux with permissions (and Github Actions CI).
We used to have it there.
Circle CI does not need this. Mac does not need it too (weird)
Testing:
- Get some linux and run
```
DB=mssql tools/setup-db.sh
```

Run MSSQL as root again

---

big_tests/tests/ct_helper.erl
big_tests/tests/mongoose_helper.erl
big_tests/tests/offline_SUITE.erl
big_tests/tests/sm_SUITE.erl
big_tests/tests/sm_helper.erl

* Remove code duplication by introducing a function connect_fresh and connect_spec.
* Explicitly specify which cases use manual_ack, when creating a connection
* Make sm_helper module with helpers
* No export_all, so we can remove unused functions.
* export_helper parse transform, so we don't specify cases three times... just two.
Motivation:
- that suite contains a lot of escalus_connection:connect calls. And 3 lines syntax makes harder to compare test cases.
Reduce complexity to keep in mind that:
- sm is enabled in test.config, unless we provide steps separately.
- manual_ack could be specified in the group settings or in test cases. Once we starting to pass Spec, it is harder to keep in mind which connections need manual acking.
- …

Simplify stream management suite

---

priv/graphql/schemas/global/protected_dir.gql
priv/graphql/schemas/user/user_schema.gql
src/mongoose_graphql.erl
src/mongoose_graphql/mongoose_graphql_permissions.erl
test/mongoose_graphql_SUITE.erl
test/mongoose_graphql_SUITE_data/permissions_schema.gql
test/mongoose_graphql_SUITE_data/protected_schema.gql
test/mongoose_graphql_SUITE_data/schema.gql

This PR addresses [MIM-1554](https://erlangsolutions.atlassian.net/browse/MIM-1560) and extends the `mongoose_graphql_permissions` module to support fields, interfaces and to check deeper.

GraphQL - extend permissions checking

---

src/global_distrib/mod_global_distrib_utils.erl
src/metrics/mongoose_metrics.erl
test/mongooseim_metrics_SUITE.erl

This PR addresses "mod_global_distrib_utls:ensure_metric/3 does not actually subscribe anything".
* Added mongoose_metrics:ensure_subscribed_metric/3
* Added logging of errors from exometer_report:subscribe
* test

Added mongoose_metrics:ensure_subscribed_metric/3

---

big_tests/tests/sm_SUITE.erl
big_tests/tests/sm_helper.erl
src/ejabberd_c2s.erl

This PR addresses [this failure](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/branch/master/95421/ldap_mnesia.24.0.5/big/ct_run.test@15206cc13c1e.2021-12-17_11.02.10/big_tests.tests.sm_SUITE.logs/run.2021-12-17_11.13.00/sm_suite.resume_session_state_send_message.29188.html)
* Reroute presences and IQs only to the same SID
* It ensures that SM-non-aware client would not receive non-expected stanzas

Reroute presences correctly on reconnect (SM fix)

---

big_tests/tests/graphql_SUITE.erl
big_tests/tests/mongooseimctl_SUITE.erl
src/mongoose_graphql.erl
src/mongoose_graphql/mongoose_graphql_cowboy_handler.erl
src/mongoose_graphql/mongoose_graphql_errors.erl
src/mongoose_graphql/mongoose_graphql_permissions.erl
test/mongoose_graphql_SUITE.erl

This PR addresses [MIM-1569](https://erlangsolutions.atlassian.net/browse/MIM-1569) and solves wrongly formatted messages returned to the user from the webserver.
* Unification of the error messages format.
* Introducing more information to authorization errors.
* Testing produced messages.
* Adding a catch that should handle all unexpected internal errors.

GraphQL - Better error messages formatting 

---

src/gen_mod.erl

These functions shouldn't be used anymore.
Removing them simplifies the upcoming rework of module config.

Remove gen_mod:set_module_opt(s)

---

src/inbox/mod_inbox.erl
src/mam/mod_mam.erl
src/mongoose_lib.erl

Similarly to what happened to inbox in 61d90d01. This time I just extract common code and reuse it in MAM.

Avoid asking for user exist with a room

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl
big_tests/tests/mam_proper_SUITE.erl
big_tests/tests/rdbms_SUITE.erl
src/mam/mod_mam_rdbms_arch_async.erl
src/mongoose_async_pools.erl
src/mongoose_batch_worker.erl
src/mongoose_hooks.erl
src/mongoose_lib.erl
src/rdbms/mongoose_rdbms_odbc.erl
src/safely.erl
test/mongoose_lib_SUITE.erl
test/safely_SUITE.erl

This PR addresses failures in mam_SUITE.
* New hooks: mam_archive_sync, mam_muc_archive_sync
* New function mongoose_async_pools:sync/2
* Extended mam_helper:maybe_wait_for_archive/1

Wait for async writers to flush messages in tests

---

tools/print-dots.sh

It gets stuck in an infinite busy loop, printing `usage: sleep seconds`
Apparently it accepts only integers now and nothing else, as `man sleep` tells me.

Fix print-dots for Mac OS Monterey

---

src/config/mongoose_config_parser.erl
src/config/mongoose_config_parser_toml.erl
src/gen_mod.erl
src/mongoose_modules.erl
test/config_parser_helper.erl

Follow-up to #3469 
The config should remain constant since it is stored in the persistent term.
This way it will be possible for modules to read config opts from the persistent term - this change will be done in the next PR.
We will most likely get rid of the unfolding altogether when converting all module options to maps.

Do not post-process config when starting modules

---

big_tests/tests/rdbms_SUITE.erl
src/rdbms/mongoose_rdbms.erl

Sometimes we might want to throw inserts without caring about the return value, so we don't need to block the c2s process for the DB worker to return. To be used carefully, it can overload the DB workers as the c2s process might then, unblocked, generate load faster than the DB workers might clear it.

Rdbms casts

---

big_tests/tests/inbox_SUITE.erl
big_tests/tests/inbox_helper.erl
src/inbox/mod_inbox.erl
src/inbox/mod_inbox_entries.erl

As we fixed the usage of the queryid, we broke the protocol in the sense
that now, if queryid is not provided, the answer will not use any id
now. We need to add the old iq-id as a fallback.

Add fallback to queryid in inbox

---

big_tests/tests/muc_light_SUITE.erl
src/mod_cache_users.erl
src/mongoose_hooks.erl
src/muc_light/mod_muc_light.erl
src/muc_light/mod_muc_light_cache.erl
src/muc_light/mod_muc_light_room.erl
test/config_parser_SUITE.erl

As usual, details on the commits. Some snippets from commit messages below:
3debe70427bf356b895781108dadca401b4e2402
```
It happens easily that querying the affiliations for a room becomes a
global bottleneck on a loaded server: note that every c2s process
fetches this information on their own and individually send the messages
to the given affiliated users, but when in a room of many users all send
a message at once, these affiliations are fetched as many times as users
sent a message, which is a potentially redundant overload of the DB,
more so when this operation is synchronous.
For this, we add new subscribers to the acc_room_affiliations hook: when
affiliations are to be fetched, first a cache handler is run, and if it
returns the value, the hook stops there. Otherwise, after the …
```

Cache muclight affs

---

src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_rdbms_arch.erl
src/mongoose_hooks.erl

Different handlers might want to listen on when a retraction happens, for example if the message being deleted wants to be rescued before being lost forever, or if we want metrics for it.

Mam retraction events

---

src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_rdbms_arch.erl
src/mongoose_hooks.erl

Env gives nothing here, params is needed

---

big_tests/tests/login_SUITE.erl
doc/configuration/access.md
doc/configuration/acl.md
doc/migrations/5.0.0_5.1.0.md
rel/files/mongooseim.toml
src/acl.erl
src/config/mongoose_config_spec.erl
src/ejabberd_c2s.erl
src/ejabberd_commands.erl
src/ejabberd_s2s.erl
src/ejabberd_s2s_in.erl
src/ejabberd_sm.erl
src/mam/mod_mam.erl
src/mam/mod_mam_muc.erl
src/mod_muc.erl
src/mod_muc_log.erl
src/mod_muc_room.erl
src/mod_register.erl
src/offline/mod_offline.erl
src/pubsub/node_flat.erl
src/pubsub/node_hometree.erl
src/pubsub/node_pep.erl
src/shaper_srv.erl
test/acl_SUITE.erl
test/commands_SUITE.erl
test/config_parser_SUITE.erl
test/config_parser_helper.erl
test/ejabberd_c2s_SUITE_mocks.erl
test/ejabberd_sm_SUITE.erl
test/mongoose_cleanup_SUITE.erl

The goal is to simplify and unify the internal ACL format and the ACL matching logic.
Main changes:
- Patterns are not converted from maps to tuples. By avoiding enumerating all allowed combinations, there are new possibilities, in particular `{user = "alice", server = "localhost", resource = "res"}`, which was unsupported before.
- There was an implicit check for the domain performed only for arbitrarily chosen patterns, e.g. for `{user = "alice"}` but not for `{resource = "res"}`, which was counter-intuitive and undocumented. Now the check is called `match = "current_domain"` and it is enabled by default unless the user disables it with `match = "all"`.
- The API is now unified and simplified. The host type (which can be global) is mandatory and the domain is optional. The domain-less …

Keep ACL conditions as maps

---

doc/configuration/acl.md
doc/configuration/listen.md
src/acl.erl
src/config/mongoose_config_spec.erl
test/acl_SUITE.erl
test/config_parser_SUITE.erl

This condition makes it possible to allow access for all locally hosted domains and deny access for all external domains.
This was possible before #3501, but undocumented and very implicit, e.g. it was used when checking if a user could send data to an external component, but only if user(regexp) was set in the pattern.
Now it is back, but this time is fully controllable by the user in a predicatable way.

Extend ACL conditions with match = "any_hosted_domain"

---

big_tests/tests/mam_SUITE.erl
src/mam/mod_mam_rdbms_arch_async.erl
src/mongoose_async_pools.erl
src/mongoose_batch_worker.erl

Right now, when using send_after, we're sending a single atom to the
process, which means, that we then don't know how to match the flush
request when it arrives, and therefore we need to act on all of them, or
explore the entire message queue to drop them when we do the selective
receive in `cancel_and_flush_timer`.
But that selective receive can potentially be expensive, when the batch
worker is really loaded and its queues are growing faster than it can
process, the code becomes really critical. Even more so when these
workers are enabled with message_queue_data=off_heap, which means that a
selective receive will go out of its heap, screwing cache locality, and
take all those heap fragments into its heap, which is all more
expensive.
To solve this, we can use start_timer instead of …

Performance and metrics touches on async workers

---

src/config/mongoose_config_parser_toml.erl
test/config_parser_SUITE.erl

Call `process` instead of `parse` in `config_parser_SUITE`
This makes it possible to test config post-processing, i.e.
- Repeating global options for each host (type)
- Module dependencies (no tests yet, but they can be easily added now)
- Aggregation of acl's and access rules (planned in my next PR)
Related changes:
- Module options are checked selectively because deps are now present (only one module is checked instead of all).
- New function `compare_nodes/3` is used for more organized comparison of config tree nodes
- `HOST_TYPE` is changed to `HOST` because some modules don't support dynamic domains yet. Before it was working only because it referred to an undefined host type and thus it managed to circumvent the check.
Note:
- The `host_key` helper will be simplified in the upcoming …

Test config parsing with post-processing

---

src/mongoose_user_cache.erl

Do not start a new cache when configured to reuse a different module

Fix starting new caches

---

big_tests/tests/mam_SUITE.erl
src/mongoose_batch_worker.erl

Often flushes happen either because of a timeout, or because of explicit
requests to flush the queue. Add an asynchronous wait for the metric to
change, and add a metric increment of explicit flush requests.

Fix async metrics test

---

.circleci/template.yml

The latest binary does not work for us at the moment.
We could debug it in detail later, but we need passing tests ASAP.

Freeze Minio version at the last working one

---

doc/configuration/outgoing-connections.md
src/config/mongoose_config_spec.erl
test/config_parser_SUITE.erl

The SNI options are formatted to be useful to OTP's `ssl` library, so in any place where they are passed down to it in the end, this should work.
This PR makes the option `server_name_indication` sensible - one can set it to either `true` OR `false`. And when using `verify_peer` SNI is (in most cases) needed, so there needs to be a way to pass the domain in the config. Because of the awkward way `ssl` expects an atom `disable` or the domain name, there is a need for a new option `server_name_indication_host` in TOML, and the subsequent parsing.
In the future could be used by other places where TLS can be set, but it's a can of worms, we have like five different ways to configure TLS in TOML, and quite a few libraries/abstractions, which all expect a little bit different options passed to …

Add server_name_indication_host config option

---

src/mongoose_user_cache.erl

The configuration key that says what module to use is called module, not cache_name. This was simply ignoring the cache handlers, logging lots of error messages. This started failing after https://github.com/esl/MongooseIM/pull/3508, but in a sense it's a continuation of that one.

Fix configuration key for cache name

---

src/ejabberd_s2s.erl
src/event_pusher/mod_event_pusher_sns.erl
src/http_upload/aws_signature_v4.erl
src/jingle_sip/jingle_sip_callbacks.erl
src/mod_auth_token.erl
src/p1_fsm_old.erl
src/system_metrics/service_mongoose_system_metrics.erl
src/wpool/mongoose_wpool_mgr.erl

This PR fixes some compiler warnings for MIM. This includes deprecated functions for example, which should mean less work when upgrading OTP versions.
There are two warnings left:
- `mod_http_upload_s3` uses `http_uri`, which is deprecated and will be removed with OTP25. It would probably be best to refactor this module to make the best of the new `uri_string` module, which has a bit different API, but I'd rather do this in a separate PR.
- conflicting behaviours of `mod_cowboy` when it comes to `init/2` and `terminate/3`. I've left it because from what I understand it shouldn't cause problems, and I'm not sure if this module is even used.

Less MIM compiler warnings

---

.circleci/template.yml
tools/retry.sh

This PR addresses "apt-get sometimes fails, we have to retry".
Example of a failure https://app.circleci.com/pipelines/github/esl/MongooseIM/7176/workflows/721ea437-c95b-4eca-8b27-279e20b33333/jobs/104484
* Retry apt-get

Retry apt-get on Circle CI

---

big_tests/tests/mam_SUITE.erl
src/mam/mod_mam_utils.erl

With the current code, a malicious retraction could have a namespace but
then not declare any id, and in that case the function would return
`{origin_id | stanza_id, none}`, which breaks the contract that the
second term must be a binary. In a worst-case scenario, this could
trigger an exception later on, maybe even killing one of the MAM
async workers with their message queues if the exception is not caught.

Safely parse mam retractions

---

src/mongoose_batch_worker.erl
test/batches_SUITE.erl

This PR adds a suite to cover the parts of cache and async workers code that wasn't covered and was only previously fixed ad-hoc in https://github.com/esl/MongooseIM/pull/3508 and https://github.com/esl/MongooseIM/pull/3518.

Test cache and async code

---

doc/modules/mod_event_pusher_http.md

It seems material for MKDocs just needs a space before a list.

Fix a list

---

.circleci/template.yml
doc/developers-guide/Testing-MongooseIM.md
tools/circle-generate-config.sh
tools/common-vars.sh
tools/db_configs/cassandra/proxy/replace-ip.sh
tools/mssql-shell.sh
tools/open-test-database-shell.sh
tools/setup-db.sh
tools/setup-ldap.sh
tools/setup-redis.sh
tools/setup-rmq.sh
tools/setup_minio.sh
tools/wait_for_healthcheck.sh
tools/wait_for_service.sh

This PR addresses "Desktop docker license change" MIM-1598.
* allows to use podman instead of docker
* podman does not support mounting volumes from the host machine yet
* But we already are not using volumes for circleci, so it makes sense to make circleci and setup-db code more similar.
And you can put `alias docker=podman` into your bash init script.
https://podman.io/whatis.html
What's else? It takes one hour to compile qemu (a dependency of podman) :D 
_One more thing, by default, podman machine takes 2GB of memory.
This means that after starting all other databases (i.e. primarily cassandra and elastic), starting mssql would fail (i.e. "podman ps" would not respond for some time, but after a minute, mssql container just stops and everything is fine). The …

Allow to use podman instead of docker

---

big_tests/tests/adhoc_SUITE.erl
src/mod_adhoc.erl
test/config_parser_SUITE.erl
test/config_parser_helper.erl

Also: require the tested module explicitly in big tests instead of relying on the initial state.

Module opts map for mod_adhoc

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/auth_methods_for_c2s_SUITE.erl
doc/configuration/listen.md
include/ejabberd_c2s.hrl
rel/files/mongooseim.toml
src/auth/ejabberd_auth.erl
src/config/mongoose_config_spec.erl
src/ejabberd_c2s.erl
src/ejabberd_listener.erl
src/ejabberd_socket.erl
src/mongoose_client_api/mongoose_client_api.erl
src/mongoose_credentials.erl
src/mongoose_listener_config.erl
src/mongoose_tcp_listener.erl
test/auth_dummy_SUITE.erl
test/auth_http_SUITE.erl
test/auth_jwt_SUITE.erl
test/ejabberd_c2s_SUITE_mocks.erl

This PR addresses "Allow to specify auth modules per a listener".
* Calculate a list of auth modules once on creds initialization
* Added type for listener options
* Added a new option `allowed_auth_methods`

Allow to customize auth module list per listener

---

tools/pkg/build.sh

This PR addresses "podman support". Also useful if you build on a remote machine.
* Use copy to extract a built package, instead of volumes.

Build packages without using volumes

---

test/config_parser_SUITE.erl

The tests would succeed if you make a mistake and write
`?cfgh([Path, Value], Opts)`
instead of
`?cfgh(Path, Value, Opts)`

Do not silently skip wrong elements in tested options

---

big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/gdpr_SUITE.erl
big_tests/tests/inbox_SUITE.erl
big_tests/tests/inbox_helper.erl
big_tests/tests/push_integration_SUITE.erl
src/inbox/mod_inbox.erl
src/inbox/mod_inbox_backend.erl
src/inbox/mod_inbox_entries.erl
src/inbox/mod_inbox_utils.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl

Wanted to come back to the topic of async workers for inbox but it would be good to have this one already, less conflicts later 🙂

Put mod_inbox in a map with defaults

---

src/event_pusher/mod_event_pusher.erl
src/gen_mod.erl
src/gen_mod_deps.erl
src/global_distrib/mod_global_distrib.erl
src/global_distrib/mod_global_distrib_hosts_refresher.erl
src/global_distrib/mod_global_distrib_mapping.erl
src/global_distrib/mod_global_distrib_utils.erl
src/inbox/mod_inbox.erl
src/mam/mod_mam_meta.erl
src/mongoose_modules.erl
src/muc_light/mod_muc_light.erl
src/offline/mod_offline_chatmarkers.erl
src/pubsub/mod_pubsub.erl
test/gen_mod_deps_SUITE.erl
test/mongoose_modules_SUITE.erl

Prepare module deps for module opts in maps - now modules using maps can be deps of other modules.
- Update dependency processing and resolution.
- Update dependency format - options are mandatory as both `[]` and `#{}` are possible now. This does not seem to be worse in any way, so I think it is a permanent change.
- Update type specs, improve type reuse.
- Update small tests to check the opts in maps. The transitional phase should be short and I see no reason to keep both formats in tests - it would be complicated.
Minor changes:
- Use host types.
- Call module options `opts`, not `args` or `params`.

Support maps in gen_mod_deps

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/mongoose_helper.erl
big_tests/tests/smart_markers_SUITE.erl
doc/migrations/5.0.0_5.1.0.md
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
src/smart_markers/mod_smart_markers.erl
src/smart_markers/mod_smart_markers_backend.erl
src/smart_markers/mod_smart_markers_rdbms.erl

This PR adds all the automatic removals, like the very important remove_domain (which requires changing the DB model), and also remove_user, forget_room, and removing a user from a room.

[markers] removals

---

big_tests/tests/mongoose_elasticsearch_SUITE.erl
src/mongoose_service.erl
src/wpool/mongoose_wpool.erl

The `is_configured` function always returned false, so some tests were skipped.
Now both the function and the tests are fixed.
Also: a minor missing exported type is added.

Fix 'is_configured' in async pools

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/graphql_muc_light_SUITE.erl
big_tests/tests/muc_light_http_api_SUITE.erl
big_tests/tests/rest_client_SUITE.erl
doc/rest-api/Administration-backend_swagger.yml
priv/graphql/schemas/admin/admin_schema.gql
priv/graphql/schemas/admin/muc_light.gql
priv/graphql/schemas/global/muc.gql
src/graphql/admin/mongoose_graphql_admin_mutation.erl
src/graphql/admin/mongoose_graphql_admin_query.erl
src/graphql/admin/mongoose_graphql_muc_light_admin_mutation.erl
src/graphql/admin/mongoose_graphql_muc_light_admin_query.erl
src/graphql/admin/mongoose_graphql_stanza_admin_query.erl
src/graphql/mongoose_graphql.erl
src/graphql/mongoose_graphql_enum.erl
src/graphql/mongoose_graphql_muc_light_helper.erl
src/graphql/mongoose_graphql_stanza_helper.erl
src/mongoose_client_api/mongoose_client_api_rooms.erl
src/mongoose_client_api/mongoose_client_api_rooms_config.erl
src/mongoose_client_api/mongoose_client_api_rooms_users.erl
src/muc_light/mod_muc_light.erl
src/muc_light/mod_muc_light_api.erl
src/muc_light/mod_muc_light_commands.erl

This PR addresses [MIM-1600](https://erlangsolutions.atlassian.net/browse/MIM-1600). It adds MUC Light admin API for GraphQL. The user part should be implemented in the next PR.
The new `mod_muc_light_api` extracted from `mod_muc_light_commands` catches all errors and returns them as a `{ErrCode, Message}` tuple. Previously these functions could fail in some cases (e.g. passing a non-existing domain).
The old REST API now expects `MUCLightServer` in each command instead of `Server`. Previously it depended on the command, and now it is unified.
Before, some commands use room name instead of room id. The room name is not unique and user can have more than one room with the same name. It is unified now and room id is used everywhere.

GraphQL - Implement MUC Light rooms API for admin

---

big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_muc_light_SUITE.erl
priv/graphql/schemas/admin/muc_light.gql
priv/graphql/schemas/global/muc.gql
priv/graphql/schemas/global/scalar_types.gql
priv/graphql/schemas/user/muc_light.gql
priv/graphql/schemas/user/user_schema.gql
src/graphql/admin/mongoose_graphql_muc_light_admin_mutation.erl
src/graphql/admin/mongoose_graphql_muc_light_admin_query.erl
src/graphql/mongoose_graphql.erl
src/graphql/mongoose_graphql_enum.erl
src/graphql/mongoose_graphql_muc_light_helper.erl
src/graphql/mongoose_graphql_scalar.erl
src/graphql/user/mongoose_graphql_muc_light_user_mutation.erl
src/graphql/user/mongoose_graphql_muc_light_user_query.erl
src/graphql/user/mongoose_graphql_user_mutation.erl
src/graphql/user/mongoose_graphql_user_query.erl
src/mongoose_client_api/mongoose_client_api_messages.erl
src/mongoose_client_api/mongoose_client_api_rooms.erl
src/mongoose_client_api/mongoose_client_api_rooms_messages.erl
src/muc_light/mod_muc_light_api.erl
src/muc_light/mod_muc_light_commands.erl

This PR implements the user part of the MUC Light category. The user API is basically the admin API without a `user` argument in queries and the user is taken from the context. User tests are mostly adapted admin tests.
In addition, this PR introduces a blocking list management API both for users and admin. It also adds a `NonEmptyString` scalar that validates if the given string is not empty.
I also provide here some admin part improvements:
- Return passed page size as a limit field in the `StanzaPayload` type.
- Use macro paths in admin tests.
- Other minor fixes.

Implement GraphQL MUC Light user queries

---

big_tests/tests/mongoose_helper.erl

The `case` expression failed, because it should be a `try` instead.
However, all modules used in the CT hook are already converted, so it makes no sense to support the obsolete dynamic modules.
Verified manually - the error message (previously present in every `end_per_suite` log) showed below is not present anymore.
```*** User 2022-03-03 18:12:18.717 ***
Suite: domain_isolation_SUITE finished dirty. Other suites may fail because of that. Details:
{'EXIT',{{badrpc,{'EXIT',{undef,[{mod_offline_backend,backend,[],[]}]}}},
[{distributed_helper,rpc,
[#{node => mongooseim@localhost},
mod_offline_backend,backend,[]],
[{file,"distributed_helper.erl"},{line,117}]},
{mongoose_helper,get_backend_old,1,
[{file,"mongoose_helper.erl"},{line,172}]},
{mongoose_helper,generic_count_per_host_type,2, …
```

Do not call the obsolete backend API in CT hook

---

big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/gdpr_SUITE.erl
big_tests/tests/metrics_roster_SUITE.erl
big_tests/tests/roster_helper.erl
src/gen_mod.erl
src/mod_roster.erl
src/mod_roster_backend.erl
src/mod_roster_mnesia.erl
src/mod_roster_rdbms.erl
src/mod_roster_riak.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/roster_SUITE.erl

Normal stuff + some clean up in comments and specs.

Put mod_roster config options in a map with defaults

---

big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/muc_light_SUITE.erl
doc/modules/mod_mam.md
src/mod_cache_users.erl
src/mongoose_user_cache.erl
src/muc_light/mod_muc_light.erl
src/muc_light/mod_muc_light_cache.erl
test/batches_SUITE.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/mod_mam_meta_SUITE.erl

Muclight still takes lists as opts, so in the small tests there's a bit of duplication that will need to be removed when muclight is migrated, so that mam caches and muclight caches test similarly. Otherwise, this does the job.

Migrate segmented cache to maps

---

big_tests/tests/mod_global_distrib_SUITE.erl
src/gen_mod.erl
src/global_distrib/mod_global_distrib_disco.erl
src/global_distrib/mod_global_distrib_mapping.erl
src/global_distrib/mod_global_distrib_mapping_backend.erl
src/global_distrib/mod_global_distrib_mapping_redis.erl
src/global_distrib/mod_global_distrib_server_mgr.erl

Get rid of the dynamically compiled module.
Also: simplify functions that always returned `{ok, Val}`.

Use mongoose_backend in mod_global_distrib_mapping

---

doc/modules/mod_smart_markers.md
doc/open-extensions/smart-markers.md
mkdocs.yml

These documents explain the functionality that `mod_smart_markers` offer alone, together with an iq-protocol not currently implemented, but that I'd like to start reviewing in order to make the implementation cleaner.
Note that for the iq-protocol, I didn't want to use Forms like we did for inbox, maybe because I imagine Forms as being actual forms presented to the user that the user fills on its own, while this request is more programmatically filled, but also, because I find forms much harder to implement, parse, validate, and test, and considering this module will already need all the removal hooks (remove_domain, remove_user, forget_room, affiliations_changed...), I didn't want to introduce more complexity to it.

[markers] Prepare a documentation page for the smart markers

---

src/mod_muc_room.erl

* The old version is impossible to read
* Same logic, just two functions, one for role, one for affiliations

Split can_change_ra function in mod_muc [refactoring]

---

big_tests/tests/smart_markers_SUITE.erl

Here we're not saving the config properly after tests are ran, so the restore at the `end_per_group` didn't restore anything.

[OS] fix restore tests

---

src/mam/mod_mam_cache_user.erl
src/mam/mod_mam_meta.erl
test/common/config_parser_helper.erl
test/mod_mam_meta_SUITE.erl

When mod_mam_cache_user checks its cache, it gives its own module name
to mongoose_user_cache so that this one fetches the config to see if it
has configured its own cache or is reusing some other module's cache.
The problem is that mongoose_user_cache will check for the module key,
but it the current implementation, we are hiding it behind a cache key
to contain the cache config.
So by just moving the config a level up, mongoose_user_cache can find it.

Fix MAM cache name

---

src/wpool/mongoose_wpool_mgr.erl
src/wpool/mongoose_wpool_sup.erl

Children of type `supervisor` should not have a shutdown flag other than
`infinity` according to the official documentation.

Reconfigure supervision flags in pools

---

big_tests/tests/mam_helper.erl
src/mam/mod_mam.erl
src/mam/mod_mam_muc.erl

No need to convert any of these TS to seconds, XMPP admits microseconds just fine, and client devices this way can ensure they'll display the messages in the right order, otherwise there's a risk of messages arriving within the same 1s window and therefore having the same timestamp.
Also, inbox show timestamps in microseconds, so it is just consistent.

Make MAM return timestamps in microseconds

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_roster_SUITE.erl
priv/graphql/schemas/admin/admin_schema.gql
priv/graphql/schemas/admin/roster.gql
priv/graphql/schemas/global/roster.gql
priv/graphql/schemas/user/roster.gql
priv/graphql/schemas/user/user_schema.gql
src/admin_extra/service_admin_extra_roster.erl
src/graphql/admin/mongoose_graphql_admin_mutation.erl
src/graphql/admin/mongoose_graphql_admin_query.erl
src/graphql/admin/mongoose_graphql_roster_admin_mutation.erl
src/graphql/admin/mongoose_graphql_roster_admin_query.erl
src/graphql/mongoose_graphql.erl
src/graphql/mongoose_graphql_enum.erl
src/graphql/mongoose_graphql_helper.erl
src/graphql/mongoose_graphql_roster.erl
src/graphql/user/mongoose_graphql_roster_user_mutation.erl
src/graphql/user/mongoose_graphql_roster_user_query.erl
src/graphql/user/mongoose_graphql_user_mutation.erl
src/graphql/user/mongoose_graphql_user_query.erl
src/mod_commands.erl
src/mod_roster.erl
src/mod_roster_api.erl

This PR addresses [MIM-1605](https://erlangsolutions.atlassian.net/browse/MIM-1605) and implements roster category for both user and admin.
This implementation reuse roster commands from `mod_commands` (used by admin and user Rest API) and extracts those functions to the new `mod_roster_api` module. 
There is also a `service_admin_extra_roster` module that delivers commands for CTL, and I tried to implement the most useful functionality in GraphQL with the use of functions proposed by Rest API. The roster functions used by extra roster commands are undocumented and seem to be older. Also, the extra roster API is a little bit different from the Rest API, so I left it unchanged.

GraphQL - Implement roster category

---

big_tests/tests/mam_helper.erl
big_tests/tests/mod_global_distrib_SUITE.erl
doc/modules/mod_global_distrib.md
src/gen_mod.erl
src/global_distrib/mod_global_distrib.erl
src/global_distrib/mod_global_distrib_bounce.erl
src/global_distrib/mod_global_distrib_connection.erl
src/global_distrib/mod_global_distrib_disco.erl
src/global_distrib/mod_global_distrib_hosts_refresher.erl
src/global_distrib/mod_global_distrib_mapping.erl
src/global_distrib/mod_global_distrib_mapping_redis.erl
src/global_distrib/mod_global_distrib_outgoing_conns_sup.erl
src/global_distrib/mod_global_distrib_receiver.erl
src/global_distrib/mod_global_distrib_sender.erl
src/global_distrib/mod_global_distrib_server_mgr.erl
src/global_distrib/mod_global_distrib_server_sup.erl
src/global_distrib/mod_global_distrib_transport.erl
src/global_distrib/mod_global_distrib_utils.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/mod_global_distrib_SUITE.erl

Highlights:
- Simplified deps, because modules are using each other's options anyway - there is no clear separation. Having the same opts is most straightforward option.
- Removed the complicated way of starting and stopping module, involving the utils module and callbacks.
- Removed the ETS tables storing options. The only extra parameter to store is the host type (equal to the global host now, as there is no support for dynamic domains), which is stored in a persistent term.
- Separate resolved endpoints from the original ones to avoid having a mixup of both endpoint types.
All changes are described in details in the commit messages.

Global distribution opts in a map

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/local_iq_SUITE.erl
src/ejabberd_local.erl
src/ejabberd_node_id.erl
test/mongoose_cleanup_SUITE.erl

The code I am touching here is a bit old and a bit hairy.
I honestly didn't read that one and it took sometime to understand why we use mnesia there to begin with.
So, TLDR:
- the code I am touching allows to route an IQ from the SERVER to the CLIENT (the opposite way they usually go).
- it is used in mod_ping.
- though, the last thing I want is to **replicate** data, that is used by mod_ping in a big cluster (because of how often it is written).
- in the real life, that iq_response would never do RPC calls (at least for mod_ping, because the process sending IQ and receiving IQ is a c2s process). We still need to test it though :(
- This change removes replication for IQ response tracking (useful in the big clusters, that use mod_ping)
- We use IQ IDs to locate …

Don't use mnesia for IQ response tracking

---

big_tests/tests/xep_0352_csi_SUITE.erl
src/ejabberd_c2s.erl
src/mod_csi.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl

Put mod_csi option in a map with defaults

---

big_tests/tests/offline_SUITE.erl
src/config/mongoose_config_parser_toml.erl
src/config/mongoose_config_spec.erl
src/offline/mod_offline_chatmarkers.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl

* Make mod_offline_chatmarkers configurable
* Use maps for config options

Make mod_offline_chatmarkers configurable

---

big_tests/tests/service_mongoose_system_metrics_SUITE.erl
src/mam/mod_mam.erl
src/mod_keystore.erl
src/mod_muc.erl
src/mod_private.erl
src/muc_light/mod_muc_light.erl
src/privacy/mod_privacy.erl

Add tests for module opts reported to system metrics
- Test multiple modules at once to reduce time (it can't be parallel).
- Skip modules without dynamic domains support when needed.
Update `config_metrics` callbacks in modules
- Remove when not used (`mod_mam`, `mod_keystore`).
- Update when the old way of providing defaults was used.
Also:
- Use `export_all` to simplify maintenance
- Rename functions returning booleans. An additional reason for this was a clash with CT callback names.

Test config metrics

---

big_tests/tests/rdbms_SUITE.erl
doc/modules/mod_inbox.md
doc/modules/mod_smart_markers.md
src/inbox/mod_inbox_rdbms.erl
src/inbox/mod_inbox_rdbms_async.erl
src/rdbms/rdbms_queries.erl
src/smart_markers/mod_smart_markers_rdbms.erl
src/smart_markers/mod_smart_markers_rdbms_async.erl

If we have asynchronous inserts for inbox or smart_markers, there's a risk of different nodes aggregating different data, and then inserting it in undefined orders, so an earlier event could be flushed by one node _after_ a latter event from another node. For example in the case of a conversation between Alice and Bob, when Alice and Bob are connected to different nodes on a cluster.
So what we want here, is for the DB to ignore updates, if the timestamp of such update is not strictly higher than the timestamp from the previous update.
For this, we add one more parameter to the preparing of queries, that constructs the appropriate query for Postgres and MySQL. This is currently not implemented for MSSQL.
With this, now the asynchronous backends for inbox and markers are much closer to …

Async rdbms order

---

src/config/mongoose_config_spec.erl
test/config_parser_SUITE.erl

It should be possible not to provide the `app` argument for some types, so config_parser cannot require `all`.
See for example how the `file` type is handled: https://github.com/ninenines/cowboy/blob/2.9.0/src/cowboy_static.erl#L61
Should fix #3428.

Fix cowboy_static options

---

src/mam/mod_mam.erl

This way, MAM's executed earlier, and a MAM-id is assigned earlier, so
that it can be used elsewhere in subsequent hooks, like inbox.

Reorder MAM's filter_local_packet order

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_roster_SUITE.erl
priv/graphql/schemas/admin/admin_schema.gql
priv/graphql/schemas/admin/muc.gql
priv/graphql/schemas/global/muc.gql
priv/graphql/schemas/global/muc_light.gql
priv/graphql/schemas/user/muc.gql
priv/graphql/schemas/user/user_schema.gql
src/graphql/admin/mongoose_graphql_admin_mutation.erl
src/graphql/admin/mongoose_graphql_admin_query.erl
src/graphql/admin/mongoose_graphql_muc_admin_mutation.erl
src/graphql/admin/mongoose_graphql_muc_admin_query.erl
src/graphql/admin/mongoose_graphql_muc_light_admin_query.erl
src/graphql/mongoose_graphql.erl
src/graphql/mongoose_graphql_enum.erl
src/graphql/mongoose_graphql_helper.erl
src/graphql/mongoose_graphql_muc_helper.erl
src/graphql/mongoose_graphql_muc_light_helper.erl
src/graphql/user/mongoose_graphql_muc_light_user_query.erl
src/graphql/user/mongoose_graphql_muc_user_mutation.erl
src/graphql/user/mongoose_graphql_muc_user_query.erl
src/graphql/user/mongoose_graphql_user_mutation.erl
src/graphql/user/mongoose_graphql_user_query.erl
src/mod_muc.erl
src/mod_muc_api.erl

This PR addresses [MIM-1619](https://erlangsolutions.atlassian.net/browse/MIM-1619) and implements the admin and user queries for the MUC category. This implementation is only a subset of all commands indicated to be added and focuses to be similar to the API offered by the MUC Light category.
The other useful commands could be added in the next PR.
Both user and admin share the same subset of commends.
- createInstantRoom
- inviteUser
- kickUser
- sendMessageToRoom
- deleteRoom
- changeRoomConfiguration
- listRooms
- getRoomConfig
- listRoomUsers
- getRoomMessages

GraphQL - Implement MUC category

---

big_tests/tests/dynamic_services.erl
big_tests/tests/mongooseimctl_SUITE.erl
big_tests/tests/service_domain_db_SUITE.erl
big_tests/tests/service_mongoose_system_metrics_SUITE.erl
rel/files/mongooseim.toml
src/admin_extra/service_admin_extra.erl
src/domain/mongoose_domain_api.erl
src/domain/mongoose_domain_core.erl
src/domain/mongoose_domain_db_cleaner.erl
src/domain/mongoose_domain_sql.erl
src/domain/service_domain_db.erl
src/mongoose_cluster.erl
src/mongoose_service.erl
src/system_metrics/service_mongoose_system_metrics.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/config_parser_SUITE_data/host_types.toml
test/config_parser_SUITE_data/miscellaneous.toml
test/mongoose_service_SUITE.erl

Store service options in maps with defaults. Other changes for each service are listed below.
`service_admin_extra`: 
- removed redundant defaults from TOML
`service_domain_db`:
- added missing config tests
- refactored big tests
- some helpers need the DB pool to be explicitly provided now, as there are no config values when the service is not loaded
`service_mongoose_system_metrics`:
- removed the shorter intervals for CI as they were not used anyway (the explicit values in TOML were overriding them). We can set the shorter values for CI explicitly if we want to, but I see no motivation to change it now.
- refactored big tests
- removed redundant defaults from TOML
Other changes:
- Added utilities for managing services dynamically: `dynamic_services`, which uses the new …

Service config in maps

---

src/domain/mongoose_subdomain_core.erl
src/ejabberd_admin.erl
src/gen_mod.erl
src/mod_muc.erl
src/mongoose_hooks.erl
src/mongoose_router.erl
test/mongoose_subdomain_core_SUITE.erl

This obsolete function was used in two places and both can be eliminated - see the commit messages for details.
The most important change is that the `(un)register_subhost` hooks were called only for `mod_muc` and not for other modules, which caused them to be called twice for `mod_muc` and only once (by `mongoose_lazy_routing`) for other modules. The issue is that lazy execution is too late, which would be caught if we tested global distribution e.g. with `mod_muc_light`. The solution is to simply call the hook in `mongoose_subdomain_core`.

Eliminate gen_mod:get_opt_subhost

---

tools/make-certs-cache-key.sh

CircleCI jobs started failing and the cache has one-week retention time. Changing the key forces it to be rebuilt now.

Force cert cache renewal

---

src/mongoose_acc.erl

Doing maps:find creates the ok-tuple, which means garbage, and also then
needs to match on it. It it more efficient to pattern-match on the map key.

Pattern match the map key for more efficiency

---

src/mongoose_acc.erl
test/json_formatter_SUITE.erl

Another low-hanging fruit. This field is actually never used anywhere in MongooseIM code ~so it could even be dropped altogether, but at the very least we can just skip the to_binary until it is used, if ever~, and in the logger we now have selective pretty-printers, so we can drop it altogether.

Skip pretty-printing of unused accumulator field

---

src/mod_ping.erl

THIS! That explains the infinite ping logs in client code, here we were passing the `LServer` instead of the `HostType`, and therefore the get config call was crashing hard.

Fix mod_ping with host_types

---

big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/muc_http_api_SUITE.erl
priv/graphql/schemas/admin/muc.gql
priv/graphql/schemas/global/muc.gql
priv/graphql/schemas/global/scalar_types.gql
priv/graphql/schemas/user/muc.gql
src/graphql/admin/mongoose_graphql_muc_admin_mutation.erl
src/graphql/admin/mongoose_graphql_muc_admin_query.erl
src/graphql/mongoose_graphql_enum.erl
src/graphql/mongoose_graphql_muc_helper.erl
src/graphql/mongoose_graphql_scalar.erl
src/graphql/user/mongoose_graphql_muc_user_mutation.erl
src/graphql/user/mongoose_graphql_muc_user_query.erl
src/mod_muc_api.erl
src/mod_muc_commands.erl
src/mod_muc_room.erl

This PR refers to [MIM-1629](https://erlangsolutions.atlassian.net/browse/MIM-1629) and extends the GraphQL MUC category about new commands.
When the room is password secured, then this command attaches the password to the invitation.
- grant member aff,
- grant admin aff,
- grant owner aff,
- ban user (set outcast aff)
- revoke aff
- grant voice (participant role),
- revoke voice (visitant role),
- grant moderator role
Allows listing all users with given affiliation or list all room affiliations.
Allows entering/exiting room per user session with the given nickname.
It is possible to enter the password-secured room.
The user can send a private message to the other room occupant. The message is sent to the given nickname.
When working on this PR I found a bug in graphql_erlang causing a …

GraphQL - Implement more commands for MUC

---

big_tests/tests/domain_rest_helper.erl
big_tests/tests/rest_helper.erl
doc/configuration/listen.md
doc/migrations/5.0.0_5.1.0.md
rel/files/mongooseim.toml
src/config/mongoose_config_parser_toml.erl
src/config/mongoose_config_spec.erl
src/config/mongoose_config_utils.erl
src/config/mongoose_config_validator.erl
src/domain/mongoose_domain_handler.erl
src/ejabberd_cowboy.erl
src/mod_bosh.erl
src/mod_websockets.erl
src/mongoose_api.erl
src/mongoose_api_admin.erl
src/mongoose_api_client.erl
src/mongoose_client_api/mongoose_client_api.erl
src/mongoose_http_handler.erl
src/system_metrics/mongoose_system_metrics_collector.erl
test/commands_backend_SUITE.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/config_parser_SUITE_data/mongooseim-pgsql.toml
test/mod_websockets_SUITE.erl
test/mongoose_listener_SUITE_data/mongooseim.basic.toml

The main goal is to use maps with defaults for the handler-specific options of all HTTP handlers in the `listen` section.
Because the rework is significant, it turned out that it makes sense to simplify the configuration of `mongoose_client_api`, which was way too complicated for the end user (and some options were giving the illusion of being configurable, while only the initial values worked, e.g. Swagger path). Now all handlers are enabled by default and the user can set a custom list (with `handlers = [...]`) or disable the Swagger docs (with `docs = false`). For simplicity and consistency, all handlers are also enabled by default for `mongoose_api`.
A new behaviour, `mongoose_http_handler`, is introduced. Its introduction improved the separation between the listener implementation …

Rework HTTP handler configuration

---

.circleci/config.yml
tools/make-certs-cache-key.sh

This PR addresses "There is no easy way to reset cache without making new changes into the code. And sometimes cache breaks, because a committer did something wrong".
* Use CI_CERT_KEY_VERSION env variable to change the key externally.
* Avoid caching invalid certificate data. It should make fixing bugs with certificates a bit easier.

Add CI_CERT_KEY_VERSION environment variable

---

big_tests/tests/rdbms_SUITE.erl
src/rdbms/mongoose_rdbms.erl

This is useful for the async workers, in line with how executes and queries where extended to support gen_server async requests, now also transactions. This is not used in open source MIM but I do use it in custom code.

Add transaction async requests

---

priv/graphql/schemas/admin/account.gql
priv/graphql/schemas/admin/domain.gql
priv/graphql/schemas/admin/muc.gql
priv/graphql/schemas/admin/muc_light.gql
priv/graphql/schemas/admin/roster.gql
priv/graphql/schemas/admin/session.gql
priv/graphql/schemas/admin/stanza.gql
priv/graphql/schemas/global/protected_dir.gql
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
src/domain/mongoose_domain_api.erl
src/domain/mongoose_domain_sql.erl
src/graphql/mongoose_graphql_errors.erl
src/graphql/mongoose_graphql_permissions.erl
src/mongoose_scram.erl
test/mongoose_graphql_SUITE.erl
test/mongoose_graphql_SUITE_data/listener_schema.gql
test/mongoose_graphql_SUITE_data/permissions_schema.gql

This PR addresses [MIM-1644](https://erlangsolutions.atlassian.net/browse/MIM-1644) and finishes the admin per domain support. 
Currently, the password storing method is not configurable, and it uses the SCRAM with default values.
Types of the permission check:
- **GLOBAL** - only global admin can execute field;
- **DOMAIN** - domain admin can execute field only with own domain;
- **DEFAULT** - anyone authorized can execute.

GraphQL - Finish admin per domain support

---

big_tests/tests/metrics_api_SUITE.erl
big_tests/tests/metrics_helper.erl
big_tests/tests/metrics_session_SUITE.erl
src/metrics/mongoose_metrics.erl
src/metrics/mongoose_metrics_definitions.hrl
src/metrics/mongoose_metrics_probe_muc_hibernated_rooms.erl
src/metrics/mongoose_metrics_probe_muc_online_rooms.erl
src/metrics/mongoose_metrics_probe_node_sessions.erl
src/metrics/mongoose_metrics_probe_total_sessions.erl
src/metrics/mongoose_metrics_probe_unique_sessions.erl
src/mod_muc.erl

This PR addresses "MIM-1637 Fix metrics being null"
```
There is a bug in how we handle computed metrics.
Computed metrics should take constant amount of time and be calculated fast.
But, uniqueSessionCount could be too slow for >600k users.
This means that exometer reporter takes longer, this means exometer misses a report window for graphite, this means missing metrics.
```
- use probe metric type for non-constant calculation time metrics. Probe metrics have a separate process for calculations, so they don't block the reporter process.
- add sample/1 function to our metrics API, so we can force update metric value without waiting one minute in our tests.
- clusterSize metric could remain eval - it is really fast call and having the most recent value for …

Use metric probes instead of eval for slow calculated metrics

---

big_tests/tests/metrics_helper.erl
src/metrics/mongoose_metrics.erl

This PR addresses the fact that metric prefixes are sanitised every single time a metric is going to be updated, which happens potentially hundreds of times per message, turning into an important waste. Here we instead build all host-type prefixes early on and store them on a persistent term, and fetch these values when updating the metrics. If a prefix wasn't built at that point, we can only then rebuild it.

Pre-build metric prefixes and fetch-or-rebuild when needed

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/graphql_account_SUITE.erl
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_last_SUITE.erl
priv/graphql/schemas/admin/account.gql
priv/graphql/schemas/admin/admin_schema.gql
priv/graphql/schemas/admin/last.gql
priv/graphql/schemas/global/last.gql
priv/graphql/schemas/user/last.gql
priv/graphql/schemas/user/user_schema.gql
src/admin_extra/service_admin_extra_accounts.erl
src/admin_extra/service_admin_extra_last.erl
src/graphql/admin/mongoose_graphql_account_admin_mutation.erl
src/graphql/admin/mongoose_graphql_account_admin_query.erl
src/graphql/admin/mongoose_graphql_admin_mutation.erl
src/graphql/admin/mongoose_graphql_admin_query.erl
src/graphql/admin/mongoose_graphql_last_admin_mutation.erl
src/graphql/admin/mongoose_graphql_last_admin_query.erl
src/graphql/mongoose_graphql.erl
src/graphql/mongoose_graphql_last_helper.erl
src/graphql/mongoose_graphql_permissions.erl
src/graphql/user/mongoose_graphql_last_user_mutation.erl
src/graphql/user/mongoose_graphql_last_user_query.erl
src/graphql/user/mongoose_graphql_user_mutation.erl
src/graphql/user/mongoose_graphql_user_query.erl
src/mod_last.erl
src/mod_last_api.erl
src/mongoose_account_api.erl
test/mongoose_graphql_SUITE.erl

This PR addresses [MIM-1647](https://erlangsolutions.atlassian.net/browse/MIM-1647) and adds the last category to the GraphQL API. Moreover, all the commends from the `account` category that need `mod_last` to work were moved to the `last` category. 
The commands `list_old_users`, `remove_old_users` and `count_active_users` take now a timestamp in ISO date-time format. All users with activity older than the given timestamp are considered old.
Domain admin shouldn't be able to execute a query containing fields with optional domain arguments without providing them. `null` domain argument means that the command should affect the global scope. Thus only global admin should be allowed to do it.

GraphQL - Implement last category

---

big_tests/tests/graphql_helper.erl
src/graphql/mongoose_graphql_cowboy_handler.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/mongoose_graphql_SUITE.erl

This PR addresses comments from Paweł in the PR about merging HTTP handlers config rework.
https://github.com/esl/MongooseIM/pull/3646#discussion_r872059068
https://github.com/esl/MongooseIM/pull/3646#discussion_r872059068

GraphQL - Use enum in cowboy handler configuration and provide test

---

big_tests/tests/sm_SUITE.erl
src/ejabberd_c2s.erl
src/mongoose_hooks.erl

This can be used to insert handlers that would filter out stanzas with a
`no-copy` hint, or any other desired condition. The handler will have
access to the full buffer and can return an entirely new one,
preferably, by only filtering whichever stanza is to be undesired.

Install a hook to filter messages being buffered

---

src/config/mongoose_config_parser_toml.erl
src/config/mongoose_config_spec.erl
src/ejabberd_commands.erl
src/ejabberd_ctl.erl
test/commands_SUITE.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/mongoose_config_SUITE.erl

Convert the configuration of command access rules to use maps with defaults.
This allows to remove the temporary `prepend_key` wrapper.

Access commands in maps

---

.circleci/template.yml
src/metrics/mongoose_metrics.erl

The goal is to use the latest OTP 24 for CI tests. Details in commit messages:
- [Use OTP 24.3 for CircleCI](https://github.com/esl/MongooseIM/pull/3661/commits/169c70911a8ab44debb6d54c9709f1c8d2215b38)
- [Get dist metrics using 'tls_sender' to make it work for OTP 24.3.4](https://github.com/esl/MongooseIM/pull/3661/commits/a9ffb2d496b111f794963973b9d12bc054988bf0)

Use OTP 24.3.4 for CircleCI

---

big_tests/tests/accounts_SUITE.erl

Trivial fix. The cleanup stage of the registration_timeout test was hitting an error because it tried to delete Alice and Bob, but user Bob was never created by the test. This is because the test was creating Alice twice, instead of creating Bob. 
The test now does not hit an error in cleanup.

Fix error in cleanup of registration_timeout big test

---

src/mongoose_rabbit_worker.erl
test/mongoose_rabbit_worker_SUITE.erl

When the rabbit connection is still alive the return will be `{pid(), {ok, pid()}}`. The worker will encounter the error when the next `amqp_channel:call/2`.
This PR ensures the return is the correct data format and adds a test for that.

Ensure maybe_restart_rabbit_connection/1 returns two pids in the tuple.

---

.circleci/config.yml

> `tags`
CircleCI does not run workflows for tags unless you explicitly specify tag filters. Additionally, if a job requires any other jobs (directly or indirectly), you must specify tag filters for those jobs.
https://circleci.com/docs/2.0/configuration-reference/#tags
This was probably lost when we built the setup stage for CircleCI jobs. Gustaw and I had the same problem a long time ago, I think for 3.6 or so, that we realise that by default CircleCI does not run workflows for tags. I just guess this is the reason again, specially after seeing CircleCI says there's no workflow to run after a setup, without errors:

Execute setup workflow for tags as well

---

doc/css/custom.css

The scheme needs to appear in the CSS selector for Material 8.3.3
Tested locally with `mkdocs serve`, and the colors are broken before the change, and fixed after the change.

Fix the Material color scheme for docs

---

doc/authentication-methods/dummy.md
doc/authentication-methods/rdbms.md
doc/configuration/Services.md
doc/configuration/access.md
doc/configuration/acl.md
doc/configuration/configuration-files.md
doc/configuration/general.md
doc/configuration/host_config.md
doc/configuration/listen.md
doc/configuration/s2s.md
doc/configuration/shaper.md

Now all options are set per node.
There are no clustered options anymore.

Drop the obsolete notion of option scope from the docs

---

.circleci/template.yml
src/async_pools/mongoose_aggregator_worker.erl

There are some dialyzer errors caught only on OTP 24, and not on OTP 25, because e.g. some types have changed. We support both, so let's run Dialyzer checks for both.
One type spec fixed to make it pass on OTP 24.

Enable dialyzer for both OTP 24 and OTP 25

---

.circleci/template.yml
src/async_pools/mongoose_aggregator_worker.erl

Resolves missing Erlang 25.0 for the debian stretch package.

Bump OTP version to 25.0.1

---

tools/circle-publish-github-summary-comment.sh

This PR addresses "No more space for comments, reached 2500".
* Post comments there instead https://github.com/esl/MongooseIM/issues/3685

Use a different issue for collecting error comments

---

src/ejabberd_c2s.erl
src/mongoose_acc.erl
src/mongoose_iq.erl

A few tiny optimisations to setting fields in the accumulator, together with places where they can be used, and some microbenchmarkings below. The main optimisation is on generating less garbage to collect later, mainly intermediate maps: adding a key to a map creates a new map that copies lots of parts from the previous, and so adding a list of keys one by one copies the map every time.
Instead, putting all new keys on a map using maps:from_list, and then doing maps:merge, generates no intermediate mongoose_acc map only the temporary map with the new keys, regardless of the number of entries being inserted. Then the resulting map after the merge is the final mongoose_acc.
```
Compiling 1 file (.erl)
Operating System: Linux
CPU Information: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
Number …
```

Mongoose acc pipelining

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/graphql_offline_SUITE.erl
priv/graphql/schemas/admin/admin_schema.gql
priv/graphql/schemas/admin/offline.gql
src/ejabberd_admin.erl
src/graphql/admin/mongoose_graphql_admin_mutation.erl
src/graphql/admin/mongoose_graphql_offline_admin_mutation.erl
src/graphql/mongoose_graphql.erl
src/graphql/mongoose_graphql_errors.erl
src/offline/mod_offline_api.erl

Adding mod_offline admin resolver and tests

Mod offline graphql

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/tcp_listener_SUITE.erl
src/mongoose_tcp_listener.erl

This PR addresses MIM-1660
* Test and case matching

Handle error from inet:sockname/1 in mongoose_tcp_listener

---

big_tests/tests/mongooseimctl_SUITE.erl
src/ejabberd_app.erl
src/ejabberd_ctl.erl
src/graphql/mongoose_graphql_commands.erl
src/graphql/mongoose_graphql_cowboy_handler.erl
src/graphql/mongoose_graphql_response.erl
src/graphql/mongoose_graphql_scalar.erl

A Proof of Concept of an Admin API that wraps the GraphQL API and can fully replace the current CLI implementation (`admin_extra` + `ejabberd_commands`).
Key points:
- Command specification is created on startup and stored in a persistent term. The specs are obtained from GraphQL with the use of introspection. The `graphql_*` modules are not used directly, because code code would get tightly coupled with the implementation of GraphQL, and it wouldn't be possible to switch to another GraphQL library.
- Commands are accepting arguments as JSON and they are returning JSON on success, just like the GraphQL endpoint. This ensures consistency.
- Query and mutation documents are auto-generated in a simple way (`iolist` concatenation) - it seems that this is enough for now.
Not included in this …

GraphQL Admin CLI PoC

---

big_tests/tests/graphql_account_SUITE.erl
big_tests/tests/graphql_helper.erl
big_tests/tests/mongooseimctl_SUITE.erl
big_tests/tests/rest_helper.erl
src/ejabberd_ctl.erl
src/graphql/mongoose_graphql_commands.erl

- Reuse the existing test code for the HTTP API - now there is a 'protocol' option per test group, that can be 'http' or 'cli'.
- Test the basic `mongooseimctl` cases, including errors.
The main drawback is that client API tests look different than admin API tests. This could be theoretically solved with precomputing docs for the client (and domain) endpoints as well, but they are not needed on the server side. We can change this later, if needed.
Also: added `export_all` for helpers, as this is convenient and useful when debugging tests, and we do it for other helpers anyway.
To do in separate stories:
- Test other categories.
- Support unions.
- Display more detailed usage information including category list.
- Document.
- Finally: remove redundant commands replaced by the GraphQL ones. …

Test GraphQL CLI for accounts

---

big_tests/dynamic_domains.config
big_tests/test.config
big_tests/tests/anonymous_SUITE.erl
src/auth/ejabberd_auth.erl
src/auth/ejabberd_auth_anonymous.erl

This PR addresses issue #3703.
After covering the functionality with tests, another bug showed up.
The PR fixes both - see individual commits for details.

Fix anonymous login

---

big_tests/tests/muc_SUITE.erl
src/mod_muc_room.erl

This PR addresses #3705: an instant persistent room was not stored in the DB.
Added missing test, and fixed the bug.

Fix muc persistent room

---

big_tests/tests/graphql_account_SUITE.erl
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_metric_SUITE.erl
big_tests/tests/graphql_vcard_SUITE.erl
src/graphql/mongoose_graphql_commands.erl

Support the UNION type in GraphQL CLI commands.
Unions are returned for metrics and vCards.
The `__typename` field is not added to the result, because the types currently used are not ambiguous and inform explicitly about the type.
Also:
- Add admin CLI tests for metrics and vCards - this ensures that unions are supported correctly.
- Limit type recursion to 2 levels, because vCards may contain nested vCards. If there is a third level of nesting, `__typename` is returned instead of the object fields.

Support unions in GraphQL CLI

---

big_tests/tests/graphql_account_SUITE.erl
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_metric_SUITE.erl
big_tests/tests/graphql_vcard_SUITE.erl
src/graphql/mongoose_graphql_commands.erl

Before the change, admin operations used auto-generated queries, while user operations used manually coded GraphQL documents.
After the change, the `build_specs` function is called with RPC per test group. It auto-generates all queries for the given endpoint. As a byproduct, the query generation code is better tested.
The specs are stored in a persistent term. There was an attempt to store them in `Config`, but the specs are huge, and test reports would grow in size and become less readable.
The scope of this PR includes the `account`, `metrics` and `vcard` categories.
Also:
- Support empty argument lists in query generation. This corner case was revealed by the `unregister` operation.

Generate user queries in GraphQL tests

---

big_tests/tests/graphql_domain_SUITE.erl
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_http_upload_SUITE.erl
big_tests/tests/graphql_inbox_SUITE.erl
big_tests/tests/graphql_last_SUITE.erl
big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_muc_light_SUITE.erl
big_tests/tests/graphql_offline_SUITE.erl
big_tests/tests/graphql_private_SUITE.erl
big_tests/tests/graphql_roster_SUITE.erl
big_tests/tests/graphql_session_SUITE.erl
big_tests/tests/graphql_stanza_SUITE.erl
big_tests/tests/offline_SUITE.erl

Finish testing GraphQL with CLI in a unified way, making use of generated queries.
Categories included in this PR:
Also: fix a race condition in `offline_SUITE`, that for some reason started presenting itself in this PR.

Test GraphQL CLI for all categories

---

big_tests/tests/graphql_domain_SUITE.erl
big_tests/tests/graphql_stats_SUITE.erl
priv/graphql/schemas/admin/admin_schema.gql
src/graphql/admin/mongoose_graphql_admin_mutation.erl
src/graphql/admin/mongoose_graphql_admin_query.erl

Use singular nouns for all category names
Motivation:
- Conflict of the new 'stats' category with the old 'stats' command in CLI.
- Consistency - there is 'metric', 'vcard', 'stanza' etc.
Tests CLI for statistics as well.
Note: I found that there are no tests for error handling in the `stat` category. It's not urgent, so I am not fixing it here.

Update stat and domain categories

---

doc/user-guide/Supported-standards.md

By https://github.com/esl/MongooseIM/blob/9690e607f4b6c28d95f87d064d38d686d5bffac9/src/mongoose_chat_markers.erl#L1-L20
Does it seem the chat markers feature can list in the doc?

Add XEP-0333 Docs

---

rel/files/mongooseim

The custom `erl` script was removed (because it got outdated in OTP 25), and `erlexec` should be used directly now.
`_build/mim1/rel/mongooseim/bin/mongooseimctl debug` fails before the change and succeeds after the change.

Use erlexec in 'mongooseimctl debug'

---

doc/configuration/outgoing-connections.md
src/config/mongoose_config_spec.erl
src/rdbms/mongoose_rdbms.erl
src/wpool/mongoose_wpool_rdbms.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/mongoose_rdbms_SUITE.erl

A strict hardcoded macro is too inflexible and this is a parameter I want to iterate on the configuration easily.

Make RDBMS query timeout configurable

---

src/async_pools/mongoose_async_pools.erl

This one I detected it with the new eqwalizer tool, the flag as given in the current place is ignored.

Fix passing the off_heap flag in the right place

---

src/mam/mam_iq.erl
src/mam/mod_mam_utils.erl

Some functions here are not used, some are used but only locally so we can skip exporting them.

Remove MAM unused functions and exports

---

big_tests/tests/domain_helper.erl
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_roster_SUITE.erl
big_tests/tests/graphql_stats_SUITE.erl
priv/graphql/schemas/admin/roster.gql

Adding example tests to graphql_stats_SUITE and tests to graphql_roster_SUITE. This PR shows how to add tests when the domain is taken from the domain variable and user variable.

Domain admin tests

---

big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl
src/mam/mod_mam.erl
src/mam/mod_mam_muc.erl
src/mam/mod_mam_muc_cassandra_arch.erl
src/mam/mod_mam_pm.erl
src/mam/mod_mam_utils.erl

This PR addresses "complete flag is not always set".
* New shared function mod_mam_utils:lookup/3
* There are two strategies to determine `complete` flag:
* is_complete_result_page_using_offset
* set_complete_result_page_using_extra_message for simple queries.
* set_complete_result_page_using_extra_message asks for an extra message on a page from a DB. After that it hides the message from the user, but sets complete flag properly

Simple MAM queries with complete result flag

---

big_tests/tests/graphql_helper.erl
big_tests/tests/mongooseimctl_SUITE.erl
rel/files/mongooseimctl
src/ejabberd_ctl.erl
src/graphql/mongoose_graphql_commands.erl

There are two main goals of this PR:
The previous argument format for the GraphQL-based CLI was always JSON, which a bit difficult to use. For example, this is how you would ask for the number of users in a domain:
```
mongooseimctl account listUsers '{"domain": "localhost"}'
```
This is how you do it after the change:
```
mongooseimctl account listUsers --domain localhost
```
Strings and integers are automatically processed, so they don't need quoting (unless the string has special characters or spaces).
Arguments with complex types (lists, input objects) need to be passed as JSON.
The new commands are to replace the old ones, which used `admin_extra`.
- `mongooseimctl` on its own displays a list of categories, basic commands (not categorized) and general help.
- `mongooseimctl help` …

GraphQL CLI args as "--name value" with new help

---

src/pubsub/mod_pubsub.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl

This PR addresses MIM-1687.
* A wpool
* Config options
* We use consistent hashing to find a worker

Use wpool for notify_loop in mod_pubsub

---

big_tests/tests/mongooseimctl_SUITE.erl
rel/files/mongooseimctl

- Pass arguments to `ctl` and `ctlexec` to allow calling `ctl status`, which is needed by `mongooseimctl started` and `mongooseimctl stopped`.
- Add tests for `started` and `status`.
- Check `started`, `status` and `stopped` manually.

Fix 'mongooseimctl started'

---

doc/configuration/Services.md
doc/configuration/general.md
doc/developers-guide/domain_management.md
doc/getting-started/Quick-setup.md
doc/modules/mod_commands.md
doc/modules/mod_http_upload.md
doc/operation-and-maintenance/gdpr-considerations.md
doc/tutorials/ICE_tutorial.md
doc/tutorials/Jingle-SIP-setup.md

- Introduce the CLI in "Quick Setup"
- Replace examples of old commands with the new ones.
The GraphQL API itself needs more docs as well - there are examples with REST API that can be converted to GraphQL.

Document the new GraphQL-based CLI

---

big_tests/tests/graphql_SUITE.erl
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_mnesia_SUITE.erl
big_tests/tests/graphql_roster_SUITE.erl
big_tests/tests/graphql_stats_SUITE.erl

Merged execute_auth and execute_domain_admin functions so both types of admins can use execute_command

Reusable code for domain admin tests

---

src/ejabberd_local.erl

The specs says that `process_packet` must return a `mongoose_acc:t()`, but here, if an exception is thrown, we'd return the result of the logged error, which is the `ok` atom, which will crash on a later use of the acc when it was expected to be a map. See the stacktrace below, which throws a `{badmap, ok}` error:
```erl
mongoose_local_delivery:restore_acc_fields/2:57
mongoose_router_localdomain:route/4:25
ejabberd_router:route/5:390
ejabberd_router:route/4:140
ejabberd_c2s:process_outgoing_stanza/4:896
ejabberd_c2s:process_outgoing_stanza/2:868
p1_fsm_old:handle_msg/10:587
proc_lib:wake_up/3:250
```

Do return an Acc unexceptionally!

---

big_tests/tests/graphql_roster_SUITE.erl

Added tests for domain admin in graphql_roster_SUITE. The tests are similar to those for a global admin, but they also check for permissions.

Domain admin tests in roster suite

---

src/async_pools/mongoose_aggregator_worker.erl
src/async_pools/mongoose_async_pools.erl
src/async_pools/mongoose_batch_worker.erl
test/batches_SUITE.erl

Might be useful for telling all workers about a certain event.

Implement broadcasts in async pools

---

src/async_pools/mongoose_aggregator_worker.erl
src/rdbms/mongoose_rdbms.erl
test/batches_SUITE.erl

Maybe one task requests to remove data a previous task added, and in the resulting task after aggregation there is no data to either remove nor request, so we might want to have the request been skipped and the next one been attempted, instead of wasting time and message passing on an empty request.

Extend aggregator requests and fix stall-after-error bug

---

big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_roster_SUITE.erl
priv/graphql/schemas/admin/roster.gql
src/graphql/admin/mongoose_graphql_roster_admin_mutation.erl

This PR fixes types in subscribeAllToAll roster GraphQL API and adds tests for them

Fix types in subscribeAllToAll roster GraphQL API

---

big_tests/tests/inbox_SUITE.erl
big_tests/tests/muc_http_api_SUITE.erl
big_tests/tests/muc_light_http_api_SUITE.erl
big_tests/tests/rest_SUITE.erl
big_tests/tests/rest_helper.erl
rel/files/mongooseim.toml
src/inbox/mod_inbox_api.erl
src/mod_muc_api.erl
src/mod_roster_api.erl
src/mongoose_admin_api/mongoose_admin_api.erl
src/mongoose_admin_api/mongoose_admin_api_contacts.erl
src/mongoose_admin_api/mongoose_admin_api_inbox.erl
src/mongoose_admin_api/mongoose_admin_api_messages.erl
src/mongoose_admin_api/mongoose_admin_api_muc.erl
src/mongoose_admin_api/mongoose_admin_api_muc_light.erl
src/mongoose_admin_api/mongoose_admin_api_sessions.erl
src/mongoose_admin_api/mongoose_admin_api_stanzas.erl
src/mongoose_admin_api/mongoose_admin_api_users.erl
src/mongoose_http_handler.erl
src/mongoose_stanza_api.erl
src/muc_light/mod_muc_light_api.erl
src/muc_light/mod_muc_light_commands.erl

The main goal is to have the following structure for the Admin REST API:
- `mongoose_admin_api` implements `mongoose_http_handler`
- `mongoose_admin_api_*` implement the individual command categories.
This is the same as for the Client API, making the two unified.
The new handler modules are using exceptions for error handling, which makes it less error-prone, as it is easier to read the logic and check if all cases are covered. The previous de-facto convention of multiple nested `case` constructs was less readable.
The following future work is excluded from this PR to reduce its size:
- Update config spec tests to check `mongoose_admin_api` instead of `mongoose_api_admin`
- Remove `mongoose_api_admin`
- Remove `mongoose_commands`
- Change `mongoose_domain_handler` and `mongoose_api` (yet …

Unify the admin REST API

---

src/ejabberd_local.erl
src/inbox/mod_inbox.erl
src/mam/mod_mam_pm.erl
src/mod_adhoc.erl
src/mod_amp.erl
src/mod_auth_token.erl
src/mod_blocking.erl
src/mod_caps.erl
src/mod_carboncopy.erl
src/mod_disco.erl
src/mongoose_hooks.erl
src/privacy/mod_privacy.erl
src/pubsub/mod_pubsub.erl

This PR changes all handlers for `disco_local_features` hook to `gen_hook` format.

Refactored disco_local_features hook to a gen_hook format

---

src/ejabberd_router.erl

This PR changes all hook handlers in `ejabberd_router` module to `gen_hook` format.

Refactored hook handlers in ejabberd_router module

---

src/ejabberd_s2s.erl

This PR changes all hook handlers in `ejabberd_s2s` module to `gen_hook` format.

Refactored hook handlers in ejabberd_s2s module

---

src/ejabberd_sm.erl
src/mongoose_hooks.erl
test/ejabberd_sm_SUITE.erl

This PR changes all hook handlers in `ejabberd_sm` module to `gen_hook` format.

Refactored hook handlers in ejabberd_sm module

---

Makefile
big_tests/run_common_test.erl
big_tests/tests/ejabberd_node_utils.erl
rebar.config
rel/fed1.vars-toml.config
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
rel/mim3.vars-toml.config
rel/reg1.vars-toml.config
rel/vars-toml.config
tools/test_runner/apply_templates.erl

As stated in the [rebar3 docs](https://rebar3.readme.io/docs/releases):
- There should be only one overlay file. I checked with the docs and the code, it just supports one file now.
- You can include one file from another. I checked that if a variable is declared more than once, the last value wins (https://github.com/erlware/relx/blob/main/src/rlx_overlay.erl#L149).
This is why we can just include the overlay files:
- `configure.vars.config` into `vars-toml.config`
- `vars-toml.config` into `*.vars-toml.config`
This way the overlays work correctly with the latest Rebar3, and there is no need to concatenate the files with `make`.
We have some templating utilities for tests, and they needed support for file inclusion as well.

Fix and simplify overlays

---

test/mod_websockets_SUITE.erl

The supervisor tree was changed in newer version of ranch. This commit fixes the issue with getting a list of ranch connections.

Fix mod_websockets_SUITE

---

big_tests/tests/graphql_domain_SUITE.erl
big_tests/tests/service_domain_db_SUITE.erl
doc/migrations/5.1.0_6.0.0.md
priv/graphql/schemas/global/domain.gql
priv/migrations/mssql_5.1.0_6.0.0.sql
priv/migrations/mysql_5.1.0_6.0.0.sql
priv/migrations/pgsql_5.1.0_6.0.0.sql
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
src/domain/mongoose_domain_api.erl
src/domain/mongoose_domain_sql.erl
src/graphql/admin/mongoose_graphql_domain_admin_mutation.erl
src/graphql/admin/mongoose_graphql_domain_admin_query.erl
src/graphql/mongoose_graphql_domain.erl
src/graphql/mongoose_graphql_enum.erl
src/graphql/mongoose_graphql_types.hrl
src/mongoose_hooks.erl

```
Current logic for domain deletion first checks that the domain exists,
then removes the domain, and then runs the remove_domain hook. But this
is a problem, because if any of the hooks fails, then retrying the
domain removal won’t work, because it will be stopped at the first check
for domain existence.
Here we instead mark the domain as "in progress for deletion", which
will already disable it, and only finally delete it _after_ all hook
handlers have run hopefully successfully.
```

Remove domain/retries

---

src/mongoose_admin_api/mongoose_admin_api.erl
src/mongoose_admin_api/mongoose_admin_api_contacts.erl
src/mongoose_admin_api/mongoose_admin_api_domain.erl
src/mongoose_admin_api/mongoose_admin_api_inbox.erl
src/mongoose_admin_api/mongoose_admin_api_messages.erl
src/mongoose_admin_api/mongoose_admin_api_metrics.erl
src/mongoose_admin_api/mongoose_admin_api_muc.erl
src/mongoose_admin_api/mongoose_admin_api_muc_light.erl
src/mongoose_admin_api/mongoose_admin_api_sessions.erl
src/mongoose_admin_api/mongoose_admin_api_stanzas.erl
src/mongoose_admin_api/mongoose_admin_api_users.erl
src/mongoose_client_api/mongoose_client_api.erl
src/mongoose_client_api/mongoose_client_api_contacts.erl
src/mongoose_client_api/mongoose_client_api_messages.erl
src/mongoose_client_api/mongoose_client_api_rooms.erl
src/mongoose_client_api/mongoose_client_api_rooms_config.erl
src/mongoose_client_api/mongoose_client_api_rooms_messages.erl
src/mongoose_client_api/mongoose_client_api_rooms_users.erl
src/mongoose_client_api/mongoose_client_api_sse.erl
src/mongoose_http_handler.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl

Unify the handler configuration for Client and Admin REST API.
- Make Admin API handlers configurable
- Specify only handler suffixes instead of the long module names
- Delegate route declaration to handler modules - this way the whole logic of a handler is in one module, and there are no long lists of Cowboy routes.
Remaining work after this PR:
- Document the updated REST API, including this change.

Unified REST API handlers

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/amp_big_SUITE.erl
src/c2s/mongoose_c2s.erl
src/ejabberd_sm_redis.erl
src/mod_amp.erl

Fixes AMP big suite

---

src/event_pusher/mod_event_pusher_push.erl

This PR changes all hook handlers in `mod_event_pusher_push` module to `gen_hook` format.

Refactored hook handler in mod_event_pusher_push module

---

src/event_pusher/mod_event_pusher_hook_translator.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_event_pusher_hook_translator` module to `gen_hook` format.

Refactored hook handlers in mod_event_pusher_hook_translator module

---

src/global_distrib/mod_global_distrib.erl

This PR changes all hook handlers in `mod_global_distrib` module to `gen_hook` format.
Note: I added `mod_global_distrib:maybe_reroute/3` to the list of handlers which use `drop` atom as a return value. They shall be refactored in another task.

Refactored hook handler in mod_global_distrib module

---

src/global_distrib/mod_global_distrib.erl
src/global_distrib/mod_global_distrib_bounce.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_global_distrib_bounce` module to `gen_hook` format.
Note: I added `mod_global_distrib_bounce: maybe_store_message/3` to the list of handlers which use drop atom as a return value. They shall be refactored in another task.

Refactored hook handlers in mod_global_distrib_bounce module

---

priv/graphql/schemas/admin/account.gql
priv/graphql/schemas/admin/admin_auth_status.gql
priv/graphql/schemas/admin/admin_schema.gql
priv/graphql/schemas/admin/last.gql
priv/graphql/schemas/admin/metric.gql
priv/graphql/schemas/admin/mnesia.gql
priv/graphql/schemas/admin/muc_light.gql
priv/graphql/schemas/admin/offline.gql
priv/graphql/schemas/admin/private.gql
priv/graphql/schemas/admin/roster.gql
priv/graphql/schemas/admin/server.gql
priv/graphql/schemas/admin/stanza.gql
priv/graphql/schemas/admin/stats.gql
priv/graphql/schemas/admin/token.gql
priv/graphql/schemas/admin/vcard.gql
priv/graphql/schemas/global/muc.gql
priv/graphql/schemas/global/muc_light.gql
priv/graphql/schemas/global/roster.gql
priv/graphql/schemas/global/scalar_types.gql
priv/graphql/schemas/global/spectaql_dir.gql
priv/graphql/schemas/global/stanza.gql
priv/graphql/schemas/global/token.gql
priv/graphql/schemas/global/vcard.gql
src/ejabberd_ctl.erl

This PR adds documentation to the GraphQL types that were missing before

Documented missing GraphQL types

---

src/global_distrib/mod_global_distrib_disco.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_global_distrib_disco` module to `gen_hook` format.

Refactored hook handler in mod_global_distrib_disco module

---

big_tests/dynamic_domains.config
big_tests/test.config
rebar.config
rel/fed1.vars-toml.config
rel/files/mongooseim.toml
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
rel/mim3.vars-toml.config
rel/prod.vars-toml.config
rel/reg1.vars-toml.config
rel/vars-toml.config

There is an issue with the overriding logic in `relx`: included vars override previously defined ones, but there is no simple
way of overriding the included vars other than including another file. This way making the `dev` releases resulted in incorrect vars.
Big tests succeeded because they had their own overriding logic.
This change ensures that no vars are overridden. The included file is always at the bottom, and in this case both `relx` and our templating scripts work the same (included vars override the previous ones).
Another changes:
- Avoid specifying defaults explicitly - they are documented, and the user could define them with different values if necessary.
- Rename `mim2` node for consistency.
Possible further improvements:
- Improve `relx` with a more intuitive and useful …

Don't override included overlay vars

---

big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_http_upload_SUITE.erl
big_tests/tests/graphql_inbox_SUITE.erl
big_tests/tests/graphql_last_SUITE.erl
big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_muc_light_SUITE.erl
big_tests/tests/graphql_offline_SUITE.erl
big_tests/tests/graphql_private_SUITE.erl
big_tests/tests/graphql_token_SUITE.erl
big_tests/tests/graphql_vcard_SUITE.erl
big_tests/tests/muc_helper.erl
priv/graphql/schemas/admin/http_upload.gql
priv/graphql/schemas/admin/muc.gql
priv/graphql/schemas/admin/muc_light.gql
priv/graphql/schemas/admin/offline.gql
priv/graphql/schemas/admin/private.gql
priv/graphql/schemas/admin/token.gql
priv/graphql/schemas/admin/vcard.gql
priv/graphql/schemas/user/http_upload.gql
priv/graphql/schemas/user/muc.gql
priv/graphql/schemas/user/muc_light.gql
priv/graphql/schemas/user/private.gql
priv/graphql/schemas/user/token.gql
priv/graphql/schemas/user/vcard.gql
src/graphql/admin/mongoose_graphql_muc_light_admin_mutation.erl
src/http_upload/mod_http_upload_api.erl
src/mod_private_api.erl
src/offline/mod_offline_api.erl
src/vcard/mod_vcard_api.erl

In this PR I have added "@use" directive to all schemas where it was needed. Moreover, I have deleted any unnecessary checks in API modules. The problems occurred with 3 modules:
- mod_muc
- mod_muc_light
- mod_vcard
---
In mod_muc there are 4 commands that are currently not using @use directive:
- ADMIN createInstantRoom -> it is currently impossible to get HostType from mucDomain variable
- ADMIN listRooms -> it is currently impossible to get HostType from mucDomain variable 
- USER createInstantRoom -> it is currently impossible to get HostType from mucDomain variable
- USER listRooms -> it is currently impossible to get HostType from mucDomain variable
In mod_muc_light there are 2 commands that are currently not using @use directive:
- ADMIN createInstantRoom -> it is currently …

Graphql use annotation

---

src/jingle_sip/mod_jingle_sip.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_jingle_sip` module to `gen_hook` format.

Refactored hook handler in mod_jingle_sip module

---

src/inbox/mod_inbox.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_inbox` module to `gen_hook` format.

Refactored hook handlers in mod_inbox module

---

big_tests/tests/distributed_helper.erl
big_tests/tests/graphql_server_SUITE.erl
src/ejabberd_ctl.erl
src/graphql/admin/mongoose_graphql_server_admin_mutation.erl
src/graphql/mongoose_graphql.erl
src/graphql/mongoose_graphql_commands.erl
src/graphql/mongoose_graphql_cowboy_handler.erl

Adding the method(HTTP or CLI) to graphQL context is being passed to the execute function.
Based on this added variable in context, the execution of server commands is different for HTTP calls and CLI calls.

Adding support for http calling of the graphql_server commands

---

big_tests/tests/mam_helper.erl
src/inbox/mod_inbox.erl
src/mam/mod_mam_pm.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_mam_pm` module to `gen_hook` format.

Refactored hook handlers in mod_mam_pm module

---

src/graphql/user/mongoose_graphql_stanza_user_mutation.erl
src/mam/mod_mam_muc.erl
src/mam/mod_mam_pm.erl
src/mod_private.erl

This PR addresses "just found some code which is a bit weird".
* use jid:are_bare_equal instead of writing the same function in the modules.
* don't use imports in mam to make code a bit cleaner - we usually use the imported function only once.

Remove imports, use library function [refactor]

---

src/metrics/mongoose_metrics.erl
src/metrics/mongoose_metrics_hooks.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mongoose_metrics` module to `gen_hook` format.

Refactored hook handlers in mongoose_metrics module

---

big_tests/tests/rest_client_SUITE.erl
src/event_pusher/mod_event_pusher_hook_translator.erl
src/mam/mod_mam_pm.erl
src/mongoose_client_api/mongoose_client_api.erl
src/mongoose_client_api/mongoose_client_api_contacts.erl
src/mongoose_client_api/mongoose_client_api_messages.erl
src/mongoose_client_api/mongoose_client_api_rooms.erl
src/mongoose_client_api/mongoose_client_api_rooms_config.erl
src/mongoose_client_api/mongoose_client_api_rooms_messages.erl
src/mongoose_client_api/mongoose_client_api_rooms_users.erl
src/mongoose_hooks.erl
src/muc_light/mod_muc_light_api.erl
src/muc_light/mod_muc_light_room_config.erl
src/muc_light/mod_muc_light_utils.erl

Rework all `mongoose_client_api_*` modules to follow the design patterns of `mongoose_admin_api_*`.
- `mongoose_client_api` has generic helpers for authentication, error handling, argument parsing etc.
- `mongoose_client_api_*` modules use the helpers consistently, and call the API helper modules (e.g. `mod_muc_light_api`) similarly to the GraphQL handlers.
Other changes:
- Fixed minor issues with error handling for MUC Light.
- Improved the test coverage by adding tests and fixing already existing ones.
Notes:
- Some API functionality exceeds the GraphQL equivalent, e.g. for MUC Light there is a support for chat markers, and stanzas are given UUID's. I haven't added these options to GraphQL, but we might want to do it later.

Refactor Client REST API handlers

---

big_tests/tests/graphql_muc_light_SUITE.erl
big_tests/tests/graphql_stanza_SUITE.erl
priv/graphql/schemas/global/muc_light.gql
rebar.lock
src/graphql/mongoose_graphql.erl

This PR changes how arguments are processed before being passed to the resolver. When an argument has an explicit null value, the GraphQL library tries to set its value to a default one if one exists.

Set default value when null is passed to GraphQL API

---

big_tests/tests/domain_rest_helper.erl
big_tests/tests/graphql_domain_SUITE.erl
big_tests/tests/service_domain_db_SUITE.erl
doc/rest-api/Administration-backend_swagger.yml
priv/graphql/schemas/admin/domain.gql
src/domain/mongoose_domain_api.erl
src/domain/mongoose_domain_db_cleaner.erl
src/domain/mongoose_domain_sql.erl
src/graphql/admin/mongoose_graphql_domain_admin_mutation.erl
src/mongoose_admin_api/mongoose_admin_api_domain.erl

Most often, tenant deletion can incur in many many DB operations, which can introduce very long delays and timeout any HTTP connection. And when the HTTP connection times out, the cowboy process running the tenant deletion hook will timeout, and could potentially leave the DB in an inconsistent state.

Remove domain/async

---

big_tests/tests/graphql_muc_SUITE.erl
priv/graphql/schemas/admin/muc.gql
src/mod_muc_api.erl

This PR addresses #3752
* Check the result of make_jid
* Require from argument.

Fix muc validation in graphql

---

src/amp_resolver.erl
src/amp_strategy.erl
src/mod_amp.erl
src/mongoose_hooks.erl
test/amp_resolver_SUITE.erl

This PR changes all hook handlers in `mod_amp` module to `gen_hook` format.

Refactored hook handlers in mod_amp module

---

src/mongoose_hooks.erl
src/smart_markers/mod_smart_markers.erl

This PR changes all hook handlers in `mod_smart_markers` module to `gen_hook` format. Also, I did a little refactoring of `mod_smart_markers :room_new_affiliations` function.

Refactored hook handlers in mod_smart_markers

---

src/mod_ping.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_ping` module to `gen_hook` format.

Refactored hook handlers in mod_ping

---

big_tests/tests/acc_e2e_SUITE.erl
big_tests/tests/acc_e2e_SUITE_data/acc_test_helper.erl

This PR changes all hook handlers in `acc_e2e_SUITE` to `gen_hook` format.

Refactored hook handlers in acc_e2e_SUITE

---

src/global_distrib/mod_global_distrib_mapping.erl
src/mongoose_hooks.erl
test/mod_global_distrib_SUITE.erl

This PR changes all hook handlers in `mod_global_distrib_mapping` module to `gen_hook` format.

Refactored hook handlers in mod_global_distrib_mapping

---

src/auth/ejabberd_auth.erl
src/auth/ejabberd_auth_anonymous.erl
src/mongoose_hooks.erl
test/mongoose_cleanup_SUITE.erl

Convert ejabberd_auth to gen_hook

Convert ejabberd_auth to gen_hook

---

src/mongoose_hooks.erl
src/vcard/mod_vcard.erl

Convert mod_vcard to gen_hook

---

src/mod_adhoc.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_adhoc` module to `gen_hook` format.

Refactored hook handlers in mod_adhoc

---

src/mod_blocking.erl

This PR changes all hook handlers in `mod_blocking` module to `gen_hook` format.

Refactored hook handlers in mod_blocking

---

src/http_upload/mod_http_upload.erl

This PR changes all hook handlers in `mod_http_upload` module to `gen_hook` format.

Refactored hook handlers in mod_http_upload

---

src/mod_auth_token.erl

This PR changes all hook handlers in `mod_auth_token` module to `gen_hook` format.

Refactored hook handlers in mod_auth_token

---

src/mod_bosh.erl

This PR changes all hook handlers in `mod_bosh` module to `gen_hook` format.

Refactored hook handlers in mod_bosh

---

src/gen_hook.erl
src/mam/mod_mam_muc.erl
src/mam/mod_mam_pm.erl
src/metrics/mongoose_metrics_mam_hooks.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mongoose_metrics_mam_hooks` module to `gen_hook` format.

Refactored hook handlers in mongoose_metrics_mam_hooks

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_sse_SUITE.erl
big_tests/tests/graphql_stanza_SUITE.erl
big_tests/tests/rest_client_SUITE.erl
big_tests/tests/sse_helper.erl
doc/configuration/listen.md
doc/graphql-api/Admin-GraphQL.md
doc/graphql-api/User-GraphQL.md
priv/graphql/schemas/admin/admin_schema.gql
priv/graphql/schemas/admin/stanza.gql
priv/graphql/schemas/user/stanza.gql
priv/graphql/schemas/user/user_schema.gql
src/graphql/admin/mongoose_graphql_admin_subscription.erl
src/graphql/admin/mongoose_graphql_stanza_admin_subscription.erl
src/graphql/mongoose_graphql.erl
src/graphql/mongoose_graphql_commands.erl
src/graphql/mongoose_graphql_cowboy_handler.erl
src/graphql/mongoose_graphql_errors.erl
src/graphql/mongoose_graphql_operations.erl
src/graphql/mongoose_graphql_sse_handler.erl
src/graphql/mongoose_graphql_stanza_helper.erl
src/graphql/user/mongoose_graphql_stanza_user_subscription.erl
src/graphql/user/mongoose_graphql_user_subscription.erl
src/mongoose_client_api/mongoose_client_api_sse.erl
src/mongoose_stanza_api.erl

The goal of this PR is to deliver incoming messages with the use of GraphQL **subscriptions**.
Such functionality existed for REST API, and it used SSE (Server-Sent Events) with [Lasse](https://github.com/inaka/lasse).
This GraphQL solution is using SSE as well.
According to [GraphQL specification](https://spec.graphql.org/draft/#sec-Subscription), executing a subscription should return a *Response Stream*, that will deliver the events to the subscriber. As the `graphql` library executes subscriptions the same way as queries, the subscription needs to be executed several times:
1. The first execution should return `null` in `data`, and a new Stream in `aux`, which corresponds to the *Source Stream* from the GraphQL docs.
2. Then, whenever an Event is received, the already processed and …

GraphQL subscriptions for stanzas

---

big_tests/tests/domain_removal_SUITE.erl
src/mod_cache_users.erl

This PR changes all hook handlers in `mod_cache_users` module to `gen_hook` format.

Refactored hook handlers in mod_cache_users

---

big_tests/tests/inbox_SUITE.erl
big_tests/tests/inbox_extensions_SUITE.erl
big_tests/tests/inbox_helper.erl
src/inbox/mod_inbox.erl
src/jlib.erl

Currently inbox introduces only the max key of the [RSM XEP](https://xmpp.org/extensions/xep-0059.html), and within the inbox form we also allow for setting something equivalent to the RSM’s before and after. But there’s no RSM payload in the iq-fin-result, and also, helper libraries might be used on the client side for more complex pagination, provided full support for RSM is available.
This PR introduces support for points:
- [Limiting the Number of Items](https://xmpp.org/extensions/xep-0059.html#limit)
- [Paging Forwards Through a Result Set](https://xmpp.org/extensions/xep-0059.html#forwards)
- [Paging Backwards Through a Result Set](https://xmpp.org/extensions/xep-0059.html#backwards)
Other points in the document might be implemented fully or partially but I haven't taken them into …

Inbox/pagination — part 1

---

src/mod_disco.erl

This PR changes all hook handlers in `mod_disco` module to `gen_hook` format.

Refactored hook handlers in mod_disco

---

big_tests/tests/graphql_account_SUITE.erl
big_tests/tests/oauth_SUITE.erl
big_tests/tests/rest_SUITE.erl
priv/graphql/schemas/admin/account.gql
src/auth/ejabberd_auth.erl
src/ejabberd_admin.erl
src/ejabberd_ctl.erl
src/graphql/admin/mongoose_graphql_account_admin_mutation.erl
src/graphql/admin/mongoose_graphql_account_admin_query.erl
src/mongoose_account_api.erl
src/mongoose_admin_api/mongoose_admin_api_users.erl

This PR improves error handling for common corner cases in account API

Improve error handling in account API

---

big_tests/tests/graphql_last_SUITE.erl
src/admin_extra/service_admin_extra_accounts.erl
src/graphql/admin/mongoose_graphql_last_admin_mutation.erl
src/graphql/admin/mongoose_graphql_last_admin_query.erl
src/mod_last_api.erl

This PR changes some of the returned values from "last" module's functions to be more consistent with the whole GraphQL API

Improve error handling in API module last

---

src/mod_keystore.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_keystore` module to `gen_hook` format.

Refactored hook handlers in mod_keystore

---

big_tests/tests/graphql_gdpr_SUITE.erl
src/gdpr_api.erl
src/graphql/admin/mongoose_graphql_gdpr_admin_query.erl

Improving error handling for errors connected with file creation. Until now, when a user inserted a strange file name such as "", or tried to create a file in a location where the permissions were insufficient for such operation, graphQL returned a simple "Internal server error". Now, this errors have their own error code and proper error message.

Improve error handling in gdpr_api

---

big_tests/tests/mam_SUITE.erl
src/mam/mod_mam_pm.erl

When client sends a message to yourself (for making notes, fo r example), we store the message twice. We should store only once.
This PR addresses MIM-1707 https://github.com/esl/MongooseIM/issues/3294#top
* Store only outgoing packet.

Do not store message sent to yourself

---

big_tests/tests/common_helper.erl
big_tests/tests/graphql_account_SUITE.erl
big_tests/tests/graphql_gdpr_SUITE.erl
big_tests/tests/graphql_http_upload_SUITE.erl
big_tests/tests/graphql_inbox_SUITE.erl
big_tests/tests/graphql_last_SUITE.erl
big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_muc_light_SUITE.erl
big_tests/tests/graphql_offline_SUITE.erl
big_tests/tests/graphql_session_SUITE.erl
big_tests/tests/graphql_stats_SUITE.erl
big_tests/tests/inbox_helper.erl
big_tests/tests/mongooseimctl_SUITE.erl
priv/graphql/schemas/admin/account.gql
priv/graphql/schemas/admin/admin_auth_status.gql
priv/graphql/schemas/admin/domain.gql
priv/graphql/schemas/admin/gdpr.gql
priv/graphql/schemas/admin/http_upload.gql
priv/graphql/schemas/admin/inbox.gql
priv/graphql/schemas/admin/last.gql
priv/graphql/schemas/admin/muc.gql
priv/graphql/schemas/admin/muc_light.gql
priv/graphql/schemas/admin/offline.gql
priv/graphql/schemas/admin/session.gql
priv/graphql/schemas/admin/stats.gql
priv/graphql/schemas/user/muc.gql
priv/graphql/schemas/user/muc_light.gql

The main goal is to use the `DomainName` instead of `String` for all fields containing XMPP doman names in the GraphQL schema. This ensures that the domain is string-prepped:
- for the checks of `@use` and `@protected` directives.
- for the API logic itself. Here we might have already existing stringprepping, which we could remove as we rework the individual API modules.
Appropriate tests are added with an "unprepped" domain, that starts with a capital letter.
`inbox_helper` contained nested `wait_until` calls, which resulted in an almost never-ending loop of retries in case of a permanent failure. The checking logic is flattened to a single `wait_until` now.

Use the DomainName type in GraphQL

---

big_tests/tests/graphql_account_SUITE.erl
big_tests/tests/graphql_gdpr_SUITE.erl
big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_muc_light_SUITE.erl
priv/graphql/schemas/admin/account.gql
priv/graphql/schemas/admin/gdpr.gql
priv/graphql/schemas/admin/muc.gql
priv/graphql/schemas/admin/muc_light.gql
priv/graphql/schemas/admin/session.gql
priv/graphql/schemas/global/scalar_types.gql
priv/graphql/schemas/user/muc.gql
priv/graphql/schemas/user/muc_light.gql
priv/graphql/schemas/user/session.gql
priv/graphql/schemas/user/user_auth_status.gql
src/graphql/mongoose_graphql_scalar.erl

Add GraphQL types: `UserName`, `RoomName` and `ResourceName`. We already have `DomainName`.
The new types ensure that the input data is string-prepped correctly, and that no empty strings are allowed.
`RoomName` and `UserName` have the same syntax, but I think that their semantics are different enough to separate them. I tried to have one type called `LocalName`, but it was confusing. Something like `LocalPart` would be even more cryptic.
Added tests for the new types.

Add GraphQL types for JID parts

---

big_tests/tests/graphql_offline_SUITE.erl
priv/graphql/schemas/admin/offline.gql
src/ejabberd_admin.erl
src/offline/mod_offline_api.erl

Improve error handling in offline

Improve error handling in offline

---

src/mod_private.erl

This PR changes all hook handlers in `mod_private` module to `gen_hook` format.

Refactored hook handlers in mod_private

---

src/auth/ejabberd_auth_anonymous.erl
src/mod_last.erl
src/mongoose_hooks.erl
test/mongoose_cleanup_SUITE.erl

This PR changes all hook handlers in `mod_last` module to `gen_hook` format.

Refactored hook handlers in mod_last

---

mkdocs.yml

I've noticed that the tabbed content was not rendering properly. Seems like a new configuration option is required for the tabbed plugin, so I've added it.
Before:
After:

Fix tabbed content in the documentation

---

big_tests/tests/graphql_http_upload_SUITE.erl
priv/graphql/schemas/admin/http_upload.gql
priv/graphql/schemas/global/http_upload.gql
priv/graphql/schemas/user/http_upload.gql
src/http_upload/mod_http_upload_api.erl

Improve error handling in httpUpload

Improve error handling in httpUpload

---

src/admin_extra/service_admin_extra_stats.erl
src/graphql/admin/mongoose_graphql_stats_domain.erl
src/graphql/admin/mongoose_graphql_stats_global.erl
src/stats_api.erl

Improve error handling in stat

Improve error handling in stat

---

src/mod_shared_roster_ldap.erl
src/mongoose_hooks.erl

This PR changes all hook handlers in `mod_shared_roster_ldap` module to `gen_hook` format.

Refactored hook handlers in mod_shared_roster_ldap

---

big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/mam_helper.erl
priv/graphql/schemas/admin/muc.gql
priv/graphql/schemas/global/muc.gql
priv/graphql/schemas/global/scalar_types.gql
priv/graphql/schemas/user/muc.gql
src/graphql/admin/mongoose_graphql_muc_admin_mutation.erl
src/graphql/admin/mongoose_graphql_muc_admin_query.erl
src/graphql/mongoose_graphql_commands.erl
src/graphql/mongoose_graphql_helper.erl
src/graphql/mongoose_graphql_muc_helper.erl
src/graphql/mongoose_graphql_scalar.erl
src/graphql/user/mongoose_graphql_muc_user_mutation.erl
src/graphql/user/mongoose_graphql_muc_user_query.erl
src/mod_muc_api.erl
src/mongoose_admin_api/mongoose_admin_api_muc.erl

The goal is to check and test error conditions in the MUC GraphQL API.
Main changes:
- Pass the whole room JID on room creation. It is more straightforward than passing both JID parts separately.
- Room JIDs should be bare.
- Nicks should be valid resource names.
- MAM-related operations check if the module is enabled.
- All JID types require the local part now.
Discovered bugs that should be fixed separately:
- If `mod_mam_muc` is enabled for `muclight.localhost`, it also stores messages for `muc.localhost`. Actually this misconfiguration was present in the tests, which were passing because of the bug.

Improve GraphQL error handling for MUC

---

src/mongoose_hooks.erl
src/privacy/mod_privacy.erl

This PR changes all hook handlers in `mod_privacy` module to `gen_hook` format.

Refactored hook handlers in mod_privacy

---

src/mod_ping.erl
src/mongoose_hooks.erl
src/pubsub/mod_pubsub.erl

This PR changes all hook handlers in `mod_pubsub` module to `gen_hook` format.

Refactored hook handlers in mod_pubsub

---

src/wpool/mongoose_wpool_cassandra.erl
test/mongoose_wpool_SUITE.erl

This PR addresses:
```
12:57:11.359 [error] Supervisor {<0.559.0>,cqerl_client_sup} had child {cqerl_client,
{{"cassandra.default.svc.cluster.local",9042},
[{cassandra_clusters,
[{default,
{[{"cassandra.default.svc.cluster.local",9042}],
[{keyspace,mongooseim},
{cqerl_auth_plain_handler,
[{<<"admin">>,<<"SECRET">>}]},
{tcp_opts,[{keepalive,true}]}]}}]},
{cqerl_auth_plain_handler,[{<<"admin">>,<<"SECRET">>}]},
{keyspace,mongooseim},
{maps,true},
{num_clients,5},
{tcp_opts,[{keepalive,true}]}]},
2} started with cqerl_client:start_link({"cassandra.default.svc.cluster.local",9042}, [{ssl,false},{keyspace,mongooseim}], #Fun<cqerl.3.76336564>, {{"cassandra.default.svc.cluster.local",9042},[{cassandra_clusters,[{default,{[{"cassandra....",...}],...}}]},...]}) at <0.573.0> exit with reason …
```

Fix cassandra auth parameters parsing

---

big_tests/tests/graphql_server_SUITE.erl
src/admin_extra/service_admin_extra_node.erl
src/ejabberd_admin.erl
src/graphql/admin/mongoose_graphql_server_admin_mutation.erl
src/graphql/admin/mongoose_graphql_server_admin_query.erl
src/mongoose_server_api.erl

Improve error handling in server

Improve error handling in server

---

big_tests/tests/graphql_roster_SUITE.erl
priv/graphql/schemas/admin/roster.gql
priv/graphql/schemas/user/roster.gql
src/graphql/admin/mongoose_graphql_roster_admin_mutation.erl
src/mod_roster_api.erl

Fixing one error in schema, it was possible to call subscription and not pass subscription action.
I've also changed the mod_roster_api:subscription to ensure the stanza is being sent to bare jid.

Fixing errors in mod_roster

---

src/ejabberd_hooks.erl
src/stream_management/mod_stream_management.erl

This PR changes all hook handlers in `mod_stream_management` module to `gen_hook` format.

Refactored hook handlers in mod_stream_management

---

test/auth_tokens_SUITE.erl

This PR changes all hook handlers in `auth_tokend_SUITE` to `gen_hook` format.

Refactored hook handlers in auth_tokend_SUITE

---

big_tests/tests/domain_removal_SUITE.erl
doc/modules/mod_inbox.md
src/inbox/mod_inbox.erl
src/inbox/mod_inbox_backend.erl
src/inbox/mod_inbox_rdbms.erl
src/inbox/mod_inbox_rdbms_async.erl
src/mam/mod_mam_utils.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl

This PR implements for inbox what was implemented already in https://github.com/esl/MongooseIM/pull/3777
Quoting and adapting to the inbox context, the current query, looking like:
DELETE FROM inbox WHERE domain = ?
is, while technically correct, surely going to fail because of timeouts, once it is actually removing any big data.
This PR introduces a configuration flag that allows to set a batch size, and then a delete work will commit only deleting that many records, and iterates until nothing more is deleted.

Remove domain/incremental db deletes

---

big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_muc_light_SUITE.erl
big_tests/tests/muc_light_http_api_SUITE.erl
big_tests/tests/rest_client_SUITE.erl
priv/graphql/schemas/admin/muc_light.gql
priv/graphql/schemas/global/muc_light.gql
priv/graphql/schemas/user/muc_light.gql
src/graphql/admin/mongoose_graphql_muc_light_admin_mutation.erl
src/graphql/admin/mongoose_graphql_muc_light_admin_query.erl
src/graphql/mongoose_graphql_muc_light_helper.erl
src/graphql/user/mongoose_graphql_muc_light_user_mutation.erl
src/graphql/user/mongoose_graphql_muc_light_user_query.erl
src/mongoose_admin_api/mongoose_admin_api_muc_light.erl
src/mongoose_client_api/mongoose_client_api_rooms.erl
src/mongoose_client_api/mongoose_client_api_rooms_messages.erl
src/mongoose_client_api/mongoose_client_api_rooms_users.erl
src/muc_light/mod_muc_light_api.erl

The main goal is to handle the error cases:
- Non-existent users shouldn't be room owners or message senders, and they shouldn't be able to have blocking lists.
- 'Room not found' should be returned if the room does not exist.
Other functional changes:
- Name and subject are not required, because they shouldn't be. They have defaults, and they can be removed by the used in a custom room config schema.
- Only room owner should be able to kick room members.
- Room JID is always bare in the schema. User JID's are not required to be bare if this doesn't break anything. The resources are mostly ignored.
- Update required modules and protected domains in the schema.
Operations are broken into reusable steps, and a fold operation is used to iterate over them.

GraphQL error handling in MUC Light

---

big_tests/tests/graphql_metric_SUITE.erl
src/graphql/admin/mongoose_graphql_metric_admin_query.erl
src/metrics/mongoose_metrics_api.erl

This PR fixes a bug with querying host types, generates an error message for nonexistent nodes, and tests the new API behavior.

Improve error handling in metric API

---

big_tests/tests/graphql_session_SUITE.erl
priv/graphql/schemas/admin/session.gql
src/admin_extra/service_admin_extra_accounts.erl
src/admin_extra/service_admin_extra_sessions.erl
src/graphql/admin/mongoose_graphql_session_admin_mutation.erl
src/graphql/admin/mongoose_graphql_session_admin_query.erl
src/graphql/mongoose_graphql_muc_helper.erl
src/graphql/mongoose_graphql_session_helper.erl
src/graphql/user/mongoose_graphql_session_user_query.erl
src/mongoose_account_api.erl
src/mongoose_admin_api/mongoose_admin_api_sessions.erl
src/mongoose_session_api.erl

Improve error handling in session

Improve error handling in session

---

src/ejabberd_app.erl
src/ejabberd_ctl.erl
src/ejabberd_hooks.erl
src/gen_hook.erl
src/mod_roster.erl
src/mongoose_hooks.erl
src/vcard/mod_vcard.erl

This PR changes all hook handlers in `ejabberd_ctl` to `gen_hook` format.

Refactored hook handlers in ejabberd_ctl

---

big_tests/tests/graphql_vcard_SUITE.erl
rebar.lock
src/graphql/admin/mongoose_graphql_vcard_admin_mutation.erl
src/graphql/admin/mongoose_graphql_vcard_admin_query.erl
src/graphql/user/mongoose_graphql_vcard_user_mutation.erl
src/graphql/user/mongoose_graphql_vcard_user_query.erl
src/vcard/mod_vcard_api.erl

Improve error handling in vcard

Improve error handling in vcard

---

big_tests/tests/graphql_helper.erl
big_tests/tests/rest_helper.erl
doc/configuration/listen.md
doc/graphql-api/Admin-GraphQL.md
rel/files/mongooseim.toml
src/graphql/mongoose_graphql_handler.erl
src/graphql/mongoose_graphql_sse_handler.erl
src/mongoose_http_handler.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/mongoose_graphql_SUITE.erl

None of the remaining HTTP handlers have 'cowboy' in their names, and there is no reason why the user would have to know that currently we are using Cowboy. This is an implementation detail that might change anyway.

Simplify the GraphQL handler name

---

.circleci/template.yml

The `build_and_deploy_docs` job is failing because the old `npm` does not work with the latest `spectaql`

Update npm to work with the latest SpectaQL

---

rel/files/mongooseim
rel/files/mongooseimctl
tools/gh-actions-configure-preset.sh

GNU grep 3.8 prints the following warning when you call `egrep`:
```
egrep: warning: egrep is obsolescent; using grep -E
```
That warning would be visible every time you use `mongooseimctl` - checked on a Linux machine

Replace 'egrep' with 'grep -E'

---

doc/History.md

This PR addresses MIM-1711
* Also added links to the releases (to be consistent).
* Bullet points are more easy to read.
* Added more info, for example, for years 2018-2019. 
* Removed Next, Next, Next sentences, because the order is in reverse.
Still could be refactored a bit, because 2011 and 2012-2015 blocks have a lot of common items (could be even merged).
Probably could add inbox introduction.

Revert history order

---

big_tests/tests/graphql_private_SUITE.erl
big_tests/tests/graphql_stanza_SUITE.erl
priv/graphql/schemas/admin/private.gql
priv/graphql/schemas/admin/stanza.gql
priv/graphql/schemas/global/scalar_types.gql
priv/graphql/schemas/global/stanza.gql
priv/graphql/schemas/user/private.gql
priv/graphql/schemas/user/stanza.gql
src/admin_extra/service_admin_extra_private.erl
src/graphql/admin/mongoose_graphql_private_admin_mutation.erl
src/graphql/admin/mongoose_graphql_private_admin_query.erl
src/graphql/mongoose_graphql_scalar.erl
src/graphql/user/mongoose_graphql_private_user_mutation.erl
src/graphql/user/mongoose_graphql_private_user_query.erl
src/mod_private_api.erl

Improving error handling in mod_private.
1. Changing the name, example, and description of the Stanza type. Now its name is XmlElement, which is used by graphql_stanza and graphql_private.
2. Adding validation to private_get to check if the given user exists
3. Changing the type of nameSpace variable in get_private to disallow empty strings
4. Changing the way the user JID is being returned in an error. Now the binary instead of JID is being returned.

Fixing errors in mod_private

---

big_tests/tests/graphql_account_SUITE.erl
big_tests/tests/graphql_account_SUITE_data/users.csv
priv/graphql/schemas/admin/account.gql
src/ejabberd_admin.erl
src/ejabberd_ctl.erl
src/graphql/admin/mongoose_graphql_account_admin_mutation.erl
src/mongoose_account_api.erl
src/mongoose_import_users.erl
test/ejabberd_admin_SUITE.erl

Add `importUsers` mutation to GraphQL.

Add importUsers to GraphQL

---

README.md
doc/History.md
doc/modules/mod_auth_token.md

This PR addresses MIM-1711
* Update revokeToken command
* Use a direct link to docss to avoid redirect
* Update history with Graphql and API info

Update GraphQL docs and history

---

big_tests/tests/graphql_mnesia_SUITE.erl
priv/graphql/schemas/admin/mnesia.gql
priv/graphql/schemas/global/scalar_types.gql
src/ejabberd_admin.erl
src/ejabberd_commands.erl
src/ejabberd_ctl.erl
src/graphql/admin/mongoose_graphql_mnesia_admin_mutation.erl
src/graphql/admin/mongoose_graphql_mnesia_admin_query.erl
src/graphql/mongoose_graphql_scalar.erl
src/mnesia_api.erl

This PR changes some of the returned values from the "mnesia" module's functions to be more consistent with the whole GraphQL API and adds a new scalar GraphQL type "NodeName" to check whether the provided string is a valid Erlang node name.

Improve error handling in mnesia API

---

doc/migrations/5.1.0_6.0.0.md
priv/migrations/mssql_5.1.0_6.0.0.sql
priv/migrations/mysql_5.1.0_6.0.0.sql
priv/migrations/pgsql_5.1.0_6.0.0.sql

Updating migration guide

---

.circleci/template.yml
big_tests/Makefile
big_tests/run_common_test.erl
big_tests/src/cth_surefire.erl
tools/test.sh

The goal is to enable CircleCI Test Insights for big tests, that can automatically detect flaky and most failing tests.
This can be achieved by using the `cth_surefire` common test hook.
However, the hook contained a few bugs, so:
1. `cth_surefire` is copied from Erlang/OTP to big tests.
2. The fixes are applied.
When reviewing, **check the last commit** to see the diff in `cth_surefire`.
Here you can see the Insights in action:
- [Reports with some failures for previous runs](https://app.circleci.com/pipelines/github/esl/MongooseIM?branch=circleci-test-insights)
- [Insights with flaky tests](https://app.circleci.com/insights/github/esl/MongooseIM/workflows/build_and_test/tests?branch=circleci-test-insights)
Screenshot of a flaky test from reports:

Enable CircleCI Test Insights

---

src/mam/mod_mam_muc.erl
src/mongoose_hooks.erl

This handler is (in open-source) used only by `mod_mam_muc`, which only looks at the `event_data` key, so we can instead pass such event data as the hook params, it is a map that already contains all that is needed.

Simplify filter_room_packet

---

doc/modules/mod_vcard.md

In newest version of MkDocs there is no support for mixing lists with headings. I removed lists markers to fix building documentation.

Remove list with headings in mod_vcard.md

---

big_tests/tests/push_SUITE.erl
big_tests/tests/push_helper.erl
src/event_pusher/mod_event_pusher_push.erl

When the push notification node is enabled with an invalid form (especially with missing keys or values), it could still be saved to the DB. Afterwards, sending a push notification either resulted in `undefined` values being sent (RDBMS) or the a crash (Mnesia). This PR fixes this issue by more strict checking of the form values and rejecting invalid forms.
This PR resolves the most likely cause of https://github.com/esl/MongooseIM/issues/3806

Check push form fields

---

big_tests/tests/acc_e2e_SUITE_data/acc_test_helper.erl
src/event_pusher/mod_event_pusher_hook_translator.erl
src/global_distrib/mod_global_distrib.erl
src/global_distrib/mod_global_distrib_bounce.erl
src/inbox/mod_inbox.erl
src/mam/mod_mam_pm.erl
src/mod_domain_isolation.erl
src/smart_markers/mod_smart_markers.erl

All handlers use return value `{stop, Acc}` to interrupt further processing. In `filter_local_packet` I couldn't remove `drop` as a result Acc since code which launch this hook has logic depending on it.

Refactored handlers to follow stop convention

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/mim_c2s_SUITE.erl
big_tests/tests/mod_global_distrib_SUITE.erl
big_tests/tests/presence_SUITE.erl
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
src/global_distrib/mod_global_distrib_receiver.erl
src/mod_presence.erl
src/stream_management/mod_stream_management.erl

Fixing global distribution, muc presence error, and stream management.
Also enable other unrelated suites that can now pass successfully.
Note that for `gen_statem`, timeouts of the type `{timeout, Time, Msg}` are considered event timeouts, and are canceled upon any event delivered before them, so they can get lost for example upon the process receiving any other routed message. So we need to name them, `{{timeout, ?MODULE}, Time, Msg}`.

Enable global_distrib, muc, and fix stream_mgmt timeouts

---

big_tests/tests/domain_removal_SUITE.erl
doc/modules/mod_inbox.md
doc/modules/mod_mam.md
src/inbox/mod_inbox_rdbms.erl
src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_rdbms_arch.erl
src/mam/mod_mam_utils.erl

This was passing because both with and without increments, the query created was under the same name, so then in tests the non-incremental test was running first and creating the prepared query that would remove everything. So then when the group with incremental delete was running, it would fail to create the right query but it would reuse the old one. In production though, the query created would fail because it is not valid SQL and we wouldn't know that until after the query is ran.
By ensuring that the used query has a different name, we can at least be sure we are not actually just using the plain one.
Unfortunately, I don't know of a way to make this work for mssql easily, syntax is entirely different. Already the current `select *` over a select is a compromise between pgsql and …

Fix query that creates inbox and mam delete domain statement

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/muc_light_legacy_SUITE.erl
src/muc_light/mod_muc_light_codec_legacy.erl

The goal is to make `muc_light_legacy_SUITE` pass with the new `mongoose_c2s`.
The new c2s implementation requires proper addressing of the stanzas, so the tests are amended according to https://esl.github.io/MongooseDocs/latest/open-extensions/muc_light/#451-requesting-a-blocking-list
There is also a small fix in the code.

C2S/fix muc_light_legacy tests

---

big_tests/tests/push_SUITE.erl
big_tests/tests/push_integration_SUITE.erl
doc/tutorials/push-notifications/MongoosePush-setup.md

Previously, disco was tested only for one type of host; now it's tested for real and virtual hosts.

Disco test for push notifications

---

big_tests/default.spec
big_tests/tests/pep_SUITE.erl
src/mod_caps.erl
src/mod_presence.erl
src/mongoose_hooks.erl
src/pubsub/mod_pubsub.erl

The goal is to enable PEP tests for `mongoose_c2s`. This required implementing missing parts of pubsub and caps, that were present directly in the legacy `c2s` implementation.
Functional changes:
- PubSub is now using `foreign_event` and `gen_statem:call` to call the functionality that requires c2s state data. The PEP-related function are still implemented as hooks, because `mod_caps` shouldn't be called directly from another module. As little as possible is delegated to the c2s processes.
- Added timeouts to `gen_statem` calls, because they were deadlock traps.
Test changes:
- PEP Tests don't use `timer:sleep` and shouldn't fail randomly anymore. Some functionality is fixed, and remaining race conditions are handled explicitly.
- Tests were performed with a repetition of 100 times to …

C2S/Enable pep_SUITE

---

.circleci/template.yml
big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_muc_light_SUITE.erl
src/mam/mod_mam_muc.erl
src/mam/mod_mam_utils.erl

This PR adds checking for the MUC domain when archiving messages. Previously, when `mod_mam_muc` was enabled for `muc` it also stored messages for `muc_light` domains that belonged to the same host type and vice versa. The MUC domain is now checked in the handler that archive messages.

Check MUC domain in mod_mam_muc

---

big_tests/tests/push_integration_SUITE.erl

extending push_integration_SUITE

---

priv/mysql.sql

Adding UNSIGNED to the type of a room_id in muc_room_aff table to match the type in muc_rooms table. It is required in MariaDB version 10.5 to ensure the proper creation of a database.

Updating mysql schema

---

src/c2s/mongoose_c2s.erl
src/c2s/mongoose_c2s_hooks.erl
src/gen_hook.erl
src/metrics/mongoose_metrics_hooks.erl
src/mod_last.erl
src/privacy/mod_blocking.erl
src/sasl/cyrsasl.erl

After merging feature/mongoose_c2s the new code was checked with the `{warnings, [unknown]}` option, and the check started failing.
The `gen_hook:extra` type should be used instead of `gen_hook:hook_extra`, because the handler function gets the extended `extra`.

Fix type issues discovered by the extended dialyzer checks

---

big_tests/tests/pep_SUITE.erl

This PR changes the `make_friends` function in `pep_SUITE` to be less prone to the race conditions that might cause the `delayed_receive` and `delayed_receive_with_sm` tests to fail. It also changes `end_per_group` function so that it always restores dynamic modules. The tests were repeated 100 times on the CI for additional certainty.

Fix randomly failing delayed_receive test in PEP suite

---

doc/tutorials/iOS_tutorial.md

There is incorrect markdown parsing issue in the iOS tutorial page https://esl.github.io/MongooseDocs/latest/tutorials/iOS_tutorial/. I deleted the space that can lead to the issue.

 Fix typo in doc [iOS tutorial]

---

src/event_pusher/mod_event_pusher_hook_translator.erl
src/mam/mod_mam_pm.erl
src/mongoose_stanza_api.erl

This PR changes the hooks used in the `mod_event_pusher` and `mod_mam` to more granular ones.

Use more granular c2s hooks

---

big_tests/tests/graphql_server_SUITE.erl

Fixing flaky test remove_dead_from_cluster_http. 
Removing join_unsuccessful_http test, because it was not testing anything(just receiving ok from GraphQL), and caused problems wit remove_dead_from_cluster_http.

Fixing flaky test remove_dead_from_cluster_http

---

big_tests/tests/inbox_extensions_SUITE.erl
big_tests/tests/smart_markers_SUITE.erl

**Disable parallel test in inbox_extensions_SUITE** to avoid eodbc timeouts. For ODBC preset. It **does not** change settings of other presents.
It disables parallel for this group, idk why it was not parallel.
Be aware, there is this call `inbox_helper:maybe_run_in_parallel` ANYWAY, so all tests are running in parallel on mysql/pgsql.
ODBC layer is just too slow to handle the load, and it was known before.
Same with smart_markers_SUITE, because we have [timeouts](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3964/166348/odbc_mssql_mnesia.25.2/big/ct_run.test%40ee67b42a4a3e.2023-02-17_13.16.50/big_tests.tests.smart_markers_SUITE.logs/run.2023-02-17_13.31.13/smart_markers_suite.repeated_markers_produce_no_warnings.133251.html)

Disable parallel test in inbox_extensions_SUITE

---

big_tests/tests/mim_c2s_SUITE.erl
src/c2s/mongoose_c2s.erl
src/c2s/mongoose_c2s_stanzas.erl

An XMPP client won't try the old session establishment step if it doesn't see it announced in the server features, even when the server is strictly waiting for it, so this would deadlock all connections.

Fix announcing session establishment feature

---

big_tests/tests/bosh_SUITE.erl
big_tests/tests/connect_SUITE.erl
big_tests/tests/graphql_metric_SUITE.erl
big_tests/tests/mim_c2s_SUITE.erl
big_tests/tests/vcard_simple_SUITE.erl
big_tests/tests/websockets_SUITE.erl
doc/operation-and-maintenance/MongooseIM-metrics.md
include/mongoose_ns.hrl
src/c2s/mongoose_c2s.erl
src/c2s/mongoose_c2s_ranch.erl
src/c2s/mongoose_c2s_socket.erl
src/ejabberd_receiver.erl
src/metrics/mongoose_metrics.erl
src/metrics/mongoose_metrics_definitions.hrl
src/mod_bosh.erl
src/mod_bosh_socket.erl
src/mod_websockets.erl

this PR introduces the following changes:
- removed `global.data.xmpp.*.compressed_size` metrics - compression support is removed a while ago.
- removed `global.data.xmpp.*.encrypted_size` metrics - the size of a stanza doesn't change much after encryption, more over, when encryption is done for a batch of stanza then this metric is completely irrelevant.
- improved `global.data.xmpp.*.xml_stanza_size` reporting - this histogram metrics make sense only when reported for a single stanza, this PR ensures that.
- introduced `global.data.xmpp.*.c2s*.raw` spiral metrics for TCP/TLS/BOSH/WebSockets - firstly spiral calculation makes much more sense than histogram in addition to that it's less expensive, in the upcoming PR support for S2S and XMPP components traffic calculation will be added.
- …

Unifying c2s metrics

---

big_tests/tests/push_helper.erl

There was a race condition which sometimes occurred in push_integration_SUITE:pubsub_less:pm_notifications_with_inbox:inbox_msg_reset_unread_count_fcm.
It looked like this:
- Bob sends presence „unavailable”
- Alice sends first message
- Alice sends second message
- First message is saved in mod_offline
- Bob sends presence „available” -> this triggers mod_pressence:resend_offline_messages/2
- Second message is saved in mod_offline -> this one is not resent
- We check for incoming messages and expect two of them
- Second message does not come -> timeout

Fix push_integration_SUITE

---

doc/migrations/6.0.0_6.1.0.md
mkdocs.yml

The migration guide is self-explanatory: it describes how to switch from 6.0.0 to the latest version 6.1.0.
Metrics are updated in a separate task, and will be described separately, most likely by @DenysGonchar.
The rolling upgrade procedure is based on the load tests.

Add migration guide for mongoose_c2s

---

big_tests/tests/presence_SUITE.erl
src/logger/mongoose_log_filter.erl
src/mod_presence.erl

Accept presence of type 'available', even if this doesn't seem correct from the RFC perspective, I have seen client code sending such presence.
Also fix the key c2s_state->c2s_data in the logger filters.

Fix minor c2s issues

---

src/async_pools/mongoose_aggregator_worker.erl
src/inbox/mod_inbox_rdbms_async.erl
test/batches_SUITE.erl

This PR addresses "Failing inbox tests on mssql". A part of MIM-1823 ticket.
*  Retry logic and a test

Add retry logic into mongooseim task aggregator

---

include/mod_bosh.hrl
src/c2s/mongoose_c2s.erl
src/ejabberd_cowboy.erl
src/mod_bosh.erl
src/mod_bosh_socket.erl
src/mod_websockets.erl

This adds missing elements to the listener_opts for websockets and bosh and enforces that in dialyzer.

Add port and ip in the listener opts for websockets and bosh

---

big_tests/tests/connect_SUITE.erl
big_tests/tests/logger_ct_backend.erl
src/c2s/mongoose_c2s.erl

This PR addresses bug occurring when a new session is started on another node and we want to log warnings about unfinished processes on prior node.

Fix mongoose_c2s:verify_process_alive/3 + add testcase

---

src/c2s/mongoose_c2s.erl
src/stream_management/mod_stream_management.erl

Ensuring that the session is closed should be the responsibility of the c2s code, which will handle the case on an external state machine state. Running close_session when the session is resumed means running close_session twice.
This PR is a quickfix for that case.

Avoid duplicated close_session

---

.circleci/template.yml
.github/workflows/ci.yml
doc/authentication-methods/riak.md
doc/configuration/auth.md
doc/configuration/database-backends-configuration.md
doc/configuration/listen.md
doc/configuration/outgoing-connections.md
doc/developers-guide/Testing-MongooseIM.md
doc/developers-guide/mod_muc_light_developers_guide.md
doc/developers-guide/release_config.md
doc/modules/mod_last.md
doc/modules/mod_mam.md
doc/modules/mod_offline.md
doc/modules/mod_privacy.md
doc/modules/mod_private.md
doc/modules/mod_roster.md
doc/modules/mod_vcard.md
doc/user-guide/Features.md
doc/user-guide/High-level-Architecture.md
doc/user-guide/Supported-standards.md
mkdocs.yml

Deleting presets requiring Riak from CricleCI.
Marking Riak as deprecated in the docs.

Deprecating riak

---

.circleci/template.yml
tools/circle-build-and-push-docker.sh
tools/circle-install-packages.sh

The goal is to build and push Docker images for both `amd64` and `arm64` architectures.
1. New multi-platform [Erlang/OTP images](https://hub.docker.com/r/mongooseim/cimg-erlang) are used.
2. A job is added to compile MongooseIM on `arm64`, and pack the results to a separate tarball.
3. The `docker_build_and_ship` job uses `docker buildx` to build a multi-platform image, combining the tarballs for both architectures.
**Notes:**
- Machine executor is used for `arm64`, because CircleCI has no Docker one (yet). Docker is used on that machine to make use of the OTP docker image, and to make build environments for both architectures more consistent.
- There are no tests for `arm64` yet, because they would complicate this PR. There is a plan to add some tests soon. The resulting …

Build docker image for arm64

---

big_tests/test.config
doc/configuration/TLS-hardening.md
rel/files/app.config

Adding tlsv1.3

---

.circleci/template.yml
test/mongooseim_metrics_SUITE.erl
tools/circleci-prepare-log-dir.sh

Run the small test job on the arm64 architecture. Details in commit messages.

Add small tests for arm64

---

.circleci/template.yml
tools/circle-build-and-push-docker.sh
tools/circleci-prepare-mongooseim-docker.sh

Run docker image smoke test for arm64

Docker arm64 smoke test

---

big_tests/tests/rdbms_SUITE.erl
src/rdbms/mongoose_rdbms.erl

This PR addresses MIM-1823
* Restarts execute call in transactions
fixed :
Test works locally.
On CI we have:
`
4986 when=2023-02-26T18:43:52.383188+00:00 level=error what=rdbms_outer_transaction_failed reason="{badmatch,{error,{error,error,<<\"42P05\">>,duplicate_prepared_statement,<<\"prepared statement \\\"insert_int8\\\" already exists\">>,[{file,<<\"prepare.c\">>},{line,<<\"412\">>},{routine,<<\"StorePreparedStatement\">>},{severity,<<\"ERROR\">>}]}}}" pid=<0.1943.3> at=mongoose_rdbms:apply_transaction_function/1:770 stacktrace="mongoose_rdbms:prepare_statement/2:831 mongoose_rdbms:sql_execute/4:797 mongoose_rdbms:sql_call/2:345 mongoose_rdbms:apply_transaction_function/1:765 mongoose_rdbms:outer_transaction/4:728 mongoose_rdbms:handle_call/3:622 …

Restart execute in transactions

---

.github/workflows/ci.yml
README.md
tools/gh-actions-configure-preset.sh
tools/gh-upload-to-s3.sh

All status badges now point to the `rel-6.0` branch. They can be previewed here https://github.com/esl/MongooseIM/tree/fix-readme-project-status.
DG: 
added 2 minor updates:
* checrry-picked c48e2ef8f
* added missing `app.` to codecov url

Fix indicators links to point to the latest release

---

README.md
doc/index.md

Changing status icons at doc/index.md
https://github.com/esl/MongooseIM/blob/fix-readme-project-status/doc/index.md
https://github.com/esl/MongooseIM/blob/fix-readme-project-status/README.md

unifying status icons at README.md and doc/index.md

---

big_tests/tests/graphql_server_SUITE.erl
priv/graphql/schemas/admin/server.gql
src/ejabberd_admin.erl
src/graphql/admin/mongoose_graphql_server_admin_query.erl
src/mongoose_server_api.erl

Changing graphql server status to return the MongooseIM version.

Changing graphql server status to return the MongooseIM version

---

.circleci/template.yml

it's required for manual docs redeployment from release branches w/o moving release tag.
Redeployment can be done using "Rerun job with SSH" option for build_and_deploy_docs job.

executing add_ssh_keys unconditionally for docs_build_deploy job

---

src/mongoose_admin_api/mongoose_admin_api.erl

There are multiple things that are wrong with that admin API `Access-Control-Allow-*` headers, also we do not support it for GraphQL nor client REST API.
Removing them for now, if we want to add CORS support in the future it must be done properly and for GraphQL and  
client REST API as well admin REST API.
Issue can be easily demonstrated with curl, below is the corresponding part of the config:
```
[[listen.http]]
port = 8088
transport.num_acceptors = 10
transport.max_connections = 1024
tls.verify_mode = "none"
tls.certfile = "priv/ssl/fake_cert.pem"
tls.keyfile = "priv/ssl/fake_key.pem"
[[listen.http.handlers.mongoose_admin_api]]
host = "_"
path = "/api"
```
and here are 2 curl commands:
* HTTP1.1 request: `curl -v --http1.1  --insecure -X OPTIONS …

removing incorrect CORS headers

---

.circleci/template.yml
big_tests/tests/rdbms_SUITE.erl
src/rdbms/mongoose_rdbms.erl

This PR adds a new API to `mongoose_rdbms` allowing to inject some additional code (e.g. measure time and record a metric) to asynchronous sql execute calls. Interface is similar to basic `sql_execute_request` with additional argument `MeasureFun` which is a function that encapsulates `sql_execute` call and performs additional actions. Intended usage is shown in newly added test.

Add capability of measuring async sql execute requests

---

.circleci/template.yml
tools/circle-upload-codecov.sh

The python uploader is now [phased out](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader).
The new uploader is a binary executable for x86-64 (amd64), so there is no simple way of running it for arm64. However, the arm64 build for small tests shouldn't affect coverage anyway (the tests are exactly the same as for amd64), so it is just
skipped for now until the uploader supports this arch, see codecov/uploader#523
`CODECOV_TOKEN` needs to be used now because of [a known issue](https://community.codecov.com/t/commit-sha-does-not-match-circle-build/4266).

Enable codecov with the new uploader

---

tools/circle-build-and-push-docker.sh

By default buildx creates OCI manifests, which cause a bug when you try to:
- Inspect the docker manifest - even in the latest docker version
- Pull the docker image in older docker - reproduced in 17.x
See docker/buildx#1509 for details.
Tested with latest docker:
```bash
root@ip-10-2-0-4:/home/ubuntu# docker manifest inspect mongooseim/mongooseim:PR-4008
no such manifest: docker.io/mongooseim/mongooseim:PR-4008
root@ip-10-2-0-4:/home/ubuntu# docker manifest inspect mongooseim/mongooseim:PR-4009
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1491,
"digest": "sha256:a419ed034140ccd982fc704f9df433b723aba17c50353ff0093d184144b26693",
"platform": { …
```

Disable provenance to make the docker manifest backwards-compatible

---

big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/muc_light_legacy_SUITE.erl
src/auth/ejabberd_auth_internal.erl

This PR adds a function for removing the domain for `auth.internal`. It also clears the users at the end of the `muc_light_legacy_SUITE` so that it doesn't finish dirty.

Add remove_domain for internal auth

---

big_tests/tests/carboncopy_SUITE.erl
big_tests/tests/carboncopy_helper.erl
big_tests/tests/mongoose_helper.erl
big_tests/tests/presence_SUITE.erl
big_tests/tests/push_SUITE.erl
big_tests/tests/push_helper.erl
big_tests/tests/sm_SUITE.erl
src/c2s/mongoose_c2s.erl
src/ejabberd_sm.erl
src/ejabberd_sm_backend.erl
src/ejabberd_sm_mnesia.erl
src/ejabberd_sm_redis.erl
src/event_pusher/mod_event_pusher_push.erl
src/jingle_sip/jingle_sip_callbacks.erl
src/mod_carboncopy.erl
src/mod_presence.erl
src/mongoose_session.erl
src/mongoose_stanza_api.erl
src/stream_management/mod_stream_management.erl
test/ejabberd_sm_SUITE.erl

This PR addresses MIM-1875 mongoose_session:merge_info merges data from different sessions
* Pass SID into store_info
* Tweaking tests
* Remove merge_info function

Pass SID into store_info

---

.circleci/template.yml
big_tests/tests/inbox_SUITE.erl
doc/modules/mod_inbox.md
src/inbox/mod_inbox.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl

This PR adds a new configuration option which allows to set a limit on a page size for queries to inbox. The default option is set to infinity, i.e. not setting such option would not change anything compared to what we have now.

Added optional max limit configuration option for quering inbox

---

.circleci/template.yml

The issue is present when the latest docs are deployed from 'master', because there is no 'checkout' step now (the workspace is restored instead), and push access is needed in git.
I tested it manually on CircleCI with SSH.

Add github to known hosts to avoid the unknown host error

---

tools/xep_tool/xep_tool.escript

Otherwise the XEPs would be displayed incorrectly at xmpp.org

Use HTTPS in XEP URLs to avoid redirections

---

tools/build-docker-from-remote.sh

Adding the script to build docker from remote MongooseIM.
It takes one argument, the commit hash or branch name based on which it builds the docker image. If it's not provided, the hash of current local commit is being used.
Example usage:
./tools/build-docker-from-remote.sh
./tools/build-docker-from-remote.sh master

Adding script building docker image from remote

---

doc/open-extensions/muc_light.md

This PR updates the `8.1. XEP-0045 mappings` section of the Multi-User Chat (MUC) Light documentation to make it more clear and easier to understand.

Update MUC Light docs

---

.circleci/template.yml
tools/pkg/Dockerfile_deb
tools/pkg/Dockerfile_rpm
tools/pkg/publish.sh
tools/pkg/scripts/deb/build_package.sh
tools/pkg/scripts/rpm/build_package.sh
tools/test.sh

This PR add a publish step to `package` jobs. It pushes packages to a dedicated S3 bucket. Also, it introduces building packages for rockylinux, almalinux and ubuntu.

Publish packages from CircleCI

---

src/privacy/mod_privacy.erl

This PR changes version of XEP-0016: Privacy Lists from 1.6 to 1.7. There were no changes in the code required as the only thing thing that's changed between the versions is the deprecation by the vote of the council.
https://xmpp.org/extensions/xep-0016.html#revision-history-v1.7

Update version of XEP-0016: Privacy Lists

---

src/mod_disco.erl

This PR changes version of XEP-0016: Privacy Lists from 2.4 to 2.5rc3.
The changes between these versions included clarifications of the existing conditions, fixing some examples, and the removal of the order restriction in the XML schema used to validate XMPP traffic.
These changes did not require any modification of the existing implementation, so only the version number has changed.
https://xmpp.org/extensions/xep-0030.html#appendix-revs

Update version of XEP-0030: Service Discovery

---

src/adhoc.erl
test/adhoc_SUITE.erl

This PR updates support for [XEP-0050](https://xmpp.org/extensions/attic/xep-0050-1.3.0.html#execute). The actual change that has to be made comes from [Chapter 3.4 - Command Actions](https://xmpp.org/extensions/attic/xep-0050-1.3.0.html#impl-actions). More precisely these sentences: 
- "The action "execute" is equivalent to the action specified in the "execute" attribute. If the "execute" attribute is absent, it defaults to "next". A form which has an <actions/> element and an "execute" attribute which evaluates (taking the default into account if absent) to an action which is not allowed is therefore invalid."
- "As user-agents treat the absence of an "execute" attribute as equivalent to "next", when the <actions/> element is provided, it is invalid to return a command that has no …

Update XEP-0050: Ad-Hoc Commands

---

src/adhoc.erl

This PR changes XEP version in module attribute, so the table on xmpp.org is rendered correctly

Change XEP-0050 version from 1.3 to 1.3.0

---

big_tests/test.config
doc/modules/mod_bosh.md
rebar.lock
rel/files/mongooseim.toml
src/mod_bosh.erl
src/mod_bosh_cets.erl

This PR addresses MIM-1943.
We want to add CETS backend for mod_bosh.
There was already existing backend support in this module, so this PR is small.
* Change SIDs generation to make them actually random. make_ref() UIDs are not cryptographically random.
* backend module for CETS.

CETS backend for mod_bosh

---

src/ejabberd_s2s_out.erl
src/sasl/cyrsasl_external.erl

This PR updates XEP-0178 version. It's still partial since we support only client-server SASL EXTERNAL.
It also adds an attribute for XEP-0220 which was already fully supported and implemented in `ejabberd_s2s_in` and `ejabberd_s2s_out`. I decided to put it only in one module to avoid mess. In `feature/cets` branch there's ongoing refactor of diaback, so this attribute should be only in newly introduced module after merge.

Update xep attributes for 178 and add for 220

---

big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_muc_light_SUITE.erl
big_tests/tests/muc_SUITE.erl
include/mod_muc_room.hrl
include/mongoose_ns.hrl
src/mod_muc.erl
src/mod_muc_room.erl

This PR updates implementation of MUC. 
The changes between version 1.25 and 1.34.5 include:
- Changes in the types of room config options
- Introduction of `<x/>` element in MUC-PMs
- Requirement to maintain the `id` attribute
- Removal of Group Chat 1.0 compatibility
- Use of a delay element in the initial subject message
Link to the full list of changes: https://xmpp.org/extensions/xep-0045.html#appendix-revs

Update version of XEP-0045: Multi-User Chat

---

.github/workflows/ci.yml

Minor fix to GH Actions.
here is a reference to the corresponding example in docs
https://docs.github.com/en/actions/learn-github-actions/expressions#example-of-failure-with-conditions

fixing GH Actions condition for metrics uploading to GA4

---

big_tests/tests/inbox_helper.erl
big_tests/tests/mam_SUITE.erl
big_tests/tests/mod_global_distrib_SUITE.erl
big_tests/tests/mongoose_helper.erl
big_tests/tests/mongooseimctl_SUITE.erl
big_tests/tests/smart_markers_SUITE.erl
test/async_helper.erl
test/mongooseim_metrics_SUITE.erl

Timeout for `trees_for_connections_present` action is increased from 5 to 10 seconds:
• in most cases waiting takes 4,5-5,5 seconds on GH Actions runner
• and almost always above 5 seconds for mysql_redis preset (as redis is used for session data as well)
so this test case failed a lot and practically blocked passing of GH Actions builds
Also, wait_until helper code is improved a bit.
Successful GH Actions build: https://github.com/esl/MongooseIM/actions/runs/5605253063

Fixing global distrib suite

---

.github/workflows/ci.yml
README.md
doc/index.md

updating MIM badges to release 6.1.x
FYI, documentation for 6.1.0 release is already updated:
- https://esl.github.io/MongooseDocs/6.1.0/
+adding missing parallel flag for coveralls GH action.

updating MIM badges to release 6.1.x

---

src/config/mongoose_config_spec.erl
src/ejabberd_router.erl
src/mongoose_packet_handler.erl
src/mongoose_router.erl
src/xmpp_router.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/router_SUITE.erl

Following the advise from https://www.erlang.org/doc/efficiency_guide/functions.html#function-calls
> Caching callback functions into funs may be more efficient in the long run than apply calls for frequently-used callbacks.
Similar logic was applied in OTP itself in
https://github.com/erlang/otp/pull/5831
https://github.com/erlang/otp/pull/7419/

Cache router, filter, and process handlers into funs

---

big_tests/test.config
big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/gdpr_SUITE.erl
big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_muc_light_SUITE.erl
big_tests/tests/inbox_SUITE.erl
big_tests/tests/mam_SUITE.erl
big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
big_tests/tests/mod_event_pusher_sns_SUITE.erl
big_tests/tests/mod_global_distrib_SUITE.erl
big_tests/tests/mongoose_helper.erl
big_tests/tests/muc_SUITE.erl
big_tests/tests/muc_helper.erl
big_tests/tests/muc_http_api_SUITE.erl
include/mod_muc.hrl
rebar.lock
src/hooks/mongoose_hooks.erl
src/mod_muc.erl
src/mod_muc_mnesia.erl
src/mod_muc_room.erl
src/mongoose_cleaner.erl
src/muc/mongoose_muc_online_backend.erl
src/muc/mongoose_muc_online_cets.erl
src/muc/mongoose_muc_online_mnesia.erl
test/common/config_parser_helper.erl
test/mongoose_cleanup_SUITE.erl

This PR addresses MIM-1933
* Add a (configurable) backend support for online MUC rooms.
* Subscription to Mnesia events is replaced with a hook. 
* node_cleanup_for_host_type hook introduced.
* CETS backend. One table per host_type.
* Test for node_cleanup added.
Kicking logic for one of the rooms in handle_conflict could be done in a separate PR (easier to review, slightly different concerns when implementing and reviewing - i.e. would need new tests, because of new functionality).

CETS backend for mod_muc

---

src/ejabberd_sm_cets.erl

This PR addresses "Just a bit easier code, no need for guards or the return pattern".
* Use ets:match_object/2 instead of ets:select/2

Use ets:match_object/2 instead of ets:select/2

---

src/ejabberd.erl
src/ejabberd_app.erl
src/mongooseim.erl
test/cowboy_SUITE.erl
test/ejabberd_helper.erl
test/mongoose_config_SUITE.erl
test/mongoose_listener_SUITE.erl

Get rid of the circular dependency between `ejabberd:start/0` and `mongooseim:start/0`. Note that `mongooseim:start/0` used to do
```erl
application:start(mongooseim),
ejabberd:start().
```
which is buggy, because application:start will not start the dependencies.
Now there's simply no `ejabberd:start/0` and `mongooseim:start/0` does `application:ensure_all_started(mongooseim)` instead. The `ejabberd` module then only holds helpers for the pid-file that are really only called from `ejabberd_app:start/0`. We can do a bit of shuffling here, old code mixes a bit getting the file and modifying it, we can leave all of it in a single module.

Put startup in mongooseim:start

---

big_tests/tests/domain_helper.erl
big_tests/tests/service_domain_db_SUITE.erl
doc/developers-guide/domain_management.md
src/domain/mongoose_domain_api.erl
src/domain/mongoose_domain_core.erl
src/domain/mongoose_domain_sup.erl
src/domain/mongoose_lazy_routing.erl
src/domain/mongoose_subdomain_core.erl
src/ejabberd_app.erl
src/ejabberd_sup.erl
test/acl_SUITE.erl
test/auth_internal_SUITE.erl
test/mod_global_distrib_SUITE.erl
test/mongoose_cleanup_SUITE.erl
test/mongoose_domain_core_SUITE.erl
test/mongoose_lazy_routing_SUITE.erl
test/mongoose_subdomain_core_SUITE.erl

Follow cleaner OTP supervision conventions, we want these workers supervised by their common supervisor, started cleanly within the supervision tree.

Initialise domain workers in the supervision tree instead of manually

---

src/domain/service_domain_db.erl

Fix a race condition in `service_domain_db_suite.db_keeps_syncing_after_cluster_join` testcase.
Our tests assume that sending message from mim() to mim2() node is instant.
But it is not true, so check_for_updates message is received after sync_local call in tests.
I.e. the following scenario fails:
1. Test node asks `mim2()` to insert a domain.
2. `mim2()` sends `check_for_updates` to `mim()` node.
3. Test node calls `sync_local` on mim() node.
4. `mim()` calls sync_local and replies to the test node.
5. `mim()` finally receives `check_for_updates` from `mim2()`, send in step 2.
This PR addresses https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4066/183250/pgsql_cets.25.3-amd64/big/ct_run.test%4048ff31232359.2023-08-01_06.11.42/big_tests.tests.service_domain_db_SUITE.logs/run. …

Fix flaky test in service_domain_db_SUITE

---

src/c2s/mongoose_c2s.erl
src/c2s/mongoose_c2s_stanzas.erl
src/hooks/mongoose_hooks.erl

Two things here:
- First is that the hook `c2s_stream_features` can already take the initial list of pre-created features as an argument, instead of giving an empty list and then appending two lists. This way, the initial list can also be picked up from subsequent handlers and modified – which SASL2 will do with SASL1 ascribed earlier.
- `cyrsasl:listmech/1` output is given to `mongoose_c2s:filter_mechanism/1` twice, once in c2s itself, and another one when creating the features in c2s_stanza. Unify them.

C2S features small optimisation

---

big_tests/src/mim_loglevel.erl
big_tests/test.config
big_tests/tests/graphql_server_SUITE.erl
big_tests/tests/inbox_SUITE.erl
big_tests/tests/push_integration_SUITE.erl
big_tests/tests/push_pubsub_SUITE.erl
big_tests/tests/rest_client_SUITE.erl
big_tests/tests/sm_SUITE.erl
big_tests/tests/vcard_simple_SUITE.erl
big_tests/tests/xep_0352_csi_SUITE.erl

This PR addresses "Once all backends have CETS backend, we could try to remove mnesia from the config and check which tests break".
* Remove mnesia from internal_databases for pgsql_cets preset.
* Add backend option where it was missing.

Disable mnesia in pgsql_cets preset

---

rebar.lock

This PR uses the latest version of CETS.
* parallel tests for CETS (i.e.  just update to ensure it is the latest version)

Update CETS dependency

---

src/metrics/mongoose_metrics.erl
test/mongooseim_metrics_SUITE.erl

Fixes MIM-1989
How to verify:
- Set a graphite node running, otherwise `exometer_repert_graphite` will crash.
- On a running node, execute in the shell `exometer_report:list_subscriptions(exometer_report_graphite)`.
- On master, we will not find `totalSessionCount` available
- In this branch it is there, similarly for all the other missing metrics.

put reporter init after app startup

---

src/global_distrib/mod_global_distrib_server_mgr.erl
src/global_distrib/mod_global_distrib_utils.erl

This PR addresses "MIM-1990". 
Fixes flaky mod_global_distrib_SUITE:test_host_refreshing testcase
There was an error happening from time to time (once every 10 CI jobs). [Report](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4079/184400/internal_mnesia.25.3-amd64/big/ct_run.test%409828cde28154.2023-08-05_13.02.13/big_tests.tests.mod_global_distrib_SUITE.logs/run.2023-08-05_13.10.10/mod_global_distrib_suite.test_host_refreshing.html)
```erlang
mod_global_distrib_SUITE:hosts_refresher:test_host_refreshing
{error,
{{trees_for_connections_present,true,[{times,50,false}],ok},
[{mongoose_helper,do_wait_until,2,
[{file,"/home/circleci/project/big_tests/tests/mongoose_helper.erl"},
{line,358}]},
{mod_global_distrib_SUITE,test_host_refreshing,1,
[{file, …
```

Fix slow getaddrs call in global distribution

---

big_tests/tests/carboncopy_SUITE.erl
big_tests/tests/carboncopy_helper.erl
big_tests/tests/sm_SUITE.erl
src/mod_carboncopy.erl

This PR addresses MIM-1966 issue. It updates XEP version to the latest version. Implementation change which is introduced: messages of type `normal` containing chat markers are now eligible for carbons delivery (see https://xmpp.org/extensions/xep-0280.html#recommended-rules). I added a test of this new logic and a few for other logic which was not covered yet.

Update xep 0280

---

doc/user-guide/Supported-standards.md

This PR addresses [failing docs CI build](https://app.circleci.com/pipelines/github/esl/MongooseIM/11196/workflows/ef685cae-8af0-498e-85c6-42a6e8160861/jobs/186868)
* Tweak path for Supported-XEPs.md in include-markdown

Fix docs build task

---

big_tests/tests/mongooseimctl_SUITE.erl

This PR addresses "Slowest tests in insights" MIM-2002.
* Fixes unneeded wait_for_stanzas (which would block for 5 seconds).
* It is particular painful, because these tests are not parallel.
* ctl commands are still painfully slow on its own (300ms to load VM just to make RPC), but would not be addressed here.
* Tests should be faster by around 35 seconds (skips 7 calls, that block for 5000 milliseconds).
Before:
After:

Wait for the correct number of stanzas in mongooseimctl_SUITE roster tests

---

rebar.config

This PR addresses "Allow to run tests faster" MIM-2003.
Changes:
Disables src_tests check:
> If option src_tests is specified, a warning is issued if the source code for a module is missing or is newer than the object code.
We ignore these warnings anyway.
It saves 30 seconds for each `make rel1` call.
Also, rebar compiles code anyway, so we could be sure that it is up to date.
Before:
```
time make mim1
make mim1  8.36s user 3.07s system 198% cpu 5.765 total
```
After:
```
time make mim1
make mim1  90.28s user 44.16s system 195% cpu 1:08.63 total
```
Rebar3 calls relx which calls systools:
```
systools:make_script("mongooseim", Opts)
```
Sadly, it takes a lot of time. And it does a lot of file operations:
```erlang
eprof:
...
gen:do_call/4                                          967514 …
```

Disable src_tests in systools:make_script/2

---

tools/parallel.sh
tools/setup-db.sh
tools/test-runner-complete.sh
tools/test-runner.sh
tools/wait_for_healthcheck.sh

This PR addresses "Faster local tests" MIM-2004.
* Rewrite wait_for_healthcheck script - now we run healthcheck command, instead of waiting for docker to run it. Saves 30 seconds for each DB start.
* Run tasks in parallel in setup_db and test_runner.
* Introduce tools/parallel.sh script.
* It does not improve setup time on CircleCI, only locally.
The parallel tasks output would have a prefix (similar how docker-compose outputs):
```
....
redis:  Setting up db: redis
pgsql:  Setting up db: pgsql
pgsql:  Configuring postgres with SSL
build-tests:    cp ../test/mim_ct_rest.erl ../test/mim_ct_rest_handler.erl ../test/mim_ct_sup.erl src/
build-tests:    ../tools/silent_exec.sh "get-deps.log" ../rebar3 deps
build-mim:      Certificate will not expire
build-mim:      if …
```

Run test-runner setup steps in parallel

---

big_tests/tests/pep_SUITE.erl
big_tests/tests/push_pubsub_SUITE.erl
src/event_pusher/mod_event_pusher_push.erl
src/pubsub/mod_pubsub.erl
src/pubsub/node_pep.erl
src/pubsub/node_push.erl

Include a feature of http://jabber.org/protocol/pubsub#rsm in disco#info response. 
Check preconditions when accepting publish-options along with a publish request. We have two node types which advertise support for the publish-options feature.
In node push the preconditions are not checked. This node type is supporting xep-0163.
In node pep the changes are implemented, and the publish-options are being checked.

Updating XEP-0060 Publish-Subscribe

---

test/ejabberd_sm_SUITE.erl

Sid's should be created for different Pids - otherwise the timestamp alone does not guarantee uniqueness.
The sm tests started failing on fast machines, which could generate a lot of sid's in a single microsecond. On Apple M1 the small tests were failing all the time.
To fix this, spawn a new process when generating a sid in the tests. Forward incoming messages to the test process, because some tests need to check them.

Fix flaky sm tests by making sid's unique

---

src/ejabberd_app.erl
src/gen_hook.erl
src/metrics/mongoose_metrics.erl
test/auth_tokens_SUITE.erl
test/component_reg_SUITE.erl
test/event_pusher_sns_SUITE.erl
test/gen_hook_SUITE.erl
test/keystore_SUITE.erl
test/mod_global_distrib_SUITE.erl
test/mongoose_cleanup_SUITE.erl
test/mongoose_subdomain_core_SUITE.erl
test/mongooseim_helper.erl
test/mongooseim_metrics_SUITE.erl
test/muc_light_SUITE.erl
test/privacy_SUITE.erl
test/roster_SUITE.erl
test/router_SUITE.erl

Optimising hooks, as every hook execution means copying a list of handler from the ets table, having them into persistent terms means faster access to super frequently used values: no copying, no GC, and keeping code hotter for memory caching.
`gen_hook` accumulates the handlers on an internal state, and does not dump into PT until explicitly requested (at the end of app startup). If any more handlers are added or removed afterwards, PT entry is updated immediately (this keeps tests easier).
Perhaps https://github.com/esl/MongooseIM/pull/4074 is preferred, needs to be discussed.

Put hooks into persistent_term using batching

---

src/mongoose_cets_discovery_rdbms.erl

This PR addresses "MIM-1998 Errors in logs for CETS + RDBMS"
* Check if rdbms has started before trying to get a list of nodes
Fixes:
```erlang
when=2023-08-09T14:34:46.376379+00:00 level=error what=discovery_failed_select reason=badarg pid=<0.601.0> at=mongoose_cets_discovery_rdbms:get_nodes/1:28 stacktrace="ets:insert_new/2:0 mongoose_rdbms:prepare/4:224 mongoose_cets_discovery_rdbms:prepare/0:61 mongoose_cets_discovery_rdbms:try_register/2:35 mongoose_cets_discovery_rdbms:get_nodes/1:22 cets_discovery:handle_check/1:125 cets_discovery:handle_call/3:94 gen_server:try_handle_call/4:1113" stacktrace_args="[prepared_statements,\
{cets_disco_select,<<\"discovery_nodes\">>,\
[<<\"cluster_name\">>],\
<<\"SELECT node_name, node_num FROM discovery_nodes WHERE …
```

Supress RDBMS warnings about pool not running in mongoose_cets_discovery_rdbms

---

src/c2s/mongoose_c2s.erl

Just a tiny change, this field is only used in the context of the session info so really we can make the c2s_data record one field smaller.

Unify auth_module and info

---

big_tests/tests/cets_disco_SUITE.erl
big_tests/tests/rdbms_SUITE.erl
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
rebar.lock
src/mongoose_cets_discovery_rdbms.erl
src/rdbms/mongoose_rdbms_timestamp.erl

Adds logic to remove nodes from the disco table, so we don't try to contact them if they are not available.
This also requires a way to signal that the node is still alive (we update timestamp column for that).
* Add `mongoose_rdbms_timestamp.erl` to get timestamp from the RDBMS server. 
* We don't use datetime() datatype to store updated_timestamp, because each database has its own functions to work with time. Even just getting the current timestamp is different in different DBs.
* We remove all records for the cluster which are not updated the last 24 hours.
* We allow to override timestamp for tests (avoids adding mocks).
* We store timestamp in seconds - microseconds are overkill for what we are using it.
This PR addresses MIM-1942:
> We put new node names …

Cleaning logic for discovery_nodes table - using database timestamp

---

tools/parallel.sh

This PR addresses "If there is a compilation error, test runner keeps going".
* Gather a list of pids to wait.
* Wait for the pids and handle the exit code.

Stop the test-runner process if any of parallel subtasks fail

---

src/ejabberd_sup.erl

This will hit workers' `terminate` callbacks, increasing code coverage btw, but mostly also letting MIM properly cleanup on termination.
Also extracts common code to a bunch of helpers to create the children definitions.

Simplify specs for ejabberd_sup and let workers terminate (no brutal_kill)

---

big_tests/tests/login_SUITE.erl
src/sasl/cyrsasl_scram.erl

Addresses MIM-2035
When the connecting user starts SASL authentication with SCRAM, e.g.
```
<auth mechanism="SCRAM-SHA-512">biwsbj0gYm9iLHI9NGVLZkZBLzVjbWp2N3FGR1FNY1V4dz09</auth>
```
which decodes to
```
n,,n= bob,r=4eKfFA/5cmjv7qFGQMcUxw==
```
MongooseIM has the following error in the logs:
```
when=2023-09-07T08:52:53.097286+00:00 level=error reason="{error,function_clause,[{ejabberd_auth,get_passterm_with_authmodule,[<<\"advanced\">>,error],[{file,\"/Users/pawelchrzaszcz/dev/mongoose/src/auth/ejabberd_auth.erl\"},{line,295}]},{cyrsasl_scram,get_scram_attributes,3,[{file,\"/Users/pawelchrzaszcz/dev/mongoose/src/sasl/cyrsasl_scram.erl\"},{line,69}]},{cyrsasl_scram,'-mech_new/3-fun-0-',5,[{file,\"/Users/pawelchrzaszcz/dev/mongoose/src/sasl/cyrsasl_scram.erl\"},{line,30}]},{fast_scram,appl …
```

Fix invalid username in scram authentication

---

doc/modules/mod_extdisco.md
src/mod_extdisco.erl

This PR addresses MIM-2038.
Changes in the newest XEP included:
- XML schema was fixed to allow more than a single `<service/>` in `<services/>`. We’re not restricting services in `mod_extdisco:process_iq/5` nor in `mod_extdisco:get_external_services/1`. No change is required.
- `port` in XML schema is now restricted to `xs:unsignedShort` but optional. It already reflected in `mod_extdisco:service_config_spec/0`. No change is required.
Additionally I fixed documentation about the service port. It was saying that port should be a string while an example of the whole config had an integer there. Also, I tested that when you put a string in such config then MongooseIM crashes during start.

Update XEP-0215: External Service Discovery

---

big_tests/tests/mim_c2s_SUITE.erl
src/c2s/mongoose_c2s.erl
src/c2s/mongoose_c2s_stanzas.erl

This was in the RFC6120 but we'd forgotten to add such code to the core c2s module. SASL2 can take advantage of this, so I'm adding it here now.

Set from field from c2s stream-start

---

doc/configuration/database-backends-configuration.md
doc/configuration/general.md
doc/operation-and-maintenance/Cluster-configuration-and-node-management.md
doc/operation-and-maintenance/MongooseIM-metrics.md
doc/tutorials/CETS-configure.md
mkdocs.yml
priv/graphql/schemas/admin/cets.gql

This PR addresses MIM-1995.
- Add information to User’s Guide / Tutorials how to set up MIM with RDBMS + CETS. 
- Update all docs relying on Mnesia configuration and commands like running_db_nodes to also show the CETS alternatives.
- Uses tabs in documentation (like window tabs, not indention tabs).

📖 Document CETS as an alternative to Mnesia

---

Makefile
tools/xep_tool/xep_tool.escript

It can be consumed by MongooseKeeper and any future services. JSON is chosen as it is easily human- and machine-readable.
Tested manually - format of `doc/supported-xeps.json` after `make xeplist`:
```
[
{
"url" : "https://xmpp.org/extensions/xep-0004.html",
"xep" : "0004",
"modules" : [
"mongoose_data_forms"
],
"version" : "2.13.1",
"status" : "complete",
"name" : "Data Forms"
},
{
"url" : "https://xmpp.org/extensions/xep-0012.html",
"xep" : "0012",
"modules" : [
"mod_last"
],
"version" : "2.0",
"status" : "complete",
"name" : "Last Activity"
},
(...)
]
```
Also tested for a proto-xep (we could add such annotations in a separate PR):
```
{
"url" : "https://xmpp.org/extensions/inbox/muc-light.html",
"xep" : "muc-light",
"modules" : [
"mod_muc_light"
],
"version" : "0.0.1",
"status" : …
```

Put xep list as JSON in the online docs

---

big_tests/tests/amp_big_SUITE.erl

This PR addresses "amp_big_SUITE would stop working in pgsql_cets backend, if we disable mnesia application".
* Just use `mongoose_helper:mnesia_or_rdbms_backend/2` helper.

Use proper backend based on preset in amp_big_SUITE

---

big_tests/tests/distributed_helper.erl
big_tests/tests/metrics_api_SUITE.erl
big_tests/tests/persistent_cluster_id_SUITE.erl
doc/operation-and-maintenance/MongooseIM-metrics.md
rebar.config
rebar.lock
src/ejabberd_app.erl
src/mongoose_cluster_id.erl
src/mongoose_internal_databases.erl

This PR addresses "MIM-2040 System metrics fail with no_client_id".
This is a copy of https://github.com/esl/MongooseIM/pull/4135 but the difference is that this branch does not try to fix all the tests, that still assume Mnesia is started.
* CETS backend for mongoose_cluster_id.
* `Added cets:insert_serial/2`. See PR for CETS library: https://github.com/esl/cets/pull/33
* _Actually ensure that Mnesia is stopped after applying preset. This requires some fixes in distributed_helper, because some functions assume Mnesia is always running._  - update: we have the code but we disable this ensuring check for now, because it breaks a lot of tests. We will try to fix tests suite-by-suite and enable this check..

CETS backend for mongoose_cluster_id (minimal logic)

---

rel/files/mongooseim.toml
src/auth/ejabberd_auth_anonymous.erl
src/mod_register.erl

This PR addresses "MIM-2071 Unable to restart VM after applying CETS preset"
* Disable strict check that mnesia is running for mod_register and ejabberd_auth_anon (they are still not supported by CETS though).
* Configure mod_stream_management with the proper backend in the templates.

Fix "Unable to restart VM after applying CETS preset"

---

big_tests/test.config
big_tests/tests/graphql_token_SUITE.erl
big_tests/tests/oauth_SUITE.erl
rebar.config
rebar.lock
src/mod_keystore.erl
src/mod_keystore_backend.erl
src/mod_keystore_cets.erl
src/mod_keystore_mnesia.erl

This PR addresses "MIM-2051 mod_keystore needs CETS backend"
* Adds mod_keystore
* uses new `cets:insert_new_or_lookup/2` (Please, review https://github.com/esl/cets/pull/36)

Add CETS backend for mod_keystore

---

src/privacy/mod_privacy.erl

Log internal-server-errors in mod_privacy.
Otherwise you will not see anything in logs, in Mnesia is not started, but mod_privacy is configured with Mnesia backend.
This PR addresses "Nothing in logs, code just ignores `Reason` variable, which is returned from mod_privacy_backend.
* Logging
Coverage for the patch is low, because we usually do not test logging.

Log internal-server-errors in mod_privacy

---

test/acl_SUITE.erl
test/ejabberd_sm_SUITE.erl

- Resolve flaky test in `acl_SUITE`
- Don't skip redis tests in `ejabberd_sm_SUITE`

Fix minor issues with small tests

---

big_tests/tests/connect_SUITE.erl
doc/configuration/listen.md
src/c2s/mongoose_c2s.erl
src/c2s/mongoose_c2s_stanzas.erl

When the TLS section is missing, then according to the [documentation](https://esl.github.io/MongooseDocs/latest/configuration/listen/#tls-options-for-c2s) STARTTLS should be rejected. This was not the case: the feature was advertised, and a TLS upgrade performed by a client (who was informed about the support) resulted in a crash.
This PR fixes these issues:
- STARTTLS is only advertised when enabled.
- Upgrade attempt results in a correct failure element, as described in [RFC 6120](https://datatracker.ietf.org/doc/html/rfc6120#section-5.4.2.2)
The tests are updated to check these conditions, and to correctly verify the features for optional and required STARTTLS as well.
The bugs were discovered accidentally when checking https://github.com/esl/mongooseim-docker/issues/42. The statement …

Correctly handle the case when TLS is disabled

---

.github/workflows/ci.yml

GH Actions build - https://github.com/esl/MongooseIM/actions/runs/6555138169
The latest `setup-beam` GH Action (`v1.16.0` as of 18/10/2023) states that only versions up to OTP 25 are supported for ubuntu-22.04 runners (see [this page](https://github.com/marketplace/actions/setup-erlang-otp-with-optional-elixir-and-mix-and-or-rebar3?version=v1.16.0#compatibility-between-operating-system-and-erlangotp) for more details).
However, for all Linux runners, the `setup-beam` GH Action uses prebuilt OTP releases stored at [builds.hex.pm](https://builds.hex.pm/). Those builds are prepared by [Bob the builder](https://github.com/hexpm/bob#erlang-builds), and the actual list of the prebuilt OTP versions for ubuntu-22.04 runners can be found [here](https://builds.hex.pm/builds/otp/ubuntu-22.04/builds.t …

updating setup-beam GH action and OTP versions

---

big_tests/test.config
doc/authentication-methods/anonymous.md
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
rel/mim3.vars-toml.config
src/auth/ejabberd_auth_anonymous.erl
src/auth/ejabberd_auth_anonymous_backend.erl
src/auth/ejabberd_auth_anonymous_cets.erl
src/auth/ejabberd_auth_anonymous_mnesia.erl
test/common/config_parser_helper.erl
test/mongoose_cleanup_SUITE.erl

MIM-2066
`ejabberd_auth_anonymous` has now two backends, mnesia and cets, which can be configured.

Anonymous auth supports mnesia and cets backends

---

big_tests/test.config
big_tests/tests/carboncopy_SUITE.erl
big_tests/tests/ct_helper.erl
big_tests/tests/distributed_helper.erl
big_tests/tests/domain_removal_SUITE.erl
big_tests/tests/gdpr_SUITE.erl
big_tests/tests/graphql_muc_SUITE.erl
big_tests/tests/graphql_muc_light_SUITE.erl
big_tests/tests/graphql_token_SUITE.erl
big_tests/tests/inbox_SUITE.erl
big_tests/tests/jingle_SUITE.erl
big_tests/tests/mam_SUITE.erl
big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
big_tests/tests/mod_event_pusher_sns_SUITE.erl
big_tests/tests/mod_global_distrib_SUITE.erl
big_tests/tests/muc_SUITE.erl
big_tests/tests/muc_helper.erl
big_tests/tests/muc_http_api_SUITE.erl
big_tests/tests/oauth_SUITE.erl
big_tests/tests/sm_SUITE.erl

This PR addresses MIM-2081.
It introduces new helper function `ct_helper:get_internal_database/0` and replaces calls `ct_helper:get_preset_var(Config, keystore_backend, mnesia)}` with it. New function does not depend on test config but on configuration of MIM nodes under tests. Former approach was not developer friendly, i.e. it didn't work while: 
- Using the `--rerun-big-tests` option of `test-runner.sh`
- Using `make quicktest`
- Running them directly from the test shell with `make console`
Also, I fixed existing `ct_helper:get_preset_var/3` implementation - 2nd clause of `case` instruction could never match, so instead of returning `Default` it raised an `bad_arg` error during `list_to_existing_atom/1` call.

Add new helper function to enable cets/mnesia in big_tests

---

big_tests/tests/mod_ping_SUITE.erl
big_tests/tests/sm_SUITE.erl
src/mod_ping.erl

This PR addresses an issue arising when both `mod_ping` (with `timeout_action = "kill”`) and `mod_stream_management` are enabled. Previously, error stanzas were routed back to the server after the ping and resume timeouts passed, leading to the resending of unacknowledged messages. Due to the lack of appropriate stanza handling in `mod_ping`, they were processed by `ejabberd_local`, resulting in ID-related errors.
The stanza arrives with the same ID in case of an error, but it doesn't require further processing since the ping timeout handling has already been invoked.
`mod_ping` likely skips using `ejabberd_local:route_iq` with a callback to avoid another laver of indirection. Handling ping responses directly in the module makes the process more straightforward and easier to understand.

Fix error on ping timeout with stream management

---

big_tests/tests/sm_SUITE.erl

Fix:
```
build-tests:    ===> Compiling tests/sm_SUITE.erl failed
build-tests:    tests/sm_SUITE.erl:173:49: function required_modules/3 undefined
```
(happened because of merging two PRs changing the same file)

Fix sm_SUITE compilation

---

tools/circleci-prepare-mongooseim-docker.sh

This new version allows overriding `NODE_HOST`, making it possible to use an IP address (or other host name) for the host part of the node name.

Use the latest version of mongooseim-docker

---

Makefile
tools/test.sh

Coverage was not reported for `eunit`, resulting in false reports for uncovered lines.

Enable coverage report for eunit

---

big_tests/tests/cets_disco_SUITE.erl
src/mongoose_cets_discovery_rdbms.erl

this PR introduces the following changes:
* fix for node num selection algorithm
* avoiding of self-removal from the DB cluster, because removal is based on row selection before TS updating.
* extension of the cets disco test suite

updating mongoose_cets_discovery_rdbms

---

big_tests/tests/muc_SUITE.erl
src/mod_muc.erl

This PR adds info about supported XEP-0249 which already worked. This XEP is required for basic IM compliance at xmpp.org

Advertise support for XEP-0249: Direct MUC Invitations

---

rebar.lock
src/ejabberd_sm_cets.erl
src/mod_bosh_cets.erl

This PR applies this fix https://github.com/esl/cets/pull/40
* Correct remoteUnknownTables/remoteMissingTables in "cets systemInfo" API.
* Also includes https://github.com/esl/MongooseIM/pull/4161 :
* * Includes **Log error once in nested long calls** https://github.com/esl/cets/pull/38 
* * Includes **Fix never returning gen_server:call(Server, sync) call** https://github.com/esl/cets/pull/37 
* * Use ping_all instead of cets:sync (it has been renamed)

Update CETS version with fixes for unknown/missing tables in the status API

---

big_tests/tests/muc_light_SUITE.erl
src/muc_light/mod_muc_light_db_rdbms.erl
src/muc_light/mod_muc_light_room.erl
src/muc_light/mod_muc_light_room_config.erl

Muclight config fix

---

big_tests/tests/cets_disco_SUITE.erl
big_tests/tests/graphql_cets_SUITE.erl
doc/configuration/release-options.md
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
rebar.lock
rel/files/vm.args
rel/mim3.vars-toml.config
src/mongoose_cets_discovery.erl
src/mongoose_cets_discovery_rdbms.erl
src/mongoose_cluster_id.erl
src/mongoose_epmd.erl

This PR addresses "previous PR https://github.com/esl/MongooseIM/pull/4174, but with simplified".
Sometimes, it could take 30 seconds for DNS record to become resolvable in k8s.
In this time, a node could try establishing outgoing erlang distribution connections but could not accept incoming erlang distribution connections. But, global tries to maintain a fully connected mesh between nodes. This means that
new node connects to the cluster
other nodes try to connect to that new node (coordinated by global)
they get nxdomain error inside net_kernel and global gets pang
global gets pang (and nodedown), asks other nodes to disconnect from this new node:
```
when=2023-11-02T14:06:42.939527+00:00 level=warning pid=<0.59.0> at=: unstructured_log="'global' at node …
```

Custom epmd module - simple solution

---

doc/configuration/listen.md
doc/configuration/outgoing-connections.md
doc/migrations/6.1.0_6.2.0.md
doc/tutorials/client-certificate.md
src/config/mongoose_config_spec.erl
src/config/mongoose_config_utils.erl
src/global_distrib/mod_global_distrib.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/config_parser_SUITE_data/mongooseim-pgsql.toml

Require `cacertfile` for `just_tls` when `verify_mode` is set to `peer` or `selfsigned_peer`.  
This validation prevents runtime crashes in Erlang 26 resulting from more strict checking of TLS options.
The requirement was already stated in the docs.
**Notes:**
- As `peer` is the default `verify_mode`, all tests for TLS options in `just_tls` need `cacertfile` or verify_mode` se to `none`.
- TLS option spec is reworked to avoid unnecessary manipulations of sections generated with the `tls/2` helper.
- Reorganized some functions, e.g. `tls_defaults` were c2s-specific
**Excluded from this PR:**
- Requirement of `cacertfile` for `fast_tls`, because `s2s.tls` section is always included, and it has no `cacertfile`, so all default configurations would become invalid. I think that `s2s` TLS …

Require 'cacertfile' for just_tls when verify_mode = 'peer'

---

README.md
doc/index.md
doc/migrations/6.1.0_6.2.0.md
priv/migrations/mssql_6.1.0_6.2.0.sql
priv/migrations/mysql_6.1.0_6.2.0.sql
priv/migrations/pgsql_6.1.0_6.2.0.sql

- Provide SQL migration scripts
- Document Riak removal
Also: add links to [trymongoose.im](https://trymongoose.im)

Update migration guide for version 6.2.0

---

big_tests/tests/mam_SUITE.erl
src/mam/mam_decoder.erl
src/mam/mam_message.erl
src/mam/mod_mam_cassandra_arch.erl
src/mam/mod_mam_muc_cassandra_arch.erl
src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_rdbms_arch.erl

This PR addresses MIM-2101
* If message fails to be decoded, we return a stanza saying so.
* Each failed message would get such a stanza.

If MAM lookup code crashes, user gets an empty result set instead of an error

---

big_tests/tests/service_domain_db_SUITE.erl

This PR refactors service_domainn_db_SUITE. New grouping of test cases is introduced. Some of the tests are using randomised domain names so they don't interfere each other.
For MSSQL the test are being run sequentially because of the random fails (due to poor dev container with MSSQL that we use on the CI). To finally check if we don't introduce new flaky tests I ran CI multiple times and none of the time this suite failed - https://app.circleci.com/pipelines/github/esl/MongooseIM/11803.
There are flaky tests in other suites though. I'd be nice if we addressed it in the future.

Rearranged service_domainn_db_SUITE to run more tests in parallel

---

big_tests/tests/graphql_cets_SUITE.erl
big_tests/tests/graphql_helper.erl
big_tests/tests/graphql_http_upload_SUITE.erl
big_tests/tests/graphql_mnesia_SUITE.erl
priv/graphql/schemas/admin/cets.gql
priv/graphql/schemas/admin/mnesia.gql
priv/graphql/schemas/global/use_dir.gql
src/graphql/directive/mongoose_graphql_directive_use.erl
test/mongoose_graphql_SUITE.erl
test/mongoose_graphql_SUITE_data/directives.gql
test/mongoose_graphql_SUITE_data/directives_schema.gql
test/mongoose_graphql_default_resolver.erl

This PR updates how messages are displayed when an internal database isn't loaded. The messages have been simplified and made more user-friendly. This was done by introducing a new option in the GraphQL `@use` directive. With this option, it can be specified which internal databases are needed for certain commands. Additionally, the messages now provide more specific information about which kind of dependencies are not loaded.

User friendly errors for internal databases

---

big_tests/tests/mam_SUITE.erl
src/mam/mod_mam_pm.erl

This PR addresses "Disco for MAM in more XEP friendly way".
* handle disco requests for both SM and local hooks.

Handle SM features request in MAM for local archives

---

rebar.lock

This PR addresses MIM-2137.
Uses https://github.com/esl/cets/pull/46.
To avoid race conditions we have to pause on all nodes.
The issue:
if join coordinator node looses connection with one of the nodes during join, that node gets unpaused.
when unpaused, the node would start sending remote ops and check_server requests.
there is a chance that other nodes in cluster would receive the messages before send_dump.
I've tried to show the errors in tests.
Solution:
we could delay the messages by unpausing only when all nodes receive DOWN from the cets_join process.

Update CETS with pause-on-all nodes fix

---

big_tests/tests/graphql_sse_SUITE.erl
big_tests/tests/rest_client_SUITE.erl
doc/configuration/listen.md
doc/rest-api/Client-frontend_swagger.yml
src/graphql/mongoose_graphql_handler.erl
src/graphql/mongoose_graphql_sse_handler.erl
src/mongoose_client_api/mongoose_client_api_sse.erl
test/common/config_parser_helper.erl
test/common/mongoose_helper.erl
test/config_parser_SUITE.erl

This PR addresses [Issue # 2754](https://github.com/esl/MongooseIM/issues/2754) (MIM-2100).
It increases `idle_timeout` in cowboy's requests options for all SSE connections (both REST and GraphQL) to 1 hour. This will ensure that client connections are not closed after 1 minute.

Increase idle_timeout for SSE connections

---

rebar.lock

This PR addresses MIM-2144
* Do not log pause_owner_crashed when the pause owner exits normally in CETS

Update CETS: Do not log pause_owner_crashed when the pause owner exits normally

---

big_tests/tests/disco_and_caps_SUITE.erl
big_tests/tests/gdpr_SUITE.erl
big_tests/tests/graphql_offline_SUITE.erl
big_tests/tests/graphql_private_SUITE.erl
big_tests/tests/last_SUITE.erl
big_tests/tests/mod_blocking_SUITE.erl
big_tests/tests/mod_event_pusher_http_SUITE.erl
big_tests/tests/muc_helper.erl
big_tests/tests/offline_SUITE.erl
big_tests/tests/pep_SUITE.erl
big_tests/tests/privacy_SUITE.erl
big_tests/tests/private_SUITE.erl
doc/modules/mod_caps.md
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
src/mod_caps.erl
src/mod_caps_backend.erl
src/mod_caps_mnesia.erl
src/mod_caps_rdbms.erl
test/common/config_parser_helper.erl
test/common/mongoose_helper.erl
test/config_parser_SUITE.erl

This PR addresses MIM-2067.
* module, tests
* using jiffy to encode, because features could be an integer according to the type spec...
We do not try to refactor/optimize or make reasonable caps logic in this PR though, just persist data in RDBMS instead of mnesia here. For example, data removal is not tested and it is not called from anywhere in the main module to begin with...

Add mod_caps_rdbms

---

big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl
doc/modules/mod_mam.md
include/mongoose_ns.hrl
src/mam/mam_iq.erl
src/mam/mod_mam.erl
src/mam/mod_mam_cassandra_arch.erl
src/mam/mod_mam_elasticsearch_arch.erl
src/mam/mod_mam_muc.erl
src/mam/mod_mam_muc_cassandra_arch.erl
src/mam/mod_mam_muc_elasticsearch_arch.erl
src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_pm.erl
src/mam/mod_mam_rdbms_arch.erl
src/mam/mod_mam_utils.erl
src/mongoose_data_forms.erl

This PR introduces the ability to fetch specific messages by using the `ids` field. Additionally, it includes the advertisement of the `urn:xmpp:mam:2#extended` feature, as all the features required by it are now supported.
This is a follow-up to an earlier pull request: https://github.com/esl/MongooseIM/pull/4218.

Update version of XEP-0313: Message Archive Management pt. 2

---

big_tests/tests/rdbms_SUITE.erl
doc/configuration/outgoing-connections.md
src/rdbms/mongoose_rdbms.erl
src/rdbms/mongoose_rdbms_timestamp.erl
src/rdbms/rdbms_queries.erl
src/wpool/mongoose_wpool.erl

Solves MIM-2182
Currently the API for mongoose_rdbms allows only for providing the host-type, but not the pool tag. Change all APIs to look approximately like the following:
```
function(HostType, Name, Parameters) ->
function(HostType, ?DEFAULT_POOL_NAME, Name, Parameters).
-spec function(HostType :: server(), PoolName :: atom(), Name :: atom(), Parameters :: term()) ->
result().
function(HostType, PoolName, Name, Parameters) when is_atom(PoolName), is_atom(Name) ->
sql_cast(HostType, PoolName, {sql_execute, Name, Parameters}).
```

Introduce pool names to mongoose_rdbms

---

test/config_parser_SUITE.erl
test/log_helper.erl
test/log_helper.hrl

The main motivation for this PR is that using `logger_ct_backend` in small tests is difficult.
I also tried the new helper in the upcoming PR for `mongoose_instrument_log`, and it simplified my tests significantly.
Small tests used `logger_ct_backend`, but it was meant for big tests:
- The default formatter was used in small tests (no `app.config`), requiring regexp matching.
- RPC was used, but it was not needed.
Advantages of the new helper:
- Concise and simple eunit-like assertions
- Does not consume unwanted received messages thanks to pattern matching in `receive`
- Easier set-up and tear-down with one handler per testcase.
I didn't move `logger_ct_backend` away from `test/common` - it does no harm apart from being more difficult to use.

Introduce log_helper, and use it in config_parser_SUITE

---

test/common/ets_helper.erl
test/config_parser_SUITE.erl
test/log_helper.erl

This PR prepares `log_helper` for being used in parallel tests.
Logger does adding/removing handlers asynchronously, which leads to race conditions, and some handlers may fail to get registered.
This is why `log_helper` is now reimplemented with only one log handler, and an ETS table for receiver Pids.
Additionally, `ets_helper` is added, which is currently used only once, but in `feature/instrument` it will be used again.

Prepare log_helper for parallel tests

---

big_tests/tests/http_helper.erl
big_tests/tests/muc_SUITE.erl

This PR fixes a problem where tests might fail if an HTTP listener has already been started in the `init_per_group` function of the MUC suite.
Sometimes, if other tests that need an HTTP listener don't work right, they can leave the listener running. This causes a problem when trying to start it again in the `init_per_group`.

Fix flaky `init_per_group` in the MUC suite

---

big_tests/tests/ca_certificate_helper.erl
big_tests/tests/graphql_SUITE.erl
big_tests/tests/graphql_SUITE_data/openssl-user.cnf
big_tests/tests/graphql_SUITE_data/sign_cert.sh
big_tests/tests/sasl_external_SUITE.erl
big_tests/tests/sasl_external_SUITE_data/sign_cert.sh
src/ejabberd_cowboy.erl
src/just_tls.erl

The `verify_mode` option had no effect on incoming HTTP connections, and always works as `none`.
In this PR, I've enabled the check and disallowed  connections from untrusted peers with the `peer` mode. 
The option `selfsigned_peer` is supported as well.
The changes in the code consist of adding the option `fail_if_no_peer_cert = true`, whenever the verify_mode is set to `peer` or `selfsigned_peer`. Because the option is desired only in https listeners, not when we are connecting to the database, a separate function was created only for cowboy listener, to allow it to work properly.
In the big_tests the tests are testing all possible scenarios, with graphql handlers: `domain_admin_listener` has verify_mode set to `none`, `user_listener` has verify_mode set to `selfsigned_peer`, and …

Fixing verify ceritificate options on https listeners

---

big_tests/tests/graphql_muc_light_SUITE.erl

This PR fixes flaky tests in the `graphql_muc_light_SUITE`. The main cause of these issues was that occasionally the RDBMS database did not have enough time to clear out data. This led to tests failing due to problems like duplicate rooms.
To fix this, the check has been added in the `end_per_group` to make sure the database is completely empty before moving on.
The tests were run on repeat on CI to make sure the problem is truly fixed.

Fix flaky GraphQL MUC light tests

---

src/component/mongoose_component_cets.erl
src/ejabberd_sm_cets.erl
src/mod_bosh_cets.erl
src/muc/mod_muc_online_cets.erl
src/s2s/mongoose_s2s_cets.erl
test/mongoose_cleanup_SUITE.erl

Previously, during node cleanup for CETS:
- Some modules removed only local content
- Others performed cluster-wide CETS operations
It is not possible to always remove local content because of `session_cleanup` and the need for insertions - see e.g. stream management. Meanwhile, Mnesia cleanup consistently removes all content across the cluster.
After this change, CETS does the same. An immediate benefit is that after the first `global:trans/2` finishes in `mongoose_cleaner:run_node_cleanup/1`, cluster state is consistent. Previously, cleanup would need to succeed on all nodes (sequentially), and before that the cluster would be in an inconsistent state.
Also:
- Refactor cleanup tests to make them more maintainable.
- Improve test coverage for CETS cleanup.

Make CETS node cleanup consistent

---

src/ejabberd_sup.erl
src/mongoose_cleaner.erl
test/mongoose_cleanup_SUITE.erl

The `dist_blocker` feature was introduced to protect a disconnected node from reconnecting before other nodes finished the cleanup to avoid issues with inconsistent CETS tables. The solution was to change the cookie value on `nodeup` (sic!) for the particular node until the cleanup for that node is finished.
There are following issues with that solution:
- Sometimes there is a delay before `nodedown` is received, and cleanup is started. However, when the node comes back online, `nodedown` would be received, followed by `nodeup`. The problem is that `dist_blocker` is preventing the node from connecting, which might delay reconnection. In [MongooseHelm tests](https://github.com/esl/MongooseHelm/blob/master/test/mim_kind_SUITE.erl#L97) this was causing a 15-second delay before reconnection, …

Revert dist blocker

---

big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl
src/mam/mod_mam_cassandra_arch.erl
src/mam/mod_mam_elasticsearch_arch.erl
src/mam/mod_mam_muc_cassandra_arch.erl
src/mam/mod_mam_muc_elasticsearch_arch.erl
src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_rdbms_arch.erl

This PR adds tests for `mod_mam_pm_dropped` and `mod_mam_muc_dropped` events to verify that they occur after a message fails to be saved to the database. It also extends logging to regular writers, rather than only logging such events for `async` writers.

Test instrumentation for dropped MAM messages

---

big_tests/tests/cets_disco_SUITE.erl
big_tests/tests/graphql_cets_SUITE.erl
priv/migrations/mssql_6.2.0_x.x.x.sql
priv/migrations/mysql_6.2.0_x.x.x.sql
priv/migrations/pgsql_6.2.0_x.x.x.sql
priv/mssql2012.sql
priv/mysql.sql
priv/pg.sql
src/mongoose_cets_discovery_rdbms.erl

This PR makes sure that when you move a node to another cluster, it is not a part of the old cluster anymore.
Previously, it would be a part of both clusters in the `discovery_nodes` table until the next cleanup (1h by default).
Additionally, this PR makes it possible to do a "split-cluster" rolling upgrade, keeping the new and old parts of the cluster disjoint.
Since I needed to test migrations, I figured out several missing and broken parts in them, so I fixed them as well.
It looked to me that the MSSQL migration was untested because of syntax errors.
After this PR, the migration guide should be ready for the next release - only the files will be renamed in the `rel-6.2` branch.

Update CETS node discovery and DB migrations

---

.circleci/template.yml

`pgsql_cets_26` was missing from the list of required jobs for successful build of the Docker container.

Require pgsql_cets_26 for successful build

---

doc/configuration/internal-databases.md
doc/migrations/6.2.0_x.x.x.md

Describe migration from `6.2.0`.

Update migration guide

---

.github/workflows/ci.yml

This PR modifies the checkout action in GitHub Actions workflow. Previously, the repository was checked out without tags, which broke the `mongooseimctl server status` command.
More info about the checkout issue can be found here: https://github.com/actions/checkout/issues/701
To ensure that this fix works the CI workflow was manually triggered for this branch: https://github.com/esl/MongooseIM/actions/runs/8630652139

Fix failing `graphql_server` tests on GitHub Actions

---

.circleci/template.yml
.github/workflows/ci.yml
README.md

Update versions of Erlang/OTP used in CircleCI and GH Actions.
Also: update the release branch in buttons.
See commits for details.

Update OTP versions

---

src/mongoose_server_api.erl

This hotfix is needed to make the build for the 6.2.1 release pass. The tests were failing only for GH tags, because the commit hash was not available.
For now - default to an empty string. We could make the field optional in the future to clean this up.
Big tests checked manually with and without the commit hash.

Make commit hash in system status fail-safe

---

doc/index.md
mkdocs.yml

Hopefully this would make the docs easier to index by search engines.
A human should also quicker realize, that the page contains docs.

Clarify in the docs, that the page contains documentation

---

big_tests/tests/graphql_SUITE.erl

Adding a function to assert the connection result. Allowing to return {error, connection_closed} in tests where the error was expected.
The proposed solution, of running the tests sequentially didn't solve the problem. Therefore it was proposed to add the error {error, connection_closed} as an acceptable result of tests where the SSL certificate wasn't valid.

Fixing flaky tests

---

rebar.lock

The new cets just simply exposes a start_link callback that I want to I can add workers to a supervision tree.

Upgrade cets to the latest main version

---

.circleci/template.yml
tools/pkg/Dockerfile_deb
tools/pkg/Dockerfile_rpm
tools/pkg/scripts/deb/build_package.sh
tools/pkg/scripts/deb/install_erlang.sh
tools/pkg/scripts/rpm/build_package.sh
tools/pkg/scripts/rpm/install_erlang.sh
tools/pkg/scripts/rpm/mongooseim.spec

This PR fixes and updates the packages built with CircleCI.
The original issue was that the `packages.erlang-solutions.com/...` repos stopped working. I reported this, and they are almost fully functional again (except for Centos 7).
In the meantime, I researched possible alternatives, because the repos are now considered old and discontinued.
- Using the new repos `binaries2.erlang-solutions.com/...` would be a good option, but they don't work. I reported this, but it will take time to fix these issues.
- Using directly downloaded packages from https://www.erlang-solutions.com/downloads/. This option worked correctly, so I used it.
With the new packages it was possible to update the Erlang versions, and add support for the newer Ubuntu 22.04 Jammy Jellyfish.
Notes:
- I had to use a few …

Fix and update package building scripts

---

big_tests/tests/sm_SUITE.erl
big_tests/tests/sm_helper.erl

This PR addresses the flaky `sm_SUITE:ping_timeout` test.
The test was failing sporadically due to the client receiving ping stanzas at inappropriate moments, such as during stream resumption configuration or while attempting to close the connection. Additionally, the client's connection was sometimes closed earlier than expected while it was still receiving information from the server.
These issues were resolved by ignoring ping stanzas during critical moments and retrieving necessary information earlier in the test process.
The test was run 1000 times on CI to confirm that the issue has been resolved.

Fix flaky `sm_SUITE:ping_timeout` test

---

.github/workflows/ci.yml

Currently, Erlang does not download on GitHub Actions, which we use to test the master branch. See 
https://github.com/esl/MongooseIM/actions/runs/8971880579 for example.
The issue was with the new scripts that download the Erlang package from our website.
The fix is taken from 05f03eb from https://github.com/esl/MongooseIM/pull/4273.
I've run GH Actions for this branch manually, and the packages jobs have passed: https://github.com/esl/MongooseIM/actions/runs/8984746064.
There are some red results, but they should be unrelated (flaky tests?).

Fix Erlang version for GitHub Actions

---

README.md
doc/getting-started/Installation.md
doc/index.md

As I was looking into packages at our website (https://www.erlang-solutions.com/downloads/), I've noticed that the list in our docs was out of date.

Docs: update packages download list

---

big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl
src/mam/ejabberd_gen_mam_prefs.erl
src/mam/mod_mam.erl
src/mam/mod_mam_cassandra_prefs.erl
src/mam/mod_mam_mnesia_prefs.erl
src/mam/mod_mam_muc.erl

Testing and fixing any issues with muc_mam_prefs. The code was not tested before, so I've made some cosmetic changes. I've also changed the handle_set_prefs function, to prevent saving unusable entries to the database.

Fully test and annotate MAM preferences

---

big_tests/tests/graphql_SUITE.erl
big_tests/tests/graphql_helper.erl

The goal is to properly fix the TLS error handling tests, which were sometimes returning `connection_closed` instead of the proper certificate error.
The reason for this was that `fusco` (just like `gun` and `httpc`) opens the connection and immediately tries to send the request. When getting the response:
- If the server closed the connection already, `connection_closed` would be the result.
- Otherwise, the result would be the TLS error.
To mitigate this, this PR uses the lower-level `ssl` module directly, breaking up the test into steps.
This way, the error can be checked without sending any further data.
The only downside was the need for manually constructing the request and parsing the response. To avoid coding this from scratch, the already existing lower-level utilities from …

Fix flaky TLS tests for GraphQL

---

big_tests/tests/bosh_SUITE.erl
big_tests/tests/instrument_helper.erl
src/instrument/mongoose_instrument_exometer.erl
src/metrics/mongoose_metrics_definitions.hrl
src/mod_bosh.erl
src/mod_bosh_socket.erl
src/mongoose_http_handler.erl

Add instrumentation to `mod_bosh`.
I think there are two non-obvious things in this PR:
1. Why not use `instrument/1` and let the new mongoose_instrument modules deal with the event registration?
The reason is that when running with multiple host_types, instrumentation callback would be run multiple times, per host type. However, `mod_bosh` acts more like a service, in that its handlers are global. Therefore, the BOSH handlers don't have access to which host types they actually run for, and therfore I decided that the instrumentation will omit the host_type label. But if we omit this label, we have to ensure that event registration is run only once - globally.
2. Why change the type of the BOSH socket supervisor?
I've noticed that after adding the call to `mongoose_instrument:tear_down/1` …

Instrument mod_bosh

---

big_tests/tests/xep_0352_csi_SUITE.erl
doc/modules/mod_csi.md
src/mod_csi.erl

A rather straightforward module instrumentation PR.
Similarly to mod_muc instrumentation, [JIDs are added as measurements to events](https://github.com/esl/MongooseIM/pull/4268/files#diff-40d0c686e8f057e968e9d74babe7ec7cb8727bb0b3799f05aec2ae8248662d03R761). I'm not sure if this is and ideal solution, but I don't have a better idea.
I decided to change the documentation since I'm already changing the module. The issue is that the full metric name will depend on the metrics backend in the current implementation if I understand correctly, but the "short name" will stay the same, so I'd say the docs are correct even in this state.

Instrument mod_csi

---

big_tests/test.config
big_tests/tests/s2s_SUITE.erl
big_tests/tests/s2s_helper.erl
rel/fed1.vars-toml.config
src/ejabberd_s2s_out.erl

This PR fixes an issue with S2S connections using DNS discovery where connecting to another server would fail. The root cause was that `inet_res:getbyname/3` returns a DNS type instead of the expected `inet` type needed for establishing connection. The updated logic now includes a proper lookup for the correct `inet` type to ensure successful connections.
Previously, the Erlang documentation did not clearly specify this behavior, which could be misleading. More details can be found here: https://github.com/erlang/otp/pull/5803.
Testing was performed by mocking the appropriate `inet` functions. An alternative solution could involve setting up a local DNS server or using external tools like `dnsmasq` to set up a lightweight DNS resolver. However, this would require installing additional …

S2S DNS discovery fix

---

big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl

This PR fixes three testcase added recently. I'm having issues with this case in my other PR, and noticed that it's surprisingly slow.
Time before fix:
Time after fix:
Explanation:
Since the room is reused across `muc_run_prefs_case` calls, there is no need to resend presence every time - the users are room participants all the time. The issue is that when (re)entering, Alice would wait for 4 stanzas - 3 presences and 1 room subject message. However, only in the beginning, as a new user would she receive the room subject - subsequent waits for 4 stanzas failed silently after only 3 presences, but only after waiting the 5s timeout. This has happend 6 times per testcase, and there were 3 tescases using this mechanism, so there is 3*6*5=90s less pointless waiting now.
I think maybe Escalus …

Fix slow MAM muc_prefs_cases tests

---

big_tests/tests/mod_event_pusher_http_SUITE.erl
src/event_pusher/mod_event_pusher.erl
src/event_pusher/mod_event_pusher_http.erl

This PR addresses instruments mod_event_pusher. I didn't touch `mod_event_pusher_rabbit`, because it reports `mongoose_rabbit_worker`, and it's better to do them together with other workers' metrics.
`mod_event_pusher_http` treats any HTTP reason code as a success, and I didn't change this behaviour.

Instrument mod_event_pusher

---

big_tests/tests/disco_and_caps_SUITE.erl
big_tests/tests/graphql_roster_SUITE.erl
big_tests/tests/instrument_helper.erl
big_tests/tests/metrics_api_SUITE.erl
big_tests/tests/metrics_roster_SUITE.erl
big_tests/tests/roster_helper.erl
rel/fed1.vars-toml.config
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
rel/mim3.vars-toml.config
rel/reg1.vars-toml.config
rel/vars-toml.config
src/ejabberd_sm.erl
src/metrics/mongoose_metrics.erl
src/metrics/mongoose_metrics_hooks.erl
src/mod_disco.erl
src/mongoose_admin_api/mongoose_admin_api_metrics.erl
src/roster/mod_roster.erl
src/roster/mod_roster_api.erl
test/ejabberd_sm_SUITE.erl

The main goal is to replace the roster-related hook handlers in `mongoose_metrics_hooks` with instrumentation in the code executing the hooks.
Instrumentation is placed in `mod_roster`, `mod_roster_api` and  `mod_disco` to cover the same cases as before. Big tests are added for all the new instrumentation events.
The `modRosterGets` metric was renamed to `mod_roster_get.count`. This metric was checked in `metrics_api_SUITE`, and the issue was, that the REST API for metrics didn't support metrics with multi-part names. As we are going to rename all metrics, we would have to remove the tests, decreasing coverage. As we aren't planning to remove the REST API yet, I decided to add support for multi-part metric names in the REST API. The API was also working only for selected metric types …

Use mongoose_instrument for roster hook metrics

---

big_tests/tests/mod_ping_SUITE.erl
src/mod_ping.erl

This PR adds instrumentation to `mod_ping`.
One important change is the merging of two events (`ping_response_time` and `ping_response`) into one, as they were always invoked simultaneously.
The measurement of time in `mod_ping_response` does not use `mongoose_instrument:span` because the time measurement is done through hooks.

Instrument `mod_ping`

---

big_tests/tests/instrument_helper.erl
big_tests/tests/pubsub_SUITE.erl
src/pubsub/mod_pubsub.erl

This PR instruments `mod_pubsub`. Luckily, it war fairly straightforward.
I wasn't sure how to represent the event names without creating new atoms, which is why there is a new "table" in pubsub code, but I think it's OK, because: 1. It follows the style of the module (https://github.com/esl/MongooseIM/pull/4297/files#diff-8f3c86211cc3400d551754d19d3dbb12cecce86b38fe9f6ca2a7f2a2c87f5f05L1366 for example) 2. This way should be fast.

Instrument `mod_pubsub`

---

big_tests/tests/bosh_SUITE.erl
big_tests/tests/instrument_helper.erl
big_tests/tests/websockets_SUITE.erl
src/ejabberd_cowboy.erl
src/metrics/mongoose_metrics_definitions.hrl
src/mod_bosh.erl
src/mod_websockets.erl
src/mongoose_http_handler.erl
src/mongoose_listener.erl

This PR is part of "MIM-2229 Instrument mod_*"
* mod_websockets is not gen_mod
* Introduce a way to define instruments for listeners
* Introduce a way to define instruments for http_handlers.
When starting `mongoose_listener` module collects instruments by calling `listener_instrumentation(ListenerOpts)` for all listeners.
From there `mongoose_http_handler` calls `http_handler_instrumentation()` for each of handlers.
After that we setup or tear down instrumentation at once.
This avoids duplicates when same handler is defined for different listeners (for different HTTP ports).
Tests are similar to  the `mod_bosh` tests.
Name is `listener_instrumentation` because it accepts `ListenerOpts` argument.
Name is `http_handler_instrumentation` because `mod_bosh` exports …

Instrument mod_websockets

---

big_tests/tests/amp_big_SUITE.erl
big_tests/tests/mod_blocking_SUITE.erl
big_tests/tests/privacy_SUITE.erl
big_tests/tests/privacy_helper.erl
src/hooks/mongoose_hooks.erl
src/metrics/mongoose_metrics_hooks.erl
src/privacy/mod_blocking.erl
src/privacy/mod_privacy.erl

The goal is to use instrumentation rather than hook handlers to collect metrics in the privacy modules (`mod_privacy`, `mod_blocking`).
Main changes:
- Events are triggered in `mod_privacy`, because `mod_blocking` is calling functions from the former.
- One hook is removed, because it was used only for metrics.
- The event is usually generated either before the relevant hook is triggered. However, the `check_packet` event is triggered in the handler, because the hook is called from other modules, while it is handled in `mod_privacy`, which performs the actual check.
- Events are checked in tests for both modules. I added the check to most of the places, but the goal was not to cover all test cases with them. Some checks are in the helpers, and this is why I needed to declare one event in …

Instrument/hook handlers: privacy

---

big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl
src/mam/mod_mam_muc.erl
src/mam/mod_mam_pm.erl

This PR adds a text to the error stanza when the message with the ID specified inside `<after/>` or `<before/>` is not found in the archive

Add error text when message with given ID is not found

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/tests/bosh_SUITE.erl
big_tests/tests/connect_SUITE.erl
big_tests/tests/instrument_helper.erl
big_tests/tests/last_SUITE.erl
big_tests/tests/login_SUITE.erl
big_tests/tests/metrics_api_SUITE.erl
big_tests/tests/metrics_roster_SUITE.erl
big_tests/tests/metrics_session_SUITE.erl
big_tests/tests/roster_helper.erl
big_tests/tests/websockets_SUITE.erl
doc/modules/mod_register.md
doc/operation-and-maintenance/Logging-&-monitoring.md
doc/operation-and-maintenance/MongooseIM-metrics.md
doc/rest-api/Administration-backend_swagger.yml
src/c2s/mongoose_c2s.erl
src/ejabberd_sm.erl
src/instrument/mongoose_instrument.erl
src/instrument/mongoose_instrument_exometer.erl
src/instrument/mongoose_instrument_prometheus.erl
src/metrics/mongoose_metrics.erl
src/metrics/mongoose_metrics_definitions.hrl
src/metrics/mongoose_metrics_hooks.erl
test/ejabberd_sm_SUITE.erl
test/mongoose_instrument_metrics_SUITE.erl

The goal is to use `mongoose_instrument` rather than hook handlers and `mongoose_metrics` for session-related events.
- Set up and execute `c2s_auth_failed` in `mongoose_c2s`.
- Create an `sm_session` event with `logins`, `logouts` and `count` metrics. I decided to keep it as one event to be able to increment and decrement the session count.
- Session count is not a probe, because as a probe it would need to be calculated per host type, and this could be a substantial work. Making it a probe could be a separate task.
- Change subscription events to include the host type, because it is known and other events in the sm module have the host type.
- Add support for a `counter` metric. In Prometheus, it is a gauge.
- Remove metric definitions, including the ones already taken care of in the …

Instrument/hook handlers - session

---

big_tests/tests/tr_util_SUITE.erl

This PR fixes a flaky test.
The expected traces are from 2 different processes, so sometimes the hook events become interleaved, and they are not aggregated. This is expected, and the tests are now less strict, allowing such condition to occur.
The test logic could be more strict, allowing specific orderings, but it would make them less readable.
Tested 1000 times. Before the change, tests were failing in 1-2% cases. Now they don't fail anymore.

Fix a race condition in tr_util tests

---

big_tests/tests/mam_SUITE.erl
src/hooks/mongoose_hooks.erl
src/mam/mod_mam_muc_rdbms_arch.erl
src/mam/mod_mam_rdbms_arch.erl

This PR changes the server response when a prepared SQL query fails to run. Now, it will respond with a 500 error instead of an empty result set.
The `try ... catch ...` block around the entire lookup function simplifies the logic for returning errors. This ensures that any error during the function's execution is caught and handled properly in one place.

Return error IQ when SQL query execution fails

---

.circleci/template.yml
.github/workflows/ci.yml
README.md
doc/configuration/database-backends-configuration.md
doc/developers-guide/Bootstrap-Scripts.md
doc/developers-guide/Testing-MongooseIM.md
doc/getting-started/Installation.md
doc/getting-started/Quick-setup.md
doc/index.md
doc/tutorials/How-to-build.md
tools/pkg/README.md
tools/pkg/scripts/rpm/install_erlang.sh
tools/test.sh

[CentOS has reached End Of Life](https://www.redhat.com/en/topics/linux/centos-linux-eol) and because of that our builds started failing on CI. This PR gets rid of CentOS builds so that we can have green CI once again.
Manual run of GH Actions: https://github.com/esl/MongooseIM/actions/runs/9792072400
I changed the docs to reflect what we support, and updated the `How to build MongooseIM from source` page. The issue there is, that there is no `erlang` package in the official repositories, and the EPEL (a repository with additional packages) package is OTP22. The solutions I found on the internet of adding ESL repositories for rpm didn't work from me in a VM - I assume those are outdated. There is no better solution on our website, hence, the "manual" downloading of a newer package.

Drop CentOS

---

big_tests/tests/mam_SUITE.erl

Fixing mam_SUITE flaky tests, by changing the muc_prefs_cases init actions.

Fixing muc_prefs_cases in mam_SUITE

---

big_tests/tests/accounts_SUITE.erl
big_tests/tests/amp_big_SUITE.erl
big_tests/tests/anonymous_SUITE.erl
big_tests/tests/auth_helper.erl
big_tests/tests/disco_and_caps_SUITE.erl
big_tests/tests/domain_isolation_SUITE.erl
big_tests/tests/graphql_roster_SUITE.erl
big_tests/tests/instrument_cets_SUITE.erl
big_tests/tests/instrument_helper.erl
big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl
big_tests/tests/metrics_c2s_SUITE.erl
big_tests/tests/metrics_roster_SUITE.erl
big_tests/tests/metrics_session_SUITE.erl
big_tests/tests/mod_blocking_SUITE.erl
big_tests/tests/mod_event_pusher_http_SUITE.erl
big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
big_tests/tests/mod_global_distrib_SUITE.erl
big_tests/tests/mod_ping_SUITE.erl
big_tests/tests/mongoose_instrument_event_table.erl
big_tests/tests/muc_helper.erl
big_tests/tests/privacy_SUITE.erl
big_tests/tests/privacy_helper.erl
big_tests/tests/pubsub_SUITE.erl
big_tests/tests/rdbms_SUITE.erl
big_tests/tests/roster_helper.erl
big_tests/tests/xep_0352_csi_SUITE.erl
src/roster/mod_roster.erl

The goal is to make instrumentation assertions more specific and flexible, allowing to test negative cases, wait for specific events, and expect a specific number of events.
In a test case, you can now use:
1. Convenience functions: `assert/3, assert_one/3, assert_not_emitted/1-3, wait_and_assert/3, wait_and_assert_new/3`. They cover most of the typical cases.
2. For more complex checks, e.g. expecting more than one event, you can use `assert/4`, which takes a map of options as the last argument. All the convenience functions are calling `assert/4`. This can be especially useful with `timestamp/0`, allowing to check events after a given point in time.
The `take` function is replaced with selection based on timestamp. By not removing events, we can now use all assertions in parallel tests …

More specific assertions for instrumentation events

---

big_tests/tests/muc_light_SUITE.erl
big_tests/tests/muc_light_helper.erl
src/instrument/mongoose_instrument.erl
src/mongoose_user_cache.erl
test/batches_SUITE.erl

This PR updates the `mongoose_user_cache` metrics to use `mongoose_instrument`. It removes old telemetry events and uses `span` to collect the needed information.
- **Metric migration**: Changed `mongoose_user_cache` metrics to use `mongoose_instrument`.
- **Telemetry removal**: Removed telemetry events and replaced them with `span` to collect relevant information.
- **Cache event checks**: Added checks for cache events to the `muc_light_SUITE` tests, as this module uses them.
- **Test updates**: Added these checks to the tests where they are most relevant.

Instrument `mongoose_user_cache`

---

rebar.config

There were some issues with geas https://github.com/crownedgrouse/geas/issues/15
But we don't even need it for MongooseIM. 
* Disable geas and geas_rebar3

Remove geas dependency of GraphQL

---

src/eldap_filter_yecc.yrl
src/eldap_utils.erl
src/mongoose_ldap_worker.erl

This PR addresses "Compilation issues in Erlang 27 related to ldap".
* We pass anon_auth option into eldap:open/2, which is not allowed in the dialyzer spec for this function. But this option is there and works. Maybe OTP team forgot to add it into the spec.
So we extract options into connect_opts, which is enough to not raise the dialyzer warning.
* `maybe_b2list` usage in some places was adjusted to not cause warnings in Erlang 27

Fix ldap dialyzer warnings on Erlang 27

---

tools/summarise-ct-results

* Erlang27 includes one more element (total execution time)
* Fix no-match in tools/summarise-ct-results

Fix no-match in tools/summarise-ct-results

---

mkdocs.yml

The main change in this PR is a bugfix for wrong links which I found by accident, relating to our documentation versions, which should improve our search engine rankings. Other than that, there are some quality of life improvements that have been added to [our theme](https://squidfunk.github.io/mkdocs-material/setup/) that we can use.
The bug was introduced in 5dee72a2b116a653720ad3390146f13fc4a34ea6 by adding a `"latest/"` suffix to the `site_url` option, and justified with the sitemap not being up to date. However, now the sitemap has doubled "latest/", see for example: https://github.com/esl/MongooseDocs/blob/e1191e40a1156d2831dc232afc55f7089270b668/latest/sitemap.xml#L4
It is even worse, because each page has a "canonical" link set up by Mike (documentation versioning tool for …

Doc improvements

---

.circleci/template.yml
tools/circle-generate-config.sh

This PR addresses MIM-2265. 
It is hard to handle updates of plugins, circleci would always use the cached old version. And rebar.lock is not tracking plugins.
* Hashing of `{plugins, ...}.` block. Useful if you are developing or updating plugins
* Invalidate CircleCI deps cache if the plugin list changes
* We use base circle ci image for initial template generation, which has no Erlang. So we use sed to match plugins block and we hash it.

Invalidate CircleCI deps cache if the plugin list changes

---

big_tests/tests/inbox_SUITE.erl
big_tests/tests/inbox_helper.erl
big_tests/tests/mam_SUITE.erl
big_tests/tests/mam_helper.erl
src/async_pools/mongoose_aggregator_worker.erl
src/async_pools/mongoose_async_pools.erl
src/async_pools/mongoose_batch_worker.erl
src/instrument/mongoose_instrument.erl
src/metrics/mongoose_metrics.erl
test/batches_SUITE.erl

This PR updates the metrics in `async_pools` to use `mongoose_instrument`. Events are tested in separate suites due to the need for specific types of pools for testing. That's why one type of event is tested in `mod_inbox` and the other one in `mod_mam`.
Some of the tests do not check the exact number of events because the number of events can depend on how long a given operation takes. For example, `async_pool_flush.timed` can be executed a different number of times depending on how many messages are flushed in a given time interval.

Instrument `async_pools`

---

tools/circle-upload-codecov.sh

This PR addresses "MIM-2151 We should fail CI if codecov upload fails".
* Exit codecov with non-zero code if fails to upload
* Retry uploading 5 times

Exit codecov with non-zero code if fails to upload

---

.circleci/template.yml

There is an issue with spectaql dependency:
https://github.com/anvilco/spectaql/issues/979
Also, use preinstalled version of the package - npx would reinstall spectaql when using the prefix option

Fix GraphQL docs building

---

doc/migrations/6.2.1_x.x.x.md

Added a migration guide. I'm not sure if the "Upgrade procedure" points are needed, as they double the information, but maybe the point by point guide will be clearer then enumeration of the changes.

Add migration documentation

---

doc/configuration/instrumentation.md
doc/modules/mod_global_distrib.md
doc/modules/mod_last.md
doc/modules/mod_muc.md
doc/modules/mod_muc_light.md
doc/modules/mod_offline.md
doc/modules/mod_ping.md
doc/modules/mod_pubsub.md
doc/modules/mod_roster.md
doc/modules/mod_vcard.md
doc/operation-and-maintenance/Logging-&-monitoring.md
doc/operation-and-maintenance/MongooseIM-metrics.md

This PR is a follow up to #4355, which addresses issues found when reviewing documentation once more.

Instrumentation documentation fixes

---

big_tests/tests/service_domain_db_SUITE.erl
src/domain/mongoose_domain_loader.erl
src/domain/mongoose_domain_sql.erl
src/domain/service_domain_db.erl

This PR addresses "MIM-2272 Fix flaky "service_domain_db" tests"
Example of the broken test timeout https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4357/235426/odbc_mssql_mnesia.27.0.1-amd64/big/ct_run.test%404f8408ead5c6.2024-08-14_09.06.15/big_tests.tests.service_domain_db_SUITE.logs/run.2024-08-14_09.27.28/service_domain_db_suite.rest_delete_domain_cleans_data_from_mam.283010.html
* Higher timeouts when pinging domain service gen_server. It affects only the test code. 15 seconds for ping timeout, 30 seconds for the RPC timeout, so we can see what the server is doing, when the ping times out.
* Add debug logging for SQL queries which are done by the domain service.
* Do some stuff in parallel.
* There was slow code in fixing gaps because duplicate …

Domain service test fix

---

.github/workflows/ci.yml

This PR updates the Erlang/OTP versions used in GitHub Actions CI workflows to the latest versions: Erlang/OTP 26 and 27.
- Erlang/OTP Version Update: Most of the CI jobs now use the latest Erlang/OTP versions (26 and 27).
- Ubuntu Xenial Package Job: The job for the Ubuntu Xenial package has been updated to the newest version of Erlang/OTP 25 because versions 26 and 27 aren't available yet.
This update keeps the CI pipeline up to date with the latest Erlang/OTP versions.
Successful CI job run: https://github.com/esl/MongooseIM/actions/runs/10526511796

Update OTP versions for GH Actions

---

big_tests/tests/graphql_sse_SUITE.erl
src/graphql/mongoose_graphql_response.erl

**Fix**: Wrap jiffy:encode in iolist_to_binary to handle long messages.
**Issue**: When encoding a message to JSON that exceeds 2048 characters, jiffy:encode returns a list of binaries instead of a single binary.
**Solution**: By wrapping jiffy:encode in iolist_to_binary, we ensure that the encoded output is always a single binary, resolving the issue with long messages.

Fixing GraphQL SSE crash with large stanza payloads

---

tools/circleci-prepare-log-dir.sh

This PR addresses MIM-2284 - Compress MIM logs before uploading from CI
* Safe space on s3
- tar.gz should compress even better.
- Check "Reports root" directory for the file like "logs_PR_4366_236711_odbc_mssql_mnesia.27.0.1-amd64_2024-08-28_14.22.50.tar.gz", download and double click to uncompress.

Zip MIM logs before uploading to S3

---

tools/test.sh

This PR addresses:
CI is failing from the recent PR merge: 
- https://github.com/esl/MongooseIM/pull/4357 
- https://github.com/esl/MongooseIM/actions/runs/10613811409/job/29418409098#step:6:26
* Skip summarise-ct-results in small tests
* We use rebar3 for small tests, it is smart enough to fail properly. 
* We also need to pull ct_groups_summary_hook dependency to use summarise-ct-results.
Hook is not used in small tests, so only basic info printed from summarise-ct-results.
We loose printing the number of groups run, but it is ok, I think (not super useful anyway).

Skip summarise-ct-results in small tests

---

tools/circleci-prepare-mongooseim-docker.sh

Update `mongooseim-docker` to the latest `master` with the new Ubuntu version. There is no change in performance, which is confirmed by a load test for 1-to-1 (PM) messaging with 100k users.

Use the new docker image based on Ubuntu 24.10

---

doc/configuration/configuration-files.md
doc/configuration/general.md
doc/developers-guide/Stanza-routing.md
doc/developers-guide/domain_management.md
doc/developers-guide/hooks_description.md
doc/developers-guide/xep_tool.md
doc/getting-started/Quick-setup.md
doc/migrations/4.0.1_4.1.0.md
doc/migrations/4.1.0_4.2.0.md
doc/migrations/5.0.0_5.1.0.md
doc/migrations/6.0.0_6.1.0.md
doc/modules/mod_inbox.md
doc/tutorials/ICE_tutorial.md

This PR addresses MIM-2055
* Fix paths
*. Use md suffix
Fixes warnings like that:
```
INFO    -  Doc file 'migrations/6.0.0_6.1.0.md' contains an unrecognized relative link '../../configuration/shaper', it was left as is. Did you mean '../configuration/shaper.md'?
```
- Why is it needed?
- The old way is "fine". It is how it should look in the compiled version. Though, it what mkdocs should do during the compilation step. In the compiled version there is no "md" suffix.

Fix relative links in docs

---

big_tests/tests/mam_SUITE.erl
src/mam/mod_mam_pm.erl
src/mongoose_acc.erl
src/stream_management/mod_stream_management.erl

The doubled message in MAM issue comes from the fact that MAM looks for a `mam_id` field in the accumulator when trying to save a message, and in the re-routing case, it is being stripped just a moment before.
This happens, because re-routing uses the normal routing procedure, which strips the non-persistent accumulator fields, including the `mam_id`, in `mongoose_local_delivery`. Stripping is done, because in the usual routing case the perspective of the message processing changes at that point - sender processing is finished, and receiver processing starts.
When retransmitting a message, we would like to process it from the receiver perspective once more, but with accumulator fields saved from the last time it was processed. I decided to use the `filter_unacknowledged_messages` hook in …

Fix doubled messaged in MAM bug

---

doc/tutorials/Docker-build.md
tools/build-docker-from-remote.sh
tools/circleci-prepare-mongooseim-docker.sh

This PR addresses MIM-2297
* Was failing when checking `mongooseim-docker`
* `./tools/build-docker-from-remote.sh` works locally again.

Fix building docker image locally

---

README.md
doc/getting-started/Installation.md
doc/index.md
doc/operation-and-maintenance/Logging.md
mkdocs.yml
tools/circleci-prepare-mongooseim-docker.sh

We are moving the docker image from [mongooseim/mongooseim](https://hub.docker.com/repository/docker/mongooseim/mongooseim/general) (free tier) to [erlangsolutions/mongooseim](https://hub.docker.com/repository/docker/erlangsolutions/mongooseim/general) (paid tier).
`DOCKERHUB_REPO` was used to name the organization. `DOCKERHUB_ORG` is now used instead, which is already set in CircleCI to `erlangsolutions`.

Move the docker repo to the 'erlangsolutions' organization

---

mkdocs.yml

This PR adds a custom separator regex to the MkDocs search plugin to improve how search works. It helps split text into searchable pieces, which is important for technical content like code, settings and XMPP stanzas.
How the Regex Works
- `[\s\-_,:!=\[\]()"/<>]+`: Matches spaces, punctuation, and special characters like underscores.
- `\.(?!\d)`: Splits at periods, but not if they’re part of a decimal number.
- `&[lg]t;`: Matches HTML entities like `&lt;` and `&gt;`.
It makes searching for configuration options easier. For example, you can now find `modules.mod_mam.pm.same_mam_id_for_peers` by searching for parts like `same_mam_id_for_peers`, `id_for_peers`, or even `mam peers`. Also, XMPP stanzas are now included in the results. So, if you search for `presence`, you’ll see results like …

Add a custom separator to improve search results in the documentation

---

src/muc/mod_muc_room.erl

With the changes done in https://github.com/esl/MongooseIM/pull/4054 the old "Groupchat 1.0" protocol is not supported. When receiving an old style presence, MIM would handle it correctly from the user's perspective, however, the MUC room process would crash loudly, as the Accumulator was passed instead of a Finite State Machine state. The fix is easy and analogous to the other `handle_new_user/5` branch.
I've checked locally, that the error is gone when running the `groupchat_user_enter_old_protocol` testcase from `muc_SUITE`.

Fix MUC room crash when handling old protocol stanza

---

doc/modules/mod_muc.md

Before the changes, the list was not rendered properly:
> ![image](https://github.com/user-attachments/assets/8f5dc764-ff59-45b3-b16a-e09af0601791)
With this PR's change, it is fixed:
> ![image](https://github.com/user-attachments/assets/4194dae1-e26a-4f58-887d-8db8fbe6202b)

Fix list rendering in MUC docs

---

big_tests/tests/connect_SUITE.erl
big_tests/tests/sasl_external_SUITE.erl
src/just_tls.erl

MIM-2315 Always set `fail_if_no_peer_cert` for just_tls when `verify_mode` is not none
The intention of this PR is to harden security by not accepting empty client certificate when MIM TLS is configured with  `verify_mode` of `peer` or `selfsigned_peer`.
In MongooseIM there are two implementations of TLS connectivity - `fast_tls` and `just_tls`.
`fast_tls` is imlemented in C and uses directly OpenSSL library.
`just_tls` is implemented in Erlang and uses OTP ssl library for connection or handshake.
This PR applies only to `just_tls`.
Some options (like `disconnect_on_failure`) are not implemented in `fast_tls` yet.
Certificate verification behaviour is governed by config setting `disconnect_on_failure`.
By default, when not configured, `disconnect_on_failure` is set to true. In this mode …

MIM-2315 Always set `fail_if_no_peer_cert` for just_tls

---

doc/operation-and-maintenance/MongooseIM-metrics.md
src/instrument/mongoose_instrument.erl
src/wpool/mongoose_wpool_rdbms.erl
test/mongoose_instrument_SUITE.erl

This PR changes the metric types in `wpool_rdbms_stats` to gauges to stop metrics from increasing in this probe. It also adds a check during probe setup to ensure all metrics are gauges. If any non-gauge metrics are found, an error is returned with a list of those metrics.

Check probe metrics types

---

include/mongoose_config_spec.hrl
src/config/mongoose_config_parser_toml.erl
src/config/mongoose_config_utils.erl

This way, you can specify a list instead of having to merge functions.
Also: remove the `list_processor` type, because it was created when all sections would be formatted as lists. Now they are formatted as maps by default. What's more, if sections are merged, only the first processor gets a map/list as the argument, and it can pass anything to the subsequent processors.
The `processor` type covers all such cases.

Allow config processor to be a list of functions

---

big_tests/tests/mam_SUITE.erl

The goal is to ensure that MAM works correctly with user preferences disabled, which is actually the default setting.
Changes to `mam_SUITE`:
- Add a configuration without prefs for regression tests. Disable prefs-related tests when prefs are disabled.
- Add a test to check that disabling prefs is effective. It seems enough to just check PM (no MUC test). 
- Fix event name in a test.
Note:
- The prefs-related events are executed even if prefs are disabled. We could later add more data to the events if needed, e.g. the result. This isn't done now, because it's out of scope of this task.

Test MAM without prefs

---

rel/mim1.vars-toml.config
src/config/mongoose_config_spec.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/config_parser_SUITE_data/mongooseim-pgsql.toml

TLS peer verification requires cacertificate, so it makes sense to reject config that misses cacertificate when verify_mode is set to verify_peer.
We have had this config validation for just_tls. This PR adds it for fast_tls.
Note that fast_tls currently skips certificate validation during TLS handshake but allows for certificate checks to happen later on during authentication.

Mim 2314 reject verify peer without cacertfile

---

big_tests/test.config
big_tests/tests/pubsub_SUITE.erl
big_tests/tests/rdbms_SUITE.erl
src/rdbms/mongoose_rdbms_pgsql.erl

The goal is to address flaky tests in `rdbms_SUITE` for CockroachDB.
The problem was caused by mocked `mongoose_rbdms_backend:execute/4`, which called `prepare` without the following `execute`. As a result, the`sync` message was missing in the protocol flow, and the subsequent query would receive stale data from the DB.
Main changes:
- Fix various issues with `rdbms_SUITE`.
- Add a test reproducing the issue reliably for CockroachDB (or for PostgreSQL with the `SERIALIZABLE` transaction isolation level).
- Fix the problem by adding missing `sync` after `prepare`, making it independent of the subsequent call to `execute`.
- Use 5 workers instead of 1 to re-enable testing concurrent queries. To address flaky pubsub tests, a repeat property is added.
There are more details in commit …

Fix cockroachdb consistency

---

tools/select_suites_to_run.erl
tools/test.sh

As described in the [CricleCI docs](https://circleci.com/docs/rerun-failed-tests), the "rerun failed tests" feature allows to rerun only failed test suites instead of all of them.
This PR makes use of this feature in big tests, because they fail the most, and there are substantial savings in terms of CI time and credits.
The steps needed were simple:
1. Use `circleci tests glob` and `circleci tests run` as described in https://circleci.com/docs/rerun-failed-tests/#output-test-files-only to have a list of test suites. For the first run, it will contain all files, but if you rerun tests, it will only contain failed suites.
2. Add a small escript to filter out the test suites in the test spec. This is similar to [selected_tests_to_test_spec.erl](https://github.com/esl/MongooseIM/blob/master/t …

Enable 'rerun failed tests' for big tests in CircleCI

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/test.config
big_tests/tests/mod_global_distrib_SUITE.erl
big_tests/tests/shutdown_SUITE.erl
include/safely.hrl
rel/fed1.vars-toml.config
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
rel/mim3.vars-toml.config
rel/reg1.vars-toml.config
src/ejabberd_app.erl
src/ejabberd_sm.erl
src/ejabberd_sm_redis.erl
src/global_distrib/mod_global_distrib.erl
src/jlib.erl
src/mongoose_listener.erl

This PR addresses "MIM-2316 event_not_registered for c2s_xmpp_element_size_out when stopping the node error".
When we call `mongooseimctl stop` (and there are some websocket connections), we see this error in logs:
`{error,#{what => event_not_registered,labels => #{},event_name => c2s_xmpp_element_size_out} .`
Code in question is this one in mongoose_listener:
```
stop() ->
Listeners = mongoose_config:get_opt(listen),
lists:foreach(fun stop_listener/1, Listeners),
mongoose_instrument:tear_down(instrumentation(Listeners)).
```
So, basically it looks like there are some c2s processes alive on the node after we call tear_down. So, metric c2s_xmpp_element_size_out was there, but not here anymore.
- **Try to reproduce the bug, most likely you will need websocket …

Fix event not registered on shutdown

---

priv/graphql/schemas/global/protected_dir.gql

The `type` argument had wrong type.
As a result, our docs started failing on the latest [spectaql@3.0.3](https://github.com/anvilco/spectaql/blob/main/CHANGELOG.md)

Fix definition of the 'protected' GraphQL directive

---

.circleci/template.yml

Previously it was for every branch.
Main motivation is to save CI credits and to limit unwanted failures in case of issues only with packages.

Limit building packages to tags and master

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/mam.spec
big_tests/src/ct_mongoose_log_hook.erl
big_tests/tests/mod_global_distrib_SUITE.erl
rel/files/app.config
src/global_distrib/mod_global_distrib_connection.erl
src/global_distrib/mod_global_distrib_receiver.erl

This PR addresses "MIM-2348 Logs are truncated on CI in the links. Increase max_no_bytes to 10 megabytes"
* Increase size of maximum log file size from 2MB to 10MB.
* Disable detailed logs for global distribution - this would reduce amount of logs. 
* And still there is too much noise in logs from GD trying to stop connections - changed the loglevel, if connections are stopped because of shutdown.
* Enable logs for mim2/mim3 - but without printing INIT/DONE for tests (that is configurable). Reason is to debug clustering logic, which is often fails on CI nowadays.
We used to disable html logs for mim2/mim3 because it breaks `--one-node` flag in `test-runner`. But now we check if the node is running, and if not - the hook would not do anything.
Example of …

Fix truncated html log

---

.circleci/template.yml
tools/pkg/Dockerfile_deb
tools/pkg/scripts/deb/build_package.sh
tools/pkg/scripts/rpm/build_package.sh
tools/pkg/verify_arch.sh

This PR enables building packages with `arm64` executors and adds a verification script to ensure the package is built for the correct architecture. It also updates the installation method for the `debsigs` package in the Docker build process, addressing issues with the previous flaky approach.
CI run with passing package build: https://app.circleci.com/pipelines/github/esl/MongooseIM/13329/workflows/7f27f6ac-82f5-4951-a9f0-25cd788c44d0

Add building `arm64` packages to CI pipeline

---

big_tests/Makefile

mim, mim2 gets connected to fed1
Which should not happen, but global would connect it It reduces the chance of a netsplit a bit
This PR addresses "".
* It helps with that:
```
26 when=2024-12-05T15:57:29.709626+00:00 level=error pid=<0.3532.0> at=: unstructured_log="** Connection attempt from node reg1@localhost rejected. Invalid challenge reply. **\
27 " 
28 when=2024-12-05T15:57:29.709940+00:00 level=warning pid=<0.3529.0> at=: unstructured_log="'global' at mongooseim@localhost failed to connect to reg1@localhost\
29 " 
30 when=2024-12-05T15:57:29.710974+00:00 level=warning pid=<0.59.0> at=: unstructured_log="'global' at node mongooseim@localhost disconnected node mongooseim2@localhost in order to prevent overlapping partitions" 
31 …
```

Start CT node as hidden to avoid global doing netsplits

---

big_tests/src/cth_surefire.erl

The goal of this PR is to fix the issues with the `cth_surefire` hook, which we are using to produce an XML test report for CIrcleCI used for:
- Listing failing tests in job reports.
- Test insights (failed tests, flaky tests, etc.)
- Rerunning failed tests instead of full presets.
There were two **main issues**:
- Automatically skipped tests, e.g. after a failed `init_per_testcase`, were reported as skipped, while they should have been reported as failed in order to rerun them with "Rerun failed tests".
- If a test is skipped, it would overwrite all previous tests with the same (e.g. from other groups), resulting in an incomplete report, and possibly causing failed tests to be marked as skipped.
Together with the fix, this PR contains **EUnit tests**, which check the correctness of …

Fix XML test report for CircleCI

---

big_tests/tests/sm_SUITE.erl
big_tests/tests/sm_helper.erl
src/mod_presence.erl
src/stream_management/mod_stream_management.erl

This PR adds `<delay>` elements to stanzas rerouted through `mod_stream_management`. This element was already present when a user requested stream resumption, and had unacknowledged stanzas.
Currently, when a user reconnects, has unacknowledged stanzas, and doesn't request stream resumption, the stream management rerouting behaviour is to try to resend the stanzas to them, because MIM doesn't know if they have reached the user. However, if the user is using a different resource, the stanzas would get rerouted only after `resume_timeout` passes, which could be surprising without the `<delay>` element. Even when rerouting to the same resource before the timeout, I think adding the `<delay>` could help client developers detect retransmitted stanzas.
The `<delay>` elements sent by SM and …

Add delays to SM buffer

---

tools/pkg/build.sh
tools/pkg/scripts/deb/debian/postinst

This issue affected Debian/Ubuntu, resulting in warnings being printed out on installation.
- Don't create `/usr/lib/mongooseim`, because it already exists
- Don't truncate Docker logs - to be able to check the output.
I verified manually, that the issue was present for Debian/Ubuntu before the fix, and that it is gone after the fix (see the [CI workflow](https://app.circleci.com/pipelines/github/esl/MongooseIM/13363/workflows/e60f0474-90b9-4aac-9d8d-7209fed8650d) with packages enabled).
**Note:** I decided not to add automatic tests. We could add a condition to fail if anything is printed to `stderr`, but for me it might be too restrictive, i.e. there might be some unrelated output. I think we could add an automatic check later if we find any similar issue.

Don't create /usr/lib/mongooseim, because it already exists

---

big_tests/default.spec
big_tests/dynamic_domains.spec
big_tests/src/ct_mongoose_hook.erl
big_tests/src/cth_validate_nodes.erl
test/common/distributed_helper.erl
tools/test-runner.sh

This PR addresses MIM-2329.
* Add cth_validate_nodes hook
*    The hook would check if MIM is running before init_per_suite for each big test
* It would check it for nodes requested by setting TEST_HOSTS variable
* --one-node flag still works as expected
* To disable this check use new --skip-validate-nodes flag
*  It is compatible with cth_surefire
We added an extra `wait_until`, so we handle the case like that:
https://esl.github.io/html-zip-reader/PR/4426/248490/pgsql_mnesia.26.2.5.4-amd64/big.tar.gz//ct_run.test@1e34d94d21f3.2024-12-09_14.59.14/index.html
mim3 is not available initially, but after a couple of skipped suites it is available again. We wait in post_end_per_suite.

Skip every test suite if MIM is not running

---

test/common/distributed_helper.erl
tools/test-runner.sh

This PR addresses "fixes after MIM-2329".
* Fix in examples (wrong order)
* Properly parse `TEST_HOSTS=""`, used in `--rerun-big-tests`.
Fixes:
```
*** CT 2024-12-12 12:53:32.459 *** Suite Hook
[🔗](file:///Users/mikhailuvarov/erlang/esl/MongooseIM/big_tests/ct_report/ct_run.test@MikhailU.2024-12-12_12.53.31/big_tests.tests.private_SUITE.logs/run.2024-12-12_12.53.32/private_suite.init_per_suite.html#e-1)
Call to CTH failed: error:{{undefined,{hosts,'',node}},
[{distributed_helper,get_or_fail,1,
[{file,
"/Users/mikhailuvarov/erlang/esl/MongooseIM/big_tests/../test/common/distributed_helper.erl"},
{line,189}]},
{distributed_helper,rpc_spec,1,
[{file,
"/Users/mikhailuvarov/erlang/esl/MongooseIM/big_tests/../test/common/distributed_helper.erl"},
{line,185}]}, …
```

Fix --rerun-big-tests not working with cth_validate_nodes

---

src/mod_presence.erl

`carboncopy_SUITE:dropped_client_doesnt_create_duplicate_carbons` is one of the flaky tests (failed run on GH Actions: https://github.com/esl/MongooseIM/actions/runs/12253944118/job/34183783884, failed run on CircleCI: https://app.circleci.com/pipelines/github/esl/MongooseIM/13363/workflows/761201e1-fae8-4792-a5df-051914a41ae6/jobs/248193).
The test:
1. Disconnects one of two user's resources,
2. waits for presence `unavailable` on the remaining resource,
3. after receiving the presence, sends a message from the remaining resource,
4. checks to make sure that the disconnected resource didn't get a carboncopy of the message.
However, sometimes the disconnected resource would actually get the stanza, resulting in a flaky test.
I think the issue comes from a race condition between sending …

Fix dropped_client_doesnt_create_duplicate_carbons flaky test

---

src/mongoose_internal_databases.erl
test/common/mongoose_helper.erl
test/mnesia_db_SUITE.erl

This PR addresses "MIM-2351 Better logging when something takes too long".
* Print log message with waiting tables to load, print table info for them.
* Repeat waiting.

Print mnesia:wait_for_tables progress

---

rel/files/mongooseim

Running this on 30e119170dd2d4b1ac44e2ea9279608826af0548 (a version of master that passes), shows that under
`_build/mim1/rel/mongooseim/lib/mongooseim-*/priv/lib` it is expected to find the `.so` objects of the recently removed native code files. This is explored when the env-var removed in this commit is attempted to be expanded. This was used until 087452273720d1f87186fda456c7e23d849c0e44 when it was removed.
This PR addresses MIM-2353.

Fix "no such file or directory" on startup

---

big_tests/src/cth_surefire.erl

Since the CI build fails if there is any fail in `end_per_testcase`, our `cth_surefire` plugin generating the report should behave the same way.
I ran the unit test manually to confirm that the change is working correctly:
```
big_tests $ rebar3 eunit -m cth_surefire -v
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling mongoose_tests
===> Performing EUnit tests...
======================== EUnit ========================
module 'cth_surefire'
cth_surefire: report_test...[1.908 s] ok
cth_surefire: report_skipped_group_test...[1.698 s] ok
cth_surefire: report_two_groups_test...[1.906 s] ok
cth_surefire: report_skipped_suite_test...[1.679 s] ok
[done in 7.203 s]
=======================================================
All 4 tests passed.
```

Update cth_surefire to report errors in end_per_testcase

---

src/ejabberd_app.erl
src/ejabberd_sup.erl
src/mongoose_cluster_id.erl
src/mongoose_start_node_id.erl
src/mongoose_task.erl
src/wpool/mongoose_wpool_mgr.erl

This PR addresses "MIM-2351 Better logging when something takes too long".
* Use mongoose_task:run_tracked/2 to report slow progress in ejabberd_app and ejabberd_sup.
Question:
* We could move [cets_long](https://github.com/esl/cets/blob/main/src/cets_long.erl) into some repo like `long_task`. Do we want to do so though? The only issues I see: `cets_long` would be reported as a part of a stacktrace - possible confusion. `cets_long` behaviour could be changed someday - we control cets though.
New found bugs:
**Bug 1 -- pep_SUITE:pep_tests:h_ok_after_notify_test**
CI task [1](https://app.circleci.com/jobs/github/esl/MongooseIM/249166)
PEP could fail: [report](https://esl.github.io/html-zip-reader/PR/4430/250534/odbc_mssql_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test% …

Report long tasks

---

.github/workflows/ci.yml

I ran a GH Actions safety checker called [Zizmor](https://woodruffw.github.io/zizmor/), which suggested that the "persist-credentials" option should be set to "false", so that git auth tokens cannot be leaked. The full rationale: https://woodruffw.github.io/zizmor/audits/#artipacked. It is not a big issue for us, as we don't upload artifacts from GH Actions, but using this option should add a bit of safety anyway.
Manually run GH Actions to see if the change doesn't break anything: https://github.com/esl/MongooseIM/actions/runs/12299291228

Do not persist credentials on GH Actions

---

big_tests/tests/carboncopy_SUITE.erl

The description of https://github.com/esl/MongooseIM/pull/4423 was not entirely correct, and this PR should unlflake the tests for good. The reason why the tests are changed, and not the implementation is because the underlying race condition is a bit tricky to fix elegantly.
`mod_carboncopy:remove_connection` is a handler for the `unset_presence` hook, and it removes CC state from the `ejabberd_sm` `info` field in the session record. This is however done in an async manner by the C2S process, and when the user terminates, the request is never handled. This doesn't matter much, as the user process exits shortly, and is removed from `ejabberd_sm` altogether. However, if they receives a message in this short time, CC might run, and see the process still with the CC state in the …

Unflake the`dropped_client_doesnt_create_duplicate_carbons` test

---

tools/open-test-database-shell.sh

Updated the open-test-database-shell.sh script to include a shell command for accessing CockroachDB's shell within a running Docker container.
When running tests with the cockroachdb_cets preset, the latest OpenSSL version causes issues with certificates.
Temporary Workaround: Downgrade OpenSSL to version 3.0 to avoid these issues until a permanent fix is implemented.

Adding support 'open_test_database_shell' for CockroachDB

---

src/mongoose_cluster.erl

It is started as a permanent app, and should stay this way to ensure that the node does not remain running without the app.

Don't restart mongooseim as temporary

---

big_tests/tests/domain_helper.erl
test/common/distributed_helper.erl

This PR addresses a couple of bugs in MIM-2368:
```
commit 424fb5b4bfd748084bec2f61b588fc105db8a930 (HEAD -> fix-dyn-domains-test-runner, origin/fix-dyn-domains-test-runner)
Author: Mikhail Uvarov <arcusfelis@gmail.com>
Date:   Thu Dec 19 10:18:46 2024 +0100
Skip service_domain_db:force_check_for_updates/0 for nodes which are not passed inside `--test-hosts`
Fixes
./tools/test-runner.sh --preset pgsql_cets --db pgsql --skip-cover --skip-small-tests --spec dynamic_domains.spec --one-node
Failed to start a CTH: error:{{badrpc,nodedown},
[{distributed_helper,rpc,
[#{node => mongooseim2@localhost},
service_domain_db,force_check_for_updates,[]],
[{file,
"big_tests/../test/common/distributed_helper.erl"},
{line,140}]},
{domain_helper,for_each_configured_domain,2, …
```

Fix dynamic domains preset failing

---

src/c2s/mongoose_c2s_ranch.erl
src/just_tls.erl
src/mongoose_tls.erl

The SSL processes were not garbage-collected sufficiently often, while the c2s is. With this change, we just pass the `hibernate_after` value of the c2s process to the SSL ones. Local load-tests with amoc show a decrease of 4x, from ~80KB per connection to ~20KB (in comparison, `fast_tls` shows ~6KB per connection 🥲).
Also clean initial calculations of the SSL options, to generate less intermediate garbage when creating the proplist and improve a bit the readability of the helpers around `verify_fun`.

Optimise just_tls with hibernate_after

---

.circleci/template.yml
tools/pkg/publish.sh

This pull request updates the script to also publish built packages as release assets for tags.
The changes were tested with a test release and confirmed to work as expected.
CircleCI workflow: [here](https://app.circleci.com/pipelines/github/esl/MongooseIM/13533/workflows/715c75df-2400-46d6-b9f8-807573f367c2)
Test release on GH:

Publish packages on GitHub

---

doc/migrations/6.3.0_6.3.1.md

Setting the name to "none" would make no sense.
It is the log level that should be changed to "none", but this didn't change in the release, so there is no need to describe it.

Fix the description of log handler migration

---

tools/pkg/publish.sh

This PR adds a link to the published package after it is built, making it easy to access.
**How to test:**
1. Go to [this CircleCI pipeline](https://app.circleci.com/pipelines/github/esl/MongooseIM/13614/workflows/75dff9e0-b772-4fe2-ab13-063c67f261fc).
2. Click on any package job.
3. Check the "Publish package" step for the link.

Generate package links

---

tools/ssl/openssl-ca.cnf

Updating openssl-ca.cnf, to fix the issue with certificates in cockroachDB with newer OpenSSL version.

Fixing certificates generation for cockroachDB

---

big_tests/tests/ca_certificate_helper.erl
big_tests/tests/sasl_external_SUITE.erl
big_tests/tests/sasl_external_SUITE_data/openssl-user.cnf
src/c2s/mongoose_c2s_ranch.erl
src/ejabberd_cowboy.erl
src/just_tls.erl
src/listeners/mongoose_listener.erl
src/mongoose_ldap_worker.erl
src/rdbms/mongoose_rdbms_mysql.erl
src/rdbms/mongoose_rdbms_pgsql.erl
src/wpool/mongoose_wpool_cassandra.erl
src/wpool/mongoose_wpool_http.erl

Note that now we can use `erlang:alias/1` to ensure that this message doesn't come from anywhere else, so the `Ref` parameter is not needed to ensure uniqueness. This allows us to unify the c2s preparing options from all other submodules preparing so, and we can fix naming convention by simply `make_client_opts` vs `make_server_opts`.
Note that the given `verify_fun` is just the default for the cases when `verify_mode` is `peer` or `none`, so only for `selfsigned_peer` it is needed to be provided explicitly. Also, the `verify_fun_wrapper` gets quite more readable this way.
We also here extend tests to ensure we are testing the case of unsupported critical extensions.

Improve the consistency of just_tls helpers

---

src/wpool/mongoose_wpool_rdbms.erl

Sometimes, `mongoose_wpool_rdbms:inet_stats()` may fail, for example when the socket is closing. This is why it's surrounded in a `try...catch`. The stats are processed with the `merge_stats/1` function, and it expects them to be proplists, as returned from `inet:getstat/2`, not a map.
Before this fix, there would be a loud error in the logs, when the failure occured:
```
when=2024-12-16T11:36:49.894423+00:00 level=error what=probe_failed reason=badarg pid=<0.3480.0> at=safely:apply_and_log/4:58 stacktrace="maps:from_list/1:0 mongoose_wpool_rdbms:'-merge_stats/1-fun-0-'/2:129 lists:foldl/3:2146 mongoose_wpool_rdbms:get_rdbms_data_stats/2:69 safely:apply_and_log/4:58 mongoose_instrument_probe:call/3:20" probe_mod=mongoose_wpool_rdbms event_name=wpool_global_rdbms_stats …
```

Fix `probe_failed` error

---

big_tests/tests/login_SUITE.erl
doc/configuration/TLS-hardening.md
doc/configuration/configuration-files.md
doc/listeners/listen-c2s.md
doc/migrations/6.3.1_6.x.y.md
rel/mim1.vars-toml.config
src/config/mongoose_config_spec.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/config_parser_SUITE_data/mongooseim-pgsql.toml

Change default TLS library for C2S to `just_tls`.
Mark usage of `fast_tls` in C2S as deprecated.
Update documentation to reflect the above.

MIM-2360 deprecate fast tls for C2S

---

big_tests/tests/pep_SUITE.erl
src/pubsub/mod_pubsub.erl

This PR addresses [#2335](https://github.com/esl/MongooseIM/issues/2335) and updates the behavior of PEP discovery in line with the XEP's specification.  
Following the discussion in the original issue and XEP's ([examples 13 and 15](https://xmpp.org/extensions/xep-0060.html#entity-info)), if a node attribute is provided in a PEP discovery request, the server will now return the same identities and features as it does for the PEP account itself.  
Similarly this PR ensures that item discovery behaves consistently, matching with [examples 9 and 11](https://xmpp.org/extensions/xep-0060.html#entity-nodes) in the specification.

Properly handle Account Owner Service Discovery request

---

priv/graphql/wsite/index.html

Current implemented GraphiQL version in this repo still uses React UMD build. This caused the IDE to be stuck at "Loading" since React 19 doesn't have UMD builds anymore: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#umd-builds-removed
Updated GraphiQL to v3 so it uses the latest tech stack.
Reference: https://github.com/graphql/graphiql/tree/main/examples/graphiql-cdn

Migrated graphiql to v3

---

src/component/mongoose_component_connection.erl
src/domain/mongoose_domain_sup.erl
src/ejabberd_local.erl
src/ejabberd_router.erl
src/ejabberd_sm.erl
src/ejabberd_sm_backend_sup.erl
src/ejabberd_sup.erl
src/gen_hook.erl
src/instrument/mongoose_instrument.erl
src/jlib.erl
src/listeners/mongoose_listener_sup.erl
src/mam/mod_mam_muc.erl
src/mod_caps.erl
src/mongoose_cleaner.erl
src/mongoose_router_dynamic_domains.erl
src/mongoose_router_external.erl
src/mongoose_router_external_localnode.erl
src/mongoose_router_global.erl
src/mongoose_router_localdomain.erl
src/mongoose_start_node_id.erl
src/muc/mod_muc_iq.erl
src/s2s/ejabberd_s2s.erl
src/vcard/mod_vcard.erl
src/wpool/mongoose_wpool_sup.erl

See commits for details, most changes are self-explanatory.

Minor optimisations and cleanups

---

src/mod_sic.erl

`remove_iq_handler_for_domain` was called with wrong namespace in mod_sic.
The symptom for this bug was that, when mongooseim app was stopped, we were getting warnings about unregistering IQ handlers for `mod_last` which were not registered at all. It turned out that there was defect in mod_sic - when stopping `mod_sic` was unregistering `mod_last` handlers instead of its own.
The fix was tested manually in live MIM node.

MIM-2389 Fix wrong namespace when removing IQ handlers in mod_sic

---

doc/migrations/6.3.1_6.3.2.md

- Add explicit information about `protocol_options` being incompatible with `just_tls`
- Reword and reformat the migration guide for improved clarity
- Add more links to documentation
- Update `exml` version to 4.1.1
- Make it explicit that some issues are only possible with mod_mam
- Describe possible issues caused by a rollback or a "split-cluster" rolling upgrade
- Fix a broken link

Improve migration guide for 6.3.2

---

README.md
doc/getting-started/Installation.md
doc/index.md
doc/tutorials/How-to-build.md

Updating MongooseIM package URLs, replacing links to the ESL page with links to the latest release page on GitHub

Changing links to MongooseIM packages

---

CHANGELOG.md
doc/configuration/outgoing-connections.md
doc/configuration/s2s.md
doc/listeners/listen-c2s.md
doc/migrations/6.3.1_6.3.2.md
doc/modules/mod_global_distrib.md
doc/tutorials/How-to-build.md

This PR updates the documentation to include information about the end of support for OpenSSL <3.0. It also adds details about the supported OpenSSL versions and updates the links to the original OpenSSL documentation.

Update OpenSSL related docs

---

big_tests/tests/fast_auth_token_SUITE.erl
src/fast_auth_token/mod_fast_auth_token_generic_mech.erl
src/sasl/cyrsasl_ht_sha256_expr.erl
src/sasl/cyrsasl_ht_sha384_expr.erl
src/sasl/cyrsasl_ht_sha3_256_expr.erl
src/sasl/cyrsasl_ht_sha3_384_expr.erl
src/sasl/cyrsasl_ht_sha3_512_expr.erl
src/sasl/cyrsasl_ht_sha512_expr.erl

This PR addresses "XEP-0484 Channel bindings for mod_fast_token_auth MIM-2380"
* New methods that support tls-exporter for channel binding
* tests
* 0rtt does not support channel binding with tls-exporter

Fast auth and channel bindings

---

big_tests/tests/sm_SUITE.erl

This PR introduces test cases documenting possible exponential duplication of the stream management buffer in case of multiple sessions being reconnected. Original issue - see the [last comment](https://github.com/esl/MongooseIM/issues/4316#issuecomment-2694619643).
The issue can be reproduced in a few different scenarios, reflected in the added test cases:
1. Alice has multiple sessions: Alice1, Alice2, ..., AliceN with stream management enabled.
2. Bob sends message M to Alice's bare JID.
3. For each session, Alice:
a. Checks incoming messages, receiving $2^{i-1}$ copies of message M in the $i$-th session.
b. Closes the connection cleanly.
1. Alice has multiple sessions: Alice1, Alice2, ..., AliceN with stream management enabled.
2. Alice terminates all sessions.
3. Bob sends message M …

Add tests capturing the current state of the duplicate buffer issue

---

src/ejabberd_sm.erl
src/hooks/mongoose_hooks.erl

The type specs suggested that the session identifier (Sid) could be `undefined`, while this is not the case anywhere in the code.
After checking the usage of Sid in calls to the changed functions, I couldn't find any place where it is `undefined`, because it is always created with `make_new_sid()`.
Assuming that Sid is always defined makes it easier to rework handling of session replacement in my upcoming PR.

Sid is always defined - reflect this in the type specs

---

src/ejabberd_local.erl

This PR addresses "https://github.com/esl/MongooseIM/issues/4489"
* Reply with error iq when receiving IQ with unknown id format in ejabberd_local 
From RFC after discussing with @DenysGonchar.
[8.2.3](https://www.rfc-editor.org/rfc/rfc6120#section-8.2.3).   IQ Semantics
4.  An entity that receives a stanza of type "result" or "error" MUST
NOT respond to the stanza by sending a further IQ response of
type "result" or "error"; however, the requesting entity MAY send
another request (e.g., an IQ of type "set" to provide obligatory
information discovered through a get/result pair).

Log error with INFO loglevel when receiving an unexpected IQ

---

big_tests/tests/sm_SUITE.erl
src/c2s/mongoose_c2s.erl
src/ejabberd_sm.erl
src/mod_presence.erl
src/stream_management/mod_stream_management.erl
test/ejabberd_sm_SUITE.erl

This PR solves the issue with duplicated stream management buffer - originally reported (and fixed) as a MAM issue, and then documented with tests in #4498. From the originally proposed [solutions](https://github.com/esl/MongooseIM/pull/4498#solutions), options 2 and 3 were chosen, but with a slightly different implementation for the latter.
Main changes:
- Prevent buffer duplication by adding `buffer_ref` to each newly buffered `Acc` and making sure they never duplicate in a single buffer. There is a need to perform a linear search of the buffer, but only if the incoming `Acc` already has `buffer_ref`.
- In case of session replacement, resend unacked messages to only to the replacing (new) session. This way, the duplication is completely avoided in case of session replacement (either …

Deduplicate stream management buffer (solution 2+3)

---

big_tests/tests/ct_helper.erl
big_tests/tests/fast_auth_token_SUITE.erl
big_tests/tests/inbox_helper.erl
big_tests/tests/service_domain_db_SUITE.erl
test/common/distributed_helper.erl

This PR addresses "CI failures, and if we look at logs":
```
69 when=2025-03-07T17:21:14.838300+00:00 level=error what=rdbms_sql_execute_failed reason=timeout pid=<0.3477.0> at=mongoose_rdbms:sql_execute/4:872 stacktrace="eodbc:call/3:900 mongoose_rdbms_odbc:execute/4:107 timer:tc/4:649 mongoose_instrument:span/6:140 mongoose_rdbms:sql_execute/4:870 mongoose_rdbms:handle_call/3:680 wpool_process:handle_call/3:291 gen_server:try_handle_call/4:2381" statement_name=fast_upsert_and_set_current params="[<<\"domain.example.com\">>,<<\"alice_cannot_use_expired_token_in_the_current_slot_413\">>,<<\"d4565fa7-4d72-4749-b3d3-740edbf87770\">>,<<\"domain.example.com\">>,<<\"alice_cannot_use_expired_token_in_the_current_slot_413\">>,<<\"d4565fa7-4d72-4749-b3d3-740edbf87770\">>,<<\"verysecret\">>,1741454 …
```

Port solution to run tests sequentially for mssql from the listeners branch

---

big_tests/tests/bosh_SUITE.erl
big_tests/tests/connect_SUITE.erl
big_tests/tests/mim_c2s_SUITE.erl
big_tests/tests/websockets_SUITE.erl
doc/operation-and-maintenance/MongooseIM-metrics.md
src/c2s/mongoose_c2s.erl
src/c2s/mongoose_c2s_listener.erl
src/ejabberd_cowboy.erl
src/listeners/mongoose_listener.erl
src/listeners/mongoose_xmpp_socket.erl
src/mod_bosh_socket.erl
src/mod_websockets.erl

this PR addresses the following things:
* updates description of the listeners' metrics.
* removes `connection_type => http` metrics since they duplicate existing mod_bosh_data_* and mod_websocket_data_* metrics and introduce inconsitency in `connection_type` label interpretation for various metrics.
* moves back c2s specific metrics definition into `mongoose_c2s` module, because it was impossible to configure websockets/bosh connection without tcp/tls c2s connection (even if tcp/tls c2s connection is not needed)

updating metrics documentation

---

src/rdbms/mongoose_rdbms_mysql.erl

This PR addresses MIM-2419
* Remove SET SESSION query_cache_type=1 in MySQL
* It is not supported in MySQL 8
* It returns {error,{1193,<<"HY000">>,<<"Unknown system variable 'query_cache_type'">>} but connection keeps working

Remove SET SESSION query_cache_type=1 in MySQL

---

.circleci/template.yml
doc/getting-started/Installation.md
tools/pkg/scripts/deb/build_package.sh
tools/pkg/scripts/deb/debian/postinst
tools/pkg/scripts/rpm/build_package.sh
tools/pkg/scripts/rpm/mongooseim.spec

This PR adds a bundled OpenSSL 3.x for systems where it is not available in official repositories. The bundled version is used only if no system-wide OpenSSL 3.x installation is detected at runtime. This provides a middle ground between requiring users to install OpenSSL 3.x themselves and risking conflicts with existing installations.
If you're looking for the source of the OpenSSL 3.x integration, please see this related PR: https://github.com/esl/cimg-erlang/pull/11
Successful package build workflow: https://app.circleci.com/pipelines/github/esl/MongooseIM/13932/workflows/346bd630-2447-47e3-beca-09095641d36a

Bundle OpenSSL 3.x with packages for older systems

---

big_tests/tests/s2s_helper.erl
doc/configuration/s2s.md
rel/fed1.vars-toml.config
rel/files/mongooseim.toml
rel/mim1.vars-toml.config
rel/mim2.vars-toml.config
rel/mim3.vars-toml.config
rel/reg1.vars-toml.config
src/config/mongoose_config_spec.erl
src/mongoose_addr_list.erl
src/s2s/mongoose_s2s_out.erl
test/common/config_parser_helper.erl
test/config_parser_SUITE.erl
test/config_parser_SUITE_data/mongooseim-pgsql.toml
test/config_parser_SUITE_data/s2s_only.toml
test/mongoose_config_SUITE.erl

After the rework of S2S options in `feature/listeners`, most options affect only outgoing connections, because incoming connections are configured with the S2S listeners. However, only three options were present in the `s2s.outgoing` subsection, making it confusing for the user. This PR moves all such options to `s2s.outgoing`. See the first commit for a complete list of options.
Additional changes:
- Improve documentation, because some S2S options were not described in the docs.
- Test all options in `config_parser_SUITE`.
- Correct multiple minor issues (see commit messages).
In the future, we have to update the migration guide with these changes.

Reorganize S2S configuration options

---

big_tests/tests/inbox_SUITE.erl
doc/modules/mod_inbox.md
src/inbox/mod_inbox_muclight.erl
src/muc_light/mod_muc_light_db_rdbms.erl

This PR adds functionality to clear inbox entries associated with a MUC Light room after it has been destroyed. The clearing will occur if the option `modules.mod_inbox.remove_on_kicked` is set to` true`.
For the original issue, look [here](https://github.com/esl/MongooseIM/issues/2497)

Clear inbox after destroying muc light room

---

rebar.config.script

It was missed during the app starting rework, leading to package building job failures.
It is required by the `mongooseimctl bootstrap` command.
Manual check (failed before the change and succeeded after it):
```
_build/prod/rel/mongooseim/bin/mongooseimctl bootstrap
```

Include bbmustache in the release

---

doc/configuration/listen.md
doc/listeners/listen-c2s.md
doc/listeners/listen-components.md
doc/listeners/listen-http.md
doc/listeners/listen-s2s.md
doc/migrations/6.3.3_6.4.0.md
mkdocs.yml
rel/vars-toml.config

The main goal of this PR is to describe the migration from version 6.3.2/6.3.3 to 6.4.0.
Main migration tasks for the user:
- Update options for S2S and components, but also C2S and some general options.
- Fix the shaper configuration after the default config was amended (see https://github.com/esl/MongooseIM/pull/4527).
- Update any dashboards to use the updated metrics.
Also changed in the PR:
- Remove unused variable `s2s_use_starttls` from config templating.
- Apply minor corrections to listener docs.

Migration guide for 6.4.0

---

doc/modules/mod_http_upload.md
src/http_upload/mod_http_upload.erl

Documentation says the default is not set, which is incorrect, the default was 10MB. This updates the code and clarifies the value in the documentation.

Fix mod_http_upload max_file_size

---

.circleci/template.yml
.github/workflows/ci.yml
big_tests/rebar.config
rebar.config

This PR updates the Erlang versions used in CircleCI and GitHub Actions. It also updates the relevant definitions in the `rebar.config` files.
Currently, there are three failing tests on GitHub Actions, but they are unrelated to the Erlang version update.
The packages are also building correctly on the new Erlang version: https://app.circleci.com/pipelines/github/esl/MongooseIM/14011/workflows/b21bceaa-a4bb-4b2c-a64d-5e2023a403dc

Bump CI Erlang versions

---

rel/vars-toml.config

This PR replaces the last mention of the old `$EJABBERD_DIR` variable with `$RUNNER_BASE_DIR` in a commented-out line.

Replace last occurance of `EJABBERD_DIR` with `RUNNER_BASE_DIR`

---

.circleci/template.yml
.github/workflows/ci.yml

This PR bumps the Erlang versions used on both GH Actions and CircleCI.

Bump Erlang versions used on CIs

---

.circleci/template.yml
tools/pkg/Dockerfile_deb

Oracular will end its support in July 2025. Plucky is the current interim release, and we support only one interim
release. See https://ubuntu.com/about/release-cycle for details
Also: get the `debsigs` package from Plucky, not from Oracular. Motivation: Plucky is the current release, and Oracular might disappear from the repos.
Also, tested the packages by temporarily enabling building them for this branch, see the [CI](https://app.circleci.com/pipelines/github/esl/MongooseIM/14075/workflows/f53f7ca3-50a0-4d10-9521-8a8171fbdcd4) pipeline. I didn't rerun the flaky tests, because the check was only for packages.

Replace Ubuntu Oracular with Plucky

---

tools/circleci-prepare-mongooseim-docker.sh

Noble has LTS, while Oracular is near its end of support (July 2025).
See the merged [PR](https://github.com/esl/mongooseim-docker/pull/58) for `mongooseim-docker` and the built [docker image](https://hub.docker.com/repository/docker/erlangsolutions/mongooseim/tags/PR-4537/sha256-72d67261d74c878781a9b125830d1d15f842e2de0c6c6b03c999bf9732e46aec).
Manual checks of the image:
- There are no critical vulnerabilities reported.
- The base OS is Ubuntu 24.04.

Use ubuntu-noble as the base docker image

---

big_tests/tests/muc_SUITE.erl
src/muc/mod_muc_room.erl

This PR fixes incorrect `xmlns` for a presence sent as a result of room creation in `muc`. Here is the example from XEP how the stanza should look like: https://xmpp.org/extensions/xep-0045.html#example-154.

Muc create room ns

---

rel/files/mongooseim.toml

1Kb/s is very little and makes tests way way slower, even more prone to hit timeouts. I'm proposing here 16KB/s, considering that this includes all ad-hoc traffic like IQs, presences, read-receipts, and any other extension, and not just human text.

Increase default shaper

---

big_tests/tests/graphql_SUITE.erl
priv/graphql/wsite/index.html

Recently, our GraphiQL website has become stuck at "Loading...".
Apparently the pinned version 3.8.3 stopped working with the latest browsers.
In this PR, I updated the version to the `main` branch of GraphiQL. This means that the JS libraries are downloaded from CDN in their latest versions. We can see how long this will work. If there are any issues, we could pin the versions again.
**Notes:**
- One of the reasons why I didn't use the latest release`5.0.0` is that it was referencing the JS libraries in "RC" versions.
- I verified that GraphiQL works manually. I used the UI to perform an admin query and checked the results. Unfortunately, I don't see an easy way to check that in big tests.

Fix and update GraphiQL

---

big_tests/tests/mod_blocking_SUITE.erl
doc/modules/mod_blocking.md
src/privacy/mod_privacy.erl

Given that [XEP-0191: Blocking Command](https://xmpp.org/extensions/xep-0191.html#matching) allows to block a jid in a `domain/resource` format (which is compliant with XEP-0016: Privacy Lists), it could be leveraged to block any messages from a particular user in any groupchat. 
For it to work properly the server mustn't send error from blocking user when a blocked user send a message to a room. This is because we have an implementation of [this optional feature from MUC](https://xmpp.org/extensions/xep-0045.html#service-error-kick).
Example:
1. Alice blocked Bob
2. Bob sent a message to a groupchat where Alice is in
3. The server sends error to Bob (on behalf of Alice) - current feature of Blocking Command for PM
4. Alice gets kicked out from the room - current feature of MUC
Not …

Implement support for blocking a user for any groupchat

---

.circleci/template.yml
.github/workflows/ci.yml

Replace debian buster with trixie
- Buster is past its LTS support.
- Trixie is the latest stable release.
Also update minor Erlang/OTP versions.
To check that the packages are built correctly, I temporarily enabled building them for this branch. You can check the [CI job](https://app.circleci.com/pipelines/github/esl/MongooseIM/14144/workflows/96624d3a-61d5-45fc-9949-f2a55d097012) - please ignore the flaky test. There was no need to rerun it, as that run was about the packages.

Update Debian release and minor OTP versions

---

big_tests/tests/connect_SUITE.erl
src/c2s/mongoose_c2s.erl

**Changes:**
- **Fixed stream error format**: Added proper `<stream:stream>` opening tag before sending connection-timeout errors during the `wait_for_stream` state
- **Added comprehensive test**: Created `disconnect_inactive_tcp_connection_after_timeout` test case to verify that inactive TCP connections receive proper XMPP stream error format and are closed after the configured `state_timeout`
**Problem:** Previously, when a client connected via TCP but didn't send any XMPP data within the `state_timeout` period, the server would send a malformed error response missing the required stream opening tag.
**Solution:** Handle the `state_timeout` event specifically during the `wait_for_stream` state to ensure proper XMPP stream error formatting with the correct `<stream:stream>` wrapper.

Fix missing stream tag for connection-timeout errors

---

doc/modules/mod_blocking.md
doc/modules/mod_privacy.md

It was incorrectly described as non-configurable.
If fact, it is not only configurable, but also passes its options to mod_privacy.

Fix documentation of mod_blocking
