- rebar.config
"extend" has been changed to "ninenines" and even though the name is
redirects to ninenines it makes rebar checkout the master repo.
master doesn't build for me without this change.
> Fix source of cowoby dependency

- apps/ejabberd/src/mod_bosh_socket.erl
Don't defer updating #state.handlers until after the call to send_to_handler/3.
send_to_handler/3 calls send_wrapped_to_handler/3 which only sets up the inactivity timer if #state.handlers is empty!
(cherry picked from commit 7aeac8eddce2fbd42b5d0b8e3a77162f9fc31bde)
> Fix inactivity timer not being set correctly

- Makefile
- rebar.config
- tools/generate_cfg.es
`make quickrun` starts Mongoose node without the need of creating release.
> No rel required

- apps/ejabberd/src/gen_mod.erl
- apps/ejabberd/src/mod_last.erl
- apps/ejabberd/src/mod_offline.erl
- apps/ejabberd/src/mod_privacy.erl
- apps/ejabberd/src/mod_private.erl
- apps/ejabberd/src/mod_roster.erl
- apps/ejabberd/src/mod_roster_mnesia.erl
- apps/ejabberd/src/mod_roster_odbc.erl
- apps/ejabberd/src/mod_vcard.erl
- rel/files/ejabberd.cfg
Roster logic module: `mod_roster`, backend modules: `mod_roster_mnesia`, `mod_roster_odbc`
> Unify roster logic

- apps/ejabberd/src/ejabberd_admin.erl
(cherry picked from commit c7d41b8d2736bb39b0b5e16b2945a7e2244d454a)
> Fix get_loglevel

- apps/ejabberd/c_src/ejabberd_zlib_drv.c
- apps/ejabberd/test/zlib_driver_SUITE.erl
We have found an issue in our production ejabberd node. Upon stream compression has been initiated any incoming stanza which is exactly 1024 bytes long would crash the zlib driver and connection would terminate. The problem is the following:
in apps/ejabberd/c_src/ejabberd_zlib_drv.c file internal buffer size is defined to be equal 1024 bytes.
In inflate logic one edge case is not properly handled, namely when original chunk (before deflated) is exactly BUF_SIZE bytes long.
Internal loop: while (err == Z_OK && d->i_stream->avail_out == 0) checks for the avail_out field to be greater than zero, however when original chunk is exactly BUF_SIZE bytes avail_zero is 0 because the output buffer was completely filled by inflating the chunk. So code enters the loop one extra time despite the fact …
> Fix zlib driver crashing on 1024-bytes chunks

- Makefile
Doing `$ make quickrun` doesn't work on a clean build because ./etc
doesn't exist
> Create ./etc if doesn't exist for quickrun

- apps/ejabberd/src/ejabberd_cowboy.erl
Passing `undefined` (i.e. not configuring this option within the listener section) will lead to the following error:
```
2015-03-10 12:04:26.187 [error] <0.333.0> CRASH REPORT Process <0.333.0> with 0 neighbours exited with reason: no match of right hand value {error,{options,{password,undefined}}} in ranch_acceptors_sup:init/1 line 38 in gen_server:init_it/6 line 330
2015-03-10 12:04:26.188 [error] <0.331.0> Supervisor {<0.331.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('ejabberd_cowboy_0.0.0.0_5280', 10, ranch_ssl, [{port,5280},{ip,{0,0,0,0}},{max_connections,1024},{certfile,"/etc/ssl/custom/server.crt"},{keyfile,...},...]) at undefined exit with reason no match of right hand value {error,{options,{password,undefined}}} in …
```
> Cowboy key_pass should be a empty string default

- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/jlib.erl
- apps/ejabberd/src/mod_admin_extra_accounts.erl
- apps/ejabberd/src/mod_muc_room.erl
- apps/ejabberd/src/mod_offline.erl
Hi guys, at my company we are developing a mobile chat based on MongooseIM. For our android client we are using the ASmack library and we get an date parsing error when the client receives an offline message.
The offending date is the one passed inside the x tag of the [XEP-0091](http://xmpp.org/extensions/xep-0091.html) extension. Since I noticed it has obsoleted, I thought I could have removed it from MongooseIM.
But I'm a Ruby developer and know just the very basics of Erlang. I've managed to remove the <x> tag from the message stanza, recompiled the repo and the server works. No date parsing error on the client anymore.
But I don't know if I need to add some tests around my changes or if the changes are correct (ie. do I need to remove/add something else?). I'd love to contribute to …
> Remove obsolete XEP-0091 timestamp

- apps/ejabberd/src/mod_admin_extra_sessions.erl
On a production system it is highly probable that some of the sessions obtained before can be dead while reading the presence info.
> catch exception when c2s process is dead while reading presence

- Makefile
- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_c2s.hrl
- apps/ejabberd/src/ejabberd_odbc.erl
- apps/ejabberd/src/ejabberd_receiver.erl
- apps/ejabberd/src/ejabberd_socket.erl
- apps/ejabberd/src/ejabberd_sup.erl
- apps/ejabberd/src/ejabberd_tls.erl
- apps/ejabberd/src/ejabberd_zlib.erl
- apps/ejabberd/src/gen_mod.erl
- apps/ejabberd/src/mod_last.erl
- apps/ejabberd/src/mod_mam_muc_odbc_async_pool_writer.erl
- apps/ejabberd/src/mod_mam_muc_odbc_async_writer.erl
- apps/ejabberd/src/mod_mam_odbc_async_pool_writer.erl
- apps/ejabberd/src/mod_mam_odbc_async_writer.erl
- apps/ejabberd/src/mod_mam_sup.erl
- apps/ejabberd/src/mod_offline.erl
- apps/ejabberd/src/mod_privacy.erl
- apps/ejabberd/src/mod_privacy_odbc.erl
- apps/ejabberd/src/mod_private.erl
- apps/ejabberd/src/mod_roster.erl
- apps/ejabberd/src/mod_roster_mnesia.erl
- apps/ejabberd/src/mod_roster_odbc.erl
- apps/ejabberd/src/mod_vcard.erl
- apps/ejabberd/src/mongoose_metrics.erl
- apps/ejabberd/src/xml_stream.erl
- rel/reltool.config.script
- src/mongooseim.erl
- tools/summarise-ct-results
* add metrics related to received and sent xmpp data size
* inet stats for:
* regular odbc workers (all types)
* async mam workers
* distributed Erlang
* allows to specify time execution of which backend functions should be measured
* improve global metrics to be properly reported
* other minor improvements
> More metrics 2

- apps/ejabberd/src/ejabberd_admin.erl
- apps/ejabberd/src/ejabberd_auth.erl
- apps/ejabberd/src/ejabberd_auth_anonymous.erl
- apps/ejabberd/src/ejabberd_auth_external.erl
- apps/ejabberd/src/ejabberd_auth_http.erl
- apps/ejabberd/src/ejabberd_auth_internal.erl
- apps/ejabberd/src/ejabberd_auth_ldap.erl
- apps/ejabberd/src/ejabberd_auth_odbc.erl
- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_gen_auth.erl
- apps/ejabberd/src/extauth.erl
- apps/ejabberd/src/mod_register.erl
- apps/ejabberd/src/mongoose_api_users.erl
- apps/ejabberd/src/scram.erl
- apps/ejabberd/test/auth_http_SUITE.erl
- rebar.tests.config
Refactoring of auth-related modules.
One of the most significant changes is that all auth backend modules expect `ejabberd:luser()` and `ejabberd:lserver()` now in callbacks defined by `ejabberd_gen_auth` behaviour. In other words they don't do `jlib:nodeprep(User)` or `jlib:nameprep(Server)`
All changes taken from PR #378
> Auth refactoring

- apps/ejabberd/src/ejabberd_c2s.erl
Split `ejabberd_c2s:handle_info/3` into multiple functions, remove redundant code, extract named predicates, reformat.
> Refactor ejabberd_c2s:handle_info/3

- apps/ejabberd/src/ejabberd_auth_anonymous.erl
- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_sm.erl
- apps/ejabberd/src/mod_ping.erl
- apps/ejabberd/src/mod_stream_management.erl
- apps/ejabberd/src/mongoose_metrics_hooks.erl
- apps/ejabberd/test/ejabberd_c2s_SUITE_mocks.erl
`Reason` says how the connection was closed:
* normal
* replaced
* resumed
> adds `Reason` arg to sm_remove_connection_hook

- rel/reltool.config.script
`reltool.config.script` referenced application `mongoose` instead
of `mongooseim`. Such application doesn't exist, hence wasn't included
in the release.
Since `ejabberd_ctl.erl` used by `mongooseimctl` looks in
`application:loaded_applications/0` for name `mongooseim`,
the subcommand `started` looped until all retries were exhausted and
always returned a failure, irrelevant of the fact that the server was
already running in the background.
> [DON'T MERGE] Fix `mongooseimctl started`

- README.md
It would be nice to give some visibility to the Docker image, even though it is still not official, and still experimental. Also a call for contribution is good.
What do you think?
> Pointing to experimental Docker image

- CHANGELOG.md
[skip ci]
- Added lacking versions: before 1.2.0 and after 1.3.1
- Added dates, in ISO format
- Added some links to some XEPs
- Fixed minor typos
TODO?
- Add items for 0.1.0, 0.9.0, 1.0.0, 1.1.0, 1.2.1, 1.2.2, 
- Add downloads
How do you feel about that? Please review...
> (tried to) maintain the CHANGLOG file

- README.md
Also: re-word the bit about re-implemented BOSH. Anyone not intimately familiar with ejabberd/MongooseIM development history won't care, and will only get confused.
> Have text flow around the MongooseIM logo in README.md [skip ci]

- apps/ejabberd/src/mod_offline_stub.erl
...when MAM is used, but mod_offline is not.
> Add mod_offline_stub to prevent <service-unavailable/>

- apps/ejabberd/src/ejabberd_c2s.erl
Local tests and coverage reports show almost complete coverage of the refactored FSM state. Testing against the version just before refactoring shows similar coverage and the same tests pass without modification.
I couldn't come up with a test case which would fall into `wait_for_stream({xmlstreamelement, _}, ...)` clause - if the first element sent on a newly opened socket is not `<stream:stream>` it still gets passed to the function wrapped as `{xmlstreamstart, _, _}`, not `{xmlstreamelement, _}`. See https://github.com/esl/ejabberd_tests/tree/element-before-stream-start for a tried but finally dropped approach. It's probably something lower (even lower than `ejabberd_receiver`, probably XML parser in `xml`).
Ready to merge once Travis passes.
> Refactor ejabberd_c2s:wait_for_stream/2

- apps/ejabberd/include/jlib.hrl
- apps/ejabberd/src/mod_muc_room.erl
> Removed obsolete namespace from mediated invitation stanza

- doc/Advanced-configuration.md
- doc/advanced-configuration/database-backends-configuration.md
Description of database configuration in docs was in two seperated locations, so I made them reffering on each other.
> Database docs fix

- apps/ejabberd/src/mod_mam_con_ca_arch.erl
- apps/ejabberd/src/mod_mam_con_ca_sup.erl
This allows amongst others to pass credentials to mod_mam_con_ca_arch wokers for connecting to cassandra.
> mod_mam cassandra: pass config to workers (eg credentials)

- .travis.yml
- apps/ejabberd/rebar.config
- apps/ejabberd/src/dynamic_compile.erl
- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_c2s.hrl
- apps/ejabberd/src/ejabberd_s2s_out.erl
- apps/ejabberd/src/eldap.erl
- apps/ejabberd/src/mod_muc_room.erl
- rebar.config
This PR makes MongooseIM compatible with OTP 18.0.
> Compatibility with OTP 18.0

- apps/ejabberd/src/ejabberd_ctl.erl
- rel/files/mongooseimctl
- test/ejabberd_tests/tests/distributed_helper.erl
- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
When invoking `mongooseimctl` with arguments containing spaces, instead of needing two levels of nested quoting, just use one. See the issue for an example: #494. Personally I think we could read command-line arguments more elegantly, with something like:
```sh
ARGS=""
for ARG in "$@"
do
if [ "$ARG" = '--' ]
then
break
else
ARGS+='"'$ARG'" '
fi
done
```
Or using a `case`.
> commandline arguments with whitespace

- apps/ejabberd/rebar.config
- apps/ejabberd/src/ejabberd_auth_odbc.erl
- apps/ejabberd/src/ejabberd_odbc.erl
- apps/ejabberd/src/odbc_queries.erl
- apps/ejabberd/test/ejabberd_odbc_SUITE.erl
- apps/pgsql/src/pgsql.erl
- doc/Advanced-configuration.md
This pull request fixes a couple of SQL queries. Above all it fixes the keep-alive query that was wrongly prepared for the ODBC layer and was not restarting a connection worker when the query failed.
> ODBC keep-alive

- apps/ejabberd/src/ejabberd_auth_odbc.erl
- test/ejabberd_tests/tests/login_SUITE.erl
In case of logging a non-existent user using PLAIN sasl method, there was a badmatch causing wrong reply sent to the client. This PR fixes it and also adds tests cases where non-existent users try to authenticate.
> Fix auth odbc check password

- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_receiver.erl
- apps/ejabberd/src/mod_ping.erl
- test/ejabberd_tests/tests/mod_ping_SUITE.erl
This PR introduces keep alive hook which is run when the client sends XMPP whitespace keep alive packets. This can be useful in mod_ping if we want to reset the timer after such packets.
> Keep alive hook

- tools/docker/start_and_prepare_slapd.sh
`docker ps` without `-a` only checks whether a container is running, not whether it exists or not. Therefore, the test performed in the script checked whether there was a running container named `mongooseim_ldap` and if not (if none was running, **not** if none existed) it tried to do `docker run` - which could result in an error (see below for the gory details). Now the check verifies whether a container exists at all - running or not.
Context:
```
17:14:42 erszcz @ x4 : ~/work/esl/mongooseim (c-766964796f *)
$ tools/docker/start_and_prepare_slapd.sh
+ boot2docker up
Waiting for VM and Docker daemon to start...
.o
Started.
Writing /Users/erszcz/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/erszcz/.boot2docker/certs/boot2docker-vm/cert.pem
Writing …
```
> Check if container exists not whether it's running or not

- apps/ejabberd/src/ejabberd_commands.erl
- apps/ejabberd/src/ejabberd_ctl.erl
- apps/ejabberd/src/mod_admin_extra_roster.erl
This PR fixes #381 
There was a function, that checked the types of input arguments. If the arguments weren't integer or string - it was displaying a note about the ejabberd_xmlrpc module +  was marking these function with "*" in the general commands listing.  
I believe that the change is so simple and more like documentation/help change, that we don't need to test it. Am I right ;)?
> Inconsistent `mongooseimctl` help text 

- apps/ejabberd/src/jlib.erl
- apps/ejabberd/src/mod_muc_room.erl
- test/ejabberd_tests/tests/muc_SUITE.erl
This PR fixes #376
The problem was the initial_state function, which wasn't handling the case in which the create-room presence had more than one `<x>` subelements. To be more specific, it was crashing when the first `<x>` subelement wasn't  exactly `<x xmlns="http://jabber.org/protocol/muc"/>` or the presence had no children.
> Fix create MUC room function

- apps/ejabberd/src/ejabberd_receiver.erl
- test/ejabberd_tests/tests/connect_SUITE.erl
> fix crash on bad xml input

- doc/Advanced-configuration.md
In fact, information can be found elsewhere in the documentation, but
it's not obvious that some require a private key and certificate
(chain) in the same file while others need them in separate files.
> Document how to configure TLS for various modules

- apps/ejabberd/src/acl.erl
- apps/ejabberd/src/ejabberd_auth.erl
- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_local.erl
- doc/developers-guide/hooks_description.md
- test/ejabberd_tests/rebar.config
- test/ejabberd_tests/tests/connect_SUITE.erl
- test/ejabberd_tests/tests/legacy_stream_helper.erl
- test/ejabberd_tests/tests/login_SUITE.erl
The idea behind this PR is to make user blocking/banning easier. Now the first phase is the old acl matching. If this allows a user the the hook `check_user_allowed` is run (as run_fold) with initial value `allow`.
> Check user allowed hook

- apps/ejabberd/src/mongoose_metrics.erl
- apps/ejabberd/test/carbon_cache_server.erl
- apps/ejabberd/test/carbon_server.erl
- apps/ejabberd/test/ejabberd_helper.erl
- apps/ejabberd/test/ejabberd_sm_SUITE.erl
- apps/ejabberd/test/mongooseim_metrics_SUITE.erl
- test/ejabberd_tests/tests/mam_SUITE.erl
This PR prevents creating a spiral metric for skipped hook. Such metric is dangerous because it may have lot of (tens of thousands) updates in a minute which can lead to too long message inbox for process holding this metric and can crash `exometer_reporter`. 
Also, this PR adds some tests for metric subscriptions.
> Do not create nor update skipped hooks

- .travis.yml
- Makefile
- tools/configure
Current default configuration which is `mnesia-only` is error-prone. This PR changes that so the default config is full now. This approach will be easier for most people trying new features like f.e. Riak backends.
> change `make rel` default configuration to `full`

- apps/ejabberd/src/ejabberd_auth.erl
- apps/ejabberd/src/mod_register.erl
- test/ejabberd_tests/tests/login_SUITE.erl
This began as a task to increase coverage, then became about making Mongoose conform to XEP 0077,  but to do this we need to refactor.
> Refactor inband registration (and cancelation)

- tools/configure
In same cases the Erlang/OTP doesn't have `odbc` application installed. In such cases we shouldn't try to include it in the release.
> configure - do not include odbc application if it doesn't exist

- apps/ejabberd/src/mod_admin_extra_accounts.erl
- apps/ejabberd/src/mod_admin_extra_last.erl
- apps/ejabberd/src/mod_admin_extra_private.erl
- apps/ejabberd/src/mod_admin_extra_roster.erl
- apps/ejabberd/src/mod_admin_extra_stanza.erl
- apps/ejabberd/src/mod_admin_extra_stats.erl
- apps/ejabberd/src/mod_admin_extra_vcard.erl
- test/ejabberd_tests/roster.template
- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
I tried to make admin interface more hospitable. It should do some checks on input and inform about result of command.
Improved following modules:
- mod_admin_extra_accounts
- mod_admin_extra_last
- mod_admin_extra_private
- mod_admin_extra_roster
- mod_admin_extra_stanza
- mod_admin_extra_stats
- mod_admin_extra_vcard
> Admin extra interface

- Makefile
- apps/ejabberd/src/ejabberd_local.erl
- apps/ejabberd/src/ejabberd_router.erl
- apps/ejabberd/src/ejabberd_s2s.erl
- apps/ejabberd/src/ejabberd_sm.erl
- apps/ejabberd/src/xmpp_router.erl
- apps/ejabberd/test/xmpp_route_SUITE.erl
I removed 8 instances of identical code from 4 separate modules, and implemented them as a generic `xmpp_router`. The modules now expose their own distinct implementations, under `Module:do_route/3`. These module-specific implemenations were not changed.
Edit: yes, this makes the ?ERROR_MSG in the generic implementation a little less informative, as the trace will always be logged as coming from `xmpp_router`. This is why the implementation module is referenced in the error message itself. I believe the cleanup is worth the tradeoff.
> Remove duplicate code, make abstract xmpp_router

- test/ejabberd_tests/tests/adhoc_SUITE.erl
- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
- test/ejabberd_tests/tests/last_SUITE.erl
- test/ejabberd_tests/tests/mam_SUITE.erl
- test/ejabberd_tests/tests/metrics_c2s_SUITE.erl
- test/ejabberd_tests/tests/metrics_roster_SUITE.erl
- test/ejabberd_tests/tests/metrics_session_SUITE.erl
- test/ejabberd_tests/tests/muc_SUITE.erl
- test/ejabberd_tests/tests/presence_SUITE.erl
- test/ejabberd_tests/tests/privacy_SUITE.erl
- test/ejabberd_tests/tests/private_SUITE.erl
- test/ejabberd_tests/tests/sic_SUITE.erl
This PR changes the old, deprecated way of user/resource (`escals:story(Config, [1,1], ...`) selecting to the new one (`escalus:story(Config, [{alice, 1}, {bob, 1}], ...`)
> change deprecated users picking

- Makefile
Either the the documentation (i.e. README.md) is out of date, or someone has introduced a mistake in the `Makefile`.
According to the documentation,  one should be able to compile `MongooseIM` by simply running `make`.  However, this does not seem to hold true anymore. This [commit](https://github.com/esl/MongooseIM/blob/7682033c3744990671cb93c16071a6b2d158fb96/Makefile#L10), injects some targets before the `all` target.
> Make's default target does not build MongooseIM

- apps/ejabberd/src/mod_mam_muc.erl
- apps/ejabberd/src/mod_mam_riak_timed_arch_yz.erl
- doc/modules/mod_mam.md
- test/ejabberd_tests/tests/mam_SUITE.erl
This PR introduces simplest MAM MUC archive in Riak. MUC archives are kept in the same buckets as regular one-to-one archives. The archive is "owned" by the room only - this means:
* the message is stored only once despite the number of occupants
* everyone can read the history, even if joined after a message was archived
> Riak MAM for muc

- apps/ejabberd/src/ejabberd_receiver.erl
- test/ejabberd_tests/tests/connect_SUITE.erl
Fixes #411 
Fixes #626 
Contains a regular test reproducing the issue.
About tests. I used sys:suspend/1 to prepare c2s process to "crash properly" :)
I tried to use "build-in" tests for Mongoose (in apps/ejabberd/tests) but we actually want to test change in ejabberd_receiver, not ejabberd_c2s. And each time I end up with mocked ejabberd_receiver. :)
I understand that ejabberd_receiver:starttls/2, compress/2 and become_controller/2 could also crash.
But I don't have a test for them yet. And I never saw them crashing :)
> Catch noproc error in ejabberd_receiver

- apps/ejabberd/src/mod_mam_cache_user.erl
- apps/ejabberd/src/mod_mam_mnesia_dirty_prefs.erl
- apps/ejabberd/src/mod_mam_mnesia_prefs.erl
- apps/ejabberd/src/mod_mam_muc_cache_user.erl
- apps/ejabberd/src/mod_mam_odbc_prefs.erl
- apps/ejabberd/src/mod_mam_odbc_user.erl
- apps/ejabberd/src/mod_mam_utils.erl
- apps/ejabberd/src/shaper_srv.erl
- test/ejabberd_tests/tests/mam_SUITE.erl
Add tests for MAM preferences
Bug 1: JIDs are not normalized before stored in preferences
Bug 2: Result from SQL query never matches in get_behaviour
> Fix bugs in mod_mam_odbc_prefs

- .travis.yml
- README.md
[Squashed commits]
Added basic integration with buildtimetrend service for easy and nice inspection of various build parameters.
More info on the service is available at: http://buildtimetrend.herokuapp.com
Other projects are available in dashboard/projects section. Not much can be said about quality of this service as it's a new thing. But looks as nice complement to travis and coveralls. More badges and better resolution (inter-test-suite statistics) will be added over time as we find more about this service.
> [skip ci] added support for build dashboard

- apps/ejabberd/src/ejabberd_c2s.erl
In a resumption, resume timeout is not merged, so it will get the default resume timeout instead of the timeout of the configuration file.
> preserve resume timeout when a session is resumed

- doc/Advanced-configuration.md
- rel/files/app.config
I  found a memory "leak" while load testing, the increased memory usage was caused by TLS processes.
The processes were started by fusco, through which the external API was called. 
I found the solution here: https://github.com/ninenines/gun/issues/68, although I don't know if 10 minutes is a sane value. I will remove the do-no-merge label after testing this value - especially, I need to check if it influence server side(in our case cowboy connections).
More info about the bug: https://support.process-one.net/browse/TSUN-225
> set ssl session_lifetime to 10 minutes

- apps/ejabberd/src/mongoose_cluster.erl
- rel/files/mongooseim
- test/ejabberd_tests/tests/distributed_helper.erl
Apart from the rationale in 20d40e8 description, there's one more reason: using just RPC (instead of a shell-out) to cluster/disband nodes makes it possible to keep cover-compiled modules loaded through the whole cluster life cycle. This is required to make rel-1.7-service tests finally pass.
> Join/leave cluster completely at the Erlang level

- .gitignore
- .travis.yml
- tools/travis-test.sh
This PR uses new docker infrastructure and introduces new job on travis which only runs dialyzer for MongooseIM.
> Dialyzer on travis

- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
Due to compiler warnings:
`` ejabberdctl_SUITE.erl:750: Warning: use of operator '=/=' has no effect ``
> Fixed dummy assertions

- .travis.yml
- Makefile
- apps/ejabberd/src/ejabberd_router.erl
- apps/ejabberd/src/ejabberd_service.erl
- apps/ejabberd/src/mod_websockets.erl
- apps/ejabberd/src/mongoose_cover_helper.erl
- apps/ejabberd/test/mod_websockets_SUITE.erl
- doc/advanced-configuration/Listener-modules.md
- rel/files/ejabberd.cfg
- rel/reltool_vars/fed1_vars.config
- rel/reltool_vars/node1_vars.config
- rel/reltool_vars/node2_vars.config
- rel/vars.config
- test/ejabberd_tests/default.spec
- test/ejabberd_tests/run_common_test.erl
- test/ejabberd_tests/test.config
- test/ejabberd_tests/tests/component_SUITE.erl
- test/ejabberd_tests/tests/conf_reload_SUITE.erl
- test/ejabberd_tests/tests/connect_SUITE.erl
- test/ejabberd_tests/tests/distributed_helper.erl
- test/ejabberd_tests/tests/privacy_SUITE.erl
- test/ejabberd_tests/tests/reload_helper.erl
- test/ejabberd_tests/tests/s2s_SUITE.erl
- tools/travis-common-vars.sh
- tools/travis-test.sh
This PR:
* changes the routing mechanism - the new `external_component` table is checked firstly
* allows to use external_component registered on different node in the cluster
* allows to expose `ejabberd_service` over WebSockets
* includes changes to tests:
* new dev node for federation
* old node2 is now meant to be used only for clustering with node2
* new `component_SUITE` testing ejabberd_service interface
* `reload_helper` module to be used whenever a node reload is required
Todo:
> External component adjustments

- apps/ejabberd/src/ejabberd_listener.erl
- apps/ejabberd/test/ejabberd_listener_SUITE.erl
- doc/advanced-configuration/Listener-modules.md
- tools/travis-test.sh
* increased tcp backlog for ejabberd_listeners
* fix passing tcp opts from config file
* test for default and passed backlog parameter
Also this PR is important to allow running parallel tests, introduced in #706, on MacOS X. Together with @pzel we discovered (mainly based on blogpost [1]) that the backlog queue implementation on MacOS X is less efficient than on linux. Too low backlog on MongooseIM side for port 5222 manifests by strange `{error,econnreset}`
[1]. http://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html
> TCP backlog improvements

- .travis.yml
- Makefile
- README.md
- apps/ejabberd/src/ejabberd_ctl.erl
- doc/user-guide/release_config.md
- mkdocs.yml
- rel/files/app.config
- rel/files/mongooseim
- rel/files/mongooseimctl
- rel/reltool.config.script
- rel/vars.config
- rel/vars.config.in
- test/ejabberd_tests/tests/distributed_helper.erl
- tools/configure
- tools/install
- tools/test-install.sh
This PR partially addresses #689 and issues mentioned therein.
It's now possible to install MongooseIM from source in two modes: so called `system` and unnamed, but let's say, `user` mode. The better tested mode is `system` as it's internally used to generate RPM packages.
An environment for building (as of now RPM) packages is accessible by cloning ESL-internal [command line interface](https://gitlab.erlang-solutions.com/current-projects/necromancer-cli).
To manually test the installation one can run `tools/test-install.sh`. This script is intended for careful inspection by a human user, not for automation. Results should be similar to those described below.
On Mac:
```sh
./tools/configure with-all user=erszcz prefix=/tmp/mim-sandbox-system system=yes
cat configure.out …
```
> Enable configure, make, make install procedure

- apps/ejabberd/src/mod_auth_token_odbc.erl
- tools/travis-setup-db.sh
* odbc settings for the Travis build now include the ``ByteaAsLongVarBinary`` setting to make sure that columns containing binary data are fetched as such, not as strings
> Add ByteaAsLongVarBinary option to odbc.ini for Travis

- apps/ejabberd/src/mod_keystore.erl
- apps/ejabberd/test/keystore_SUITE.erl
This PR addresses https://github.com/esl/MongooseIM/issues/723
* Clearing ets table `keystore` for appropriate domain when module stops instead of deleting the whole table.
* Added test in `keystore_SUITE` which checks `mod_keystore` functionality for multiple domains when the module stops for one of them
> Mod_keystore clearing the table

- .gitignore
- Makefile
- apps/ejabberd/src/ejabberd_session.erl
- apps/ejabberd/src/ejabberd_sm.erl
- apps/ejabberd/src/ejabberd_sm_mnesia.erl
- apps/ejabberd/src/ejabberd_sm_redis.erl
- apps/ejabberd/src/mod_carboncopy.erl
- apps/ejabberd/src/mongoose_session.erl
- apps/ejabberd/test/ejabberd_sm_SUITE.erl
- apps/ejabberd/test/mongoose_cleanup_SUITE.erl
- test/ejabberd_tests/src/ct_mongoose_hook.erl
- test/ejabberd_tests/tests/carboncopy_SUITE.erl
This PR addresses #[not-assigned]
Per-session carbon copy status (enabled/disabled/version) is stored as part of `#session.info` in the `session` table. This eliminates the need for a separate `carboncopy` table, and reduces the number of lookups made by `mod_carboncopy`, per message route event, from 2 to 1. Additionally, no cleanup phase is necessary when a node goes down, as carbons get cleaned up as part of the `session` table cleanup.
To allow this, the `ejabberd_sm_*` backends must be capable of merging `info` proplists when overwriting a user session with `create_session`. This is conveniently achieved via `ejabberd_session:merge_info(#session{}, #session{}) -> #session{}`
To store information for a given xmpp full jid, use `ejabberd_sm:store_info(user(), server(), resource(), …
> Carbons in sessions

- rebar.config
- test/ejabberd_tests/rebar.config
- test/ejabberd_tests/test.config
- test/ejabberd_tests/tests/mam_SUITE.erl
- test/ejabberd_tests/tests/metrics_c2s_SUITE.erl
- test/ejabberd_tests/tests/mod_time_SUITE.erl
- test/ejabberd_tests/tests/muc_SUITE.erl
- test/ejabberd_tests/tests/oauth_SUITE.erl
To enable it, uncomment the following line:
`   {stanza_log, true}.`
in test config.
The log contains only stanzas which have JID defined and are:
-  either sent using escalus_connection
-  or received (not peeked) in escalus_client.
> Add an option to log stanzas in CT tests.

- apps/ejabberd/src/ejabberd_admin.erl
- apps/ejabberd/src/mongoose_cluster.erl
- doc/operation-and-maintenance/Cluster-configuration-and-node-management.md
- rel/files/mongooseim
- rel/files/mongooseimctl
- test/ejabberd_tests/test.config
- test/ejabberd_tests/tests/cluster_commands_SUITE.erl
- test/ejabberd_tests/tests/distributed_helper.erl
- test/ejabberd_tests/tests/ejabberd_node_utils.erl
- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
- test/ejabberd_tests/tests/ejabberdctl_helper.erl
This PR addresses https://github.com/esl/MongooseIM/issues/685
* Replacing commands `add_to_cluster` and `remove_from_cluster` with brand-new
`join_cluster` and `leave_cluster` in _ejabberd_admin_ module. The commands use module _mongoose_cluster_ for the cluster management hence it's done completely at the Erlang level
* updated tests in _cluster_commands_SUITE_
> Rel 1.7 mongoose cluster

- test/ejabberd_tests/test.config
- test/ejabberd_tests/tests/login_SUITE.erl
- test/ejabberd_tests/tests/s2s_SUITE.erl
In most cases it's enough to just register/remove users by doing rpc calls to the server. This will shorten the time required for users registration before the real test case which makes parallel tests with fresh users even more efficient.
> escalus_ejabberd as default escalus_user_db in tests

- test/ejabberd_tests/tests/mongoose_helper.erl
- test/ejabberd_tests/tests/sm_SUITE.erl
This PR optimises `sm_SUITE` by running test cases in parallel. All tests cases have been divided into 2 separate groups, both have `parallel` property.
> parallelize sm_SUITE

- apps/ejabberd/src/mod_bosh.erl
- test/ejabberd_tests/tests/bosh_SUITE.erl
This PR:
* removes repetitions from bosh_SUITE and changes group `time` to run test cases in parallel. This group is the longest one. Further parallelisation is possible but will not optimise the whole SUITE that much (probably 3-4 s)
* removes dead code from `mod_bosh`
> Parallel bosh suite

- rel/files/ejabberd.cfg
- rel/reltool_vars/node1_vars.config
- rel/reltool_vars/node2_vars.config
- test/ejabberd_tests/rebar.config
- test/ejabberd_tests/tests/connect_SUITE.erl
- test/ejabberd_tests/tests/mod_http_notification_SUITE.erl
* module used by mod_http_notification_SUITE is started only for the suite
* optimised connect_SUITE (by running more test cases in parallel)
* uses [proger/erlsh](https://github.com/proger/erlsh) to run `opnessl s_client` command to get status code - fixes strange and random failures of `node2_supports_DHE-RSA-AES256-SHA_only'}]
end.
` test case
> Stabilise and clean tests

- doc/modules/mod_http_notification.md
Change  url->URL and http->HTTP in mod_http_notification doc, plus added some examples of external services
> [skip ci] http notifs doc: typos and precisions 

- doc/modules/mod_mam.md
From user-to-user to one-to-one, from client-to-client to one-to-one, form groupchat to group chat, from Riak to Riak KV, some more typos...
> [skip ci] precisions, unification on mod_mam doc

- apps/ejabberd/src/ejabberd_listener.erl
- apps/ejabberd/test/ejabberd_listener_SUITE.erl
Calls to accept/3 and udp_recv/3 are local. This results in the ejabberd_listener keeping
the old version of code. The manual code reloading forces the listener process to crash.
With fully qualified calls the manual code reloading would not
crash the listener process.
> Make calls to accept/3 and udp_recv/3 fully qualified

- apps/ejabberd/src/cyrsasl.erl
- apps/ejabberd/src/ejabberd_c2s.erl
- test/ejabberd_tests/default.spec
- test/ejabberd_tests/tests/sasl_SUITE.erl
This change allows SASL authentication mechanism implementations to optionally supply a value for the `<text>` tag in `<failure>` results (as permitted by https://tools.ietf.org/html/rfc6120#section-6.5). It's backwards-compatible, so shouldn't break anything.
> Add support for <text> tag in auth failures

- doc/Advanced-configuration.md
- doc/advanced-configuration/Listener-modules.md
This PR addresses (none)
* Extends documentation
* No tests updated/added
*  Document how to apply max_fsm_queue to particular listeners: `ejabberd_c2s` and `ejabberd_service` and how the value of this option set globally relates to the ones set per listeners.
> Extend documentation on max_fsm_queue

- apps/ejabberd/include/jlib.hrl
- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/mod_privacy.erl
- test/ejabberd_tests/tests/privacy_SUITE.erl
- test/ejabberd_tests/tests/privacy_helper.erl
This PR is the first step towards addressing #718.
Blocking commands are a simplified api to privacy lists, and some minor things were missing in current implementation of privacy lists, so here they are.
It also introduces some changes in c2s to make it a bit more readable.
> Privacy fixes and a bit of cleanup

- apps/ejabberd/src/ejabberd_sm.erl
- test/ejabberd_tests/tests/muc_SUITE.erl
This PR parallelises most of the groups in muc_SUITE. Before, suite time was around 152s, now it's 32s.
Further optimisations are possible by. f.e merging some groups together.
> Parallel muc suite

- Makefile
- doc/advanced-configuration/database-backends-configuration.md
- doc/user-guide/release_config.md
- tools/travis-build-and-push-docker.sh
- tools/travis-build.sh
(The following is copied from commit description)
This target requires another one:
%:
@:
which drastically affects how make handles undefined targets.
A single typo in the CLI or dependency chain can cause silent errors.
With the above target, this works:
$ make zxczxczxc && echo a
a
While the default make behaviour is:
$ make zxczxczxc && echo a
make: *** No rule to make target `zxczxczxc'.  Stop.
Fail fast and loud, don't let silent errors sneak into the build process.
> Remove `configure` make target

- rel/files/ejabberd.cfg
- rel/files/ejabberd.cfg.token-support
- test/ejabberd_tests/tests/component_SUITE.erl
- test/ejabberd_tests/tests/mam_SUITE.erl
- test/ejabberd_tests/tests/muc_SUITE.erl
- test/ejabberd_tests/tests/muc_helper.erl
As it was, if muc_light_legacy_SUITE was run before muc_SUITE then the latter failed. The reason was that muc was loaded statically at startup, and registered itself under muc.localhost in local routing table. muc_light was loaded dynamically, registered itself under the same domain, and then was unloaded.
> Muc test fix

- apps/ejabberd/priv/mysql.sql
- apps/ejabberd/priv/pg.sql
This PR addresses #713 
Just two indices, verified to do what they are supposed to. It is probably not a big deal (do users create lots of privacy lists?), but it doesn't hurt to have them since additional cost of inserting/updating is negligible, while speedup can be large.
> Privacy indices

- apps/ejabberd/src/mod_muc_light.erl
- apps/ejabberd/src/mod_muc_light_db_mnesia.erl
- test/ejabberd_tests/tests/muc_light_SUITE.erl
This PR addresses https://github.com/esl/MongooseIM/issues/838 and #839
For #838:
added tests with four cases:
- set `{rooms_per_page, infinity}` and empty room list
- set `{rooms_per_page, infinity}` and not empty room list
- set `{rooms_per_page, 1}` and not empty room list
- set `{rooms_per_page, 1}` and empty room list <-- this test hasn't passed
Fixed the issue in module `mod_muc_light`
---
For #839 :
- added test for changing room name configuration
- fixed the issue with replacing the room configuration in mnesia backend
> Muc light disco#items fix + room confuguration fix

- apps/ejabberd/src/mod_muc_light_db_mnesia.erl
- test/ejabberd_tests/tests/muc_light_SUITE.erl
It was not possible for client to [retrive room list](https://xmpp.org/extensions/inbox/muc-light.html#disco-occupied-rooms) after[ destroying any room](https://xmpp.org/extensions/inbox/muc-light.html#destroying-a-room) in Muc Light because of a timeout. 
The reason lies in `mod_muc_light_db_mnesia:destroy_room_transaction/1` [1]. 
The room is removed from `muc_light_room` table but it's still untouched in the user's room list in `muc_light_user_room`. Then, the _disco#items_ request looks through this table and tries to obtain unexistent room's information[2] which results with `{error, not_exists}`[3] and client get no response
* tests for destrying room and retriving a room list
* fixed the issue in `mod_muc_light_db_mnesia`
[1] …
> Retrieve rooms after room destruction (muc_light)

- apps/ejabberd/src/ejabberd_auth.erl
This PR addresses #856 
It is just a simple one-liner - some client implementation call this function with empty username, which might be a bug, but still - since you can't register a user with an empty username we don't have to check backends here, can return immediately and save on resources.
> If username is empty return immediately

- apps/ejabberd/src/ejabberd_app.erl
- doc/Advanced-configuration.md
Do not change lager loglevel when the parameter is specified in the env.
When the ejabberd app is started all lager handlers are set to the same loglevel,
either from config or default. Sometimes it is necessary to keep different handlers at
different loglevels. In this case the loglevels are set for the lager app and
a particular parameter is set in the ejabberd env so ejabberd doesn't changes
the lager loglevels on start.
> Lager init

- apps/ejabberd/src/ejabberd_auth.erl
This PR addresses #862 
* renames an instance of is_user_exists() to do_user_exist that was missed in commit e4ca38c8e622be5dae3f0bb5b4c1ff682a5afecc
> rename is_user_exists to does_user_exist

- .travis.yml
- apps/ejabberd/src/mod_keystore.erl
- rel/files/ejabberd.cfg
- test/ejabberd_tests/tests/mam_SUITE.erl
- test/ejabberd_tests/tests/oauth_SUITE.erl
- tools/setup_riak
* start `mod_keystore` and `mod_auth_token` only for tests
* stable riak job on travis
> Stabilize riak job

- apps/ejabberd/include/jlib.hrl
Both `index` and `count` in `rsm_out` can, by my reading of the XEP-0059, have 0 as a value. The existing `pos_integer()` type, however, causes dialyzer warnings for this case.
> Fix count and index types in rsm_out

- apps/ejabberd/src/mod_blocking.erl
- test/ejabberd_tests/tests/mod_blocking_SUITE.erl
The problem occured when sending [IQ block request](https://xmpp.org/extensions/xep-0191.html#block) containing some additional white characters like '\n' or indentation inside the `<block>` tag. It was causing some `function_clase` error on the server side which resulted with `not-implemented` response to the client
* test for IQ block set request containing '\n` character in it
* fixed the issue in `mod_blocking`
> Blocking Commands white spaces fix

- apps/ejabberd/src/mod_mam_utils.erl
- test/ejabberd_tests/tests/mam_SUITE.erl
Due to [XEP-0313 section Retrieving form fields](http://xmpp.org/extensions/xep-0313.html#query-form) in order to get form fields I sent IQ:
```xml
<iq id='z6WRz-20' type='get'>
<query xmlns='urn:xmpp:mam:1' queryid='3bd9571e-6fe6-4341-8589-a3f5d5371404'>
</query>
</iq>
```
and got Response:
``` xml
<iq from='ludwik.bukowski@erlang-solutions.com' to='ludwik.bukowski@erlang-solutions.com/9bb69f6dacb33248' id='z6WRz-20' type='result'>
<query xmlns='urn:xmpp:mam:1'>
<x xmlns='jabber:x:data' type='form'>
<field type='hidden' var='FORM_TYPE'>urn:xmpp:mam:1</field>
<field type='jid-single' var='with'/>
<field type='text-single' var='start'/>
<field type='text-single' var='end'/>
</x>
</query>
</iq>
```
At the first field, the *urn:xmpp:mam:1* should be between `<value>`
tags.
Proposed changes …
> Missing "value" tag while retrieving form fields

- .travis.yml
- README.md
- apps/ejabberd/rebar.config
- apps/ejabberd/src/ejabberd.erl
- apps/ejabberd/src/ejabberd_config.erl
- apps/ejabberd/src/ejabberd_sm_mnesia.erl
- apps/ejabberd/src/eldap.erl
- apps/ejabberd/src/mod_muc_room.erl
- apps/ejabberd/src/shaper_srv.erl
- doc/user-guide/Getting-started.md
- rebar.config
- test/ejabberd_tests/rebar.config
This PR addresses #785
* removed workaround for utf8 characters in host name
* removed workaround for prefixed types like `dict:dict()`
> Ditch support for R16

- apps/ejabberd/src/ejabberd_cowboy.erl
- doc/advanced-configuration/Listener-modules.md
This PR addresses #888
Allows specifying the following addition SSL options in cowboy, all optional:
* "cacertfile" specifies CA certs, used to build cert chain;
* "ciphers" specifies allowed ciphersuites;
* "versions" specifies allowed TLS/SSL versions.
> Pass more SSL options to cowboy

- doc/advanced-configuration/Listener-modules.md
Fixed typo in listener-modules.md
> fix typo in `listener-modules.md` [skip ci]

- apps/ejabberd/src/ejabberd_cowboy.erl
- doc/advanced-configuration/Listener-modules.md
- rel/reltool_vars/node1_vars.config
- rel/vars.config.in
This PR addresses #888
* cowboy ssl params are broken out into a separate section, which is just passed down to ranch_ssl, i.e., most ranch_ssl params will now be accepted
* listener module docs are updated
Resulting config will look smth like:
{ 5285, ejabberd_cowboy, [
{num_acceptors, 10},
{max_connections, 1024},
{ssl, [
{certfile, "priv/ssl/fake_cert.pem"},
{keyfile, "priv/ssl/fake_key.pem"},
{cacertfile, "priv/ssl/fake_cert_chain.pem"}
]},
> Accept most ranch_ssl options in cowboy

- apps/ejabberd/src/mod_muc_light.erl
- apps/ejabberd/src/mod_muc_light_db_mnesia.erl
- apps/ejabberd/src/mod_muc_light_utils.erl
- test/ejabberd_tests/tests/muc_light_SUITE.erl
- test/ejabberd_tests/tests/muc_light_legacy_SUITE.erl
This PR addresses #904 
* Config changes in MUC Light are now properly applied.
* Separation of responsibilities: main MUC Light code ensures config fields uniqueness after parsing the requests, the backend ensures the order of fields.
> Fix #904 - broken MUC light config update due to invalid sanitisation

- apps/ejabberd/src/ejabberd_c2s.erl
- test/ejabberd_tests/tests/privacy_SUITE.erl
- test/ejabberd_tests/tests/privacy_helper.erl
XEP-0016 section 2.11 contains the following requirement:
> When a user blocks outbound presence to a contact, the user's server MUST send unavailable presence information to the contact (but only if the contact is allowed to receive presence notifications from the user in accordance with the rules defined in RFC 6121).
However for this case no unavailable message was being sent. This patch adds this behaviour, sending an "unavailable" from A to B when all the following conditions are met:
* B is subscribed to receive presence information from A (and is therefore a contact)
* A has changed their active privacy list or modified their currently active list
* The change means that where presence notifications were previously sent from A to B, they are now blocked
This covers the unambiguous …
> Add unavailable presence after blocking contact

- apps/ejabberd/src/ejabberd_sm.erl
This PR addresses possible timeout for a cleanup call
* increase timeout for cleanup call from 5 seconds to 1 minute
I have a 3 node mongooseIM cluster with a redis sm backend. When one node goes down,
the other do a cleanup. The cleanup takes more than 5 seconds and crashes 
```
2016-08-04 14:25:03.186 [error] <0.306.0>@ejabberd_hooks:run1:240 {timeout,{gen_server,call,[ejabberd_sm,{node_cleanup,'n3@172.12.2.202'}]}}
Running hook: {node_cleanup,['n3@172.12.2.202']}
Callback: ejabberd_sm:node_cleanup
2016-08-04 14:25:03.187 [warning] <0.306.0>@mongoose_cleaner:run_node_cleanup:83 cleanup took=5001ms, result: ok
2016-08-04 14:25:03.193 [warning] <0.306.0>@mongoose_cleaner:cleanup_modules:77 cleanup result: ok
```
> Increase timeout for cleanup

- apps/ejabberd/src/ejabberd_sm_redis.erl
This PR addresses missing logging for one of cleanup calls.
* log duration of a cleanup on start
The duration of the cleanup is logged during the normal operations when the other node
goes down in `mongoose_cleaner:run_node_cleanup/1`. Let's log it on start as well.
> Log cleanup duration on start

- apps/ejabberd/src/mod_blocking.erl
- test/ejabberd_tests/tests/mod_blocking_SUITE.erl
This PR addresses the Trello card: "Blocking Command: Bad push received when unblock all"
As stated in XEP-0191, point 3.5, when a user sends an "unblock" stanza without specifying jids to unblock, the server should unblock all contacts and reply with an empty result (no jid list). This PR fixes this.
> When unblocking all contacts response should not contain jids

- apps/ejabberd/include/jlib.hrl
- apps/ejabberd/src/jid.erl
- apps/ejabberd/src/mod_muc_admin.erl
- apps/ejabberd/src/muc_admin.erl
- rel/files/ejabberd.cfg
- test/ejabberd_tests/default.spec
- test/ejabberd_tests/tests/muc_http_api_SUITE.erl
Introduce MVP for the MUC HTTP API:
This cherry-picks the commits off of what was PR #903.
> Finalize MVP for the MUC HTTP Administration API

- apps/ejabberd/priv/mysql-part.sql
- apps/ejabberd/priv/mysql.sql
- apps/ejabberd/priv/pg.sql
- apps/ejabberd/src/mod_mam_odbc_arch.erl
Use this query under the root mysql user to check which indexes are created:
```sql
select database_name, table_name, index_name, stat_value*@@innodb_page_size
from mysql.innodb_index_stats where stat_name='size';
```
Basically,
```sql
... PRIMARY KEY (my_key) ... // create BTREE with data in leafs
CREATE INDEX another_index (my_key); // create BTREE with pointers on data in leafs
```
creates two indexes.
This second index can affect performance.
So, the pull request removes unwanted index duplicates.
> Remove mam index duplicates

- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
- test/ejabberd_tests/tests/metrics_c2s_SUITE.erl
- test/ejabberd_tests/tests/metrics_roster_SUITE.erl
- test/ejabberd_tests/tests/mod_http_notification_SUITE.erl
- test/ejabberd_tests/tests/presence_SUITE.erl
- test/ejabberd_tests/tests/private_SUITE.erl
- test/ejabberd_tests/tests/sic_SUITE.erl
Not all of them fixed. Privacy suite requires some extra refactoring.
So, far I want this first bunch of fixes to be merged, it will simplify our work with travis (less noise when test fails).
No other changes in the test, just passing Config in testcases where it's trivial to do..
> Fix escalus warnings

- apps/ejabberd/src/xml.erl
A tiny fix to broaden the return type of `xml:get_path_s` so that it includes `iodata()` (the permitted type for cdata and a superset of `binary()`) and `jlib:xmlel()` which is returned if you request an `elem`.
> Fix return type of xml:get_path_s

- apps/ejabberd/src/ejabberd_ctl.erl
This PR addresses https://github.com/esl/MongooseIM/issues/853
* add `days` to uptime statistics in `mongooseimctl status` command
Before, it was `seconds_to_time/1` fun used. What Erlang documentation says about it:
> Computes the time from the specified number of seconds. Seconds must be less than the number of seconds per day (86400).
so the call was crashing every time uptime was longer than one day because it was called with
seconds returned by `erlang:statistics(wall_clock)` [1]
[1] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_ctl.erl#L911
> make status ctl working for uptime longer than one day

- apps/ejabberd/src/ejabberd_users.erl
- apps/ejabberd/src/mod_mam.erl
- test/ejabberd_tests/tests/login_SUITE.erl
- test/ejabberd_tests/tests/mam_SUITE.erl
This PR initially addressed https://github.com/esl/MongooseIM/issues/890
but then it turned out that cassandra backend has been temporary removed so
now, it's not possible to reproduce this particular issue. 
However, I introduce the fix for that bug in case to avoid similar problems in future.
When function `ejabberd_users:is_chached_user_exists/2` was called with an unexistent domain name the crash occurred instead of returning `false` value.
> Fix for`is_cached_user_exists` function crash

- doc/open-extensions/muc_light.md
Freestanding XML elements aren't rendered properly unless the pointy brackets are substituted with XML entities (&lt;) or taken into backticks - this seriously changes the meaning of some sentences. Before this changeset we had:
No exchange of any stanza inside the room.
When `<presence/>` is taken into backticks we get:
No exchange of any <presence/> stanza inside the room.
Apart from the backticks there's some minor stuff in this PR to make the doc more cohesive.
> MUC Light doc proofreading

- mkdocs.yml
"Advanced Configuration Overview" should be under "Advanced Configuration"
> [skip ci] tree/structure review

- apps/ejabberd/include/mod_muc_light.hrl
- apps/ejabberd/src/mod_muc_light.erl
- apps/ejabberd/src/mod_muc_light_room.erl
- apps/ejabberd/src/mod_muc_light_utils.erl
- doc/developers-guide/mod_muc_light_developers_guide.md
- doc/modules/mod_muc_light.md
- test/ejabberd_tests/tests/muc_light_SUITE.erl
- test/ejabberd_tests/tests/muc_light_legacy_SUITE.erl
This PR allows to set custom room config schema in `mod_muc_light` options. In extreme case even all parameters may be replaced (i.e. default `roomname` and `subject`).
I will also make possible to set custom default values for these fields.
**TODOs:**
> Customisable MUC Light room config schemas

- apps/ejabberd/src/jlib.erl
- apps/ejabberd/src/mongoose_cassandra_worker.erl
- apps/ejabberd/test/acl_SUITE.erl
- apps/ejabberd/test/auth_tokens_SUITE.erl
- apps/ejabberd/test/jid_SUITE.erl
- apps/ejabberd/test/jlib_SUITE.erl
- apps/ejabberd/test/muc_light_SUITE.erl
This PR addresses #615 
* Deprecated functions have been removed
* Fixed a call to `jlib:make_jid` in `mongoose_cassandra_worker`
> Remove deprecated functions from jlib

- doc/http-api/backend_swagger.yml
This PR addresses #958 
1. Change name of the field `username` to `user` to work with the REST API
> [skip ci] Update name of username field in request

- apps/ejabberd/src/mod_muc_light.erl
- apps/ejabberd/src/mod_muc_light_db_mnesia.erl
- apps/ejabberd/src/mod_muc_light_room.erl
- test/ejabberd_tests/tests/muc_light_SUITE.erl
- test/ejabberd_tests/tests/muc_light_legacy_SUITE.erl
This PR addresses #955 
* Room destruction now may be triggered by user removal.
* Room removal is now working correctly when affiliation list is empty.
* New test case for user removal.
* Added a check in `leave_room` test case, whether the room gets removed.
> Fix broken MUC Light room destruction

- apps/ejabberd/src/mod_muc_room.erl
This PR addresses #964 
Convert integer to string inside decode_http_auth_response/1
> Fix error reporting by mod_muc_room using External HTTP Authentication

- apps/ejabberd/src/ejabberd_cowboy.erl
This race condition causes some of the tests to fail (REST-related primarily).
For example, it will fix some 404-code unexpected errors.
> Reload cowboy dispatch synchronously to avoid race conditions

- rel/files/mongooseimctl
- test/ejabberd_tests/tests/reload_helper.erl
Because of this some of our tests fail when we reload configuration.
Unescaped $EJABBERD_EBIN_PATH seams to have some different meaning (there shouldn't be any white-spaces, but it seams that erlang expects something escaped. Most likely error is caused by "@" character or something similar in the path).
> Fix syntax error in mongoosectl

- apps/ejabberd/include/jlib.hrl
The 'index', 'first' and 'last' fields of rsm_out are permitted to have
'undefined' as a value, per jlib:rsm_encode_[first|last].
> Fix types on #rsm_out structure

- .travis.yml
- test/ejabberd_tests/test.config
This PR merges 2 jobs on travis `interl_redis` and `mysql_mnesia` into 1 - `mysql_redis`. This reduces the total time of a build by around 30 minutes and keeps the code coverage at the same level.
> Test redis backend with mysql

- test/ejabberd_tests/rebar.config
Includes https://github.com/esl/wsecli/pull/9
Fix race conditions in wsecli library when reading stanzas from server
> Upgrade escalus for tests 2.7.0 => 2.7.1

- apps/ejabberd/src/mod_muc_light_admin.erl
- apps/ejabberd/src/mongoose_client_api_rooms.erl
- apps/ejabberd/src/mongoose_client_api_rooms_users.erl
- doc/http-api/client_swagger.yml
- elvis.config
- rel/files/ejabberd.cfg
- test/ejabberd_tests/tests/rest_client_SUITE.erl
This PR goes on top of #973 
* user's management move to path /room/:id/users
* id attribute to affiliation change messages initiated by the API
> HTTP client API - improve room users API

- rel/reltool.config.script
When release generation on clearing is called directly from `rebar`
and not via `make` the APPS env may not be exported.
This patch tries to read the file or configure the release to include
all optional libraries.
This patch is needed mainly to allow @gadgetci run compiler task.
> Extend reltool.config.script to try reading configure.out file

- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
The `num_active_users` tests case from ejabberdctl_SUITE is failing randomly very often. This PR tries to stabilise it by checking if number of active users is the same as before the change. Previously this test cases assumed that it will always be 1, which is no always true.
> Stabilise ejabberdctl_SUITE

- apps/ejabberd/include/mod_muc_light.hrl
- apps/ejabberd/src/mod_muc_light_codec_legacy.erl
- apps/ejabberd/src/mod_muc_light_codec_modern.erl
- apps/ejabberd/test/muc_light_SUITE.erl
Fixed invalid call to `filter_room_packet` hook - handlers for that hook have different arity.
The call never really makes it to handlers because it is made from muc_light, while the only handler for this hook is added by mam, but still it should be done right.
> Fix muclight hook call

- .travis.yml
- tools/travis-test.sh
This PR improves the travis-test.sh script by adding following options:
* `-p` to specify the PREST, default is `internal_mnesia`
* `-s` to specify if small tests should be run, default is `true`
* `-c` to specify is cover should be enabled on MongooseIM, default is `true`.
Example, in order to run only big tests without cover, following option can be used:
```bash
tools/travis-test.sh -p mysql_redis -s false -c false
```
> Improve travis test script

- apps/ejabberd/src/ejabberd_app.erl
- apps/ejabberd/src/ejabberd_cowboy.erl
- apps/ejabberd/src/mod_websockets.erl
- apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.default.cfg
- apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.split.cfg
- apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.with_mod_offline.cfg
- apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.with_mod_offline.different_opts.cfg
- apps/ejabberd/test/ejabberd_listener_SUITE_data/ejabberd.alt.cfg
- apps/ejabberd/test/ejabberd_listener_SUITE_data/ejabberd.basic.cfg
- doc/advanced-configuration/Listener-modules.md
- doc/modules/mod_websockets.md
- rel/files/ejabberd.cfg
- test/ejabberd_tests/rebar.config
- test/ejabberd_tests/test.config
- test/ejabberd_tests/tests/component_SUITE.erl
- test/ejabberd_tests/tests/websockets_SUITE.erl
The only supported XMPP over WebSockets is the one defined in  [RFC 7395](https://tools.ietf.org/html/rfc7395)
Also following changes has been made:
* removed unnecessary code from `mod_websockets`
* `component_SUITE` now truly uses WebSocket connection in the `xep_0114_ws` group
> Remove support for legacy WebSockets

- apps/ejabberd/src/mongoose_client_api_rooms.erl
- doc/http-api/client_swagger.yml
- test/ejabberd_tests/tests/rest_client_SUITE.erl
This PR adds name and subject to the action returning list of room to which user is subscribed.
> REST API: extend the list of my rooms by name and subject

- apps/ejabberd/src/ejabberd_cowboy.erl
- apps/ejabberd/test/cowboy_SUITE.erl
- test/ejabberd_tests/tests/bosh_SUITE.erl
- test/ejabberd_tests/tests/rest_SUITE.erl
This PR aims to stabilize randomly failing tests on travis.
* allow empty list in `rest_helper:assert_notinlist`
* wait for connection to be closed in `rest_SUITE.erl`
* try starting cowboy listener if it failed due to `{error, eaddrinuse}`
> Stabilise tests on travis

- tools/travis-test.sh
This PR addresses #1036 
* protect against unset environment variable
* ignore SIGTERM on EXIT trap, so that killing the process group does not kill bash itself
> Fix for issue #1036 - Make travis-test.sh usable from the command line

- doc/REST-API.md
- doc/user-guide/Features-and-supported-standards.md
- mkdocs.yml
* dedicate page for client's REST API
* updated `Features and supported standards` page
The relevant readthedocs page is here: http://mongooseim.readthedocs.io/en/connection-methods-and-endpoints-doc/REST-API/
> Client's REST API doc

- apps/ejabberd/src/mod_bosh_socket.erl
- test/ejabberd_tests/rebar.config
- test/ejabberd_tests/src/ct_tty_hook.erl
- test/ejabberd_tests/tests/bosh_SUITE.erl
- test/ejabberd_tests/tests/bosh_interleave_reqs.erl
* fix for wrong deferred `rid` processing when there was a response delivered to the hendler which send bigger `rid` then expected
* fix for missing `xmlns:stream` attr in `<body>` when stream features arrives in their own message
* PopEr tests for message sending/receiving over BOSH
Detailed description of the deferred rids processing.
Assume expected `rid` has value `X`
This bug happens when MongooseIM processes a request with `rid` `X+1` before `X` **and** there is a pending response to the client. In this situation Mongoose puts the request into deferred list which is expected. Also it sends the pending response to the client using this deferred connection which  results in adding the `X+1` `rid` to cached responses list (used to track retransmissions). Later …
> Hunt BOSH interleave requests issue

- test/ejabberd_tests/tests/amp_SUITE.erl
- test/ejabberd_tests/tests/login_SUITE.erl
- test/ejabberd_tests/tests/mod_ping_SUITE.erl
- test/ejabberd_tests/tests/pubsub_SUITE.erl
- test/ejabberd_tests/tests/pubsub_tools.erl
Following test SUITE were optimised
* mod_ping_SUITE
* pubsub_SUITE
* login_SUITE
* amp_SUITE
> More parallel tests

- apps/ejabberd/src/ejabberd_auth.erl
This PR doesn't address any particular issue, it'is just a cleanup - the code tries to update an 'authorize' metric which is not created before.
> a tiny fix - authorize was trying to update a non-existent metric

- test/ejabberd_tests/test.config
This PR addresses no known tracked issue.
* No functionality changes
* No new or updated tests
* No changes to the documentation
This commit aims at avoiding misleading the reader of the test config re how to target the tests at MongooseIM machine distinct from localhost.
> Delete leftover configuration item ejabberd_addr

- doc/http-api/client_swagger.yml
This PR adds tags to swagger spec. This groups methods into logical parts.
> Re-organise Swagger spec for client REST API

- doc/advanced-configuration/database-backends-configuration.md
This PR fixes documentation about initialising riak database - there were all required commands, but in the wrong order, so some of them failed.
> wrong order of riak initialisation commands in documentation

- rel/files/mongooseimctl
The issue manifested with the following crash report:
```
bin/mongooseimctl
2016-11-03 11:24:45 Can't set long node name!
Please check your configuration
2016-11-03 11:24:45 crash_report
initial_call: {net_kernel,init,['Argument__1']}
pid: <0.24.0>
registered_name: []
error_info: {exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,344}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
ancestors: [net_sup,kernel_sup,<0.12.0>]
messages: []
links: [<0.21.0>]
dictionary: [{longnames,true}]
trap_exit: true
status: running
heap_size: 1598
stack_size: 27
reductions: 1039
2016-11-03 11:24:45 supervisor_report
supervisor: {local,net_sup}
errorContext: start_error
reason: {'EXIT',nodistribution}
offender: …
```
> Fix node name generation in mongooseimctl

- README.md
- doc/README.md
Generating correct links for both github's README and readthedocs
was not possible while the main README.md was a symlink to doc/README.md
> Restore real README.md in root dir [skip ci]

- apps/ejabberd/src/mod_privacy.erl
- test/ejabberd_tests/tests/mod_blocking_SUITE.erl
- test/ejabberd_tests/tests/privacy_SUITE.erl
XEP-0016 s2.9 describes the `<message>` blocking system only in terms of
incoming messages, however the existing implementation also blocks
matching outgoing messages. This change alters the behaviour so that
only incoming messages that match `message` privacy list entries are
blocked.
The reasoning for this is twofold:
* First, it brings the behaviour in to line with that described in the XEP, and
* Second, the previous behaviour precluded any kind of privacy list based asymmetric messaging (eg a follower/followed relationship where messages can only be sent in one direction).
> Make privacy list message blocking incoming only

- apps/ejabberd/include/mod_muc_light.hrl
- apps/ejabberd/priv/mysql.sql
- apps/ejabberd/priv/pg.sql
- apps/ejabberd/src/mod_muc_light.erl
- apps/ejabberd/src/mod_muc_light_commands.erl
- apps/ejabberd/src/mod_muc_light_db.erl
- apps/ejabberd/src/mod_muc_light_db_mnesia.erl
- apps/ejabberd/src/mod_muc_light_db_odbc.erl
- apps/ejabberd/src/mod_muc_light_db_odbc_sql.erl
- apps/ejabberd/src/mod_muc_light_room.erl
- apps/ejabberd/src/mod_muc_light_utils.erl
- apps/ejabberd/src/mongoose_client_api_rooms.erl
- doc/modules/mod_muc_light.md
- test/ejabberd_tests/tests/amp_SUITE.erl
- test/ejabberd_tests/tests/mam_SUITE.erl
- test/ejabberd_tests/tests/mam_helper.erl
- test/ejabberd_tests/tests/mongoose_helper.erl
- test/ejabberd_tests/tests/muc_light_SUITE.erl
- test/ejabberd_tests/tests/muc_light_legacy_SUITE.erl
This PR adds basic ODBC backend for MUC Light.
It should be a subject of load testing, whether this backend needs optimisation, caching, stored procedures or any other improvements.
> MUC Light ODBC

- apps/ejabberd/include/mod_muc_room.hrl
- apps/ejabberd/src/mod_mam_muc.erl
- apps/ejabberd/src/mod_muc.erl
- apps/ejabberd/src/mod_muc_room.erl
- doc/modules/mod_muc.md
- test/ejabberd_tests/tests/muc_SUITE.erl
- test/ejabberd_tests/tests/muc_helper.erl
This PR introduces deep hibernation of room's process.
The optimisation works only for persistent rooms for which the process can be stopped and recreated later on demand.
Goes on top of #1086
> Stop hibernated room

- apps/ejabberd/include/mod_muc_room.hrl
- apps/ejabberd/src/mod_muc.erl
- apps/ejabberd/src/mod_muc_room.erl
- doc/modules/mod_muc.md
- test/ejabberd_tests/tests/muc_SUITE.erl
- test/ejabberd_tests/tests/muc_helper.erl
This PR hibernates the MUC process after configurable period of inactivity. This is very similar to what we already have for c2s process.
The timeout is configurable and default value is 90s.
> Hibernate MUC processes

- test/ejabberd_tests/tests/privacy_SUITE.erl
- test/ejabberd_tests/tests/privacy_helper.erl
This PR removes warnings emitted by escalus when running privacy_SUITE.
Since [this commit](https://github.com/esl/escalus/commit/93ee6eef1cce80ae7d1213c62b31cfebe301b11f) escalus prints warning whenever we try to lookup JID by atom representing user in config file.
* removed sending stanzas to recipients defined by atoms in `privacy_SUITE`
* removed setting privacy lists' targets  as atoms in `privacy_helpers` module
> Remove escalus warnings in privacy_SUITE

- .gitignore
- apps/ejabberd/src/ejabberd_app.erl
- apps/ejabberd/src/ejabberd_config.erl
- apps/ejabberd/src/gen_mod.erl
- apps/ejabberd/src/gen_mod_deps.erl
- apps/ejabberd/test/gen_mod_deps_SUITE.erl
- elvis.config
- test/ejabberd_tests/tests/mod_http_notification_SUITE.erl
This PR introduces a mechanism for inter-modular dependencies. With this PR, a module (`mod_*`) can expose a `deps/2` function:
```erlang
-spec deps(Host :: ejabberd:server(), Opts :: proplists:proplist()) ->
[{module(), proplists:proplist(), hard | soft} |
{module(), hard | soft}]. 
```
`deps/2` returns a list of dependencies of the module. The dependent module can specify parameters with which the dependee should be started (the parameters will be merged with those given by the user). The last element of the tuple specifies whether the ordering can be broken in case of cycle (in that case `soft` dependency may be started after the dependent module).
A new `gen_mod_deps` module is responsible for resolving the dependencies along with their parameters and topologically sorting the …
> Add intermodular dependency mechanism

- apps/ejabberd/src/gen_mod.erl
- apps/ejabberd/src/mod_mam.erl
- apps/ejabberd/src/mod_mam_meta.erl
- apps/ejabberd/src/mod_mam_muc.erl
- apps/ejabberd/src/mod_mam_utils.erl
- apps/ejabberd/test/mod_mam_meta_SUITE.erl
- doc/modules/mod_mam.md
- rel/files/ejabberd.cfg
Configuration is simplified by introducing a new module, mod_mam_meta, that only parses its arguments and pulls in relevant MAM modules using deps/2 callback introduced in #1103. This way a unified configuration may be introduced without disrupting existing modules and providing full backwards compatibility with old configs.
> Simplify MAM configuration

- apps/ejabberd/src/ejabberd_service.erl
- test/ejabberd_tests/rebar.config
- test/ejabberd_tests/tests/component_SUITE.erl
This PR addresses #1104
* ejabberd_service now monitors the (cowboy web)socket process and terminates itself when the monitor is triggered. This causes the route to be unregistered so the external component will be accepted without conflict when it connects again.
This is effectively equivalent to ejabberd_c2s behavior - it also uses the monitor to detect that web socket is closed.
> Fix external component disconnect over websocket

- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_c2s.hrl
- apps/ejabberd/src/mod_blocking.erl
- apps/ejabberd/src/mod_privacy.erl
- test/ejabberd_tests/tests/mod_blocking_SUITE.erl
This PR addresses an issue with blocking commands - according to XEP-0191:
"If the user attempts to send an outbound stanza to the JID, the user's server MUST NOT route the stanza to the JID"
therefore, we should block outgoing messages. Also, a block should be propagated to all user's resources, which is not explicitly required by the XEP, but suggested by common sense, plus required if we want to effectively block via REST API.
> Blocking cmds fix

- apps/ejabberd/c_src/ejabberd_zlib_drv.c
> ejabberd_zlib_drv: avoid overflow when OOM

- rebar.config
This PR addresses #888 
The ranch version pulled in by cowboy is quite outdated and does not expose a number of useful ssl parameters (dh/dhfile being one of the more critical ones). As of 1.3.0 ranch blacklists ssl_options it doesn't like (rather than whitelisting).
I've ran some tests with the upgraded ranch and everything seems to be working fine.
* add up-to-date ranch dependency to mongooseim's rebar.config
> Upgrade to ranch 1.3.0

- apps/ejabberd/c_src/ejabberd_zlib_drv.c
- apps/ejabberd/rebar.config.script
Set CFLAGS in rebar.config.script based on the emulator version as
discussed in:
https://github.com/esl/MongooseIM/pull/1134
> zlib_drv: use erts_exit() if available

- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_sm.erl
- apps/ejabberd/src/mod_carboncopy.erl
- apps/ejabberd/test/ejabberd_sm_SUITE.erl
This PR addresses #1082
When the race condition could happen? Two processes (f.e. `c2s` and process `A` ) operates on the same `user`'s session. At the same time, process `A` updates `user`'s session info and `c2s` deletes the info because the `user` disconnected. Function `ejabberd_sm:store_info` (called by `A`) first checks if there is any record for given `user` and only then updates (sets new value). It's possible that the record is deleted by `c2s` just after the get returns to `A` but set is not yet started. In this situation the info about the `user` will remain in the table, even though the `user` disconnected.
Following PR fixes this bug by running all session updates in the context of c2s process.
It was found and fixed by @arcusfelis.
> Fix race condition in ejabberd_sm

- .travis.yml
- apps/ejabberd/src/mod_mam_cassandra_arch.erl
- apps/ejabberd/src/mod_mam_cassandra_prefs.erl
- apps/ejabberd/src/mod_mam_muc_cassandra_arch.erl
- apps/ejabberd/src/mongoose_cassandra.erl
- apps/ejabberd/src/mongoose_cassandra_sup.erl
- apps/ejabberd/src/mongoose_cassandra_worker.erl
- rebar.config
- rel/files/ejabberd.cfg
- tools/configure
This PR changes Cassandra backend to use cqerl client library instead seestar.
> Use cqerl as cassandra client library

- apps/ejabberd/priv/cassandra.cql
- apps/ejabberd/src/mod_mam_cassandra_arch.erl
- apps/ejabberd/src/mod_mam_muc_cassandra_arch.erl
- rebar.config
This PR changes cassandra's client library to cqerl which is better supported by community then seestar. Also there are some changes in cassandra DB schema in order to improve query performance.
> Improve cassandra MAM backend performance

- apps/ejabberd/src/mod_muc_light.erl
- test/ejabberd_tests/tests/muc_light_SUITE.erl
This PR fixes infinite route loop triggered by muc_light.
Essentially, when someone tried to invite a user who contained domain reserved for the muclight service in his JID (by default its "muclight.HOST"), there was triggered infinite loop of function `ejabberd_router:route/3`. This was happening because muc_light processing didn't ignore error message
* test that checks if memory of c2s process is not growing when the loop is triggered by special affiliation change stanza
* fix for the issue in the `mod_muc_light`
> Muc light loop fix

- doc/open-extensions/muc_light.md
Added clarification from #997 to the docs.
Created PR with misspelled "skip ci". :( There is nothing for Travis to check here.
> [skip ci] Update MUC Light specs on legacy Blocking feature

- apps/ejabberd/src/backend_module.erl
- apps/ejabberd/src/gen_mod.erl
This PR refactors backend module creation out of gen_mod so it can be used by generic, non-mongoose-mods modules.
> Refactor start_backend_module out of gen_mod.

- apps/ejabberd/src/cyrsasl_digest.erl
- apps/ejabberd/src/ejabberd_auth_internal.erl
- apps/ejabberd/src/ejabberd_commands.erl
- apps/ejabberd/src/ejabberd_ctl.erl
- apps/ejabberd/src/ejabberd_s2s_out.erl
- apps/ejabberd/src/ejabberd_socket.erl
- apps/ejabberd/src/ejabberd_tmp_sup.erl
- apps/ejabberd/src/ejabberd_zlib.erl
- apps/ejabberd/src/eldap.erl
- apps/ejabberd/src/jlib.erl
- apps/ejabberd/src/mod_admin_extra_vcard.erl
- apps/ejabberd/src/mod_offline.erl
- apps/ejabberd/src/mod_offline_mnesia.erl
- apps/ejabberd/src/mod_private_mnesia.erl
- apps/ejabberd/src/mod_private_mysql.erl
- apps/ejabberd/src/mod_private_odbc.erl
- apps/ejabberd/src/mod_sic.erl
- apps/ejabberd/src/mod_vcard.erl
- apps/ejabberd/src/mod_vcard_ldap.erl
- apps/ejabberd/src/mod_vcard_mnesia.erl
- apps/ejabberd/src/mod_vcard_odbc.erl
- apps/ejabberd/src/p1_fsm_old.erl
- apps/ejabberd/src/rdbms/rdbms_queries.erl
- apps/ejabberd/src/scram.erl
- apps/ejabberd/src/supervisor2.erl
- apps/ejabberd/test/carboncopy_proper_tests_SUITE.erl
- apps/ejabberd/test/commands_SUITE.erl
In most files tabs were replaced with 8 spaces, but some files required
4-space replacements. Some whitespace misformats were corrected
manually. Other whitespace errors in modified files were corrected
automatically by Atom.
> Replace all tabs with spaces.

- apps/ejabberd/src/ejabberd_s2s_in.erl
- apps/ejabberd/src/ejabberd_socket.erl
During testing I have found that TLS options aren't correctly and/or always passed to `fast_tls`.
I'm not sure why nobody in the wild has already stumbled over this, because this essentially means that incoming S2S connections get the default cipher list, which is not very strong.
This now correctly handles `protocol_options` and recognizes `ciphers` in `ejabberd_s2s_in`.
I'm currently busy with other things, so I'm not sure whether I have time to add tests for this. So I've opened an issue (#1183) for this.
> Fix handling of TLS options

- apps/ejabberd/include/ejabberd.hrl
- apps/ejabberd/src/ejabberd_local.erl
- apps/ejabberd/src/ejabberd_router.erl
- apps/ejabberd/src/ejabberd_service.erl
- apps/ejabberd/src/mod_muc.erl
- apps/ejabberd/src/mod_muc_light.erl
- apps/ejabberd/src/mod_pubsub.erl
- apps/ejabberd/src/mod_vcard.erl
- apps/ejabberd/src/mongoose_api_admin.erl
- apps/ejabberd/src/mongoose_api_client.erl
- apps/ejabberd/src/mongoose_local_delivery.erl
- apps/ejabberd/src/mongoose_metrics_hooks.erl
- apps/ejabberd/src/mongoose_metrics_mam_hooks.erl
- apps/ejabberd/src/mongoose_packet_handler.erl
- apps/ejabberd/src/mongoose_riak.erl
- apps/ejabberd/src/mongoose_riak_sup.erl
- apps/ejabberd/test/component_reg_SUITE.erl
* Refactored `mongoose_*` modules, according to Elvis' suggestions
* Introduced `mongoose_packet_handler` behaviour for modules that are called during local routing
* Handler modules are responsible for creating a handle for `register_route` and `register_component`.
> Rocked mongoose_* + new behaviour: mongoose_packet_handler

- apps/ejabberd/src/http_upload/mod_http_upload.erl
- apps/ejabberd/src/jlib.erl
- apps/ejabberd/src/mod_disco.erl
- apps/ejabberd/src/mongoose_router_localdomain.erl
- doc/modules/mod_http_upload.md
- rel/files/ejabberd.cfg
- test.disabled/ejabberd_tests/tests/mod_http_upload_SUITE.erl
This PR introduces `max_file_size` configuration option for mod_http_upload, and moves the upload service to its own subhost. mod_disco has also been tweaked to allow registering subhost services.
> HTTP Upload size limits

- apps/ejabberd/include/jlib.hrl
- apps/ejabberd/src/http_upload/mod_http_upload.erl
- apps/ejabberd/src/http_upload/mod_http_upload_s3.erl
- apps/ejabberd/test/mod_http_upload_s3_SUITE.erl
- test.disabled/ejabberd_tests/tests/mod_http_upload_SUITE.erl
This PR adds support for XEP-0363 v 0.3.0 while preserving backwards compatibility with version 0.2.5 (which looks to have conforming client implementations).
> Add support for XEP-0363 (HTTP Upload) version 0.3.0.

- apps/ejabberd/src/ejabberd_c2s.erl
- test.disabled/ejabberd_tests/tests/sm_SUITE.erl
This PR addresses #843
The issue is very well described in this comment: https://github.com/esl/MongooseIM/issues/843#issuecomment-279312597
Basically if the stream resumption fails, there was session entry remaining after stopped `c2s` process. This entry would only be removed in users connects with the same resource, otherwise it may remain in the session table for ever.
* moved session item creation after checking the `h` parameter
* regression test
> Fix uncleaned resumed sessions

- apps/ejabberd/include/ejabberd.hrl
- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_hooks.erl
- apps/ejabberd/src/ejabberd_sm.erl
- apps/ejabberd/src/mod_last.erl
- apps/ejabberd/src/mod_privacy.erl
- apps/ejabberd/src/mongoose_acc.erl
- apps/ejabberd/src/mongoose_metrics_hooks.erl
This is a rewrite of a very small part of the whole processing chain - early stages of processing outgoing presence. The idea is to eventually create a mongoose_acc:t() from xmlel when a stanza enters the system, pass it along and terminate when it is about to leave. We start with a very small part, then we'll move initialisation and termination points further apart, untill they reach both ends.
Being an intermediate PR, it contains lots of utilities, comments, commented-out code which will eventually go away. Also, in `ejabberd_hooks` there are some useful things which show cool things we can do - those may stay or go, it depends.
> Accum stage one

- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_receiver.erl
- apps/ejabberd/src/ejabberd_s2s_in.erl
- apps/ejabberd/src/ejabberd_s2s_out.erl
- apps/ejabberd/src/ejabberd_socket.erl
- apps/ejabberd/src/mod_bosh_socket.erl
- apps/ejabberd/src/mod_websockets.erl
- rebar.config
- rebar.lock
- test.disabled/ejabberd_tests/rebar.config
- test.disabled/ejabberd_tests/tests/bosh_SUITE.erl
- test.disabled/ejabberd_tests/tests/connect_SUITE.erl
- test.disabled/ejabberd_tests/tests/sm_SUITE.erl
This PR introduces pipelining via updating exml to a version that can self-reset XMPP streams, allowing to parse payloads with <stream:stream> tag and XML declaration in the middle.
> Introduce XMPP pipelining.

- tools/travis-build-and-push-docker.sh
* build time values passed to `docker build` via `--build-args`
* removal of deprecated `--email` parameter to `docker login`
* frozen version of https://github.com/esl/mongooseim-docker/commit/843558fb15ddbde6c0fbb704295208449034b123
> Add labels to docker images created on travis

- tools/travis-test.sh
This PR addresses fails big tests if there is missing suite. This can happen mostly because of the following reasons:
* there is a syntax error in the SUITE
* the SUITE was added to `default.spec` but the file was not added to the repo
> Fail tests on missing suite

- test.disabled/ejabberd_tests/services/mongoose_push-compose.yml
Use new, renamed version of MongoosePush docker image - `mongoose-push`.
> Rename MongoosePush docker image to mongoose-push

- apps/ejabberd/src/mod_mam_muc_odbc_async_pool_writer.erl
- apps/ejabberd/src/mod_mam_odbc_async_pool_writer.erl
This PR adds a metric that shows how long it takes for MAM to flush messages, averaged over a message batch.
> Add per_message_flush_time metric

- tools/setup_riak
This PR allows to customize setup_riak script with environmental variables e.q.: `RIAK_HOST=custom_riak_address ./setup_riak`.
There are still default values for variables, that will be used by Travis.
> Allow customizing riak_setup script with env variables

- apps/ejabberd/src/mongoose_acc.erl
- apps/ejabberd/test/acc_SUITE.erl
This PR addresses #1218 
* improvement to mongoose_acc:read_children, so that it doesn't try to process cdata, plus stops when it finds xmlns
* test for the fix (failed in the old version)
> fix for #1218, with regression test

- apps/ejabberd/src/node_push.erl
This PR makes xform validation in `node_push` less strict. This will allow to process forms that are not valid considering [XEP-0004](https://xmpp.org/extensions/xep-0004.html) standard, but since some examples in [XEP-0357](https://xmpp.org/extensions/xep-0357.html) contain mistake when comes to xfrom `type` attribute, we may need to skip this check to be complaint with some existing clients.
> Default to 'submit' form type in node_push

- apps/ejabberd/src/gen_pubsub_node.erl
- apps/ejabberd/src/mod_pubsub.erl
- apps/ejabberd/src/node_dag.erl
- apps/ejabberd/src/node_flat.erl
- apps/ejabberd/src/node_hometree.erl
- apps/ejabberd/src/node_pep.erl
- apps/ejabberd/src/node_push.erl
This PR fixes `node_push` behaviour when used with multiple virtual hosts. This fix required passing `ServerHost` variable to `publish_item` callback. Without It, it would be possible to fetch from `ets` pubsub's host in form of 'pubsub.somehost.com', but that would require getting the host prefix from configuration in order to strip it before running callback. Therefore passing the original `ServerHost` seemed to be better idea, although it's not as pretty as I would like it to be.
> Pass ServerHost to mod_pubsub's publish_item callback

- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_sm.erl
- apps/ejabberd/src/mod_muc.erl
- apps/ejabberd/src/mod_muc_room.erl
- apps/ejabberd/src/mod_offline.erl
- apps/ejabberd/src/mongoose_client_api_sse.erl
- apps/ejabberd/src/monitored_map.erl
- apps/ejabberd/src/shaper.erl
- apps/ejabberd/test/monitored_map_SUITE.erl
- test.disabled/ejabberd_tests/test.config
- test.disabled/ejabberd_tests/tests/pubsub_SUITE.erl
- test.disabled/ejabberd_tests/tests/sm_SUITE.erl
The previous shaper implementation penalized users for sending
several small packets in burst, causing connection/reconnection
to be greatly delayed. To change this behaviour, this  commit
reimplements the shaper as a token bucket:
https://en.wikipedia.org/wiki/Token_bucket .
The PR also fixes several issues that came to light with un-delaying packets:
* Fixes/reduces severity of stanza racing to SM buffer / mod_offline when recipient "flickers" on and off
* enables mod_offline for all presets
* adds `monitored_map` module for recurring usecase of storing data bound to peer-process lifetime
* Splits test for notifying unavailable pubsub subscribers and disables the part that never really worked
* Ensures MUC room won't be routed to after its process stops
> Reimplement shaper as a token bucket.

- test.disabled/ejabberd_tests/tests/push_integration_SUITE.erl
This PR fixes random push_integration_SUITE crashes.
> Use new connection to fcm/apns mock after each communication failure

- apps/ejabberd/src/mod_mam_utils.erl
This PR modifies the MAM envelope for archive results so that each MAM wrapper has a UUIDv4 canonical form `id` attribute. This makes debugging and programming against the server XMPP interface easier, but carries a performance penalty - generating random UUIDs is potentially expensive.
> Put UUIDs in MAM archive query results

- apps/ejabberd/src/gen_mod.erl
- tools/travis-test.sh
This is a rebased version of #971
------------------
Copied description from #971:
This PR contains two features:
Allow for some log messages to trigger CI failure
Warn about links added inside start_module callback.
Bad-written modules can link to the caller process in start_module callback
It works without errors until we try to start modules in the shell or using RPC
-------------
Changes:
- Allow for some log messages to trigger CI failure
- Bad-written modules can link to the caller process in start_module callback
- It works without errors until we try to start modules in the shell or using RPC
- Use Heroku's logfmt for log message format
> Check for unsupervised links in gen_mod

- .travis.yml
- apps/ejabberd/test/ejabberd_listener_SUITE.erl
- apps/ejabberd/test/mod_aws_sns_SUITE.erl
This PR runs one preset and dialyzer jobs on travis with Erlang/OTP 19.3
Also implements missing init or end per_suite when the opposite is defined. See commit message for more details.
> Erlang 19.3

- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/test/ejabberd_c2s_SUITE.erl
- apps/ejabberd/test/ejabberd_c2s_SUITE_mocks.erl
attempt to set session, it should send an error and close the stream
This PR addresses #1252 
* when c2s is waiting for stanza which would establish session, receives it and fails to reply (for whatever reason), it is an unrecoverable stream error - it tries to send back error message and stream termination and then exit (previously it just crashed)
* two new tests in common test suite - one establishes a session on bare c2s, the other replicates the above problem and asserts c2s replied with error and stream end
> Fix for #1252 - if MongooseIM fails to send message while replying to an

- apps/ejabberd/src/jlib.erl
- apps/ejabberd/src/mod_vcard.erl
- test.disabled/ejabberd_tests/tests/vcard_SUITE.erl
This augments the vCard user directory results with [XEP-0059](http://www.xmpp.org/extensions/xep-0059.html) support.
Of course, it would be more efficient to handle this in the backend modules. For a start, it provides support regardless of specific database backends.
> mod_vcard: implement search Result Set Management support

- apps/ejabberd/src/ejabberd.app.src
- apps/ejabberd/src/ejabberd_admin.erl
- apps/ejabberd/test/ejabberd_admin_SUITE.erl
- apps/ejabberd/test/ejabberd_admin_SUITE_data/valid.csv
- apps/ejabberd/test/ejabberd_admin_SUITE_data/valid_quoted.csv
- rebar.config
This allows to register users specified in CSV file in following
format: `user,domain,password`
- Proposed change is adding new command `import_users` to mongooseimctl.
- It expects one parameter which is path to CSV file containing user accounts to register. They are expected to be formatted in following order - `user,host,password`. 
- File reading is lazy, so we are not loading whole file into memory at once.
- The `ejabberd_admin:import_users/1` function returns list of tuples `{Result, Binary}`, where `Result :: ok | exists | not_allowed | invalid_jid | null_password | bad_csv `, and `Binary :: ejabberd:user() | binary()`.
- Library `csv` is added as dependency. It is used for parsing csv files.
- describe new or updated tests
- add suite for this functionality.
> Add `import_users` command to mongooseimctl

- tools/travis-build-and-push-docker.sh
I'm going to enable weekly builds on travis. Such builds will produce docker images with tag which equals current version of MongooseIM, f.e `2.1.0beta1-665-gcb0a666`. These weekly builds will help us better monitor performance changes.
> Use MongooseIM version from git to tag builds form cron

- apps/ejabberd/src/mod_mam_muc.erl
- apps/ejabberd/src/mod_muc.erl
- apps/ejabberd/src/mod_muc_light.erl
- test.disabled/ejabberd_tests/tests/mam_helper.erl
This PR addresses #1267 
* A call to `mod_muc_room:can_access_identity` in `mod_mam_muc` has been changed to a hook call. `mod_muc` and `mod_muc_light` have been modified accordingly.
* A short (1ms) sleep has been added in MAM tests, because messages sometimes are stored out of order (because we no longer use strictly monotonic time) on fast machines.
> Fix MAM+MUC Light

- apps/ejabberd/src/mod_pubsub.erl
- test.disabled/ejabberd_tests/tests/push_pubsub_SUITE.erl
This PR addresses the following issues:
- node `push` disco info shall be visible under pubsub's sub domain, instead of the main server's domain
- `mod_pubsub` should allow for running on custom sub-domain
Please note that the second fix only allows to run pubsub on custom, non "pubsub.*" sub-domain. You can still run only one pubsub at a time. This is another issue which is much more complicated to fix, because the `mod_pubsub` internally holds its state on the main domain of the server. Therefore starting second `mod_pubsub` will always conflict with the first one.
> Fix node push discovery in mod_pubsub

- test.disabled/ejabberd_tests/tests/http_helper.erl
- test.disabled/ejabberd_tests/tests/push_pubsub_SUITE.erl
This PR fixes possible TCP port conflict in `push_pusbsub_SUITE` that sometimes crashes the test SUITE.
> Use empheral ports for http mocks in push_pubsub_SUITE

- apps/ejabberd/src/ejabberd_cowboy.erl
- apps/ejabberd/test/cowboy_SUITE.erl
- doc/advanced-configuration/Listener-modules.md
- rel/files/ejabberd.cfg
* describe the functionality changes:
Change way of providing configuration options in ejabberd.cfg file. Instead of providing only arbitrary options, we can provide all options now.
Adapted one test case to new configuration.
* docs:
Add info about cowboy endpoint cofiguration
> Allow to specify Cowboy options in configuration file

- apps/ejabberd/src/mod_mam.erl
- apps/ejabberd/src/mod_mam_meta.erl
- apps/ejabberd/src/mod_mam_utils.erl
- apps/ejabberd/test/mod_mam_meta_SUITE.erl
- doc/modules/mod_mam.md
- test.disabled/ejabberd_tests/tests/mam_SUITE.erl
- test.disabled/ejabberd_tests/tests/mam_helper.erl
- test.disabled/ejabberd_tests/tests/mongoose_helper.erl
- test.disabled/ejabberd_tests/tests/muc_light_SUITE.erl
This PR addresses #827 and #1231
* When there is incoming groupchat message to a user, `mod_mam` stores it in individual archive only when `archive_groupchats` flag is enabled
BTW: Thanks @studzien for test case!
**TODO:**
> Add archive_groupchats option to mod_mam

- apps/ejabberd/src/mod_muc_room.erl
- test.disabled/ejabberd_tests/tests/muc_SUITE.erl
Function expulse_participant updates state, but it's not what the original code expects.
This PR addresses a bug.
* Kicked user is actually kicked
* Room state is properly updated
> Properly handle incoming presence of type error by MUC room

- doc/developers-guide/mod_muc_light_developers_guide.md
- doc/modules/mod_admin_extra.md
- doc/modules/mod_http_upload.md
- doc/modules/mod_muc.md
- doc/modules/mod_muc_light.md
- doc/modules/mod_muc_log.md
- doc/modules/mod_pubsub.md
- doc/modules/mod_register.md
- doc/modules/mod_vcard.md
> [skip ci] Update some mods' docs - part 2

- apps/ejabberd/src/ejabberd.app.src
- rebar.config
- rebar.lock
[observer_cli](https://github.com/zhongwencool/observer_cli) increases our ability to perform runtime diagnostics of the system.
> Add observer_cli dependency.

- apps/ejabberd/rebar.config.script
Fix copy/paste error in rebar.config.script from commit da78e183b:
the initial config was returned instead of the modified config.
> rebar.config.script: return updated config

- apps/ejabberd/src/mod_caps.erl
- apps/ejabberd/src/mod_pubsub.erl
- test.disabled/ejabberd_tests/tests/pep_SUITE.erl
This PR addresses random `pep_SUITE` failures on Travis.
Before this change, a scenario was possible when a check for supported features in cache (when about to send PEP message) was performed before processing feature response from a client. This PR moves "PEP last item resend" trigger to a place when it's 100% certain we have the features stored in cache.
Unfortunately it may lead to duplicated notifications in federation but it's because `mod_caps` should subscribe not to `user_receive_packet` but to some hook in s2s. I think it is a separate matter to investigate (that requires new test case). It's out of scope of fixing failures on Travis.
It's difficult to reproduce with a dedicated integration test, because it would require ensuring that feature request is sent after PEP resend is …
> Fix race condition between caps and PEP

- apps/ejabberd/include/pubsub.hrl
- apps/ejabberd/src/ejabberd_sm.erl
- apps/ejabberd/src/mod_commands.erl
- apps/ejabberd/src/mod_pubsub.erl
- apps/ejabberd/src/mod_roster.erl
- apps/ejabberd/src/mod_roster_odbc.erl
- apps/ejabberd/src/mod_shared_roster_ldap.erl
- apps/ejabberd/src/mongoose_api_common.erl
- apps/ejabberd/src/mongoose_client_api_contacts.erl
- doc/http-api/backend_swagger.yml
- doc/http-api/client_swagger.yml
- rel/files/ejabberd.cfg
- test.disabled/ejabberd_tests/tests/presence_SUITE.erl
- test.disabled/ejabberd_tests/tests/rest_SUITE.erl
- test.disabled/ejabberd_tests/tests/rest_client_SUITE.erl
- test.disabled/ejabberd_tests/tests/rest_helper.erl
This PR addresses the need to have roster management in rest api.
* user commands to add/remove roster entry and send subscription request to the contact (we call it "invite", also to accept and invitation ("accept"), see caveat below
* admin commands to manage user's rosters and to set up connection between two users at one go
There is one minor issue: if a user adds a contact to his roster, but does not send subscription, and then the contact sends "subscribe" to the user, then the contact is in {none, in} state and as such, following the RFC, is not visible to the user. The user can not then accept the invitation because the roster entry is, from his point of view, nonexistent.
> Rest client api roster management

- test.disabled/ejabberd_tests/services/mongoose_push-compose.yml
The latest version was not working (most likely due to some python lib dependencies)
so we try to use older version to check if Travis jobs still fail.
> Use older image of rslota/fcm-http2-mock-server

- apps/ejabberd/include/jlib.hrl
- apps/ejabberd/src/foreign_event/mod_foreign.erl
- apps/ejabberd/src/foreign_event/mod_foreign_http.erl
- test.disabled/ejabberd_tests/tests/mod_foreign_SUITE.erl
This PR installs handler for foreign-event IQ stanzas and simple verification of requests format.
> Create foreign-event IQ handler and verify requests

- apps/ejabberd/src/mod_muc.erl
- test.disabled/ejabberd_tests/tests/mongoose_helper.erl
- test.disabled/ejabberd_tests/tests/muc_SUITE.erl
This PR addresses the error on travis:
```
====== Suite FAILED: muc_SUITE (5 of 119 tests failed)
====== Test name: pagination_empty_rset
====== Reason:    {test_case_failed,"assert_equal( \"i2b ( TotalCount )\", \"Out # rsm_out . count\") failed\n\tExpected <<\"15\">>\n\tValue <<\"16\">>\n"}
====== Test name: pagination_last5
====== Reason:    {test_case_failed,"assert_equal( \"i2b ( TotalCount )\", \"Out # rsm_out . count\") failed\n\tExpected <<\"15\">>\n\tValue <<\"16\">>\n"}
====== Test name: pagination_first5
====== Reason:    {test_case_failed,"assert_equal( \"i2b ( TotalCount )\", \"Out # rsm_out . count\") failed\n\tExpected <<\"15\">>\n\tValue <<\"16\">>\n"}
====== Test name: pagination_before10
====== Reason:    {test_case_failed,"assert_equal( \"i2b ( TotalCount )\", \"Out # …
```
> Fix muc_SUITE sometimes fails on RSM disco cases

- apps/ejabberd/src/foreign_event/mod_foreign.erl
- apps/ejabberd/src/foreign_event/mod_foreign_http.erl
- snippets.erl
There're 3 mod_foreign global metrics:
[HOST, mod_foreign, failed_requests]
[HOST, mod_foreign, successful_requests]
[HOST, mod_foreign, response_time]
There're 3 mod_foreign_http metrics:
[HOST, mod_foreign_http, failed_http_requests]
[HOST, mod_foreign_http, successful_http_requests]
[HOST, mod_foreign_http, http_request_time]
> Add Foreign-Event related metrics

- apps/ejabberd/src/ejabberd_hooks.erl
- apps/ejabberd/src/mod_adhoc.erl
- apps/ejabberd/src/mod_amp.erl
- apps/ejabberd/src/mod_aws_sns.erl
- apps/ejabberd/src/mod_roster.erl
* `ejabberd_hooks:add/1` - accepting list of hooks to add
* `ejabberd_hooks:delete/1` - accepting lit of hooks to delete
* changed some modules showing how above new functions can be used
This is basically to simplify adding/deleting hooks from modules and reducing code duplication.
> Simplify adding and deleting hooks from modules

- apps/ejabberd/src/ejabberd_s2s.erl
- apps/ejabberd/src/ejabberd_s2s_out.erl
When addresses are set in the configuration file via s2s_addr tuple,
it's a confusing behaviour to additionaly perform a DNS lookup of
the peer host and use its results alongside the preconfigured ones.
> Disable DNS lookup for S2S hosts with predefined addresses.

- test.disabled/ejabberd_tests/tests/sm_SUITE.erl
This PR lengthens session resume timeout for `sm_SUITE:preserve_order`. On Travis it could happen that the client was reconnected after the session timeout, and the test would then behave unpredictably (though correctly). With the lengthened timeout we ensure that the test tests what it wants to test.
> Lengthen session resume timeout for sm_SUITE:preserve_order test.

- Makefile
- apps/ejabberd/src/ejabberd_auth_jwt.erl
- apps/ejabberd/test/auth_jwt_SUITE.erl
- doc/Advanced-configuration.md
- rel/files/ejabberd.cfg
- tools/ssl/Makefile
This PR adds more configuration options to `ejabberd_auth_jwt` backend, enabling more token types.
Auth docs are updated to match current configuration format, although further docs refactoring is necessary (i.e. extracting auth config options to dedicated page).
> Make auth_jwt more configurable

- apps/ejabberd/include/jlib.hrl
- apps/ejabberd/src/mod_mam.erl
- apps/ejabberd/src/mod_mam_meta.erl
- apps/ejabberd/src/mod_mam_utils.erl
- doc/modules/mod_mam.md
- rebar.config
- rebar.lock
- test.disabled/ejabberd_tests/rebar.config
- test.disabled/ejabberd_tests/tests/mam_SUITE.erl
This PR addresses #1354
* archiving chat markers when `mod_mam_utils` is used as `is_archivable_message` callback when `{archive_chat_markers, true}` option is set
> Archive chat markers

- test.disabled/ejabberd_tests/tests/mam_SUITE.erl
- test.disabled/ejabberd_tests/tests/mam_helper.erl
- test.disabled/ejabberd_tests/tests/muc_light.hrl
- test.disabled/ejabberd_tests/tests/muc_light_SUITE.erl
- test.disabled/ejabberd_tests/tests/muc_light_helper.erl
- test.disabled/ejabberd_tests/tests/muc_light_http_api_SUITE.erl
- test.disabled/ejabberd_tests/tests/muc_light_legacy_SUITE.erl
- test.disabled/ejabberd_tests/tests/push_SUITE.erl
- test.disabled/ejabberd_tests/tests/push_integration_SUITE.erl
This PR introduces `muc_light_helper` for test. This makes reusing existing parts related to MUC light tests easier.
> Tests muc light helper

- apps/ejabberd/c_src/mongoose_mam_id.cpp
- apps/ejabberd/rebar.config
- apps/ejabberd/src/mod_mam_utils.erl
- apps/ejabberd/src/mongoose_mam_id.erl
The difference is that the underlying implementation ensuring
unique microsecond timestamps is now based on atomic operations,
optimized for speed and should not be any kind of bottleneck.
> Go back to old now()-like behaviour for generating MAM ids.

- apps/ejabberd/src/mongoose_client_api.erl
`ejabberd_auth:check_password/3` crashes when one of the auth modules' `check_password/3` also crashes. `authorize/1` is safer to use, since it catches the errors.
> Use `ejabberd_auth:authorize/1` when authorizing API user

- apps/ejabberd/src/mod_mam_riak_timed_arch_yz.erl
Problem with saving unicode message to riakkv mam with exception badarg in list_to_binary function
> fixed packet_to_search_body for unicode strings

- apps/ejabberd/src/mongoose_client_api_rooms.erl
- apps/ejabberd/src/mongoose_client_api_rooms_users.erl
- doc/http-api/client_swagger.yml
- test.disabled/ejabberd_tests/tests/rest_client_SUITE.erl
This PR allows creating rooms with specific JID via API.
Before, we could only do:
`PUT /api/rooms/some_id`
and after this PR:
`PUT /api/rooms/some_id@muclight.localhost`
> Allow creating rooms with specific JID via API

- doc/user-guide/How-to-build.md
- doc/user-guide/ICE_tutorial.md
- doc/user-guide/Push-notifications.md
- mkdocs.yml
> [skip ci] rename "howto" articles

- test.disabled/ejabberd_tests/tests/rest_client_SUITE.erl
This PR increases timeouts in `rest_client_SUITE`. In some places `escalus:wait_for_stanza/2` had timout set to 1 ms, which made the suite fail often.
> Increase escalus timeouts in rest_client_SUITE

- apps/ejabberd/src/http_upload/mod_http_upload_s3.erl
- apps/ejabberd/test/mod_http_upload_s3_SUITE.erl
- doc/modules/mod_http_upload.md
Setting {add_acl, false} disables adding x-amz-acl to presigned PUT urls,
making the backend compatible with some alternative S3 implementations
(e.g. Minio).
To properly support non-AWS S3, the host header value also needed to support
non-standard ports.
> Add add_acl option for mod_http_upload S3 backend.

- apps/ejabberd/src/ejabberd_router.erl
- apps/ejabberd/src/ejabberd_service.erl
- apps/ejabberd/src/mod_muc.erl
Takes Error element instead of packet and adds it to the original packet
> add ejabberd_router:route_error_reply/4

- apps/ejabberd/src/mongoose_acc.erl
Rationale: modules should use `to_send` to inspect the packet that
will be sent. There are cases of logic paths in the system, though, that
do not set `element`, so with no `to_send` field a simple get/2 is not
sufficient and a default is needed.
> Add special mongoose_acc case for getting to_send with default.

- apps/ejabberd/include/ejabberd.hrl
Use new product page instead of the old one which unavailable.
> Update MongooseIM URI

- tools/install
With /bin/sh, the following comparison is unsupported:
[ x"$SYSTEM" == x"yes" ]
Tested on Debian and Ubuntu
> Fix shebang of tools/install

- apps/ejabberd/src/cyrsasl.erl
- test.disabled/ejabberd_tests/tests/oauth_SUITE.erl
This PR addresses #1312 
* The cyrsasl.erl module has been updated to filter out X-OAUTH sasl mechanism if the mod_auth_token.erl module is not loaded.
* The xouath_SUITE.erl test suite has been updated with a new test case.
> [#17184]: Advertise X-OAUTH as a sasl mechanism only if mod_auth_token module is loaded.

- tools/travis-test.sh
There is no need to stop MongooseIM and other services after the test on travis. It shortens every job for about 1-2 minutes.
> do not stop MongooseIM nodes and other services after test

- apps/ejabberd/src/mod_mam_meta.erl
- apps/ejabberd/test/cowboy_SUITE_data/ejabberd.onlyhttp.cfg
- apps/ejabberd/test/cowboy_SUITE_data/ejabberd.onlyws.cfg
- apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.default.cfg
- apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.split.cfg
- apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.with_mod_offline.cfg
- apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.with_mod_offline.different_opts.cfg
- apps/ejabberd/test/mod_mam_meta_SUITE.erl
- apps/ejabberd/test/revproxy_SUITE_data/ejabberd.norules.cfg
- apps/ejabberd/test/revproxy_SUITE_data/ejabberd.onerule.cfg
- doc/modules/mod_mam.md
- doc/user-guide/ICE_tutorial/ejabberd.cfg
- rel/files/ejabberd.cfg
- rel/files/ejabberd.cfg.token-support
The main change of this PR is a removal of `mnesia_dirty` prefs store from documentation **and** `mod_mam_meta` module. I've also fixed the link to MAM XEP (it points to 0.6 though) and took a chance to improve rendering of bullet points (4 spaces make a nested bullet point! 👍 )
> MAM documentation fixes

- doc/http-api/backend_swagger.yml
This PR fixes a couple of backend API documentation format issues. The docs should now render properly.
Closes #1411
> Fix format of backend API Swagger docs

- apps/ejabberd/src/mod_muc_light.erl
- apps/ejabberd/src/mod_muc_light_commands.erl
- apps/ejabberd/src/mongoose_commands.erl
- doc/http-api/backend_swagger.yml
- test.disabled/ejabberd_tests/tests/muc_light_http_api_SUITE.erl
This PR addresses the feature to delete a MUC room via REST API.
* The module ```mod_muc_light_commands.erl``` and ```mod_muc_light.erl``` have been updated with a function to delete a MUC light room.
* New tests have been added to the ```muc_light_http_api_SUITE.erl```
> [#17558]: Implement the REST API to delete a MUC Light room.

- README.md
- doc/README.md
Buildtime trend was not an available service anymore, the badge was broken.
> [skip ci] Buildtime trend removal

- doc/operation-and-maintenance/Cluster-configuration-and-node-management.md
From MongooseIM 2.0.0 there were quite significant changes to clustering.
I removed doc for older version in order to make it more understandable, doc for older version is still here in git repo and in readthedocs.io when a prev version is chosen.
> Update doc regarding clustering and node management [skip ci]

- apps/ejabberd/include/mongoose_api.hrl
- apps/ejabberd/src/mongoose_api_admin.erl
- apps/ejabberd/src/mongoose_api_common.erl
- apps/ejabberd/src/mongoose_client_api.erl
- apps/ejabberd/src/mongoose_client_api_contacts.erl
- doc/advanced-configuration/Listener-modules.md
- test.disabled/ejabberd_tests/tests/ejabberd_node_utils.erl
- test.disabled/ejabberd_tests/tests/muc_http_api_SUITE.erl
- test.disabled/ejabberd_tests/tests/muc_light_http_api_SUITE.erl
- test.disabled/ejabberd_tests/tests/rest_SUITE.erl
- test.disabled/ejabberd_tests/tests/rest_client_SUITE.erl
- test.disabled/ejabberd_tests/tests/rest_helper.erl
This PR addresses introduces admin http api authorization. 
Changes include:
* Implementing cowboy callback `is_authorized` for mongoose_api_admin
* Extracting common part for client and admin authorization
* Implementing tests for newly implemented feature
* refactoring rest_helper so that it is more general and can be helpful for new tests
> Admin http auth

- apps/ejabberd/src/mod_mam.erl
- apps/ejabberd/src/mod_mam_meta.erl
- apps/ejabberd/src/mod_mam_muc.erl
- apps/ejabberd/src/mod_mam_utils.erl
- doc/modules/mod_mam.md
- rel/files/ejabberd.cfg
- test.disabled/ejabberd_tests/tests/mam_SUITE.erl
This PR makes archive id elements introduced in XEP 0313 (<stanza-id/> v0.6 and <archived/> v0.2) configurable which means they can be enabled or disabled with the ejabberd.cfg file.
* archived - disabled by default (and warning if someone enables it with suggestion to use stanza-id)
* stanza-id - enabled by default
> Configurable archiveid element

- doc/advanced-configuration/Listener-modules.md
- doc/authentication-backends/HTTP-authentication-module.md
- doc/modules/mod_aws_sns.md
This PR attempts to unify the way docs inform about a config option being optional. It's removing the `optional` label when the default values are given. Now each config option entry should be considered optional if it has some `default` value **or** `optional` label (in which case it probably means that something is not activated at all).
The motivation for this PR was a bit of a mess when it comes to marking optional or required options. Sometimes `optional` with `default` was given, sometimes only `default` etc.
> Remove redundancy as default already means optional

- doc/README.md
The TTD graph of Tide was only on /README.md
> [skip ci] replicate Tide graph

- apps/ejabberd/src/ejabberd_sm.erl
- test.disabled/ejabberd_tests/default.spec
- test.disabled/ejabberd_tests/tests/acc_e2e_SUITE.erl
- test.disabled/ejabberd_tests/tests/acc_e2e_SUITE_data/acc_test_helper.erl
The `Packet` has to be passed to mongoose_acc:strip in this case.
Otherwise the recipient will get the original stanza from Acc which
may not be correct.
Simple case to reproduce:
1. `User A` sends and IQ to MongooseIM
2. This IQ results in a `message` stanza to `User B` (bare jid)
3. Withtout this change `User B` recieves the IQ sent by `User A`
> Fix routing messages to bare jids

- doc/user-guide/Get-to-know-MongooseIM.md
> introduce Tide

- apps/ejabberd/src/ejabberd_c2s.hrl
Can be confusing, but it's not just IP, but IP and remote TCP port.
> Fix spec for state.ip in ejabberd.hrl

- apps/ejabberd/src/cyrsasl_digest.erl
- apps/ejabberd/src/cyrsasl_scram.erl
- apps/ejabberd/src/ejabberd_auth.erl
- apps/ejabberd/src/ejabberd_auth_http.erl
- apps/ejabberd/src/ejabberd_auth_odbc.erl
- apps/ejabberd/src/ejabberd_auth_riak.erl
- apps/ejabberd/src/ejabberd_gen_auth.erl
The name `passwordlike` smells. As it can't be `password` because it is either binary (word) OR TUPLE of type scram:scram_tuple() we will call it `passTERM`. 
It plays a role of passWORD but instead of being a **WORD** it is a **WORD or TUPLE**. The smallest denominator then is **TERM**. This way we also let somebody extend it for any type of pass phrase he/she needs.
> Change passwordlike to passterm

- apps/ejabberd/src/ejabberd_s2s_in.erl
- apps/ejabberd/src/ejabberd_s2s_out.erl
This PR improves s2s modules code style in order to make the modules pass Elvis checks.
Changes that was made:
* decrease nesting level in some functions
* remove if expressions
* improve spec
* remove macros from function calls
* cosmetic changes (too long lines, indentation)
> Make s2s files pass elivs checks

- apps/ejabberd/src/mod_mam_odbc_arch.erl
> Delete archive_message hook on module stop instead of adding again

- src/jlib.erl
This PR removes unsed functions from `jlib` module.
> remove unused functions from jlib

- c_src/mongoose_mam_id.cpp
This PR fixes mongoose_mam_id.cpp build on 32 bit platforms.
> Use ErlNifUInt64 for retrieving 64bit value from NIF's args.

- src/mod_vcard_mnesia.erl
- src/mod_vcard_odbc.erl
- src/mod_vcard_riak.erl
- test.disabled/ejabberd_tests/tests/vcard_SUITE.erl
- test.disabled/ejabberd_tests/tests/vcard_simple_SUITE.erl
I found that we return code 503 when a vcard has not been found after clients' iq get request. According to xep it should return either empty vcard or a 404 (item-not-found) error code.
> Return 404 when vcard not found

- doc/developers-guide/Moving-to-single-app-project-structure.md
- src/ejabberd_admin.erl
- src/ejabberd_config.erl
- src/ejabberd_ctl.erl
- src/gen_mod.erl
As in title,  I've removed some leftovers after unumbrellafication.
> Fix remaining code which assumed existence of ejabberd app

- src/ejabberd_auth.erl
- src/ejabberd_auth_external.erl
- src/ejabberd_auth_http.erl
- src/ejabberd_auth_jwt.erl
- src/scram.erl
> Ejabberd auth

- src/mod_websockets.erl
This PR addresses #1602
* change `mod_websockets:close/1` to send `stop` message as this is what `mod_websockets:websocket_info` expects to get
> Fix mod_websockets:close/1

- src/ejabberd_c2s.erl
- test.disabled/ejabberd_tests/tests/mod_blocking_SUITE.erl
- test.disabled/ejabberd_tests/tests/privacy_SUITE.erl
- test.disabled/ejabberd_tests/tests/privacy_helper.erl
This PR addresses crash of ejabberd_c2s process when receiving iq with blocking or privacy namespace
Check if IQ is of record iq, if not return old state
> C2S crash fix

- rebar.config
- rebar.lock
This PR upgrades fast_tls to a version that eschews -flat_namespace linking flag that - on macOS High Sierra - caused wrong TLS library to be found during runtime, which resulted in segmentation faults.
There are quite a few changes between the version we used and the version this PR upgrades to, probably the most important being [a switch from port to NIF implementation](https://github.com/processone/fast_tls/commit/17bfcb769cb6573c53497e01957fffccd384cf6a), so we should look closely at load test results.
> Upgrade fast_tls to a version using two-level namespace on macOS.

- doc/modules/mod_mam.md
- src/mam_iq.erl
- src/mod_mam.erl
- src/mod_mam_meta.erl
- src/mod_mam_muc.erl
- src/mod_mam_utils.erl
* unify message forwarding for different MAM versions
* move `pm` and `muc` duplicated helper function to `mam_iq`
* add possibility to configure a callback module which can add extra lookup params based on custom form fields
> MAM refactoring - part 2

- src/mod_vcard_ldap.erl
- test.disabled/ejabberd_tests/tests/vcard_simple_SUITE.erl
fix for ldap_vcard_map option format, making it aligned with [description at documentation](http://mongooseim.readthedocs.io/en/latest/modules/mod_vcard/)
> fix for mod_vcard_ldap:parse_option/2 function

- src/event_pusher/mod_event_pusher_http.erl
Remove usage of constant to get callback module for http notifications
Some investigations were made and tests were run to figure out in which context the callback module is needed. My conclusion so far is to use the To-server due to the following.
Attribute: `From`
Description: The Jabber ID of the entity that originally sent the XML stanza or that **delayed the delivery of the stanza**
The "from" attribute in the delay element is the same as the receiving user's host:
```
{xmlel,<<"message">>,
[{<<"from">>,<<"bOb@localhost">>},
{<<"to">>,<<"alicE@localhost.bis">>},
{<<"xml:lang">>,<<"en">>},
{<<"type">>,<<"chat">>}],
[{xmlel,<<"body">>,[],[{xmlcdata,<<"Hi, Alice!">>}]},
{xmlel,<<"delay">>,
[{<<"xmlns">>,<<"urn:xmpp:delay">>},
{<<"from">>,<<"localhost.bis">>}, …
```
> Change ?MYHOST to To#jid.lserver

- src/global_distrib/mod_global_distrib_receiver.erl
- test.disabled/ejabberd_tests/default.spec
- test.disabled/ejabberd_tests/tests/mod_global_distrib_SUITE.erl
This PR fixes timing issues of global distrib tests on very slow machines (i.e. Travis).
> Fix global distribution tests for Travis

- .gitattributes
This PR addresses ugly output of "git grep function" and similar commands.
Minified files are usually one-liner, that matches almost every search request.
This PR would replace output with:
```
git grep function | grep js                                                    
Binary file doc/open-extensions/prettify.js matches                                                                               
Binary file doc/swagger/lib/backbone-min.js matches                                                                               
Binary file doc/swagger/lib/es5-shim.js matches                                                                                   
Binary file doc/swagger/lib/handlebars-2.0.0.js matches …
```
> Treat minified javascript as binary

- doc/advanced-configuration/database-backends-configuration.md
- priv/mysql.sql
This PR updates recommended configuration options for MySQL backend.
Default for both variables is `on`.
Default is **on**
Accepts `on/true` and `off/false`.
Default is **on**
Accepts `on/off` and `true/false`
Default is **off**,
Accepts `on/true` and `off/false`
for v. <= 5.6.5, default is **off**
and v. >= 5.6.6, it is **on**
Accepts `on/true` and `off/false`
> Update recommended config values

- test.disabled/ejabberd_tests/tests/sm_SUITE.erl
This PR is first part of #1638.
It should "fix" CI.
The real fix would be a separate PR.
> Disable resend_unacked_on_reconnection

- test.disabled/ejabberd_tests/tests/cluster_commands_SUITE.erl
- test.disabled/ejabberd_tests/tests/component_SUITE.erl
This PR disables test cases that stop MIM node completely, effectively breaking (stopping) cover.
These should be fixed later.
> Disable tests that break cover

- test.disabled/ejabberd_tests/rebar.config
New version of escalus should display stanza log XML file using XML viewer.
Viewer example:
http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1663/3971/pgsql_mnesia.20.0/big/ct_run.test@travis-job-791bd2f0-1981-4f7a-8184-24247fc02da4.2018-01-17_17.02.39/ejabberd_tests.tests.offline_SUITE.logs/run.2018-01-17_17.15.54/log_private/error_message_is_not_stored.xml
> Update escalus to use xmlview

- test.disabled/ejabberd_tests/tests/mongoose_helper.erl
- test.disabled/ejabberd_tests/tests/offline_SUITE.erl
Fixes 
This PR addresses #1667 #1672  #1664
* Fix for failing offline tests
* New helper function mongoose_helper:logout_user/2
> Ensure that user actually logouts in offline_SUITE tests

- tools/travis-test.sh
Print `epmd -names` if any test fails.
This PR helps to check, if node crashed during test execution.
It does not check, that ejabberd application crashed, which can be checked by grepping ejabberd.log (a separate PR, maybe).
> Print running nodes if test fails

- test.disabled/ejabberd_tests/rebar.config
New code copies XSL file to ct_reports.
It should fix XML stanza reports in Chrome.
This PR addresses https://github.com/esl/escalus/pull/165
Example, should work in chrome
http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1687/4023/pgsql_mnesia.20.0/big/ct_run.test@travis-job-a932f466-a9c7-4eca-80fb-70f5d2844923.2018-01-24_13.46.14/ejabberd_tests.tests.push_integration_SUITE.logs/run.2018-01-24_14.00.06/log_private/muclight_msg_notify_on_fcm_w_click_action.xml
> Use escalus with copy-xml-pretty-viewer fix

- src/ejabberd_receiver.erl
This PR addresses #1614
Use cumulative chunk size when reporting the size of received stanzas. Chunk size "accumulates" until exml parses out a full stanza.
This is still imperfect since a single chunk can potentially contain more than one stanza but it's a much more useful approximation than never reporting anything above MTU size.
> Fix up received stanza size metric

- src/gen_mod.erl
- src/mod_mam.erl
- src/mod_mam_muc.erl
- src/mod_mam_params.erl
- src/mod_mam_utils.erl
- test.disabled/ejabberd_tests/tests/mam_SUITE.erl
This PR removes dynamically compiled `mod_mam_prefs` and `mod_mam_muc_prefs` modules in favor of fetching module options with ETS via `gen_mod:get_module_opts()` and then searching for the right option with `lists:keyfind`.
> Use gen_mod opts in MAM

- test.disabled/ejabberd_tests/tests/muc_SUITE.erl
muc_SUITE kicked_after_sending_malformed_presence does not terminate room until test is done.
This PR addresses redmine 17047
I'm disabling this test case on master to reduce the pain with Travis builds. It has to be verified and fixed.
```
====== Suite FAILED: muc_SUITE (1 of 119 tests failed)
====== Test name: kicked_after_sending_malformed_presence
====== Reason:    {timeout_when_waiting_for_stanza,
[{escalus_client,wait_for_stanza,
[{client,<<"kate87.108954@localhost/res1">>,
escalus_tcp,#Port<0.40135>,false,false,
<0.20540.0>,
[{event_manager,<0.20285.0>},
{server,<<"localhost">>},
{username,<<"kate87.108954">>},
{resource,<<"res1">>}]},
1000],
[{file,"src/escalus_client.erl"},{line,121}]},
{muc_SUITE,
'-kicked_after_sending_malformed_presence/1-fun-0-',
3, …
```
> muc_SUITE kicked_after_sending_malformed_presence test 

- doc/user-guide/Features-and-supported-standards.md
Fixes minor spelling mistakte in User-Guide/Features-and-supported-standards.md
Happy FOSDEM - great to see you're there! :-)
> Fix spelling mistake in User Guide

- .travis.yml
Tide is served over encrypted connection now. If Travis pushes notification to non-encrypted endpoint it gets HTTP 301.
> Fix Tide webhook address

- src/global_distrib/mod_global_distrib.erl
- src/global_distrib/mod_global_distrib_bounce.erl
This PR fixes #1683 and obsoletes #1684
The race condition was provoked by `test_in_order_messages_on_multiple_connections_with_bounce` test case. It manifested under following conditions:
1. Due to lack of recipient mapping, e.g. 4 messages were stored in bounce storage
2. Mapping appeared
3. 5th message got sent and it triggered `known_recipient` hook, which in turn triggered retransmission of stored items
4. For every retransmitted item, full routing logic is executed, so each time the recipient mapping is retrieved
5. Test process may remove (as a part of test case) recipient mapping in the middle of retransmission, so only some of the items reach recipient.
6. Code returns from hook execution to a point, where the mapping is already retrieved and the message 5 gets delivered anyway …
> Fix race condition in Global Distribution packet retransmission

- src/mod_ping.erl
In some cases it can happen that a jid without resource ends up in mod_ping's internal 'database'.
In our case it was that a custom module injected messages manually into the system for users without a resource and manually ran the user_send_packet hook. 
The result is an endless loop of iq-error replies bringing the whole system to a halt within a short time (system replying a 'bad-request' error to an iq-error and so on). 
The proposed fix just makes sure we never try to ping a user without a resource.
> make sure we don't ping user w/o resource

- src/event_pusher/mod_event_pusher_push.erl
This PR addresses #1722
It adds a hard check for `body` subelement in message processed by `mod_event_pusher_push`. It overrides `should_publish` result, as this element is mandatory in constructed payload.
> Don't try to push message without body

- test.disabled/ejabberd_tests/tests/push_SUITE.erl
- test.disabled/ejabberd_tests/tests/push_integration_SUITE.erl
- test.disabled/ejabberd_tests/tests/push_pubsub_SUITE.erl
is_result is deprecated
This PR addresses 
```erlang
=INFO REPORT==== 8-Feb-2018::17:19:04 ===
calling deprecated function is_result, use is_iq_result instead
[{escalus_new_assert,assert,2,[{file,"src/escalus_new_assert.erl"},{line,31}]},
{push_SUITE,'-muclight_no_msg_notifications_if_user_online/1-fun-1-',4,
[{file,"push_SUITE.erl"},{line,477}]},
{escalus_story,story,4,[{file,"src/escalus_story.erl"},{line,72}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1529}]},
{test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1045}]},
{test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,977}]}]
```
in CI tests
> Replace is_result with is_iq_result

- rel/files/erl
- rel/files/mongooseim
- rel/files/mongooseimctl
- rel/files/nodetool
- tools/configure
This PR addresses #1620
* the bulk of the changes is just quoting bash variables correctly
* the only "interesting" change is to the `nodetool`, which is changed to call `epmd` through `open_port` directly since `os:cmd` tries to parse its parameter and, naturally, fails on spaces too.
This seems to be fully operational with OTP 20. Unfortunately, `nodetool` invocations are still broken on prior releases; this is due to escript itself breaking when invoked from a directory with spaces - I'm not sure how much can be done about that...
> Allow spaces in install dir name

- test.disabled/ejabberd_tests/tests/vcard_SUITE.erl
This PR addresses "don't keep all eggs in one basket".
Eradicate relative paths for good! (part 1 or 2 of more than 2 PRs).
> Remove jlib including from inside big tests

- src/mod_vcard.erl
This PR addresses very obscure error reports when something bad happens in mod_vcard code.
Example of before report:
http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1697/4089/riak_mnesia.18.3/big/ct_run.test@travis-job-31e90c86-1d4e-42f8-bbd1-a60c5f954d67.2018-02-08_19.17.42/mongooseim@localhost.log.html#L313
> Print more debug information when an error is caught in mod_vcard

- doc/user-guide/Features-and-supported-standards.md
The link to compliance suite was correct, but the number was not changed. Also, XEP-0387 does not require MIX.
> [skip ci] Fixed compliance xep number, removed caveat

- Makefile
- doc/developers-guide/Testing-MongooseIM.md
- doc/user-guide/How-to-build.md
- rebar.config
- rel/reg1.vars.config
- test.disabled/ejabberd_tests/test.config
- test.disabled/ejabberd_tests/tests/mod_global_distrib_SUITE.erl
- test.disabled/ejabberd_tests/tests/s2s_SUITE.erl
- tools/travis-common-vars.sh
Separate s2s and global distribution test nodes.
Global distribution tests should use new node reg1 (region 1)
localhost should not be loaded on fed1, because it would make
any additional s2s tests hard to implement.
An example of such test is muc and s2s combination.
Remove debug printing to console from mod_global_distrib_SUITE.
Use generic rpc function provided by escalus from mod_global_distrib_SUITE.
Update docs.
This PR addresses "I can't merge #1311" without this patch.
> Dedicate fed1 node for s2s tests

- rebar.config
This brings the number of Dialyzer warnings at commit 80b56ec from 8 to 0.
Without this change the Dialyzer output is:
```
16:51:22 erszcz @ x4 : ~/work/esl/mongooseim (master)
$ r3 dialyzer
===> Verifying dependencies...
===> Skipping goldrush (from {pkg,<<"goldrush">>,<<"0.1.7">>,
<<"349A351D17C71C2FDAA18A6C2697562ABE136FEC945F147B381F0CF313160228">>}) as an app of the same name has already been fetched
===> Compiling mongooseim
===> Generating ASN.1 files.
===> Generating ASN.1 files.
===> Dialyzer starting, this may take a while...
===> Updating plt...
===> Resolving files...
===> Updating base plt...
===> Resolving files...
===> Removing 1 files from "/Users/erszcz/.cache/rebar3/rebar3_19.2_plt"...
===> Checking 163 files in "/Users/erszcz/.cache/rebar3/rebar3_19.2_plt"...
===> …
```
> Add some deps to plt_extra_apps to get 0 Dialyzer warnings

- .gitignore
- .travis.yml
- README.md
- test.disabled/ejabberd_tests/run_common_test.erl
Example: https://codecov.io/gh/esl/MongooseIM/tree/651a44752aa95cb390c4e277a3119c9463905292/src
Import coverdata into codecov.json.
Use module_info to find source files location.
It increases travis job time by ~ 15 seconds.
- pip install - 5 seconds
- codecov - 5 seconds
- codecov.json generation - 2 seconds
Admin stuff
----
The PR can be merged without "admin stuff" tasks.
Apparently, the only thing is missing without granting access is a check in "All checks have passed" from codecov.
To enable codecov bot, add esl/MongooseIM to https://codecov.io/ (10 minutes for someone who have admin access for esl github account).
- first auth codecov using github oauth. It does not give codecov code access, but they can comment to PRs.
- than enable codecov for a specific repo on codecov site. …
> Add codecov integration

- src/global_distrib/mod_global_distrib_outgoing_conns_sup.erl
- src/global_distrib/mod_global_distrib_server_mgr.erl
- src/global_distrib/mod_global_distrib_server_sup.erl
This PR addresses an issue observed in load tests, where sometimes a call to `get_connection` crashed with `noproc` exception (that applies to connection manager process).
It may happen if a process starts outgoing connections supervisor and second one tries to access the pool in a state, when supervisor is already running but manager (child of the supervisor) is not (yet).
Also please check the comments in the code.
Load tests confirm that this branch fixes the issue.
> Fix a race condition in a call to GD conn manager

- .travis.yml
Pass PRESET variable to codecov to distinguish builds on a build tab
Also disable gcov
[Before](https://codecov.io/gh/esl/MongooseIM/commit/fc9abfe5bb79e55c6c0151142061829bf57e572c/build)
[After](https://codecov.io/gh/esl/MongooseIM/commit/5def43b1c8e0683fc95a93be0623400c2edf6b0f/build)
> Pass PRESET variable to codecov to distinguish builds

- src/global_distrib/mod_global_distrib_mapping_redis.erl
- src/global_distrib/mod_global_distrib_server_mgr.erl
- src/global_distrib/mod_global_distrib_utils.erl
- src/mongoose_metrics.erl
This pull request:
* Changes level of some less important logs to `debug`.
* Fixes the check for existing metric.
* Adds 2 new logs: with resolved endpoints diff (info) and full resolved endpoints list (debug).
* Renames Redis refresher logs, so their content can't be confused with server manager refresh logs.
> Change Global Distribution loglevels + some new logs

- rel/reg1.vars.config
- src/global_distrib/mod_global_distrib.erl
- src/global_distrib/mod_global_distrib_bounce.erl
- src/global_distrib/mod_global_distrib_utils.erl
- src/mongoose_acc.erl
- test.disabled/ejabberd_tests/tests/component_SUITE.erl
- test.disabled/ejabberd_tests/tests/mod_global_distrib_SUITE.erl
* `mod_global_distrib:get_metadata/2,3` now may return `{error, missing_gd_structure}` error.
* Fixed ETS creation in `mod_global_distrib_utils` - `{heir, none, testing}` parameter is illegal.
* `maybe_update_mapping/2` won't crash now if `global_distrib` structure is missing in acc.
* New integration test is a byproduct of attempts to reproduce the issue; since it covers a new scenario, I haven't removed it.
* Fixed `component_SUITE:connect_component/2` as it was returning invalid component address.
> Make packet_to_component GD handler more robust

- src/mod_mam_muc_odbc_arch.erl
- src/mod_mam_odbc_arch.erl
- src/mod_mam_riak_timed_arch_yz.erl
- src/mod_mam_utils.erl
- src/rdbms/mongoose_rdbms_odbc.erl
- src/rdbms/mongoose_rdbms_pgsql.erl
- test.disabled/ejabberd_tests/tests/mam_SUITE.erl
This PR allows storing and retrieving unicode messages in MAM. It changes a few places to properly handle unicode, as well as sidesteps escaping needed for some databases by using prepared queries also in synchronous writes (previously only in asynchronous)
> Fix saving unicode MAM messages.

- test/auth_jwt_SUITE.erl
- test/component_reg_SUITE.erl
- test/small_path_helper.erl
Use PWD variable in small_path_helper module
Simplify include statements
> Eradicate relative paths for small tests

- test/mod_global_distrib_SUITE.erl
I forgot to add this suite to PR #1763 :(
> Add missing GD small suite

- .travis.yml
- doc/modules/mod_muc.md
- include/mod_muc.hrl
- src/jlib.erl
- src/mod_muc.erl
- src/mod_muc_db.erl
- src/mod_muc_db_mnesia.erl
- src/mod_muc_room.erl
- test.disabled/ejabberd_tests/tests/muc_SUITE.erl
- test.disabled/ejabberd_tests/tests/muc_helper.erl
- test.disabled/ejabberd_tests/tests/s2s_SUITE.erl
- test.disabled/ejabberd_tests/tests/s2s_helper.erl
It's a **subset** of https://github.com/esl/MongooseIM/pull/1311
Includes mnesia backend
Includes common backend code
Includes registration tests
We want to add odbc backend as a separate PR.
Because we first need to discuss schema.
Maybe we would have two RDBMS backends, one normalized, one denormalized and compare performance.
Add load_permanent_rooms_at_startup option
New result format for some mod_muc functions
Document mod_muc.backend option
Remove mnesia migrations from mod_muc
Replace catch with try..catch
Simplify mod_muc Mnesia code
Subtruct unset_nick from set_nick function
Do not allow to use a nick if DB returns an error
Add MUC registration tests
Test registration over S2S
Move generic s2s code into s2s_helper
Use s2s_helper in muc_SUITE
Disable fed1 cover for MUC-over-S2S …
> Separated database logic from mod_muc into backend modules

- doc/user-guide/Getting-started.md
- rel/files/mongooseim
- rel/files/mongooseimctl
In rebar the 'foreground' mode is usually used when the erlang app is
running as a daemon within a supervising service such as systemd or
upstart. To work correctly within those services some flags for 'erl'
are necessary so that for example unix pipelines can be used. This
patch introduces the 'foreground' mode as known from rebar which is
very similar to live/console but sets the following additional flags:
-noshell -noinput +Bd
Those are documented at:
http://erlang.org/doc/man/erl.html
The very same flags are also used in relx and distillery:
https://github.com/bitwalker/distillery/blob/master/priv/libexec/commands/foreground.sh#L18
https://github.com/erlware/relx/blob/86d415f33c500d432d6c9fa2fcbff3bb2fff3e8f/priv/templates/extended_bin#L623
It should definitely be thought about …
> Introduce 'foreground' mode

- src/mod_push_service_mongoosepush.erl
This PR makes it easier to debug errors with MongoosePush / MongooseIM API incompatibility.
> Improve MongoosePush's logs on 4xx errors

- big_tests/tests/ejabberdctl_SUITE.erl
- big_tests/tests/login_SUITE.erl
- big_tests/tests/mam_SUITE.erl
- big_tests/tests/mod_global_distrib_SUITE.erl
- big_tests/tests/rest_SUITE.erl
- src/gen_mod.erl
- test.disabled/ejabberd_tests/tests/gen_mod_SUITE.erl
- test/gen_mod_SUITE.erl
This PR refers to the discussion about improvements to module/service management. Part of the scope was making gen_mod check if a module has already been started (for a host) and if so refuse to start it (same for stopping). After some changes to return values gen_mod behaves now a bit like OTP.
> otp-ish API for starting/stopping modules via gen_mod

- src/gen_mod.erl
- src/mongoose_service.erl
- test/mongoose_service_SUITE.erl
**EDIT:**
This PR improves #1792 with stuff discussed during tech meeting.
**Old description:**
This is an alternative to PR#1792, see
https://redmine.erlang-solutions.com/issues/18914
and
https://redmine.erlang-solutions.com/projects/mongooseim/wiki/MongooseIM_global_modules_tech_discussion
> Mongoose service+

- big_tests/test
- big_tests/tests/push_SUITE.erl
- big_tests/tests/push_integration_SUITE.erl
- big_tests/tests/push_pubsub_SUITE.erl
- doc/modules/mod_event_pusher_push.md
- src/event_pusher/mod_event_pusher.erl
- src/event_pusher/mod_event_pusher_http.erl
- src/event_pusher/mod_event_pusher_push.erl
- src/event_pusher/mod_event_pusher_push_plugin.erl
- src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
- src/event_pusher/mod_event_pusher_sns.erl
- test/mod_aws_sns_SUITE.erl
The main change is that the final push notification delivery was moved to plugin module. This allows to create a plugin which can push an event to a queue so some backend service may decide what to do next with the push notification.
Additionally following changes were mad:
* Accumulator is passed to mod_event backends
* Push notification tests were refactored - helper module was created
> Push notifications refactoring

- rebar.config
- rebar.lock
There is no tagged version yet but the latest version fixes important performance issue.
> Update fast_tls to stat-less version

- src/ejabberd_c2s.erl
- src/ejabberd_local.erl
- src/ejabberd_router.erl
- src/ejabberd_s2s.erl
- src/ejabberd_s2s_out.erl
- src/ejabberd_sm.erl
- src/jlib.erl
- src/mod_muc.erl
- src/mod_muc_room.erl
- src/mod_offline.erl
- src/mod_vcard.erl
- src/mongoose_acc.erl
- src/mongoose_subhosts.erl
- test/jlib_SUITE.erl
- test/router_SUITE.erl
This PR provides a safety measure to prevent infinite error looping. The loop starts when routing an error message triggers an error and mongooseim tries to route error message in response to that, and so on. In this PR we use accumulator to store a flag saying that we are routing error message, and if it loops back we do not route it.
> Prevent infinite error loop

- Makefile
- doc/modules/mod_jingle_sip.md
- tools/configure
> Remove esip from default build

- big_tests/tests/rest_client_SUITE.erl
This PR addresses
```erlang
====== Suite FAILED: rest_client_SUITE (1 of 30 tests failed)    
====== Test name: add_contact_and_invite                         
====== Reason:    {{badmatch,                                    
#{ask => <<"out">>,                       
jid => <<"alice12.325484@localhost">>,  
subscription => <<"none">>}},           
[{rest_client_SUITE,'-add_contact_and_invite/1-fun-0-',2,                                                      
[{file,"rest_client_SUITE.erl"},{line,697}]},                                                             
{escalus_story,story,4,                      
[{file,"src/escalus_story.erl"},{line,72}]},                                                              
{rest_client_SUITE,add_contact_and_invite,1, …
```
> Fix a race condition in rest_client_SUITE

- big_tests/tests/cluster_commands_SUITE.erl
- big_tests/tests/ejabberdctl_SUITE.erl
- big_tests/tests/ejabberdctl_helper.erl
This PR is similar to #1803.
It also addresses the same resource reuse between several stories.
* ejabberdctl_helper prints command, when a timeout error occurs
* kick_everyone between test cases
* Actually wait for cleanup to finish, not just fire a stanza and forget (because the result can arrive to a reconnected device)
> Properly handle resource reusing between stories in ejabberdctl_SUITE

- big_tests/tests/privacy_SUITE.erl
- tools/docker-setup-mysql.sh
- tools/travis-setup-db.sh
From 8.0.11 release notes:
The following features related to account management have been removed:
Using GRANT to modify account properties other than privilege assignments. This includes authentication, SSL, and resource-limit properties. Instead, establish such properties at account-creation time with CREATE USER or modify them afterward with ALTER USER.
> Fix Travis tests with new MySQL

- tools/setup_riak
This PR addresses adding an option for disabling Riak SSL configuration in setup_riak script.
The script is used by Tide in order to provision Riak but we do not want to use SSL for connection to the DB. Introduced changes allows to disable the configuration while it's still enabled by default for testing purposes.
* add an option for disabling SSL configuration in the script that provisions Riak
> Add an option for disabling Riak SSL configuration in setup_riak script

- src/mod_mam.erl
- src/mod_mam_cassandra_arch.erl
- src/mod_mam_muc.erl
- src/mod_mam_muc_cassandra_arch.erl
- src/mod_mam_muc_odbc_arch.erl
- src/mod_mam_muc_odbc_async_pool_writer.erl
- src/mod_mam_odbc_arch.erl
- src/mod_mam_odbc_async_pool_writer.erl
- src/mod_mam_riak_timed_arch_yz.erl
- src/mod_mam_utils.erl
This PR addresses simplifies MAM-backend code.
* do policy check in one place in mod_mam/muc. 
There is a small performance degradation in case we hit the policy violation (we extract but don't forward the messages). But the policy-violation is never hit in the real systems.
Motivation: KISSify MAM backend modules.
> Move policy-violation check from backend modules into mod_mam

- big_tests/tests/muc_SUITE.erl
- src/mongoose_http_client.erl
Fixes:
```erlang
2017-07-21 14:53:18.754 [warning] <0.23644.0> ====== SUITE muc_SUITE starting        
2017-07-21 14:53:36.164 [error] <0.20165.0> Supervisor received unexpected message: {'ETS-TRANSFER',mongoose_http_client_pools,<0.24818.0>,<0.24818.0>}
2017-07-21 14:53:37.245 [error] <0.24847.0> gen_fsm <0.24847.0> in state normal_state terminated with reason: no case clause matching {'EXIT',{shutdown,{gen_server,call,[<0.24826.0>,{request,<<"/muc/auth/check_password?from=bO
b16.201532%40localhost%2Fres1&to=room-alice16.199701%40muc.localhost&pass=pa5sw0rd">>,<<"GET">>,[],<<>>,1,2000},infinity]}}} in mongoose_http_client:make_request/5 line 138
2017-07-21 14:53:37.245 [error] <0.24847.0> CRASH REPORT Process <0.24847.0> with 0 neighbours exited with reason: no case clause matching …
```
> Fix http muc tests

- rel/files/app.config
At some point we broke logs in the live shell, i.e.
```erlang
_build/mim1/rel/mongooseim/bin/mongooseim console
```
Log message in `log/ejabberd.log`:
```erlang
Lager fatally failed to install handler lager_console_backend into
lager_event, NOT retrying: {bad_console_config, info}
```
> Fix broken lager_console_backend backend

- big_tests/run_common_test.erl
- big_tests/test.config
Allows to start just some nodes for tests:
```erlang
./tools/configure with-all
DB=mysql ./tools/travis-setup-db.sh
make mim1
%% just run with one node
%% be aware, that tests, that need other nodes would fail :(
%% but I usually test with modified test spec file, that does not have all the tests enabled.
TEST_HOSTS="mim" DEV_NODES="mim1" ./tools/travis-test.sh -c false -s false -e false -p mysql_mnesia
```
or
```erlang
TEST_HOSTS="mim fed" DEV_NODES="mim1 fed1" ./tools/travis-test.sh -c false -s false -e false -p mysql_mnesia
```
Without this PR we need to run all nodes to run a test.
> Allow to enable preset on just some nodes

- big_tests/rebar.config
- big_tests/tests/muc_SUITE.erl
- src/mod_muc_room.erl
Fix handling of form submits and cancels in MUC rooms
Previously any cancel request sent at any time would trigger room destruction. Additionally, form with non-default values could be submitted without fetching the form first (which is disallowed in the XEP).
The new behaviour is as follows:
* cancel IQs sent when room is in the locked state destroy the room ([link](https://xmpp.org/extensions/xep-0045.html#example-162))
* cancel IQs sent when the room is unlocked, but before fetching the
form return an error
* cancel IQs sent when the room is unlocked, but after fetching the
form return an IQ result and don't modify any values in the room ([link](https://xmpp.org/extensions/xep-0045.html#example-166))
* submit IQs without modified values sent when the room is locked
create an instant …
> Fixes to MUC configuration cancellation and form submission handling

- doc/advanced-configuration/Listener-modules.md
- include/ejabberd_c2s.hrl
- src/ejabberd_c2s.erl
- src/ejabberd_receiver.erl
- src/ejabberd_socket.erl
This PR introduces a new configuration variable for listeners: `hibernate_after`.
This variable configures the timeout (in milliseconds) after which a c2s and receiver process will hibernate if they're idle. It replaces old in-code constants that hibernated these processes after 90 seconds of idle time.
If `hibernate_after` is 0 (the default), the processes will hibernate as soon as they get a chance. Load tests have shown that this **greatly** reduces MongooseIM's memory consumption while producing no noticeable slowdown or increase in CPU load under common scenarios.
> Add hibernate_after listener opt with 0 default value.

- src/ejabberd_c2s.erl
- src/jingle_sip/mod_jingle_sip.erl
This PR improve consistency of acc fields.
> use already present origin_jid from acc instead of adding new field

- rel/files/app.config
Reverts esl/MongooseIM#1832 as it actually has broken the console logger.
> Revert "Fix broken lager_console_backend backend"

- doc/advanced-configuration/Listener-modules.md
- doc/authentication-backends/PKI-authentication-module.md
- doc/authentication-methods/client-certificate.md
- mkdocs.yml
This PR:
- Updates `Listener modules` page with missing c2s options.
- Adds "Client Certificate" page under new section: Authentication Methods
- Adds "PKI" page under Authentication Backends section
As a bonus:
- Adds missing `mod_jingle_sip` entry in `mkdocs.yml`
> [skip ci] SASL EXTERNAL docs

- rebar.config
- rebar.lock
The one with a workaround to `enif_inspect_binary` for Erlang/OTP older than 20
> Use esl/exml 3.0.1

- tools/pkg/platforms/centos6/Dockerfile
- tools/pkg/platforms/centos7/Dockerfile
- tools/pkg/platforms/debian_stretch/Dockerfile
This package includes `sql.h` file which is required to compile eodbc.
Somehow it stopped being installed when creating the builder container so Mongoose could not be compiled.
> Install unixodbc dev package in pkg builder containers

- tools/docker-compose.sh
- tools/travis-test.sh
This PR addresses "Travis is slow!".
* use docker pull --parallel
* use "docker-compose tries to resolve an ip, so slow" - not sure, if we actually need it.
> Parallel pull for docker-compose

- .travis.yml
- big_tests/run_common_test.erl
- src/mongoose_cover_helper.erl
This PR addresses "Slow Travis? Slow cover."
* Add KEEP_COVER_RUNNING variable
"Executing Export cover data from MongooseIM nodes" step works 10 times faster now.
> Reduce waiting time for cover on CI

- src/mongoose_rabbit_worker.erl
> Remove undefined functions from exports

- big_tests/tests/last_SUITE.erl
- big_tests/tests/mam_helper.erl
- big_tests/tests/mod_global_distrib_SUITE.erl
- big_tests/tests/muc_SUITE.erl
- big_tests/tests/muc_light_SUITE.erl
- big_tests/tests/muc_light_legacy_SUITE.erl
- big_tests/tests/pep_SUITE.erl
- big_tests/tests/s2s_SUITE.erl
This PR addresses warnings like 
```erlang
Suite: mod_global_distrib_SUITE finished dirty. Other suites may fail because of that. Details:                                   
[{registered_users,[{<<"eve97.992760">>,<<"localhost.bis">>},                                                                     
{<<"eve97.992760">>,<<"localhost">>}]}, 
```
It does not remove ALL the warnings, because unregister call is async in clean (?).
- Add missing escalus_fresh:clean()
> Erradicate registered_users warnings in tests

- big_tests/test.config
- tools/travis-common-vars.sh
- tools/travis-setup-db.sh
- tools/travis-setup-ldap.sh
This PR addresses "Travis scripts are too travis specific".
* LDAP running in docker container
* Make docker-volume logic generic
> Dockerize LDAP

- big_tests/tests/jingle_SUITE.erl
- big_tests/tests/jingle_helper.erl
- big_tests/tests/jingle_sip_translator.erl
- src/jingle_sip/jingle_sip_callbacks.erl
- src/jingle_sip/mod_jingle_sip.erl
This PR extends Jingle/SIP integration translates:
1. From MongooseIM to SIP proxy. Jingle actions `source-add`, `source-remove`, `source-update` in established Jingle session to SIP's in-dialog INVITE message. A custom attribute `a=jingle-action:NAME` is added to the SDP packet to indicate what was the original action.
2. From SIP proxy to MongooseIM SIP's in-dialog INVITE (reINVITE) is translated to corresponding jingle action (based on the custom `a=jingle-action` attribute. If the attr is missing, the action is `transport-info`.
> Jingle sip reINVITE

- big_tests/tests/muc_helper.erl
- src/cassandra/mongoose_cassandra_sup.erl
- src/ejabberd_auth_http.erl
- src/ejabberd_auth_ldap.erl
- src/ejabberd_listener.erl
- src/ejabberd_rdbms.erl
- src/ejabberd_sup.erl
- src/ejabberd_users.erl
- src/global_distrib/mod_global_distrib_bounce.erl
- src/global_distrib/mod_global_distrib_hosts_refresher.erl
- src/global_distrib/mod_global_distrib_mapping_redis.erl
- src/global_distrib/mod_global_distrib_receiver.erl
- src/mod_caps.erl
- src/mod_mam_cache_user.erl
- src/mod_mam_muc_cache_user.erl
- src/mod_muc.erl
- src/mod_muc_log.erl
- src/mod_offline.erl
- src/mod_pubsub.erl
- src/mod_shared_roster_ldap.erl
- src/mod_vcard.erl
- src/mongoose_http_client.erl
- src/mongoose_riak_sup.erl
- src/rdbms/mongoose_rdbms.erl
This PR ensures that start_module would fail, if start_child fails.
It allows to catch badly started module at start time, not when we try to use it.
It helps with failing muc_http_api_SUITE, that fails with service unavailable reason sometimes.
```erlang
big_tests/tests/muc_http_api_SUITE.erl:    muc_helper:load_muc(muc_helper:muc_host()),
```
* `ejabberd_sup:start_child/1` crashes when child already present
* I haven't touched places, when code expects to add child several times. i.e. ejabberd_users. It needs an extra refactoring effort.
* `muc_helper:load_muc/1` unloads already started module and proceeds instead of doing nothing.
> Strict control for starting supervised processes

- big_tests/tests/mod_global_distrib_SUITE.erl
This PR addresses [this error](http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/branch/master/4836/cassandra_mnesia.19.3/big/ct_run.test@travis-job-982975d2-4383-4f1f-bcae-e3e649d81c0a.2018-06-06_17.33.42/big_tests.tests.mod_global_distrib_SUITE.logs/run.2018-06-06_17.48.06/mod_global_distrib_suite.test_muc_conversation_history.html)
* more sync way to test
> Fix a race condition in mod_global_distrib_SUITE:test_muc_conversation_history

- src/mongoose_cluster.erl
This patch removes the check if Mnesia directory reported by `mnesia:system_info(directory)` is the same as `application:get_env(mnesia, dir)` when deleting Mnesia files.
The check sometimes resulted in unexpected errors. Users set Mnesia directory path using application env `mnesia.dir`. This path might be a relative path (it might be even an atom!). When Mnesia starts, it takes this value, converts it to absolute path and stored it in initial config. This is what `mnesia:system_info(directory)` returns, thus the check failed in simple situations when someone sets `mnesia.dir` to relative path. The check only succeeded in cases when `mnesia.dir` path is a normalized, absolute path, or when Mnesia is stopped, in which caes `mnesia:system_info(directory)` falls back to application env's …
> Remove the check which compares Mnesia directory with the value set in the app env when deleting Mnesia files

- .travis.yml
- big_tests/default.spec
- big_tests/src/ct_markdown_errors_hook.erl
- tools/travis-helpers.sh
- tools/travis-publish-github-comment.sh
This PR addresses "Better test visibility".
* New ct hook handler that writes errors into /tmp/ct_markdown
* tools/travis-publish-github-comment.sh that sends a link to reports and errors to github
* New secret variable COMMENTER_GITHUB_TOKEN
* @felisbot meow
*  https://github.com/esl/MongooseIM/pull/1916#issuecomment-395878938 - comment example. Big test errors are inlined, 25 max. Comments from all tasks are grouped by git commit.
Email notifications:
- so far first task would create a comment email. Email would contain non-collapsed markdown for first task only. Ideally, we should suppress the emails. (todo, non trivial).
> Comment reports link and a list of failed tests to Github

- big_tests/tests/muc_light_http_api_SUITE.erl
- doc/advanced-configuration/database-backends-configuration.md
- src/mod_muc_light_db_odbc.erl
- src/mongoose_commands.erl
- tools/travis-setup-db.sh
After deeper investigation it turned out that MUC light's transactions causes many deadlocks in MSSQL. This resulted, for instance, in the strange duplicated (the same id) returned when selecting data by a primary key. In fact MSSQL returned only one row (which was expected) along with an error notifying about a deadlock (found when tracing with Wireshark).
The root cause of these deadlocks was default `READ_COMMITED_SNAPSHOT` (database property) set to `OFF`. With this property set to `OFF` MSSQL uses shared locks, which tries to be intelligent  and locks more then really needed when it sees a transaction modifies many data. If this property is set to `ON`, row-level locks are used which limits deadlocks in muc light's transaction while still keeping the needed transaction isolation.
> Stabilizing MUC light transaction on MSSQL

- .travis.yml
- big_tests/mam.spec
- big_tests/test.config
- tools/travis-setup-db.sh
- tools/travis-test.sh
This PR addresses travis-ci usage optimisations.
The only unique functionality for ElasticSearch and Cassandra job is MAM. In this PR both these jobs are combined into one and mam_SUITE is tested with both back-ends. Additionally there are cassandra and elastic specific suites run.
Thanks to that the needed functionality is tests in less then 20 minutes instead of almost 1 hour as it was before when these 2 jobs were run separately.
> Elastic search and cassandra job

- big_tests/tests/mam_SUITE.erl
- big_tests/tests/mam_helper.erl
- doc/modules/mod_mam.md
- src/mod_mam_muc_odbc_async_pool_writer.erl
- src/mod_mam_odbc_async_pool_writer.erl
This PR addresses issue with async writer being too synchronous for reading.
* removed `wait_for_flushing` when a user reads messages from the archive
* renamed `max_packet_size` option to `max_buffer_size`
* in tests use `mam_helper:wait_for_archive_size` in some places instead of `maybe_wait_for_archive`
* documented new behaviour and old config options for async writers
> Fix async pool writer

- doc/developers-guide/hooks_description.md
- src/mod_muc_room.erl
This PR addresses lack of hook on users leaving and entering multi-user chats
* Hooks for user enter/leave muc
* No tests added, not sure what to do in this. Will add tests if pointed in the right direction (if needed).
* Added hook to list of hooks in developer documentation hooks_description.md
> Ported User Leave and Join muc hooks from ejabberd

- big_tests/tests/mam_SUITE.erl
It happened that messages send from Alice to Bob were indexed by Elastic Search for Bob already, but were not yet for Alice. In this PR the test waits until all messages are indexed for Alice before the search query is sent.
> Wait for Alice archive in full text archive search test

- big_tests/tests/pubsub_SUITE.erl
There are tests in `pubsub_SUITE` for sending payload to subscriber if he's online.
The scenario was that user sent `presence unavailable` and just after that item was published. 
When message was routed to user, the session table wasn't refreshed yet and he still seemed to be online. In order to fix it I use `push_helper:become_unavailable/1` that check the session table after sending the presence.
> stabilise pubsub_SUITE

- big_tests/tests/presence_SUITE.erl
- src/mod_roster_mnesia.erl
- src/mod_roster_odbc.erl
- src/mod_roster_riak.erl
This PR fixes a bug that manifests when a user adds a contact to a roster with a nickname and then sends subscription request to the same user. In such case, the nickname information will get removed when using RDBMS backend.
> Fix roster update on subscription request

- big_tests/tests/amp_big_SUITE.erl
There were some remaining `escalus:story` even though the test was intended to run with parallelisation. In this PR I change those to `fresh_story`.
I believe it was the reason of some failing tests due to privacy lists duplication (because one non-parallel test created a list for a user and another non-parallel test did the same for the same user).
> stabilise amp_big_SUITE

- src/ejabberd_receiver.erl
- src/ejabberd_socket.erl
This PR supersedes #1942.
Based on @ludwikbukowski work it turned out that c2s dies with reason like:
```erlang
{normal,
{gen_server,call,
[<6900.28922.0>,
{starttls,
[verify_none,
{certfile,"priv/ssl/fake_server.pem"},
{tls_module,just_tls},
{protocol_options,"no_sslv3"}]}]}}}}
```
Because of a race condition around sending gen_server call to the receiver process. It might happen that receiver dies with reason `normal` after the call is sent but before it's processed by the receiver. From C2S perspective this still ok, as `noproc` case (when there is no receiver process when the call is about to be sent) is.
The PR extends receiver's code to handle the above corner case. Having repeatable tests for that is doable but very difficult. In my opinion it's not worth to add a test case for …
> Return error if receiver dies after sending a call to it

- tools/travis-publish-github-comment.sh
This PR addresses "small tests link leading nowhere" and "no link for small_tests task".
* fix
> Fix commenter for tasks that only run big or only small tests

- src/mongoose_cluster.erl
MongooseIM in production systems usually has mnesia in something like /var/lib/mongoose, whereby /var/lib is not writable for the user which is running mongooseim. Joining or leaving a cluster requires wiping out mnesia dir, but we don't have to recreate the dir itself; attempt to do so may fail due to lack of permissions.
> fix filesystem permissionproblem with clustering mongeese

- tools/setup_riak
This PR addresses instability in Riak setup. With this PR, the script setting up Riak waits for the expected HTTP status of just created schema or index before it proceeds.
> Wait for expected HTTP status code after creating schema or index

- big_tests/tests/bosh_interleave_reqs.erl
A fresh user will be used in another try so there is no need to stop testing if one user was slow to stop
> Catch timeout when stopping clients in bosh_SUITE:interleave_requests

- src/jingle_sip/mod_jingle_sip.erl
This PR makes sure that `nksip` app is started while starting `mod_jingle_sip`. Also it allows to start the module for more than just one host.
> Accept error already_started and make sure nksip app is running

- big_tests/tests/rest_client_SUITE.erl
- doc/rest-api/Client-frontend_swagger.yml
- src/mongoose_client_api.erl
- src/mongoose_client_api_rooms.erl
- src/mongoose_client_api_rooms_messages.erl
- src/mongoose_client_api_rooms_users.erl
With this PR MongooseIM will respond with the following error for room's message sending via client's HTTP API
* `400 Bad Request` if the request body is not valid:
* the body is not JSON
* or doesn't have `body` element
* or the `body` element is not string
* `403 Forbidden` if the user sending the message is not member of the room
> Improve room http api

- src/mam/mod_mam_meta.erl
This PR adds support for  `default_result_limit` and `max_result_limit` parameters in `mod_mam_meta`.
> Add missing params support to mod_mam_meta

- big_tests/tests/bosh_SUITE.erl
- big_tests/tests/component_helper.erl
- big_tests/tests/mam_helper.erl
- big_tests/tests/metrics_register_SUITE.erl
- big_tests/tests/mod_global_distrib_SUITE.erl
- big_tests/tests/mod_http_upload_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- big_tests/tests/muc_SUITE.erl
- big_tests/tests/push_helper.erl
- big_tests/tests/push_integration_SUITE.erl
- big_tests/tests/sm_SUITE.erl
- big_tests/tests/users_api_SUITE.erl
Refactor ```mongoose_helper:wait_until/{2,3}``` for simple and overridable interface and raplace as many as possible ```wait_for_SOMETHING``` functions in big tests
> Incremental sleep redundancy

- src/ejabberd_c2s.erl
See #1963. There are error logs occuring when a client attempts to
reconnect in a very short timespan and at the same time a stanza is
routed to the old invalid connection.
As this is just an application/client oddity the log severity should be
lowered to "warning". This is simply nothing to alert an operations guy
in the middle of the night.
There are actually a lot more logs like this but this one currently
stands out ;).
> Adjust "conflict_check_failed" log severity

- big_tests/tests/rest_client_SUITE.erl
- big_tests/tests/rest_helper.erl
- doc/rest-api/Client-frontend.md
- src/mongoose_client_api_messages.erl
This PR addresses #1910
Basic idea is to add Smack Lib properties part of raw xml message to the result json. If there are properties then old json will be returned.
> json result object extended with message extension properties if there are some Smack lib properties in raw message.

- big_tests/tests/pep_SUITE.erl
- big_tests/tests/pubsub_tools.erl
- src/ejabberd_local.erl
- src/ejabberd_router.erl
- src/ejabberd_sm.erl
- src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
- src/gen_iq_handler.erl
- src/mam/mod_mam_muc.erl
- src/mod_caps.erl
- src/mod_muc_iq.erl
- src/mod_muc_room.erl
- src/mod_offline.erl
- src/mod_ping.erl
- src/mod_roster.erl
- src/muc_light/mod_muc_light.erl
- test/mongoose_cleanup_SUITE.erl
In some corner cases (e.g. when using pubsub with stream management on) it triggered errors on hook calls, because some handlers rely on server key being present (which is usually the case). It produced error log messages, made some metrics incorrect, and could potentially cause more trouble.
I think we should make those two values required in accumulator, as kind of "environment variables", whereby server is host in context of which we are operating, and user is the caller. Server-generated actions and admin's rest api calls might have user=undefined.
Also, this PR fixes acc processing in iq handling machinery, also cleaning it up so that functions have the same signatures and fixing function specs.
> acc-related fixes and cleanups

- big_tests/tests/inbox_SUITE.erl
This PR addresses the error in autocompletion:
```erlang
./tools/test-runner.sh --skip-small-tests --preset mysql_mnesia --skip-cover --rerun-big-tests -- inbox:all_call_failed suite=inbox_SUITE reason=error:badarg                                                                                                        
stacktrace=[{ets,select,                                                                                                         
[ct_attributes,                                                                                                  
[{{ct_conf,'_','$1','_','_',hosts,'_'},[],[{{'$1'}}]}]],                                                        
[]}, …
```
> Fix test-runner test cases completion for inbox_SUITE

- rebar.config
- rebar.lock
- src/event_pusher/mod_event_pusher_push.erl
- src/mod_push_service_mongoosepush.erl
This PR upgrades worker_pool dep to 3.1.1. In fact it uses worker_pool from branch `rel-3.1` (with small fix to function specs) since master branch works only with Erlang/OTP 21.
> Upgrade worker_pool to 3.1.1

- tools/test-runner-complete.sh
- tools/test-runner.sh
This PR adds a new option for test runner.
So this works:
```bash
./tools/test-runner.sh --help --examples --colors | more
```
Before we would only use colors if they are supported my terminal. i.e.
```bash
./tools/test-runner.sh --help --examples 
./tools/test-runner.sh --help --examples | more
```
> Add --colors option for test-runner

- big_tests/tests/inbox.hrl
- big_tests/tests/inbox_SUITE.erl
- big_tests/tests/inbox_helper.erl
- doc/modules/mod_inbox.md
- include/mod_inbox.hrl
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- src/inbox/mod_inbox.erl
- src/inbox/mod_inbox_muclight.erl
- src/inbox/mod_inbox_odbc.erl
- src/inbox/mod_inbox_odbc_mssql.erl
- src/inbox/mod_inbox_odbc_mysql.erl
- src/inbox/mod_inbox_odbc_pgsql.erl
- src/inbox/mod_inbox_utils.erl
- src/jlib.erl
This PR adds timestamps support to `mod_inbox`, including sorting and filtering by them.
Also includes a significant refactor of Inbox tests.
> Timestamp support in mod_inbox

- codecov.yml
Our code coverage varies a bit from run to run. There is no point in failing a PR if it coverage dropped a bit (0.1%). The allowed threshold is configurable so we can adjust it if needed.
> Configure codecov to allow small coverage drop

- big_tests/tests/sm_SUITE.erl
- src/ejabberd_c2s.erl
This PR fixes only `resend_unacked_on_resonnection` test itself. It doesn't fix the real problem.
> Resend unacked on reconnection fix

- doc/modules/mod_mam.md
- doc/operation-and-maintenance/Mongoose-metrics.md
- src/mam/mod_mam_muc_odbc_async_pool_writer.erl
- src/mam/mod_mam_odbc_async_pool_writer.erl
- src/rdbms/mongoose_rdbms.erl
This PR adds very useful metrics for gauging MAM's performance with `async_writer` enabled (default).
> Add flush_time metric to MAM RDBMS async pool writers.

- big_tests/tests/amp_big_SUITE.erl
- big_tests/tests/s2s_SUITE.erl
This PR addresses https://redmine.erlang-solutions.com/issues/19508
Although I could not reproduce the exact issue, I found that in some cases the response from s2s might be a bit delayed for some messages. In general, AMP tests should not test s2s functionality, so I 
extracted the check for s2s routing to a malformed JID out of `amp_big_SUITE` and put it in `s2s_SUITE`, where it belongs.
> Do not test s2s routing in AMP tests

- src/config/mongoose_config_parser.erl
- src/config/mongoose_config_reload.erl
- src/ejabberd_config.erl
- test/ejabberd_config_SUITE.erl
- test/ejabberd_config_SUITE_data/ejabberd.no_listeners.loglevel_err.cfg
Config files on nodes have to be matching in order to successfully reload cluster configuration. The check was broken, so the reload could have proceeded (loading incompatible configurations on nodes) and then fail during a check if the loaded configs are compatible.
> Fix checks for matching configuration before reload_cluster.

- big_tests/test.config
- big_tests/tests/mongoose_elasticsearch_SUITE.erl
- doc/Advanced-configuration.md
- doc/advanced-configuration/outgoing-connections.md
- doc/migrations/3.1.1_3.1.1++.md
- src/elasticsearch/mongoose_elasticsearch.erl
- src/mongoose_wpool.erl
- src/mongoose_wpool_elastic.erl
This PR changes the way how ElasticSearch pool is configured
* mongoose_wpool_elastic - starts and stops the pool
* ability to configure ElasticSearch pool via `outgoing_pools` option
* adjust test to start the pool in the new way
> Allow to configure ElasticSearch pool via outgoing_options

- src/shaper_srv.erl
This PR removes debug log about old shapers being deleted.
I'm not sure if these were useful to anyone ever but for me they were usually annoying and make working with debug log level more difficult (console spamming, interleaving with command being typed).
> Remove debug log about old shapers

- .gitignore
- Makefile
- big_tests/Makefile
- big_tests/tests/mod_global_distrib_SUITE.erl
- big_tests/tests/mongoose_push_mock.erl
- big_tests/vm.dist.args.in
- rebar.config
- src/global_distrib/mod_global_distrib_connection.erl
- test/auth_jwt_SUITE.erl
- tools/db_configs/cassandra/docker_entry.sh
- tools/ssl/Makefile
- tools/ssl/openssl-ca.cnf
- tools/ssl/openssl-mongooseim.cnf
- tools/travis-setup-db.sh
This PR reorganises a bit how certificates are generated and used in tests. This refactoring was inspired by the work done by @chrzaszcz in a side project.
This is needed for the SASL end-2-end tests I'm currently working on.
> Reorganise certs generation

- src/ejabberd_app.erl
This PR fixes log level setting after node start.
> fix setting loglevel as in config file after starting node

- big_tests/tests/sasl_external_SUITE.erl
- doc/authentication-methods/client-certificate.md
- src/ejabberd_cowboy.erl
- src/ejabberd_tls.erl
- src/just_tls.erl
* extended test cases when self-signed certs are allowed and not
* extended ejabberd_cowboy to allow self-signed certs
TODO:
> Self-signed certs for SASL-EXTERNAL

- big_tests/tests/push_http_SUITE.erl
- doc/modules/mod_event_pusher_http.md
- src/event_pusher/mod_event_pusher.erl
- src/event_pusher/mod_event_pusher_http.erl
- src/event_pusher/mod_event_pusher_http_defaults.erl
This PR improves mod_event_pusher a bit, making it more configurable (ref. MIM-70):
- pass accumulator down to event pushing logic
- http backend can have multiple configurations (like, push messages to various backends using various predicates)
- http backend callbacks can customise message body and headers
- http backend can push both incoming and outgoing messages
> Event pusher improvements

- src/muc_light/mod_muc_light_utils.erl
tried to simplify user affiliation change code.
hope this version is a bit easier to read. 
multiple room ownership can be enabled by removing `maybe_demote_old_owner/1` call from `change_aff_users/2`
> muc light user affiliation rework

- doc/modules/mod_pubsub.md
- src/pubsub/gen_pubsub_node.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/node_dag.erl
- src/pubsub/node_flat.erl
- src/pubsub/node_hometree.erl
- src/pubsub/node_pep.erl
- src/pubsub/node_push.erl
- src/pubsub/nodetree_tree.erl
This PR adds dynamic DB backend to `mod_pubsub`, with Mnesia backend supporting `pubsub_state` table for now.
> Add dynamic backend to mod_pubsub

- src/event_pusher/mod_event_pusher_rabbit.erl
- src/mongoose_amqp.erl
- src/mongoose_rabbit_worker.erl
- test/mongoose_rabbit_worker_SUITE.erl
Closes https://github.com/esl/tide/issues/418#issuecomment-434607213.
> [clt-rabbit] Don't crash RMQ worker when amqp exception occurs

- src/mod_revproxy.erl
mod_revproxy currently leaks the fusco Clients that it creates when proxying the HTTP requests, one per request.
* Disconnect the fusco Client to stop the leak.
> fix a memory leak in mod_revproxy

- big_tests/rebar.config
- tools/test-runner.sh
- tools/test_runner/complete-test-name.sh
- tools/test_runner/complete_test_name.erl
- tools/test_runner/selected-tests-to-test-spec.sh
- tools/test_runner/selected_tests_to_test_spec.erl
This PR addresses some errors, because test runner assumes that someone run it before. And it expects beam files of SUITEs to be available for spec generation and autocompletion.
Be aware, that with this patch travis test would stop, if `redis-server` is running without a docker container. Use `--db` in this case.
Later we can add code, that would test database options sanity before running any tests (gen_tcp connect? actually probing connection with some library? idk).
> More error resilient test runner

- tools/test-runner-complete.sh
Check, that `_get_comp_words_by_ref` function does not exist yet, before including bash_completion from brew
If it exists, than bash_completion is loaded from some other source (MacPorts? newer bash version?)
> Do not load bash completion from brew in Mac OS if it is already loaded

- include/pubsub.hrl
- src/jid.erl
- src/pubsub/gen_pubsub_node.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/node_flat.erl
- src/pubsub/node_push.erl
This PR refactors DB calls, mostly in `node_flat`, to be more efficient for future RDBMS backend. Causes more Mnesia operations but Mnesia backend should probably be rewritten or deprecated anyway.
> Refactor PubSub code to prepare for RDBMS

- src/mod_websockets.erl
- test/mod_websockets_SUITE.erl
This PR addresses #1221 
* This PR fixes compatibility issues with some Websocket libraries (chrome, some dot net stuff).
* Do not set `Sec-Websocket-Protocol` header in response if it's missing in request.
* Set `Sec-Websocket-Protocol` header with xmpp value, if it is specified in request.
* Do not set `Sec-Websocket-Protocol` header in respond if request does not specify xmpp.
Some libraries does not set Sec-Websocket-Protocol, but check that Sec-Websocket-Protocol exists in the result. It confuses the libraries and they disconnect from the server with "cryptic" error description.
Spec:
```
The |Sec-WebSocket-Protocol| header field is used in the WebSocket
opening handshake.  It is sent from the client to the server and back
from the server to the client to …
```
> Set Sec-Websocket-Protocol header according RFC

- big_tests/rebar.config
- big_tests/rebar.lock
- big_tests/tests/pubsub_SUITE.erl
- big_tests/tests/pubsub_tools.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/node_flat.erl
This PR only moves low level functions modifying `pubsub_item` table to the `mod_pubsub_db_mnesia` backend.
> Extract pubsub_item table operation to pubsub's mnesia backend

- big_tests/tests/pubsub_SUITE.erl
- src/pubsub/node_flat.erl
This PR adds publish only retract scope test and refactors delete_item node_flat.
> Pubsub test coverage

- big_tests/tests/pubsub_SUITE.erl
- big_tests/tests/pubsub_tools.erl
This PR add two test cases for `mod_pubsub` configured with `{publisher, true}`.
> Cover `item_publisher` option with tests

- src/pubsub/gen_pubsub_node.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/node_dag.erl
- src/pubsub/node_flat.erl
- src/pubsub/node_hometree.erl
- src/pubsub/node_pep.erl
- src/pubsub/node_push.erl
This PR is a preparation for more efficient RDBMS backend for pubsub_item. Proposed changes include:
* removal of tons of unused forwarding calls in `node_*` modules
* storing the item in backend's `add_item` function
* filtering by id and limiting results in backend function
> Pubsub refactoring for more efficient pubsub item in rdbms

- big_tests/tests/mongoose_helper.erl
- big_tests/tests/muc_helper.erl
- big_tests/tests/muc_light_SUITE.erl
- big_tests/tests/muc_light_http_api_SUITE.erl
- big_tests/tests/muc_light_legacy_SUITE.erl
- big_tests/tests/pep_SUITE.erl
- big_tests/tests/pubsub_SUITE.erl
- big_tests/tests/push_integration_SUITE.erl
- doc/modules/mod_pubsub.md
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- src/jid.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/mod_pubsub_db_rdbms.erl
- src/pubsub/mod_pubsub_db_rdbms_sql.erl
- src/pubsub/node_flat.erl
- src/pubsub/node_pep.erl
- src/pubsub/node_push.erl
This PR adds PubSub RDBMS backend for `pubsub_state` operations.
*Notes:*
- I have switched the input format of JIDs for backends to `jid:ljid()` as unfortunately `mod_pubsub` is a bit careless about what it passes (`jid()` vs. `ljid()`) to the node implementations. I've decided it makes more sense to reduce `jid()` to `ljid()` when necessary than the other way around.
- At some point `del_state` operation shouldn't be necessary, as items table will be expanded and no longer should be cleared e.g. when a user is removed from the node.
> pubsub_state RDBMS backend

- src/ejabberd_hooks.erl
- src/ejabberd_local.erl
- src/ejabberd_router.erl
- src/ejabberd_s2s.erl
- src/ejabberd_sm.erl
- src/mod_bosh.erl
- src/mongoose_cleaner.erl
- test/mongoose_cleanup_SUITE.erl
This PR fixes node_cleanup hook handlers crashes.
> Pass empty map to node_cleanup hook

- src/mod_vcard.erl
This PR tries to stabilize the `ldap` job on travis. After investigation I found out that the `mod_vcard_ldap_HOST` process cannot start because the old one was not stopped (and unregistered). In this PR the main `mod_vcard_HOST` process is stopped explicitly when the module stops.
> Stop mod_vcard process when stopping the module

- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/mod_pubsub_db_rdbms.erl
- src/pubsub/mod_pubsub_db_rdbms_sql.erl
- src/pubsub/node_flat.erl
This PR optimizes the way a pubsub node is removed. New function `del_node` was introduced which removes all data associated with given node id.
> Optimise pubsub's node removal

- rel/files/app.config
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/mod_pubsub_db_rdbms.erl
- src/pubsub/nodetree_dag.erl
- src/pubsub/nodetree_tree.erl
This PR extracts mnesia operations around pubsub_node table to the backend module. Fully covered is the `nodetree_dag` module implementing [Pub Sub Collection Nodes](https://xmpp.org/extensions/xep-0248.html). The default `nodetree_tree` module (implementing custom nodes structure)  is covered to some extend.
> Pubsub node mnesia backend

- big_tests/rebar.config
- big_tests/rebar.lock
- big_tests/tests/pubsub_SUITE.erl
- big_tests/tests/pubsub_tools.erl
- src/pubsub/gen_pubsub_nodetree.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/node_hometree.erl
- src/pubsub/nodetree_dag.erl
- src/pubsub/nodetree_tree.erl
This PR adds new or extends existing PubSub test cases to significantly improve coverage of code that performs `pubsub_node` operations in DB. It also includes small fixes and removes unused functions in plugins.
Depends on esl/escalus#193
> Extended PubSub tests to cover Mnesia + #pubsub_node usage

- rebar.config
- rebar.lock
- tools/summarise-ct-results
This PR uses patched `nkpacket` lib which works fine with ranch 1.7.
Also this PR includes a fix for test verification, more details in #2146
> Use patched nkpacket lib

- tools/pkg/platforms/centos7/Dockerfile
Installing hard coded version (7.9) stopped working yesterday (03.12) when this version
was removed form the mirror.
> Install the most up to date epel-release

- big_tests/tests/pep_SUITE.erl
- big_tests/tests/pubsub_SUITE.erl
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_cache.erl
- src/pubsub/mod_pubsub_cache_mnesia.erl
- src/pubsub/mod_pubsub_cache_rdbms.erl
This PR introduces following changes to `mod_pubsub`:
- `mnesia` cache backend for `pubsub_last_item` extracted to a separate _cache_ backend module
- _cache_ backend can be configured also to use `rdbms`
- the `mod_pubsub_cache_rdbms` is implemented
> Pubsub last item cache

- src/mod_vcard.erl
- src/mod_vcard_ldap.erl
In this PR mod_vcard calls optional `tear_down` callback on the backend module. This is needed mostly to properly stop all vcard processes (including the one holding eldap connection) in tests.
> Adds optional tear_down callback to mod_vcard backends

- src/pubsub/gen_pubsub_nodetree.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/mod_pubsub_db_rdbms.erl
- src/pubsub/nodetree_dag.erl
- src/pubsub/nodetree_tree.erl
- src/pubsub/pubsub_index.erl
This PR moves calls to pubsub_index to pubsub's backend modules
* simplified pubsub_index API, removed `free` function
* backend modules call pubsub_index when the `id` is not passed
> Move pubsub_index to backend

- doc/modules/mod_pubsub.md
Update `mod_pubsub` documentation.
> [skip ci] Add note about cache backend for pubsub_last_item

- big_tests/tests/mam_SUITE.erl
- big_tests/tests/rest_SUITE.erl
- src/gen_mod.erl
- test/gen_mod_SUITE.erl
Admin love: 
- adds a function gen_mod:opts_for_module/2 which allows you to selectively retrieve opts passed through config to a given module
- changes stop_module_keep_config/2 and stop_module/2 to return those opts
> add opts_for_module/2 and return opts on stop_module

- big_tests/tests/pubsub_SUITE.erl
- big_tests/tests/pubsub_s2s_SUITE.erl
- big_tests/tests/pubsub_tools.erl
This PR addresses ejabberd CVE (https://www.cvedetails.com/cve/CVE-2011-4320/) about infinite loop causing DoS when a user from other domain publishes an item to not existent node (no `node` attribute).
- Added new test suite for pubsub over s2s
- Added 2 test cases for publish item by remote user
- Node attribute is present
- Without node attribute
In both cases `remote-server-not-found` error should be returned
> CVE-2011-4320

- big_tests/tests/mod_aws_sns_SUITE.erl
- src/event_pusher/mod_event_pusher_sns.erl
- test/mod_aws_sns_SUITE.erl
This PR fixes issue with setting `MessageStructure` option properly (to `json`) in   `erlcloud_sns:publish/5`.
> Fix erlcloud_sns:publish content format

- big_tests/tests/vcard_SUITE.erl
- src/mod_vcard_ldap.erl
This PR fixes the issue with `infinity` mapped to `0` in `matches` option in `vcard_ldap`.
> Fix value is set to infinity but it is parsed as 0 by ldap backend

- big_tests/tests/vcard_simple_SUITE.erl
- doc/modules/mod_vcard.md
- src/mod_vcard_ldap.erl
This PR repairs the following bug:
`mod_vcard_ldap` ignored `ldap_uids` formed as `{"attribute"}` and only parsed `{"attribute", "format"}` correctly
Both option formats are now acceptable
> ldap uids option bug

- doc/advanced-configuration/Listener-modules.md
- src/ejabberd_cowboy.erl
- test/cowboy_SUITE.erl
After upgrading `Cowboy` to version `2.6` Ranch was automatically upgraded to version `1.7`. This version deprecates old API where transport options are passed as proplists where socket options are mixed with other ranch specific options.
This PR uses the new map syntax where all socket specific options like `port`, `ip` and `ssl_opts` are passed as `socket_opts` key in the map.
> Use map syntax to pass ranch transport options

- rel/files/mongooseim
- rel/files/vm.args
This approaches fixing `mongooseimctl debug` for cases of no hostname provided with `-sname`/`-name` in `vm.args`. The details are in respective commit log messages.
One remaining caveat is the case of the Mac example - running the script on a Mac is not that worrying, since it's not going to happen in production, but it means that we might run into the problem somewhere in production due to incomplete knowledge of how the Erlang VM expands `-name a` into `-name a@FQDN`.
This fix is necessary for remote shell access in a Kubernetes pod.
> Fix `mongooseimctl debug` command

- tools/travis-build-and-push-docker.sh
Test whether the container image built with the newest mongooseim-docker changes builds a valid container.
> Use mongooseim-docker with name flag and nodename fixes

- big_tests/tests/sasl_external_SUITE.erl
- doc/Advanced-configuration.md
- doc/authentication-methods/client-certificate.md
- src/auth/ejabberd_auth_pki.erl
- src/sasl/cyrsasl_external.erl
This PR addresses best practices for using `SASL EXTERNAL` as defined by https://xmpp.org/extensions/xep-0178.html.
> Sasl external best practices

- big_tests/tests/bosh_SUITE.erl
- src/mod_bosh.erl
This PR addresses #2210 
* make HTTP headers lowercase to avoid HTTP/2 connection errors
> lowercase HTTP headers in mod_bosh for HTTP/2 compliance

- big_tests/tests/sasl_external_SUITE.erl
- doc/authentication-methods/client-certificate.md
- rel/files/mongooseim.cfg
- rel/vars.config.in
- src/sasl/cyrsasl_external.erl
Added option in `mongooseim.cfg` to configure to use common name. This PR completes the implementation of SASL EXTERNAL best practices (https://xmpp.org/extensions/xep-0178.html).
> Add option to configure whether to use cn in SASL EXTERNAL authentication

- big_tests/tests/vcard_SUITE.erl
- src/mod_vcard_ldap.erl
This PR is an attempt to fix error when `eldap_pool_search/6` returns empty list in `mod_vcard_ldap`.
> Vcard ldap handle user not found

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
- src/mongoose_amqp.erl
- src/wpool/mongoose_wpool_rabbit.erl
Rabbit pool should pick up default options when none of `PoolOptions`
and `ConnectionOptions` are passed via the `outgoing_pools` config option.
> Fix starting rabbit pool if no options are passed

- big_tests/tests/inbox_SUITE.erl
- src/inbox/mod_inbox.erl
The only supported backned for `mod_inbox` is `rdms`. This PR makes it default.
> Default inbox backend fix

- big_tests/tests/sasl_external_SUITE.erl
- doc/authentication-methods/client-certificate.md
- rel/files/mongooseim.cfg
- rel/vars.config.in
- src/sasl/cyrsasl_external.erl
This PR adds three three options of the configuration of `cyrsasl_external`:
- with the use of `common_name`;
- standard (according to `XEP 0178`);
- with the use only of identity of the user.
> Configuration of cyrsasl_external

- big_tests/tests/connect_SUITE.erl
- big_tests/tests/lager_ct_backend.erl
- big_tests/tests/mod_aws_sns_SUITE.erl
- big_tests/tests/mod_global_distrib_SUITE.erl
- big_tests/tests/mongoose_cassandra_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- big_tests/tests/muc_SUITE.erl
- big_tests/tests/push_SUITE.erl
- big_tests/tests/push_pubsub_SUITE.erl
- big_tests/tests/race_conditions_SUITE.erl
- big_tests/tests/sasl_SUITE.erl
- big_tests/tests/sm_SUITE.erl
- doc/Advanced-configuration.md
- include/ejabberd_c2s.hrl
- src/ejabberd_c2s.erl
This PR addresses #1880 
When a node is slow, it may take more than 100ms for the replaced session to close or for `'DOWN'` message to reach the new c2s.
TODO:
> Wait longer for replaced c2s

- big_tests/tests/sm_SUITE.erl
- include/ejabberd_c2s.hrl
- src/ejabberd_c2s.erl
- src/jlib.erl
This PR addresses #2020
1. Flushing messages during SM handover was done improperly
Function responsible for gathering incoming messages was returning them in wrong format (returned tuples had wrong elements).
2. Presence subscription requests are buffered improperly
Subscription requests were resent with `From` and `To` as binaries, not JID record, leading to an error.
3. Conflict check failed improperly after successful resumption
If a session sends a request and the reply is received by a new process (the resumed one), there is a SID mismatch. In order to deal with it, new C2S remembers old SID to use it for conflict check.
TODO:
Blocked until #2054 is merged, because it relies on module injection helper.
> Fix 3 issues in SM resumption

- big_tests/tests/login_SUITE.erl
- big_tests/tests/oauth_SUITE.erl
- doc/Advanced-configuration.md
- doc/authentication-methods/client-certificate.md
- src/auth/ejabberd_auth.erl
- src/auth/ejabberd_auth_anonymous.erl
- src/auth/ejabberd_auth_external.erl
- src/auth/ejabberd_auth_http.erl
- src/auth/ejabberd_auth_internal.erl
- src/auth/ejabberd_auth_jwt.erl
- src/auth/ejabberd_auth_ldap.erl
- src/auth/ejabberd_auth_pki.erl
- src/auth/ejabberd_auth_rdbms.erl
- src/auth/ejabberd_auth_riak.erl
- src/auth/ejabberd_gen_auth.erl
- src/sasl/cyrsasl.erl
- src/sasl/cyrsasl_external.erl
- test/auth_external_SUITE.erl
- test/auth_http_SUITE.erl
- test/auth_jwt_SUITE.erl
Each auth backend had a `store_type/1` callback, which could return
'external', 'plain' or 'scram'.
There was a function called `store_type/1` in `ejabberd_auth` as well.
It traversed all backends, trying to determine the store type
for the whole host with a logic that e.g. favored 'external' over
'plain' (see the implementation for details).
Each SASL mechanism had its own password type, which was stored
in the sasl_mechanism ETS table on mechanism registration.
The possible password types were 'plain', 'digest', 'scram' and 'cert'.
To determine supported mechanisms in `cyrsasl:listmech/1`,
the store type for the current host was used to filter the SASL
mechanisms with the following rules:
```
Auth store_type     Supported password types
--------------      ------------------------ …
```
> Get rid of store_type/1 in auth backends

- big_tests/tests/mam_SUITE.erl
- src/jlib.erl
- src/mam/mod_mam_muc.erl
According to [XEP-0313](https://xmpp.org/extensions/attic/xep-0313-0.4.1.html#sect-idp1586112) the 'to' attribute of the forwarded stanza MUST be empty.
However, Smack fails to parse archived MUC messages with 'to'.
> Remove the empty 'to' attribute from archived MUC messages

- Makefile
- tools/xep_tool/xep_tool.escript
In order to answer #2251.
I don't know why, but following https://mongooseim.readthedocs.io/en/latest/developers-guide/xep_tool/ showed that the procedure to run `make xeplist` or even `escript tools/xep_tool/xep_tool.escript markdown _build/default/lib/mongooseim/ebin/` does not work. After the changes it works for me, but it would be good if somebody else could also try it. Works for me on Erlang 21.3.
> Fix xeplist Makefile rule and xep_tool escript

- doc/modules/mod_pubsub.md
This PR addresses fixes `last_item_cache` description in PubSub doc page. It was inconsistent and suggested that it's a boolean value.
> Update inconsistent PubSub cache doc

- big_tests/tests/gdpr_SUITE.erl
- priv/parse_logs.sh
- src/admin_extra/service_admin_extra_gdpr.erl
- src/ejabberd_config.erl
- src/ejabberd_ctl.erl
- src/ejabberd_loglevel.erl
currently **get_logs_from_node/4** receives zipped logs from other nodes as rpc call return value. as agreed that is ok for the first version, if logs are too big this should be changed to some other delivery method (e.g. FTP) 
for testing run:
```
tools/test-runner.sh --db --preset internal_mnesia --skip-small-tests --skip-cover -- gdpr:retrieve_personal_data:retrieve_logs
```
> gdpr logs collection

- big_tests/tests/ejabberdctl_SUITE.erl
- doc/user-guide/Getting-started.md
- doc/user-guide/ICE_tutorial.md
- doc/user-guide/Jingle-SIP-setup.md
- src/ejabberd_admin.erl
This PR modifies `register` command in the cli as well as adds `register_identified` command.
`register` - it no longer accepts username argument and instead generates random and monotonic user uid.
`register_identified` - it behaves the same way as `register` used to behave.
TODO:
> Register command with automatic jid creation

- big_tests/tests/gdpr_SUITE.erl
- src/admin_extra/service_admin_extra_gdpr.erl
- src/mod_vcard.erl
- src/mongoose_lib.erl
- src/pubsub/mod_pubsub.erl
This PR replaces hardcoded GDPR modules list with a dynamic lookup. It also changes the retrieval implementations to query all module backends.
> Dynamic lookup of GDPR-related modules for retrieval

- big_tests/tests/gdpr_SUITE.erl
- src/mod_private.erl
- src/mod_private_mnesia.erl
- src/mod_private_mysql.erl
- src/mod_private_rdbms.erl
- src/mod_private_riak.erl
- src/rdbms/rdbms_queries.erl
This PR retrieves personal data from mod_private
implement `get_all_nss/2` callback for:
> Gdpr retrieve personal data from mod_private

- big_tests/tests/gdpr_SUITE.erl
In one of pubsub retrieval test, vcard was being disabled instead of pubsub
> Gdpr retrieve pubsub - fix

- big_tests/tests/gdpr_SUITE.erl
- include/mod_inbox.hrl
- src/inbox/mod_inbox.erl
- src/inbox/mod_inbox_rdbms.erl
This PR supersedes #2282
It adds personal data retrieval from inbox.
> GDPR retrieve inbox (clean)

- big_tests/tests/gdpr_SUITE.erl
- src/mod_offline.erl
- src/mod_offline_mnesia.erl
- src/mod_offline_rdbms.erl
- src/mod_offline_riak.erl
- src/rdbms/rdbms_queries.erl
This PR addresses https://erlangsolutions.atlassian.net/browse/MIM-306
TODO:
Notes:
- Timestamp is in format of utc datetime, eg:
`2019-04-29T11:03:21Z`
> Gdpr retrieve data from mod_offline

- big_tests/tests/inbox_SUITE.erl
- src/inbox/mod_inbox.erl
If messages from inbox are sent to bare jid, then if a requestor has another connection open at the same time with higher priority, then he is going to receive iq result, but messages would go to the other connection. This PR fixes it and adds a regression test.
> send messages from inbox directly to the requesting resource

- tools/ssl/Makefile
Speed up tests on travis a little bit.
Comparing "cd tools/ssl && time make"
Before:
make  10.26s user 0.13s system 99% cpu 10.487 total
After:
make  5.46s user 0.10s system 98% cpu 5.625 total
> Use dsaparam argument when generating DH parameters to speed up generation

- doc/developers-guide/Basic-iq-handler.md
`mod_iq_handler` is now loaded within the `init_per_suite` function and unloaded on the `end_per_suite` function, avoiding having to do so manually on the shell.
And a typo was corrected, in `should_return_error` it should call `alice_bis`.
> [skip ci] Basic IQ Handler tutorial automates Common Test.

- big_tests/tests/gdpr_SUITE.erl
- big_tests/tests/muc_light_SUITE.erl
- big_tests/tests/muc_light_helper.erl
- src/mod_roster.erl
> Try to stabilize rooms for rosters

- big_tests/tests/gdpr_SUITE.erl
- src/mod_private.erl
This PR addresses MIM-338
https://erlangsolutions.atlassian.net/browse/MIM-338
Remove data from mod_private
* add test for removal of data from mod_private
> Add test for GDPR removal of data from mod_private

- big_tests/tests/gdpr_SUITE.erl
- src/inbox/mod_inbox.erl
> Remove personal data from mod_inbox

- big_tests/tests/rest_client_SUITE.erl
- big_tests/tests/rest_helper.erl
- doc/Advanced-configuration.md
- rel/files/mongooseim.cfg
- rel/mim2.vars.config
- src/config/mongoose_config_parser.erl
- src/ejabberd_cowboy.erl
- test/commands_backend_SUITE.erl
- test/mod_websockets_SUITE.erl
This PR adds `cowboy_server_name` config option, which sets the reported HTTP server name in response headers. It may be used for hardening MIM (by hiding Cowboy's identity).
> Add option to modify Cowboy server name returned in headers

- rel/files/mongooseim.cfg
- src/admin_extra/service_admin_extra.erl
- src/mongoose_lib.erl
- src/service_cache.erl
- test/mam_jid_mini_SUITE.erl
tested manually:
- build and run MIM:
```
make rel
_build/prod/rel/mongooseim/bin/mongooseim live
```
- run `mongoose_lid:find_behaviour_implementations/1` few times, notice dramatic decrease of execution time:
```
timer:tc(mongoose_lib, find_behaviour_implementations, [mongoose_service]).
timer:tc(mongoose_lib, find_behaviour_implementations, [mongoose_service]).
timer:tc(mongoose_lib, find_behaviour_implementations, [mongoose_service]).
```
- disable `service_cache` and repeat the test:
```
mongoose_service:stop_service(service_cache).
timer:tc(mongoose_lib, find_behaviour_implementations, [mongoose_service]).
timer:tc(mongoose_lib, find_behaviour_implementations, [mongoose_service]).
```
- re-enable `service_cache` and repeat the test:
``` …
```
> Cache found behaviour implementations

- big_tests/tests/gdpr_SUITE.erl
- big_tests/tests/mam_SUITE.erl
- big_tests/tests/muc_SUITE.erl
- big_tests/tests/muc_helper.erl
- big_tests/tests/rest_helper.erl
- priv/cassandra.cql
- priv/elasticsearch/muc.json
- rel/files/mongooseim.cfg
- src/admin_extra/service_admin_extra.erl
- src/mam/mod_mam_meta.erl
- src/mam/mod_mam_muc.erl
- src/mam/mod_mam_muc_cassandra_arch.erl
- src/mam/mod_mam_muc_elasticsearch_arch.erl
- src/mam/mod_mam_rdbms_arch.erl
- src/mam/mod_mam_riak_timed_arch_yz.erl
- src/mongoose_lib.erl
- src/service_cache.erl
- test/mam_jid_mini_SUITE.erl
- test/mod_mam_meta_SUITE.erl
- test/roster_SUITE.erl
> DB schema rework for GDPR MAM MUC retrieval 

- big_tests/tests/gdpr_SUITE.erl
- big_tests/tests/mam_SUITE.erl
- big_tests/tests/mam_helper.erl
- big_tests/tests/muc_SUITE.erl
- doc/migrations/3.3.0_3.3.0plus.md
- mkdocs.yml
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- src/mam/mod_mam_meta.erl
- src/mam/mod_mam_muc.erl
- src/mam/mod_mam_muc_rdbms_arch.erl
- src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
- src/mam/mod_mam_rdbms_arch.erl
- src/mam/mod_mam_rdbms_user.erl
- test/mod_mam_meta_SUITE.erl
This PR adds new column to `mam_muc_message` table in RDBMS, which is required for GDPR retrieval to work efficiently.
> Add sender_id to mam_muc_message RDBMS table

- .travis.yml
- big_tests/test.config
- big_tests/tests/rdbms_SUITE.erl
- doc/advanced-configuration/outgoing-connections.md
- tools/ssl/openssl-mongooseim.cnf
This PR abandons OTP 19 and changes Travis jobs to OTP 20. It also fixes issue with  distributed TLS and MongooseIMs connecting fail due to adding http://erlang.org/doc/man/public_key.html#pkix_verify_hostname-2 to `ssl:connect/2,3`.
> Fix tls erlang 20 issue

- big_tests/tests/gdpr_SUITE.erl
- src/mam/mod_mam_riak_timed_arch_yz.erl
- tools/mam_search_schema.xml
There are two new fields that are indexed in Riak schema:
* `owner_jid` - (essentially JID of person that "owns" a
message - for PM that's all messages that include this person,
for MUC those are all messages that were sent by this person).
* `mam_type` - we store information about what MAM module has been used
to save the message. This is not "really" necessary, as we could
filter messages for GDPR outside database, or prepare different GDPR
implementations for PM and MUC, but this would result in either
slower or more complicated code.
The implementation of GDPR for `mod_mam` / `mod_mam_muc` on Riak is now
the same - there are no real differences between those two, other then
`mam_type` field in the query.
This PR closes #2330 as the solution here is effectively alternative approach to …
> GDPR data retrival for mod_mam_muc @ Riak DBMS

- doc/migrations/3.3.0_3.3.0plus.md
- doc/migrations/jid-from-mam-muc-script.md
- test/migration_scripts_SUITE.erl
- tools/migration/sender-jid-from-mam-message.escript
* `3.3.0_3.3.0plus.md` has been modified by adding migration
guide for Riak @ MIM 3.3.0+
* `jid-from-mam-muc-script.md` has been modified reflect the changes
made to `sender-jid-from-mam-message.escript` script
* `sender-jid-from-mam-message.escript` script has been changed so that
it returns `-2\n` when the given stanza is not a correct MUC message.
> Add migration instructions for Riak @ MIM 3.3.0+

- big_tests/rebar.config
- big_tests/rebar.lock
This PR addresses updates escalus reference to the most recent master in order to verify if we can tag it with new version number.
> Escalus update before the release

- doc/migrations/3.3.0_3.3.0plus.md
- test/mam_jid_mini_SUITE.erl
- test/migration_scripts_SUITE.erl
- tools/migration/sender-jid-from-mam-message.escript
```bash
source tools/test-runner-complete.sh 
git checkout a41c96c42 ##some commit before elasticsearch schema update
test-runner.sh --db elasticsearch --preset elasticsearch_and_cassandra_mnesia --one-node --skip-small-tests --skip-cover  --skip-stop-nodes -- mam gdpr
tools/stop-nodes.sh 
curl -sX GET "localhost:9200/muc_messages/_mapping/"  | jq
##update mapping
curl -sX PUT "localhost:9200/muc_messages/_mapping/muc" -w ' {"status": "%{http_code}"}' -d'
{
"properties": {
"mam_id": {
"type": "long"
},
"room": {
"type": "keyword"
},
"from_jid" : {
"type": "keyword"
},
"source_jid": {
"type": "keyword"
},
"message": {
"type": "text",
"index": false
},
"body": {
"type": "text",
"analyzer": "english"
}
}
}' | jq
curl -sX GET "localhost:9200/muc_messages/_mapping/"  | jq
git checkout …
```
> Elasticsearch GDPR migration guide.

- doc/advanced-configuration/Services.md
> Service cache docs

- big_tests/tests/gdpr_SUITE.erl
- big_tests/tests/pubsub_tools.erl
- src/pubsub/gen_pubsub_node.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/mod_pubsub_db_rdbms.erl
- src/pubsub/mod_pubsub_db_rdbms_sql.erl
- src/pubsub/node_flat.erl
- src/pubsub/node_pep.erl
- src/pubsub/node_push.erl
- src/pubsub/pubsub_index.erl
Tests by @NelsonVides and @ludwikbukowski
This PR is an alternative implementation for #2348
> Add GDPR removal for pubsub (alternative)

- big_tests/tests/metrics_api_SUITE.erl
- doc/operation-and-maintenance/Mongoose-metrics.md
- src/mongoose_metrics.erl
- src/mongoose_metrics_definitions.hrl
This PR addresses **MIM-261**.
I have some doubts regarding this line: https://github.com/esl/MongooseIM/compare/add-cluster-state-metric?expand=1#diff-54e29ccb6566fec2bcf8aad705f9d93eR83, specifically this `tagged` atom. Do you know what it exactly does?
TODO:
* ~~update documentation~~
> Add `clusterState` metric

- big_tests/Makefile
This is a quickfix to a problem that I had while testing `metrics_api_SUITE`, for which @chrzaszcz got a solution. First of all the `pwd/ebin` folder does not exist, and second, tons of `{error, enoent}` were thrown because the paths were given in the wrong order and couldn't find what it was looking for. In my case it was the `*_data/` folders inside of `tests/`, which should have been the first folder in the _path_ (note that `-pa` appends the given paths one by one, hence, they end up kinda reverted in the _path_).
People might remember me complaining on our slack channel that I had to `rebar3 clean | make clean | git clean -fdx | git unicorn-blood | universe restart` to get the tests working again.
> Fix 'make console' for big tests

- .gitignore
This thing was not added to gitignore and it gets a bit annoying to have git all the time telling me there's an untracked file and having to be careful not to add it accidentally and ahh... Just gitignore it!
> reg*.log added to gitignore

- big_tests/tests/muc_helper.erl
- big_tests/tests/muc_light_helper.erl
- src/muc_light/mod_muc_light_codec_legacy.erl
- src/muc_light/mod_muc_light_codec_modern.erl
- src/muc_light/mod_muc_light_utils.erl
- test/muc_light_SUITE.erl
`x` element archived with MUC Light messages (to ensure compatibility with MAM spec) "spoofs" MUC role. However, this was set to the same value as affiliation, effectively breaking communication with Smack. With this PR, the role is spoofed correctly.
> Fix MUC Light "role" archived in MAM

- tools/circleci-upload-to-s3.sh
Use `s3-parallel-put` tool for uploading logs to S3 (currently our Travis uses it as well).
Speeds up whole build for 1-2 minutes
> CircleCI parallel logs upload

- big_tests/tests/pubsub_tools.erl
Hometree consideres the character "/" as a path divider. When pubsub_node() creates a random name, it can indeed use this character, and hence randomly make hometree consider the path longer than expected and hence returning an auth failure.
> Fix hometree_specific group

- big_tests/tests/mod_global_distrib_SUITE.erl
First issue:
After sending initial presence to the server's we were not waiting till it is sent back the the client.
Solving the above issue makes the race condition described below even MORE unlikely to happen.
Still, `mod_global_distrib` does not support the feature which is tested in `test_pm_with_ungraceful_reconnection_to_different_server`  and it (the feature) is not trivial to implement. 
When race condition happens:
1. Eve’s process is killed on cluster 1.
2. Alice sends a message to Eve.
3. Eve connects to cluster 2. Entry in Redis from C1 is overwritten by C2.
4. The session/routing table is refreshed on C1. Since Eve’s session is still present there, entry from C2 is overwritten by C1.
5. The message is not delivered to C2, as it is supposed to (it goes to C1 instead).
It fails …
> "fix" test in global_distrib_SUITE

- big_tests/tests/connect_SUITE.erl
- doc/Advanced-configuration.md
- doc/advanced-configuration/Listener-modules.md
- doc/advanced-configuration/TLS-hardening.md
- doc/modules/mod_global_distrib.md
- doc/user-guide/ICE_tutorial/mongooseim.cfg
- mkdocs.yml
- rel/fed1.vars.config
- rel/files/app.config
- rel/files/mongooseim.cfg
- rel/files/mongooseim.cfg.token-support
- rel/mim2.vars.config
- rel/mim3.vars.config
- rel/reg1.vars.config
- src/ejabberd_socket.erl
- src/ejabberd_tls.erl
- src/global_distrib/mod_global_distrib_transport.erl
- test/cowboy_SUITE_data/mongooseim.onlyhttp.cfg
- test/cowboy_SUITE_data/mongooseim.onlyws.cfg
- test/ejabberd_config_SUITE_data/mongooseim.default.cfg
- test/ejabberd_config_SUITE_data/mongooseim.split.cfg
- test/ejabberd_config_SUITE_data/mongooseim.with_mod_offline.cfg
- test/ejabberd_config_SUITE_data/mongooseim.with_mod_offline.different_opts.cfg
- test/revproxy_SUITE_data/mongooseim.norules.cfg
- test/revproxy_SUITE_data/mongooseim.onerule.cfg
Due to known vulnerabilities in 1.0 and 1.1.
> Deprecate TLS older than 1.2

- big_tests/rebar.config
- big_tests/rebar.lock
Expand tcp_closed_timeout in escalus so that the system receives the `tcp_closed` message in time.
> Solve mam_SUITE tcp_closed_timeout issue

- src/auth/ejabberd_auth.erl
- src/auth/ejabberd_auth_http.erl
- src/auth/ejabberd_auth_internal.erl
- src/auth/ejabberd_auth_rdbms.erl
- src/auth/ejabberd_auth_riak.erl
- src/mongoose_scram.erl
- src/sasl/cyrsasl_scram.erl
- test/auth_http_SUITE.erl
There are two _different_ scram modules:
in mongooseim - https://github.com/esl/MongooseIM/blob/8e0d3e2d35f73921ec7d2343ceb803b091bc781a/src/scram.erl
in escalus - https://github.com/esl/escalus/blob/master/src/scram.erl
Which cause conflicts, if you try to load escalus into mongooseim.
As a developer, I want to resolve name conflict.
(it blocks compilation of cover modules, done from the CT node)
> Rename scram to mongoose_scram to avoid name clashes with escalus

- big_tests/run_common_test.erl
- rebar.config
* Properly detect ct_run directory in run_common_test
* Let cover to handle compiling and loading coverage once on all nodes
after: Cover compilation took 27.896 seconds
before: Cover compilation took 168.034 seconds (Also Cover compilation took 103.721 seconds)
There should be no modules with the same name used both in mim and tests.
Otherwise  similar errors are possible: https://github.com/arcusfelis/MongooseIM/pull/53#issuecomment-519278689 (it's without renaming scram module)
It also fixes elasticsearch job failing issue https://travis-ci.org/arcusfelis/MongooseIM/builds/569276362
> Compile cover once

- rel/fed1.vars.config
- rel/files/vm.args
- rel/mim1.vars.config
- rel/mim2.vars.config
- rel/mim3.vars.config
- rel/reg1.vars.config
- rel/vars.config.in
Disable high-performance, high-memory usage Erlang VM options for dev builds
This PR addresses high memory usage of dev mongooseim VMs and slow start.
* less memory usage by tweaking vm-args.
> Reduce memory usage for dev MongooseIM VMs

- big_tests/src/ct_markdown_errors_hook.erl
- tools/travis-test.sh
This PR addresses:
old version of ct_markdown_errors_hook does not include all groups.
mam_SUITE uses a lot of subgroups.
* properly handle groups - show complete testcase paths
* create summary_file with failed tests, so we can use this one to restart tests (done separately)
Let's compare testcase format before and after:
before: mam_SUITE:muc_rsm04:pagination_simple_before10
after: mam_SUITE:rdbms_async_pool_muc_all:muc_rsm_all:muc_rsm04:pagination_simple_before10
> Improve ct_markdown_errors hook

- tools/silent_exec.sh
tee was always returning 0
This PR addresses:
Before:
```
~/erlang/mim_july|master $ VERBOSE=1 ./tools/silent_exec.sh cat nonono
RUN: nonono
LOG: /Users/mikhailuvarov/erlang/mim_july/cat
./tools/silent_exec.sh: line 31: nonono: command not found
~/erlang/mim_july|master $ echo "$?"
0 # This is wrooong
~/erlang/mim_july|master $ VERBOSE=0 ./tools/silent_exec.sh cat nonono
RUN: nonono
LOG: /Users/mikhailuvarov/erlang/mim_july/cat
./tools/silent_exec.sh: line 33: nonono: command not found
~/erlang/mim_july|master $ echo "$?"
1
```
After:
```
VERBOSE=1 ./tools/silent_exec.sh cat nonono
RUN: nonono
LOG: /Users/mikhailuvarov/erlang/mim_july/cat
./tools/silent_exec.sh: line 38: nonono: command not found
~/erlang/mim_july|fix-exit-code-handling-in-silent-exec $ echo "$?"
127
```
> Fix error handling in silent_exec when VERBOSE=1

- .circleci/config.yml
- We can run small tests and big tests in parallel. It makes more sense assuming we will not have limit for concurrent jobs, hopefully soon
We can **save up to 8 mins** for whole build
- Run dialyzer parallel to builds. It doesnt need releases installed. Not saving total time but we can know faster if the specs are broken
> CircleCI parallel small tests

- test/ejabberd_sm_SUITE.erl
The old way would not work, if redis is running in docker
* Use eredis_client instead of ps to check if redis is running
> Properly detect that redis is not running in ejabberd_sm_SUITE

- test/mongoose_wpool_SUITE.erl
This PR addresses error in mongoose_wpool_SUITE.
The changes include:
* properly handle missing worker processes (i.e. whereis returns undefined).
> Fix undefined pid error in dead_pool_is_restarted

- .circleci/config.yml
Due to error that happens:
```
<h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>
```
We should just ignore that error
> Always return success status code for sending codecov in CircleCI

- .travis.yml
- tools/cache-build.sh
- tools/cache-certs.sh
- tools/cache-tests.sh
This PR addresses "we don't need to recompile deps each build".
* Cache binaries of deps based on hash of our configs
* Each job has its own cache
* We would assume, that job uses cache of a parent
* Allow full builds during crons to detect possible problems with missing deps, for example
* Changes in rebar.config or rebar.lock would invalidate cache
> Cache built deps

- .travis.yml
- tools/travis-pull-db.sh
This PR addresses "build parallelization".
* while we compiling, we can also pull database images.
* rabbitmq is not handled. Planning to do it after moving code for ldap, redis and rabbit into travis-setup-db as a separate step
* Do magic in a separate `tools/travis-pull-db.sh`, because doing it in setup-db would make that script even more unfriendly.
> Pull database images in parallel with compiling on Travis

- .circleci/config.yml
- .travis.yml
- big_tests/default.spec
- big_tests/mam.spec
- big_tests/run_common_test.erl
- big_tests/src/ct_mim_config_hook.erl
- big_tests/tests/acc_e2e_SUITE.erl
- big_tests/tests/ejabberdctl_SUITE.erl
- big_tests/tests/katt_helper.erl
- big_tests/tests/path_helper.erl
- big_tests/tests/sasl_external_SUITE.erl
This PR speeds up compilation by allowing travis to use test files, already compiled by rebar3.
* SKIP_AUTO_COMPILE=true variable to tell ct to not compile anything
* some linking and copying (because ct and rebar don't like each other haha).
> Don't compile tests twice on CI

- .circleci/config.yml
- .travis.yml
- tools/test-runner.sh
This PR changes the versions matrix to follow these rules:
* Use OTP 22 for almost everything
* Use OTP 20 and 21 for one preset each
* Execute small tests for 20, 21 and 22
I've decided to run everything on OTP 22 except for `ldap_mnesia` (OTP 20.3) and `pgsql_mnesia` (OTP 21.3). The choice is pretty much arbitrary.
> Update OTP versions matrix for Travis and CircleCI

- .travis.yml
This PR is a follow up to #2421. In the previous PR the small tests weren't executed for OTP 21.3 and executed twice on OTP 22.
> Fix .travis.yml to execute small tests both on OTP 22 and 21

- big_tests/default.spec
I saw it disabled in our test environment, basically by not being written to big_tests/default.spec. I checked several master builds on aws and it’s not on the reports either, so I’m pretty confident it’s just never ran. Tested in on my fork and it’s all green. On the git history I haven’t found any place where it was added and then removed from default.spec. So let's just add it there.
> add pubsub_s2s_SUITE to default.spec

- .circleci/config.yml
Don't `apt-get update` twice in CircleCI config.
PS. Seems that recently `apt-get update` hangs too long (4 minutes) because of that issue:
https://askubuntu.com/questions/574569/apt-get-stuck-at-0-connecting-to-us-archive-ubuntu-com
If its not temporal issue, some hack fix needs to be added
> CircleCI install packages order

- big_tests/tests/pubsub_SUITE.erl
Certain groups are placed in sequence because they run a heavier set of tests, which in parallel might cause deadlocks in the transactions for MNESIA and MYSQL.
TODO: Optimise pubsub backends (MYSQL! Mnesia?)
NOTE: the suite used to take 20-25s, now it's closer to 50s 😞
> [CI] pubsub: run bigger groups in sequence and not in parallel

- big_tests/tests/muc_light_SUITE.erl
- src/mod_disco.erl
This PR addresses #2353.
This adds support in `mod_disco:is_presence_subscribed` for the `jid:jid()` format used by rooms when MUC Light `rooms_in_rosters` is enabled.
> Fix user disco#info when rooms_in_rosters enabled

- big_tests/tests/rest_SUITE.erl
- src/mongoose_api_admin.erl
- src/mongoose_api_client.erl
- src/mongoose_commands.erl
This PR fixes #2278
Commands in REST weren't filtered by subcategory, so for any two commands with the same method and category but different subcategories, the handler will crash and return 500 error.
Tests that would have detected the problem were for some reason disabled.
> Filter REST commands by subcategory as well

- .circleci/config.yml
- .travis.yml
- tools/build-releases.sh
- tools/circle-build-and-push-docker.sh
This PR changes following stuff:
1. Renames `otp` parameter in many of Circle jobs to `otp_package` because it's more accurate actually.
2. Adds an optional step to build prod release in `build` job. It's faster to create it preemptively than do it in Docker job
3. Adds `docker_image` job to CircleCI, which builds and pushes an image based on OTP 22.0 prod build.
4. Adds `docker_build_and_ship` workflow that is executed when all other jobs are successful (except for packaging jobs).
5. Travis no longer builds and pushes Docker images
6. Commit hash is now the default image tag, instead of branch name
7. PR number is extracted from PR URL, because Circle doesn't provide an env. var. with the number.
8. Logic for special tags of cron jobs is temporarily disabled until we add cron builds to …
> Switch Docker image build to CircleCI

- big_tests/tests/push_integration_SUITE.erl
- big_tests/tests/push_pubsub_SUITE.erl
- doc/user-guide/Push-notifications.md
- src/pubsub/node_push.erl
This PR checks if push node configuration takes effect
* fixed affiliation checking in node_push
* push_integration_SUITE now always creates push node with the following configuration:
* `access_model` -> `whitelist`
* `publish_model` -> `publishers`
> Pubsub push node improvements

- .circleci/config.yml
- Makefile
- README.md
- doc/index.md
- rebar.config
- rebar.config.script
This PR addresses re-enables coverage reporting from small tests. It also removes integration with coveralls which was broken since Jun.
> Send coverage report from small tests job

- src/auth/ejabberd_auth_jwt.erl
- src/ejabberd_zlib.erl
- src/mod_auth_token.erl
- src/mod_blocking.erl
- src/mod_commands.erl
- src/mod_muc_room.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/pubsub_form_utils.erl
This PR replaces usage of `binary_to_atom` or `binary_to_existing_atom` where possible and needed.
> Get rid of binary_to_(existing_)atom

- src/auth/ejabberd_auth_jwt.erl
- src/ejabberd_zlib.erl
- src/mod_auth_token.erl
- src/mod_blocking.erl
- src/mod_commands.erl
- src/mod_muc_room.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/pubsub_form_utils.erl
It is a port of #2444 for the previous release (3.4)
> Explicitly convert binary to atom where possible

- doc/operation-and-maintenance/gdpr-considerations.md
Language check, some articles missing mostly.
On the ` ## Data affected by GDPR commands` section, I just attempted consistency on the usage of the sentence's subject's noun: sometimes it was _user_, some others _client_, and some others _subject_. I went for _subject_ to all of them.
> [skip ci] Language check for GDPR docs

- big_tests/tests/mod_global_distrib_SUITE.erl
If the test fails with the known reason, simply exit the escalus story and return `{skip, Reason}`. This way, we don't get CI in red any more for the known issue, but if it ever fails with a different one, then CI will get red and we will know about it.
Unfortunately, `escalus:story` ignores the return value of the function given, so the only way to move the control flow is by throwing: it exits the function and gives us a "return value".
Yes, this is kicking the ball down the road. But it's there, and we'll have a chance to work on it if we ever need to come back to global distribution.
I also fixed the suite by ~removing the user that is created in the `ungraceful` test, which was not being removed and then leaving the environment dirty; and~ refactoring the tests by moving not relevant …
> mod_global_distrib_SUITE: ignore known failure, fail otherwise

- big_tests/tests/mam_SUITE.erl
- big_tests/tests/mam_helper.erl
- big_tests/tests/mam_helper.hrl
- big_tests/tests/muc_light_helper.erl
- src/mam/mod_mam_meta.erl
- src/mam/mod_mam_muc.erl
This PR fixes chat marker archiving in `mod_mam_muc`
The causes of a problem were:
- `mod_mam_meta` didn't accept `archive_chat_markers` option for `mod_mam_muc`
- `mod_mam_muc` was retrieving aforementioned option improperly
> Fix chat marker archiving in MUC

- tools/circle-build-and-push-docker.sh
This PR updates docker image building scripts so a commit message is passed to MIM dockerfile. The message is attached to an image as a new label.
> Pass a commit msg to MIM dockerfile

- big_tests/tests/mod_global_distrib_SUITE.erl
This PR addresses "Long tests are evil".
* Helper functions
> Simplify mod_global_distrib_SUITE:multi_connection:test_muc_conversation_history

- priv/mssql2012.sql
- tools/setup-mssql-database.sh
- tools/setup-redis.sh
- tools/setup_riak
- tools/setup_riak.escript
- tools/ssl/Makefile
- tools/travis-common-vars.sh
- tools/travis-setup-db.sh
- tools/travis-setup-ldap.sh
- tools/wait_for_service.sh
This PR addresses "some tweaks".
* Move some code into tools/setup-mssql-database.sh to allow calling it separately, when needed
* Remove unused stuff from mssql schema
* Rewrite setup_riak script into erlang (because it's faaaster)
* `-dsaparam` optimization goes away :( (but we cache certs anyway, so...).
* But we improve starting time of ldap container, because we don't need to generate dh pair (we reuse mongooseim pair).
* Fix a bug with path calculation, allowing to run start_setup_db from any directory
* `docker rm` removes volumes now (finally)
* Make database ports configurable using env variables (we don't use the feature yet)
* Use `docker exec` to setup cassandra schemas (speedup)
* Remove "docker -i" attribute (to allow to run from non-interactive …
> Improve setup db script

- big_tests/tests/cluster_commands_SUITE.erl
* Ensure passwd table created in cluster_commands_SUITE for two nodes - currently, we don't see the issue, because we always start with internal auth enabled (and after we apply preset with other auth type). But the tests would fail, if we apply preset before starting mongooseim.
* Add leave_using_rpc testcase.
> Improve cluster commands suite

- .circleci/config.yml
This PR addresses 
```
Reading package lists... Done
W: Failed to fetch http://ftp.heanet.ie/pub/ubuntu/dists/xenial/InRelease  Could not resolve 'ftp.heanet.ie'
W: Failed to fetch http://ftp.heanet.ie/pub/ubuntu/dists/xenial-updates/InRelease  Could not resolve 'ftp.heanet.ie'
W: Failed to fetch http://ftp.heanet.ie/pub/ubuntu/dists/xenial-backports/InRelease  Could not resolve 'ftp.heanet.ie'
W: Failed to fetch http://ftp.heanet.ie/pub/ubuntu/dists/xenial-security/InRelease  Could not resolve 'ftp.heanet.ie'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
> Use Acquire::ForceIPv4 with default ubuntu repositories

- doc/modules/mod_mam.md
- src/mam/mod_mam_utils.erl
This PR adds a deprecation message when MAM 0.3 request is received from a client.
It also adds a note to MAM documentation about the supported versions.
*EDIT:* Deprecation message may be seen in https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/2466/5113/elasticsearch_and_cassandra_mnesia.2207/logs/2019-09-20_10.34.24/mim1/log/ejabberd.log
> Deprecate MAM 0.3

- big_tests/test.config
- big_tests/tests/mod_global_distrib_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- src/global_distrib/mod_global_distrib_mapping_redis.erl
This PR addresses error in mod_global_distrib_SUITE:mod_global_distrib:test_pm_with_graceful_reconnection_to_different_server
TLDR:
- escalus_connection:stop(Eve) is async
- the message is delivered to Eve, not NewEve.
* Otherwise timeout waiting for SecondFromAlice message
* Remove old hot fix
TODO:
```erlang
{test_pm_with_graceful_reconnection_to_different_server,mod_global_distrib}
{timeout_when_waiting_for_stanza,
[{escalus_client,wait_for_stanza,
[{client,<<"eve81.429937@localhost/res1">>,escalus_tcp,<0.22576.0>,
[{event_manager,<0.22569.0>},
{server,<<"localhost">>},
{username,<<"eve81.429937">>},
{resource,<<"res1">>}],
[{event_client,
[{event_manager,<0.22569.0>},
{server,<<"localhost">>},
{username,<<"eve81.429937">>},
{resource,<<"res1">>}]}, …
```
> Ensure that process is stopped in mod_global_distrib_SUITE:test_pm_with_graceful_reconnection_to_different_server

- doc/developers-guide/OpenSSL-and-FIPS.md
- doc/modules/mod_jingle_sip.md
- doc/operation-and-maintenance/known-issues.md
- doc/user-guide/How-to-build.md
- rebar.config
- src/ejabberd_app.erl
This PR adds deprecation warning for OTP < 21.2 and updates documentation accordingly.
No tests added as IMO it's sufficient to verify on CI that the warning is shown on OTP 20.3 and not in the other jobs.
> Deprecate OTPs older than 21.2

- big_tests/tests/accounts_SUITE.erl
This PR makes the test accounts_SUITE:null_password more robust by using an user with a random name.
> Use fresh user in accounts_SUITE:null_password

- big_tests/tests/inbox_helper.erl
- src/ejabberd_c2s.erl
This PR removes XMLNS stripping in ejabberd_c2s, as there are no clear reasons why we do it and it makes some clients sad.
The stripping code dates back to 2006, quite likely it is no longer valid.
> Remove XMLNS strip in ejabberd_c2s

- doc/advanced-configuration/Listener-modules.md
Fixes documentation about `mongoose_api_admin` authorization. The example given does not work, User and Password need to be binaries.
* Make explicit that User and Password are binaries by using << >> in the example given.
> fix docs about mongoose_api_admin authorization

- CHANGELOG.md
- doc/Advanced-configuration.md
- doc/operation-and-maintenance/Mongoose-metrics.md
I found typo in word "RDBMS" when reading docs, so I corrected the typo across the whole project.
> Fix rdbms typo

- doc/user-guide/Getting-started.md
There is a need for a carriage return on ReadTheDocs, forgot that, sorry...
> [skip ci] Lists are inline

- src/mod_websockets.erl
- test/mod_websockets_SUITE.erl
This fixes a bug introduced when upgrading to `cowboy` 2.x. The connection timeout stopped working as the way it's set changed.
> WebSocket idle timeout

- big_tests/tests/push_integration_SUITE.erl
- src/inbox/mod_inbox.erl
- src/inbox/mod_inbox_rdbms.erl
- src/inbox/mod_inbox_utils.erl
This PR fixes the unread count retrieval in a conversation for the push notifications logic.
The root cause was insufficient filtering in the SQL query.
TBH now I see that we really lack proper docs with examples for this feature. And also I think that it would be more useful to return total unread count for all conversations, as this is what is usually displayed on the app badge.
However, the PgSQL-specific logic implies that the code is supposed to return unread count for the conversation, not the sum for all of them, so this is the approach taken in this PR.
> Fix inbox unread count retrieval for push notifications

- .circleci/config.yml
- tools/circle-build-and-push-docker.sh
Adding tags to MIM did not trigger builds on CircleCI, which gave unwanted results such as no Docker image for 3.5.0 on dockerhub.
I added filters which should not affect normal builds, but also run all jobs when CircleCI sees that a new tag was added.
Maybe there is a more elegant way to do it, this copy-paste approach is a quick fix, perhaps someone more experienced with yml/CircleCI can take a look. I hope proposed changes really don't brake our CI, as I tested on a fork of MIM.
Some links with additional information:
[CircleCI docs](https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag)
[Similar problem](https://discuss.circleci.com/t/can-you-filter-on-a-workflow-level/30624/5)
> Run builds on CircleCi when adding tags

- big_tests/test.config
- big_tests/tests/ct_helper.erl
This function was first of all overwriting any other repeat type given
to common test, so when doing for example, CI stabilization, if I wanted
to do a `{repeat_until_any_fail,10000}` just so to see it never failing, I
always had to remove the call to repeat_all_until_all_ok, which was
redundant, and confusing when staging only the selected changes.
This PR pretty much doesn't change the interface of common_tests, but it
curates this misbehaviour. It also prevents us from not giving a limit
to the repeats (like giving `repeat_until_all_ok` instead of
`{repeat_until_all_ok,100}`), which would then run foreveeeer. This
limit is configured in test.config.
> Curate ct_helper:repeat_all_until_all_ok

- doc/operation-and-maintenance/Mongoose-metrics.md
I broke that markdown table when I put line separators 😛 
Bad markdown, bad. That's not consistent with your philosophy of considering _two_ new lines as a line separator. Evil markdown.
> [skip ci] Make sure it stays in one line

- .travis.yml
- tools/travis-upload-to-gdrive.sh
This PR addresses "I've finally started uploading test results to gdrive in my fork!".
* Better error reporting for tools/travis-upload-to-gdrive.sh
* Print information about uploaded file
* Cache gdrive uploader
Prints:
```erlang
then tools/travis-upload-to-gdrive.sh; fi
tools/travis-upload-to-gdrive.sh: line 31: hash: gdrive: not found
Uploading test results to google drive
gdrive_get_id PARENT_ID=root
gdrive_get_id PARENT_ID=1h8uOvEBq0k75bdlZ2KB4-RMqu0le0HPs
gdrive_get_id PARENT_ID=1l8qkKsPsg24TOAdQEiwAAyDA0Vrb6OkY
CT_REPORTS_PATH=PR/67/729/internal_mnesia.22.0
Uploading /tmp/internal_mnesia.22.0.tar.gz
Uploaded 1xD_bjDzbZhUIhJCKW5Kh3BPmDIgs7Bnp at 221.1 KB/s, total 2.5 MB
gdrive_get_id PARENT_ID=1QWhQpVAqL_HjLRzkqCbrwGbhEz31r3qW
Uploaded with …
```
> Better error reporting for tools/travis-upload-to-gdrive.sh

- big_tests/tests/sm_SUITE.erl
- src/ejabberd_c2s.erl
- test/ejabberd_c2s_SUITE_mocks.erl
If `mod_stream_management` is disabled, the session shouldn't crash if it requests so. Rather, the server should simply respond with a`service-unavailable` and continue.
Currently, as the code for stream management is mostly hardcoded in ejabberd_c2s, if the client sends the `<<"enable">>` stanza, the server goes nuts:
https://github.com/esl/MongooseIM/blob/1fa0898d6901549e5df5a646dcbd95a7c05b9e7d/src/ejabberd_c2s.erl#L2737-L2749
If the user requests stream management without resumption, the server answers with a nonsensical `<<"enabled">>` and continues as if nothing happened, until it crashes, and if the client requests so but _with_ resumption, then his c2s process fails fast.
TODO:
> Disabled stream mgmt crashes

- .circleci/config.yml
- big_tests/rebar.config
- doc/advanced-configuration/database-backends-configuration.md
- doc/advanced-configuration/outgoing-connections.md
- doc/developers-guide/Testing-MongooseIM.md
- doc/operation-and-maintenance/known-issues.md
- doc/user-guide/How-to-build.md
- rebar.config
- src/ejabberd_app.erl
- test/ejabberd_loglevel_SUITE.erl
This PR removes support for OTP 20.* and older from CircleCI and older OTPs deprecation message.
> Remove otp 20 from MIM

- big_tests/tests/connect_SUITE.erl
- doc/Advanced-configuration.md
- src/ejabberd_c2s.erl
This PR adds a new option, that allows to hide XMPP service type when a client purposefully sends malformed data to XMPP socket. With `hide_service_name` option enabled, MongooseIM will simply close the connection instead of acting by the RFC 6120 which obliges the XMPP server to reply with stream error anyway.
> Hide service name option

- big_tests/tests/rest_client_SUITE.erl
- big_tests/tests/rest_helper.erl
- doc/rest-api/Client-frontend_swagger.yml
- src/mongoose_client_api_rooms_messages.erl
This PR adds support for chat markers in rooms' messages endpoint in client API. Similar support for 1-1 messages is out of scope for now.
This is based on #2271, which should be merged first.
> Add chat markers support to room REST API

- doc/advanced-configuration/outgoing-connections.md
- src/wpool/mongoose_wpool.erl
- src/wpool/mongoose_wpool_redis.erl
- src/wpool/mongoose_wpool_riak.erl
- test/mongoose_wpool_SUITE.erl
This PR addresses #2184
`riak` and `redis` connection pools are not compatible with `available_worker` strategy, because their API needs to get a worker PID from a pool instead of sending request to it. This PR doesn't allow to start these pools with this strategy. It's not a definite solution but at least avoids confusion for now and is pretty short.
A proper solution would improve these pools to work with `available_worker` but it most likely involves adding a proxy process or modifying `worker_pool`.
> Handle available_worker incompatibility

- .travis.yml
- tools/travis-upload-to-gdrive.sh
This PR hot-fixes https://github.com/esl/MongooseIM/pull/2492
* Caching is done before tools/travis-upload-to-gdrive.sh is triggered
* We need to call install_gdrive inside 'install' block
* Cache is working in action here https://travis-ci.org/arcusfelis/MongooseIM/jobs/599611167 - 10 seconds difference
> Actually cache gdrive script on Travis

- big_tests/tests/mam_SUITE.erl
This PR addresses "mam_SUITE related changes".
* Rewrite mam_SUITE:parallel_story/3 to reduce CPU consumption
* We don't send initial presence in the new version
* We were filtering out presences from other stories in the old version on the client
* Handle Riak YZ lag in tests (which leads to rare error like in https://travis-ci.org/arcusfelis/MongooseIM/jobs/599208109)
> Rewrite parallel helper for mam_SUITE

- tools/setup_riak.escript
- tools/travis-setup-db.sh
This PR continues "https://github.com/esl/MongooseIM/pull/2459"
* extend `setup_riak.escript` to configure everything.
* don't use `./tools/setup_riak` anymore :) (less bash). Keep it for poor people, who needs it to configure riak in the real life.
> Add setup_schemas and setup_indexes into tools/setup_riak.escript

- big_tests/tests/muc_SUITE.erl
- big_tests/tests/muc_helper.erl
escalus stanza log does not work for users, connected outside of story.
So, with old code we would not see Alice in logs.
This PR addresses "no Alice in stanza logs".
* helper function `story_with_room` to be used instead of `connect_fresh_user`.
* Create fresh room and all fresh users in one call.
* Less stuff in init_per_testcase.
* In some tests kate is eve for some reason :)
> Add and use muc_helper:story_with_room/4

- src/stream_management/stream_management_stale_h.erl
This PR addresses "sm_SUITE:stale_h:resume_expired_session_returns_correct_h" fails sometimes with stale_h not found in failed resumption stanza.
```erlang
FailedResumption {xmlel,<<“failed”>>,
[{<<“xmlns”>>,<<“urn:xmpp:sm:3”>>}],
[{xmlel,<<“item-not-found”>>,
[{<<“xmlns”>>,
<<“urn:ietf:params:xml:ns:xmpp-stanzas”>>}],
[]}]}
```
Failed test example:
* https://travis-ci.org/arcusfelis/MongooseIM/jobs/601763639#L4477
* Fix cutoff time calculation in removal of old data code.
Logs:
```erlang
2019-10-23 11:18:41.473 [info] <0.11698.0>@ejabberd_c2s:terminate:1540 ({socket_state,gen_tcp,#Port<0.951>,<0.11697.0>}) Close session for alicE18.142936@localhost/escalus-default-resource
2019-10-23 11:18:41.539 [info] <0.11690.0>@stream_management_stale_h:clear_table:129 …
```
> Fix pruning in stream_management_stale_h

- .circleci/config.yml
This is to prevent random failures in uploading test results to S3.
> Upgrade pip after installing it from pkg

- big_tests/tests/sm_SUITE.erl
- src/ejabberd_receiver.erl
Sometimes we get timeout when waiting for stream_end.
For example:
```erlang
----------------------------------------------------
2019-10-16 10:13:34.899
{h_non_given_closes_stream_gracefully,parallel}
{thrown,{timeout,stream_end}}
Testing big_tests.tests.sm_SUITE: *** FAILED test case 15 ***
```
https://travis-ci.org/arcusfelis/MongooseIM/jobs/598572297
This test can fail, because we just hit the stream end timeout of 5 seconds or that we close socket on server side without waiting for all data received. I've failed to reproduce the last condition on my Mac though. Though there are some stackoverlow ideas:
- https://stackoverflow.com/questions/36533028/how-to-send-a-message-before-closing-tcp-connection-posix
- Or OTP docs:
>       close(Socket) -> ok
Types:
Socket = socket()
Closes a …
> Workaround transport delivery problems

- doc/user-guide/Features-and-supported-standards.md
- doc/user-guide/Getting-started.md
This PR adds a note to "Features & supported standards" and "Getting started" pages about MongooseIM behaviour in case of a session collision.
> Add a clarification about session replacement to docs

- big_tests/tests/acc_e2e_SUITE.erl
- big_tests/tests/acc_e2e_SUITE_data/acc_test_helper.erl
- src/ejabberd_service.erl
- src/ejabberd_sm.erl
- src/mongoose_local_delivery.erl
- src/pubsub/mod_pubsub.erl
This PR addresses ticket MIM-659.
The issue being solved here is that in filter_local_packet we have already done all the sender-side processing and switch to the recipient side - it is run before ejabberd_sm ships the message to the recipient process, because we don't yet know if he is online and want to do some stuff regardless. So the accumulator should be already stripped of all sender-related cached data.
* strip acc in mongoose_local_delivery, not in ejabberd_sm
* test which stops the message if at the filter_local_packet stage the acc still contains some data cached by the sender
> strip acc before running filter_local_packet

- tools/generate_vsn.sh
This PR addresses #1988
* removal of dependency on `/bin/bash` for generating the version number, use POSIX `/bin/sh`
> tools: generate_vsn: remove bashism and use POSIX /bin/sh

- src/jid.erl
- test/jid_SUITE.erl
IMO the readability benefit outweighs the extra computation cost of 3 eager calls to build the tuple, even if one fails. All in all, I'd guess the majority of these calls are successful.
> Refactor jid:make/3

- big_tests/default.spec
- big_tests/tests/mongoose_user_stats_SUITE.erl
- rel/fed1.vars.config
- rel/files/mongooseim.cfg
- rel/mim1.vars.config
- rel/mim2.vars.config
- rel/mim3.vars.config
- rel/reg1.vars.config
- rel/vars.config.in
- src/config/mongoose_config_parser.erl
- src/ejabberd_app.erl
- src/mongoose_user_stats.erl
This PR creates a module reporting MongooseIM usage data to Google Analytics.
Currently reporting:
- Number of configured hosts
- Open source mods with backends (if configured)
> Create mogoose user stats prototype

- src/ejabberd_c2s.erl
> Fix to "Do not recreate accumulator when sending out a stanza"

- doc/modules/mod_event_pusher_http.md
- doc/modules/mod_offline.md
I stumbled upon small errors in `mod_offline` and `mod_event_pusher_http` descriptions and fixed them
> [skip ci] Fix small documentation errors

- big_tests/tests/distributed_helper.erl
This PR ports a `distributed_helper:rpc/4` improvement from a private project. It aims to make the call target explicit, but maintains backwards compatibility to some extent by providing an extra clause and an extra arity helper.
> Better distributed_helper:rpc/4

- big_tests/tests/muc_light_SUITE.erl
- doc/migrations/3.5.0_3.5.0plus.md
- doc/modules/mod_muc_light.md
- doc/operation-and-maintenance/known-issues.md
- include/mod_muc_light.hrl
- mkdocs.yml
- src/muc_light/mod_muc_light.erl
- src/muc_light/mod_muc_light_codec_legacy.erl
- src/muc_light/mod_muc_light_codec_modern.erl
- src/muc_light/mod_muc_light_db.erl
- src/muc_light/mod_muc_light_db_mnesia.erl
- src/muc_light/mod_muc_light_db_rdbms.erl
- src/muc_light/mod_muc_light_room.erl
- src/muc_light/mod_muc_light_room_config.erl
- src/muc_light/mod_muc_light_utils.erl
- test/muc_light_SUITE.erl
This PR:
**Note for the reviewers:** Former 3 commits include only the refactoring part (item 2 in the list above) so may be reviewed independently for clarity.
> Better MUC light room config

- big_tests/tests/vcard_SUITE.erl
- src/mod_vcard.erl
This PR addresses #2384
* parse vcard fields which are part of search index
* allow emoji in `NICKNAME` but remove it from the nickname index
* extend tests to check if nickname with emoji is set correctly
> Allow emoji in vcard's nickname field

- src/mongoose_client_api.erl
When user try do authorization by REST API and try send data without JID in Authorization field eg, `base64(<<":password">>)` or `<<"">>` -  the MongooseIM provide crash report.
* Fix crash if User JID binary is empty
```sh
12:24:10.481 [error] CRASH REPORT Process <0.1343.0> with 0 neighbours crashed with reason: no match of right hand value error in mongoose_client_api:check_password/2 line 115
12:24:10.483 [error] Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['ejabberd_cowboy_0.0.0.0_8089',<0.1341.0>,2,<0.1343.0>,{badmatch,error},[{mongoose_client_api,check_password,2,[{file,"/home/user/mongooseim/_build/prod/lib/mongooseim/src/mongoose_client_api.erl"},{line,115}]},{mongoose_client_api,do_authorize,2,[{file,"/home/user/mong …
```
> Fix crash if user JID binary is empty

- big_tests/tests/mongoose_push_mock.erl
- big_tests/tests/push_integration_SUITE.erl
- doc/migrations/3.5.0_3.5.0plus.md
- doc/modules/mod_push_service_mongoosepush.md
- doc/user-guide/Push-notifications.md
- src/mod_push_service_mongoosepush.erl
* allow to specify what HTTP status and body is returned to MongooseIM from MongoosePushMock
* extend MongoosePushMock to accept requests to API v3
> MongoosePush API v3 mock

- big_tests/rebar.config
- big_tests/rebar.lock
- src/pubsub/mod_pubsub_db_rdbms_sql.erl
After merging esl/escalus#179 the `gdpr_SUITE` stopped working in test cases related to pubsub. This was because previous way of selecting nodes by owner didn't work with long JIDs and the PR to escalus made usernames significantly longer.
> Fix MSSQL GDRP pubsub retrival for long usernames

- big_tests/rebar.config
- big_tests/rebar.lock
- big_tests/tests/push_integration_SUITE.erl
- doc/migrations/3.5.0_3.5.0plus.md
- doc/user-guide/Push-notifications.md
- src/event_pusher/mod_event_pusher_push.erl
- src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
- src/mod_push_service_mongoosepush.erl
- src/pubsub/node_push.erl
This PR removes push nodes corresponding to an expired device id when MongoosePush returns appropriate error code.
* fix for publish iq response handlers
* now the push notification is sent from the user's **server** JID (before it was user's JID)
* it requires to add server's JID to affiliations with `publish-only` role in case the push node is configured with more strict options
* generate IQ error reply with code `406` (`not-acceptable`) of type `cancel` in case MongoosePush API v3 returns error code `410` indicating `unregistered` device
* the migration guide and push notifications user guide where update to reflect the changes.
> Push notifications remove expired device

- src/ejabberd_c2s.erl
- src/ejabberd_gen_sm.erl
- src/ejabberd_sm.erl
- src/ejabberd_sm_mnesia.erl
- src/ejabberd_sm_redis.erl
- src/mongoose_session.erl
- test/ejabberd_sm_SUITE.erl
This PR allows to remove keys from session's info attribute.
* new `ejabberd_sm:remove_info` function
* internal change to ejabberd_sm and its backends which updates a session (not trying to create one and merge with previous) when `store_info` or `remove_info` functions are called.
> Extend session manager

- big_tests/tests/push_integration_SUITE.erl
- doc/user-guide/Push-notifications.md
- src/mod_push_service_mongoosepush.erl
Make the push node take into account the priority given in the enable stanza. This should be compatible with the future pubsub-less push notifications, and it makes the priority configurable with the granularity of the node.
Tests are added following the logic of the already present tests, and the values of this new field are also added to the docs.
> Push priority configurable by node

- big_tests/tests/mongoose_helper.erl
- big_tests/tests/push_SUITE.erl
- big_tests/tests/push_integration_SUITE.erl
- src/ejabberd_sm.erl
- src/event_pusher/mod_event_pusher_push.erl
- src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
- src/mongoose_session.erl
This PR stores push node details (form the `enable` stanza) in user's session info field.
* store push notifications node details (node and form fields) to user's session info field when user sends the `enable` stanza
* remove the push notifications details form user's session info field when:
* the device id for the push node is considered expired by MongoosePush
* the user send `disable` stanza
> Store push notification details in session

- rel/files/vm.args
According to Lukas, in the blogpost http://blog.erlang.org/IO-Polling/, the flag `+K` was removed since our very oldest supported OTP version, so we can get rid of that.
> Kernel polling flag removed since OTP21

- big_tests/tests/distributed_helper.erl
Until https://github.com/esl/MongooseIM/pull/2533 is ready, CI has very long logs that basically leave both Travis and CI a bit unreadable across very long scrolls, for example in https://circleci.com/gh/esl/MongooseIM/11097
So I think that this commit can be reverted together with the merge from 2533 once he's ready 🙁
> Remove excessive logging in CI

- big_tests/tests/last_SUITE.erl
- src/ejabberd_c2s.erl
- src/ejabberd_sm.erl
This PR addresses #MIM-752: errors sent in jabber:iq:last namespace were rejected with an error, which means that error response to a last activity query addressed to a subscription=none peer did not come. Also, if full jid was used, error stanzas entered an infinite loop.
This PR adds a tiny clause to the c2s function, plus tests.
> Fix error iqs in mod last

- c_src/jid.cpp
- rebar.config
- src/jid.erl
- test/jid_SUITE.erl
When running and profiling MIM, a thing to pay attention to was these results from `cprof` on master, for a scenario like "5k users sending a 1-to-1 message per second", where this was the very top:
```
[{jid,580785,
[{{jid,binary_to_jid2,3},151070},
{{jid,binary_to_jid1,2},147721},
{{jid,to_binary,1},60428},
{{jid,binary_to_jid3,4},45315},
{{jid,from_binary,1},15107},
```
Curious about the module `jid` being the most often called module, this is what I got from `eprof`:
```
FUNCTION                        CALLS        %      TIME  [uS / CALLS]
--------                        -----  -------      ----  [----------]
jid:from_binary/1               18166     0.04     14198  [      0.78]
jid:binary_to_jid1/2           177606     0.19     75071  [      0.42]
jid:binary_to_jid2/3 …
```
> Move logic from jid:from_binary into a nif

- rel/files/vm.args
Since OTP 20, the Async Thread Pool is not used anymore, in favour of
the dirty schedulers, and this Async Thread Pool is left for whatever
old libraries still written to use them, but all of OTP was already
rewritten the "Dirty Schedulers" way. So these are just unused. I
haven't find any of our dependencies using this pool, and to add insult
to injury, documentation for this is hard to find in the internet.
Even, on my load tests, accounting showed results like this:
```
(mongooseim@localhost)> msacc:start(1000), msacc:print().
Thread      aux check_io emulator       gc    other     port    sleep
Stats per type:
async    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00% <--
aux    0.00%    0.00%    0.00%    0.00%    0.02%    0.00%   99.97%
dirty_cpu_sche    0.00%    0.00% …
```
> Async thread pool not used anymore

- big_tests/tests/sm_SUITE.erl
- include/ejabberd_c2s.hrl
- src/ejabberd_c2s.erl
- src/mongoose_acc.erl
- test/acc_SUITE.erl
the work on the push notifications is restarted in this branch/PR just too preserve the initial discussion/comments.
this PR will focus only on the changes in c2s:
* storing stripped accumulators instead of exml in C2S buffers (we must preserve `non_strippable` fields when rerouting message or resuming the session).
* proper implementation of the `unacknowledged_message` hook (hook handler must be able to modify the original message accumulator, the list of the nodes where the message is pushed can be added/extended by `mod_event_pusher_push` as `non_strippable` field).
things to be implemented in the separate PRs:
* mod_offline must preserve `non_strippable` fields of the message accumulator and return them on `resend_offline_messages_hook` (testcase is already implemented but disabled, …
> Push notifications

- big_tests/tests/jingle_SUITE.erl
- src/jingle_sip/jingle_sip_callbacks.erl
There is a typo in xmlns in jingle handling.
Relevant docs https://xmpp.org/extensions/xep-0167.html#info-ringing
Provided additional check in suite.
> [jingle_sip] Fix wrong xmlns for ringing stanza

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- src/config/mongoose_config_parser.erl
- src/system_metrics/mongoose_system_metrics_sender.erl
- src/system_metrics/service_mongoose_system_metrics.erl
When gathering system metrics is allowed, this PR allows to configure additional Tracking ID for gathering metrics in Google Analytics. On every reporting cycle, the metrics are being sent twice with different tracking IDs. 
*DEV Google Analytics dashboard 
*Configured Tracking ID
MIM User is assumed to have access to the configured Tracking ID. Using this feature allows User to view and possibly use for their purposes, all system metrics that are being collected.
> System metrics - additional and configurable Tracking ID

- big_tests/tests/gdpr_SUITE.erl
- big_tests/tests/pubsub_SUITE.erl
- big_tests/tests/pubsub_s2s_SUITE.erl
- big_tests/tests/pubsub_tools.erl
- big_tests/tests/push_SUITE.erl
- big_tests/tests/push_integration_SUITE.erl
- big_tests/tests/push_pubsub_SUITE.erl
The goal of this PR is to unify all the duplicated functionality across different test suites related to pubsub nodes: we have many functions that generate a pubsub node name, or subdomains, or tagged by number... It can all be implemented once in `pubsub_tools` and used everywhere.
Something that might have potentially been a problem is when in both `push_integration_SUITE` and `push_pubsub_SUITE` we generate a random name (`rand_name`) but we don't make sure the random string does not contain slashes (`/`), which has been a problem before in pubsub; it doesn't hurt to keep the node names always curated against it.
> Test pubsub tools cleanup

- big_tests/tests/mongoose_push_mock.erl
- big_tests/tests/push_SUITE.erl
- big_tests/tests/push_helper.erl
- big_tests/tests/push_integration_SUITE.erl
- big_tests/tests/sm_SUITE.erl
- include/mod_event_pusher_events.hrl
- src/ejabberd_c2s.erl
- src/event_pusher/mod_event_pusher.erl
- src/event_pusher/mod_event_pusher_hook_translator.erl
- src/event_pusher/mod_event_pusher_push.erl
- src/event_pusher/mod_event_pusher_push_plugin.erl
- src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
things done in this PR:
* handling of `unacknowledged_message` hook at `mod_event_pusher_hook_translator`. currently the event generated on this hook is ignored by all the `mod_event_pusher` backends.
* rework of the `mod_event_pusher_push_plugin`:
- all the callbacks are optional. if any of them is not implemented in the pluging, `mod_event_pusher_push_plugin_defaults` implementation is used instead.
- `should_publish` accepts the list of all services and returns the list of services where notification should be published. so it can be easily fully accepted/rejected or filtered.
- separate `prepare_notification` interface can be used to reject the event (e.g. message doesn't have body) or create push notification payload.
- `publish_notification` interface. …
> adding unacknowledged_message hook processing at event_pusher

- big_tests/tests/push_SUITE.erl
- big_tests/tests/push_integration_SUITE.erl
- big_tests/tests/sm_SUITE.erl
- include/mod_event_pusher_events.hrl
- src/ejabberd_c2s.erl
- src/ejabberd_sm.erl
- src/event_pusher/mod_event_pusher_hook_translator.erl
- src/event_pusher/mod_event_pusher_push.erl
- src/event_pusher/mod_event_pusher_push_plugin.erl
- src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
- src/event_pusher/mod_event_pusher_push_plugin_enhanced.erl
This branch contains implementation of the enhanced push plugin (`mod_event_pusher_push_plugin_enhanced`), here are some notes:
the implementation is minimalistic. comparing to the default plugin enhanced one adds only immediate push notifications to the devices that just lost connection (session waits for resumption) also it works only if device (re)enabled notifications during the session. this helps to avoid the notification duplicates in most of the cases.
> initial implementation of the enhanced push plugin

- big_tests/default.spec
- big_tests/tests/persistent_cluster_id_SUITE.erl
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- src/ejabberd_app.erl
- src/mongoose_cluster_id.erl
- src/rdbms/mongoose_rdbms.erl
> Persistent cluster ID

- src/system_metrics/service_mongoose_system_metrics.erl
This PR most importantly makes `system_metrics` use the new `mongoose_cluster_id` functionality (commit 9ccb790).
In the commit 918ceea I just cleaned a bit of code in `system_metrics` like, whitespace, specs, removing an unused record definition, and some `erlc` warnings like capturing variables from a case expression.
> Use cluster id in system metrics

- doc/developers-guide/flat_options.md
- src/ejabberd_config.erl
- src/mod_last.erl
http://erlang.org/doc/man/erlang.html#timestamp-0 says that
> Current Erlang system time can more efficiently be retrieved in the time unit of your choice using `erlang:system_time/1`.
So we save erts time, and also time on the `now_to_seconds` function. I just though of tagging the value into a tagged tuple, so ensure some sort of "type-safety" 🤷‍♂
> [Small] Modernise time functionality for mod_last

- tools/circle-build-and-push-docker.sh
This PR updates mongooseim-docker ref to contain fix from esl/mongooseim-docker#30
> Try mongooseim-docker able to setup clusters bigger than 9 nodes

- big_tests/tests/mam_helper.erl
- big_tests/tests/muc_SUITE.erl
- big_tests/tests/muc_helper.erl
- big_tests/tests/muc_light_SUITE.erl
- big_tests/tests/muc_light_legacy_SUITE.erl
- src/mod_muc.erl
- src/mod_muc_room.erl
- src/muc_light/mod_muc_light_codec_legacy.erl
- src/muc_light/mod_muc_light_codec_modern.erl
This PR addresses #2269.
* Advertise MAM for user JIDs.
* Advertise MAM for MUC Light rooms.
As currently written, this unconditionally advertises MAM for MUC Light rooms, since MAM is a requirement for MUC Light.
> Advertise MAM in disco#info

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- src/system_metrics/service_mongoose_system_metrics.erl
This PR addresses tests failing for collecting metrics about XMPP components. There was a typo in the code while getting values from the args.
> Fix periodic timer when collecting metrics

- tools/pkg/platforms/debian_stretch/files/build/debian/postinst
- tools/pkg/platforms/debian_stretch/files/build/debian/postrm
- tools/pkg/platforms/debian_stretch/files/build/debian/prerm
This PR addresses #1404 and #1405 
Changes include:
* removing trailing slashes in `postinst` script
* removing unnecessary commands in `prerm` and `postrm` scripts
> Fix deb package logic

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- rebar.config
- rel/files/mongooseim.cfg
- rel/mim1.vars.config
- rel/mim2.vars.config
- rel/mim3.vars.config
- src/system_metrics/service_mongoose_system_metrics.erl
This PR:
* enables system metrics service by default on all nodes
* new GA Tracking ID is added for prod nodes
* metrics tests refactoring
> System Metrics - prod node GA Tracking ID

- mkdocs.yml
Apparently readthedocs didn't build the client-side doc if it is not on the mkdocs.yml file, this should hopefully fix that
> [skip ci] fix docs

- rel/files/mongooseim
- rel/files/mongooseimctl
> Use runuser instead of sudo

- doc/user-guide/release_config.md
- rel/files/mongooseim
- rel/files/mongooseimctl
- tools/configure
- tools/install
This PR allows configure to set directories for `pid` and `status` files. Their default location for system install is now set to `/var/lib/mongooseim`.
> Install pid and status directories explicitly

- src/ejabberd_receiver.erl
- src/shaper.erl
On `shaper.erl`, the arithmetics are done by converting to and from `native`-`second` time units, which shows on the profiling statistics I gathered last time:
> for a scenario like "5k users sending a 1-to-1 message per second"
```
FUNCTION                              CALLS        %      TIME  [uS / CALLS]
--------                              -----  -------      ----  [----------]
erlang:monotonic_time/0                5999     0.01      1022  [      0.17]
erlang:convert_time_unit/3            11998     0.04      8580  [      0.72]
```
We see that `convert_time_unit/3` is called twice as often as `monotonic_time/0`, which is exactly what `shaper:update/2` does.
On `fprof`, we can see that, of the accumulated 130us that `shaper:update/2` takes, 20us of them are spent on …
> Refactor the calculation to avoid reduntant time conversions

- big_tests/src/mim_loglevel.erl
- big_tests/tests/cluster_commands_SUITE.erl
- big_tests/tests/component_SUITE.erl
- big_tests/tests/conf_reload_SUITE.erl
- big_tests/tests/distributed_helper.erl
- big_tests/tests/dynamic_modules.erl
- big_tests/tests/ejabberd_node_utils.erl
- big_tests/tests/ejabberdctl_helper.erl
- big_tests/tests/gdpr_SUITE.erl
- big_tests/tests/metrics_api_SUITE.erl
- big_tests/tests/mod_global_distrib_SUITE.erl
- big_tests/tests/mongoose_cassandra_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- big_tests/tests/muc_light_helper.erl
- big_tests/tests/persistent_cluster_id_SUITE.erl
- big_tests/tests/push_SUITE.erl
- big_tests/tests/push_integration_SUITE.erl
- big_tests/tests/reload_helper.erl
- big_tests/tests/rest_helper.erl
- big_tests/tests/s2s_SUITE.erl
- big_tests/tests/s2s_helper.erl
This PR refactors big tests to use `rpc_spec()` instances for specifying RPC call targets.
> Use rpc_spec()

- doc/modules/mod_mam.md
The list was intended to be a nested list, but only 2 spaces were used instead of 4. Because of that all items were on the same level.
> [skip ci] Fix nested list in mod_mam.md

- tools/travis-setup-db.sh
This PR fixes pgsql docker container setup by specifying main `POSTGRES_PASSWORD` via env while starting the container with `docker run`
> Fix pgsql docker container setup

- .dockerignore
- tools/pkg/Dockerfile_deb
- tools/pkg/Dockerfile_rpm
- tools/pkg/scripts/smoke_test.sh
A bug related to `mongooseimctl` script was fixed in #2631. This PR adds tests in order extend .deb and .rpm package verification and to catch similar bugs in the future.
> Test mongooseimctl after package installation

- c_src/jid.cpp
BEAM requires some `upgrade` function in the nifs definition in order to be able to reload the module. This is just a stub that does nothing, as this module is stateless, but it is required if we want to do a `l(jid)` on the shell 🤷‍♂
> jid reload

- src/auth/ejabberd_auth_anonymous.erl
- src/ejabberd_sm.erl
- src/global_distrib/mod_global_distrib_mapping.erl
- src/mod_amp.erl
- src/mod_ping.erl
- src/mongoose_hooks.erl
This PR makes `ejabberd_sm` use newly written hooks in `mongoose_hooks` module. It also fixes some inconsistencies found in specs for handlers.
> Change ejabberd_sm hooks to use mongoose_hooks

- src/ejabberd_c2s.erl
- src/mongoose_hooks.erl
This PR updates `ejabberd_c2s` to use new `mongoose_hooks` module. I have tried to write specs for the functions from `mongoose_hooks` as correctly as possible. I have noted hooks that are good candidates for removal, because they are not handled as far as I can see:
-  `c2s_update_presence` - it was not only not handled but also called with different number of arguments. One place when this hook is fired is in `handle_info({force_update_presence, LUser}...` in `c2s`. This message is sent only in `ejabberd_sm` and is exposed in API as `force_update_presence/1`. Is there a reason for such functionality? It seems that nothing executes this code right now.
- `forbidden_session_hook`
- ` c2s_loop_debug` which is also executed with different arguments but does not seem to be handled
- …
> Change ejabberd_c2s to use mongoose_hooks

- src/ejabberd_c2s.erl
- src/mongoose_hooks.erl
This PR follows the discussion from #2641 . It makes it mandatory to pass an accumulator to `mongoose_hooks` calls. It also adds `global` as an option for `Server` values for consistency with `ejabberd_hooks` specs.
> Hooks cleanup

- src/ejabberd_s2s.erl
- src/ejabberd_s2s_in.erl
- src/ejabberd_s2s_out.erl
- src/mongoose_hooks.erl
I've moved the hook execution to the new wrapper module. However, all hooks except for `s2s_stream_features` are not handled as far as I can see. I removed `s2s_loop_debug` because it seems to be a counterpart of `c2s_loop_debug`, but I don't know whether the other ones can be removed. I am also not sure about naming conventions in s2s (especially `myname` and `server` kept in the state of `ejabberd_s2s_out`).
> Make s2s use hooks wrapper

- src/global_distrib/mod_global_distrib_disco.erl
- src/http_upload/mod_http_upload.erl
- src/mod_adhoc.erl
- src/mod_amp.erl
- src/mod_disco.erl
- src/mod_vcard.erl
- src/mongoose_hooks.erl
- src/muc_light/mod_muc_light.erl
- src/pubsub/mod_pubsub.erl
This PR reworks `mod_disco` to use new `mongoose_hooks` module.
I tried not to change the logic of the hooks, although sometimes it seemed a good fit for refactoring (like passing `empty` atom instead of an empty list).
The `disco_sm_items` hook call is not covered by tests at all.
> Rework mod_disco to use mongoose_hooks

- src/amp_strategy.erl
- src/mod_amp.erl
- src/mongoose_hooks.erl
- tools/travis-setup-db.sh
This PR changes `mod_amp` module to use new `mongoose_hooks` module.
My comments for possible future refactoring of hooks:
* `amp_notify_action_triggered` and `amp_error_action_triggered` seem to not be handled anywhere
* `amp_check_condition`, `amp_verify_support` and `amp_check_packet` seem to only be handled in AMP modules. Also `amp_check_packet` call contains a weird comment which I do not fully understand,
* `amp_determine_strategy` has specs that suggest that `To` argument may be `undefined` but only one handler reacts to this correctly (`determine_strategy` in `amp_strategy`) and handlers`determine_amp_strategy` in `mod_offline` and `mod_mam` may fail because of that. I do not know whether it is possible for `To` to really be undefined so I did not know whether to change specs in …
> Change mod_amp to use mongoose_hooks

- src/mod_muc.erl
- src/mod_muc_room.erl
- src/mongoose_hooks.erl
- src/muc_light/mod_muc_light_codec_legacy.erl
- src/muc_light/mod_muc_light_codec_modern.erl
- src/muc_light/mod_muc_light_db_mnesia.erl
- src/muc_light/mod_muc_light_room.erl
This PR changes `muc_light` as well as `muc` modules to use new `mongoose_hooks` module. 
As usually some hooks seem to not be handled at all.
In this PR I decided to change some code around the `filter_local_packet` hook, as it will never return the `drop` atom. Dialyzer was not happy about expecting this atom in a case expression branch, so I had to either change the specs to be less precise or incorrect, or to change the implementation and chose the latter. In general the `filter_local_packet` hook was not really used for filtering as I understand.
> Hooks wrapper muc and muc_light

- src/mod_caps.erl
- src/mongoose_hooks.erl
This PR addresses changes `mod_caps` to use new `mongoose_hooks` module.
`caps_add` and `caps_update` are not handled.
> Change mod_caps to use mongoose_hooks

- src/mongoose_hooks.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/node_push.erl
This PR changes pubsub modules to use new `mongoose_hooks` module.
All of them are not handled in the code explicitly, but may be useful for metrics.
> Change pubsub to use mongoose_hooks

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- src/system_metrics/mongoose_system_metrics_collector.erl
Extending system metrics to collect information regarding types of outgoing pools that are configured.
> System Metrics: types of outgoing pools

- src/admin_extra/service_admin_extra_roster.erl
- src/mod_commands.erl
- src/mod_disco.erl
- src/mod_last.erl
- src/mod_privacy.erl
- src/mod_roster.erl
- src/mongoose_hooks.erl
I believe `roster_push`  should be called from `mod_roster:push_item/5` not `/4` . It is used for metrics and now it seems it is executed only when roster versioning is not enabled, but I didn't change the logic for now.
> Change roster related hook executions to use mongoose_hooks

- src/ejabberd_config.erl
- src/ejabberd_ctl.erl
- src/ejabberd_local.erl
- src/ejabberd_router.erl
- src/ejabberd_service.erl
- src/ejabberd_sm_mnesia.erl
- src/ejabberd_sm_redis.erl
- src/mongoose_hooks.erl
This PR changes `ejabberd_*` modules to use `mongoose_hooks`. I did not add many doc comments because I wasn't sure about the meaning of the hooks, this should be added later.
The `ejabberd_ctl_process` has handlers added dynamically in `ejabberd_ctl:register_commands` but this part of code is not covered by tests, so I don't know whether it is used.
> Change `ejabberd_*` modules to use mongoose_hooks

- big_tests/tests/connect_SUITE.erl
- src/ejabberd_c2s.erl
Addressing my introductory story MIM-849. While setting session up in `ejabberd_c2s` fsm there are cases where on receiving stanzas that are not following any of the standarized sequence the state machine is crashing. I ensured these cases to close fsm gracefully and reply to client with `policy-violation` error.
Due to difficulties with stanzas injecting into `ejabberd_c2s:wait_for_sasl_response/2` state using `escalus` library, I agreed with @NelsonVides to omit this part of PR and focus on discovering another parts of the project.
I also took the opportunity to do a little refactor of copy-pasted code in state machine.
> Unexpected c2s stanzas

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- src/system_metrics/mongoose_system_metrics_collector.erl
- src/system_metrics/mongoose_system_metrics_file.erl
- src/system_metrics/service_mongoose_system_metrics.erl
This PR extends functionality of collecting metrics. It allows to gather the number of sent and received:
* Message Stanzas
* Iq Stanzas
* Presence Stanzas
The information is retrieved from exometer. The metrics are sending information regarding number of stanzas since the last report and total amount of stanzas as reported by exometer.
> Metrics xmpp stanzas count

- doc/advanced-configuration/outgoing-connections.md
This PR documents how to pass extra parameters to fusco and gives example how to enforce peer certificate verification.
> Describe the http pool's `http_opts` parameter

- src/mam/mod_mam.erl
- src/mam/mod_mam_elasticsearch_arch.erl
- src/mam/mod_mam_muc.erl
- src/mam/mod_mam_muc_elasticsearch_arch.erl
- src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
- src/mam/mod_mam_rdbms_async_pool_writer.erl
- src/mam/mod_mam_riak_timed_arch_yz.erl
- src/metrics/mongoose_metrics.erl
- src/metrics/mongoose_metrics_mam_hooks.erl
- src/mongoose_hooks.erl
I've made fairly mechanical changes removing hooks used only for metrics in `mod_mam`. I don't know however if it is not a step to far as we loose some API as metrics are updated directly.
> [WIP] Remove hooks used only for metrics in mod_mam

- src/mod_ping.erl
This PR aims to fix some random failures introduced with mod_ping. Timers that are passed are in seconds and ping_req_timeout was not converted to milliseconds. 
Thanks @bartekgorny for troubleshooting and finding the issue.
> Fix ping request timeout from seconds to miliseconds

- big_tests/tests/mod_ping_SUITE.erl
There was some tricky issue: another test, ran just a little while before, did not respond to pings, waited a few seconds, then killed the connection and checked metrics. It was all fine, but the test waited for ping_req_timeout + 1, which incidentally is equal to ping_interval. Server sent one more request, which incremented metrics a few seconds later, which happened be exactly when another test was run, thus breaking that one. The second run of the other tests was ok.
> Fix mod_ping tests so that they pass at the first go

- big_tests/tests/muc_SUITE.erl
- src/jlib.erl
This change fixes structure of invite sent from MongooseIM.
Doc reference https://xmpp.org/extensions/xep-0045.html#invite-mediated
Currently looks like:
```xml
<message
from='coven@chat.shakespeare.lit'
id='nzd143v8'
to='hecate@shakespeare.lit'>
<x xmlns='http://jabber.org/protocol/muc#user'>
<reason>Hey Hecate, this is the place for all good witches!</reason>
<password>cauldronburn</password>
<invite from='crone1@shakespeare.lit/desktop'/>
</x>
</message>
```
Should be
```xml
<message
from='coven@chat.shakespeare.lit'
id='nzd143v8'
to='hecate@shakespeare.lit'>
<x xmlns='http://jabber.org/protocol/muc#user'>
<invite from='crone1@shakespeare.lit/desktop'>
<reason>
Hey Hecate, this is the place for all good witches!
</reason>
</invite>
<password>cauldronburn</password>
</x>
</message>
```
> Fix mediated invite structure

- src/mongoose_api_common.erl
- src/mongoose_commands.erl
- test/commands_SUITE.erl
Maybe TODO: test it? Anybody has any idea how?
This allows to use JSON boolean types when we define commands like
```erlang
{name, some_name},
{category, <<"some_name">>},
{desc, <<"Do something">>},
{module, ?MODULE},
{function, some_name},
{action, some_action},
{args, [{caller, binary},
{conversation_id, binary},
{some_boolean_condition, boolean}]}, % <---
{result, {some_kind_of_result, binary}}
```
As we know, in JSON, `<<"false">>` is of type string, while `false` is of type boolean. Two different things, good to have both.
> Allow for boolean types in REST calls

- tools/circle-build-and-push-docker.sh
This PR uses mongooseim-docker where:
* The base image was updated to `phusion/baseimage:master` which is based on Ubuntu 18.04
* Installs OpenSSL 1.1
This PR supersedes #2687 and #2683
> Update ref to esl/mongooseim-docker

- src/auth/ejabberd_auth_internal.erl
- src/sasl/cyrsasl_scram.erl
- test/auth_internal_SUITE.erl
This PR extends tests to check if mnesia can properly work with entries in the old scram format
* `ejabberd_auth_internal:get_password` returns new map if old entry is found in the database
* new tests for:
* `get_password`
* plaintext to scram converstion script
> Extend `scram-sha` mnesia tests

- doc/authentication-backends/External-authentication-module.md
- doc/authentication-backends/HTTP-authentication-module.md
- src/auth/ejabberd_auth.erl
- src/auth/ejabberd_auth_anonymous.erl
- src/auth/ejabberd_auth_dummy.erl
- src/auth/ejabberd_auth_external.erl
- src/auth/ejabberd_auth_http.erl
- src/auth/ejabberd_auth_internal.erl
- src/auth/ejabberd_auth_jwt.erl
- src/auth/ejabberd_auth_ldap.erl
- src/auth/ejabberd_auth_pki.erl
- src/auth/ejabberd_auth_rdbms.erl
- src/auth/ejabberd_auth_riak.erl
- src/auth/ejabberd_gen_auth.erl
- src/auth/extauth.erl
- test/auth_external_SUITE.erl
- test/auth_external_SUITE_data/sample_external_auth.py
- test/auth_http_SUITE.erl
- test/auth_jwt_SUITE.erl
Currently there is no way to call this function other than from MongooseIM console.
In the past (long time ago) this function was used to verify if a user is allowed to remove itself by providing the password.
Nowadays there is no admin interface for that nor XMPP protocol / XEP.
> Remove dead ejabberd_auth:remove_user/3

- big_tests/test.config
- big_tests/tests/offline_SUITE.erl
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- rebar.config
- src/mod_smart_markers.erl
- src/mod_smart_markers_rdbms.erl
- src/mongoose_acc.erl
- src/muc_light/mod_muc_light.erl
- src/muc_light/mod_muc_light_room.erl
- src/offline/mod_offline.erl
- src/offline/mod_offline_chatmarkers.erl
- src/offline/mod_offline_chatmarkers_rdbms.erl
- src/rdbms/mongoose_rdbms_odbc.erl
commands for manual DB backend testing:
test-runner.sh --one-node --skip-cover --skip-small-tests --skip-stop-nodes --preset odbc_mssql_mnesia -- offline
_build/mim1/rel/mongooseim/bin/mongooseim debug
```
mod_smart_markers_rdbms:init(<<"localhost">>,ok).
JID1=jid:make({<<"a">>,<<"c">>,<<"">>}).
JID2=jid:make({<<"a">>,<<"b">>,<<"">>}).
CM =#{from=>JID1,
to=>JID2,
thread=>undefined,
type=>received,
timestamp=>100,
id=><<"aaa">>}.
mod_smart_markers_rdbms:update_chat_marker(<<"localhost">>,CM).
mod_smart_markers_rdbms:get_chat_markers(<<"localhost">>, JID2, undefined, 100).
mod_smart_markers_rdbms:get_chat_markers(<<"localhost">>, JID2, undefined, 0).
mod_smart_markers_rdbms:get_chat_markers(<<"localhost">>, JID2, undefined, 101).
mod_smart_markers_rdbms:update_chat_marker(<<"localhost">>,CM# …
```
> Chat markers cache

- big_tests/tests/login_SUITE.erl
- doc/Advanced-configuration.md
- doc/developers-guide/SCRAM-serialization.md
- src/auth/ejabberd_auth_http.erl
- src/auth/ejabberd_auth_internal.erl
- src/auth/ejabberd_auth_rdbms.erl
- src/auth/ejabberd_auth_riak.erl
- src/mongoose_scram.erl
- test/auth_http_SUITE.erl
This PR extends functionality of multi sha support. This PR allows to specify which sha algorithms can be used for storing passwords in scram format. 
The change of the config file allows now to specify scram password format in two different ways:
* {password_format, scram} - how the password format was specified so far
* {password_format, {scram, [sha, sha256]}} - new format allowing to select sha algorithms within the list. This format will allow to store the scram of the passwords using only those algorithms that are specified in the list.
> allow to select sha algorithm from config file

- src/ejabberd_c2s.erl
- src/mongoose_transport.erl
`ejabberd_c2s` is calling `starttls` in two different ways: in one, it
calls it through the `mongoose_transport` behaviour, which in turns calls
`starttls` on the module that was given to the first as a parameter, and
on the second it calls it directly over such module, which seems like an
inconsistent way to call such function.
All the modules we have that implement mongoose_transport actually
implement two `starttls` callbacks, and even in some, like in
`mod_websockets`, we mention in the comments that some callbacks are just
to make them compatible with `ejabberd_sockets`, but the `starttls/3`
callback is not required in the behaviour definition. So that's a first
code cleaning.
> Transport consistency

- big_tests/tests/login_SUITE.erl
- doc/Advanced-configuration.md
- doc/authentication-methods/client-certificate.md
- doc/developers-guide/SCRAM-serialization.md
- doc/migrations/3.6.0_3.6.x.md
- mkdocs.yml
- rel/vars.config.in
- src/auth/ejabberd_auth_anonymous.erl
- src/auth/ejabberd_auth_http.erl
- src/auth/ejabberd_auth_internal.erl
- src/auth/ejabberd_auth_rdbms.erl
- src/auth/ejabberd_auth_riak.erl
- src/mongoose_scram.erl
- src/sasl/cyrsasl.erl
- src/sasl/cyrsasl_scram.erl
- src/sasl/cyrsasl_scram_sha1.erl
- src/sasl/cyrsasl_scram_sha224.erl
- src/sasl/cyrsasl_scram_sha384.erl
- src/sasl/cyrsasl_scram_sha512.erl
- test/auth_external_SUITE.erl
- test/auth_http_SUITE.erl
- test/auth_jwt_SUITE.erl
This PR is a next step to extend SCRAM fictionality for authentication mechanisms. Changes include:
* Adding SHA-224, SHA-384 and SHA-512 as possible password formats and authentication mechanisms.
* List of authentication mechanisms that are offered is taking into account configured password format. This is to avoid situation that we store password in e.g. only SHA-1 and try to authenticate with SHA-256. The list of advertised authentication mechanisms is filtered to be compatible with password format that is configured. It is done in similar way to how it was accomplished for digest.
* Extending login_SUITE - testing if it's possible to login with different combinations of configured SCRAM SHA and not possible to login for the corner case described above.
* `cyrsasl_scram` module is …
> Extend SCRAM auth - SHA-224, SHA-384, SHA-512

- .dockerignore
- .gitignore
- doc/user-guide/Bootstrap-Scripts.md
- rebar.config
- rel/files/mongooseimctl
- rel/files/scripts/bootstrap20-template.escript
- rel/files/templates.ini
- rel/files/templates/demo.config
- tools/configure
- tools/pkg/Dockerfile_deb
- tools/pkg/Dockerfile_rpm
- tools/pkg/scripts/rpm/mongooseim.spec
- tools/pkg/scripts/smoke_templates.escript
- tools/pkg/scripts/smoke_test.sh
* New script for templating
* Docs
> Template bootstrap script

- big_tests/tests/amp_big_SUITE.erl
- big_tests/tests/mam_SUITE.erl
- big_tests/tests/mam_helper.erl
- big_tests/tests/mam_helper.hrl
- big_tests/tests/rest_helper.erl
- include/mongoose_ns.hrl
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- src/mam/ejabberd_gen_mam_archive.erl
- src/mam/mod_mam.erl
- src/mam/mod_mam_cassandra_arch.erl
- src/mam/mod_mam_elasticsearch_arch.erl
- src/mam/mod_mam_meta.erl
- src/mam/mod_mam_muc.erl
- src/mam/mod_mam_muc_cassandra_arch.erl
- src/mam/mod_mam_muc_elasticsearch_arch.erl
- src/mam/mod_mam_muc_rdbms_arch.erl
- src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
- src/mam/mod_mam_rdbms_arch.erl
- src/mam/mod_mam_rdbms_async_pool_writer.erl
- src/mam/mod_mam_riak_timed_arch_yz.erl
- src/mam/mod_mam_utils.erl
- src/metrics/mongoose_metrics_mam_hooks.erl
- src/mongoose_hooks.erl
Message retraction support in MAM for RDBMS
This PR introduces the support for [XEP-0424 Message Retraction](https://xmpp.org/extensions/xep-0424.html).
- Retraction messages are stored in MAM archives even though they contain no body, as required by the XEP.
- MAM archives using RDBMS handle the retraction messages by replacing the original message (referenced by `origin-id`) with a tombstone.
TO DO in next pull requests:
- Discovery of the retraction feature.
- Documentation of the retraction feature.
- Possible error replies to the sender when the message to retract from MAM does not exist.
> Message retraction: RDBMS

- big_tests/tests/login_SUITE.erl
- doc/Advanced-configuration.md
- src/sasl/cyrsasl.erl
- src/sasl/cyrsasl_digest.erl
This PR addresses deprecating DIGEST-MD5 as authentication method. 
The change include adding log message stating that DIGEST-MD5 is deprecated and will be removed in the next release. Log message is added using mongoose_deprecations module.
RFC on Moving DIGEST-MD5 to Historic can be found below:
[https://tools.ietf.org/html/rfc6331](https://tools.ietf.org/html/rfc6331 )
> Deprecate DIGEST-MD5 authentication method

- big_tests/tests/login_SUITE.erl
- doc/developers-guide/SCRAM-serialization.md
- src/mongoose_scram.erl
- src/sasl/cyrsasl_scram.erl
- test/auth_internal_SUITE.erl
This PR addresses improving best practices for password storage by having different SALT for each password SCRAM hash.
This is according to the XEP-0438
[https://xmpp.org/extensions/xep-0438.html](https://xmpp.org/extensions/xep-0438.html)
* changes in the password format
* updating tests that verify password format
* documentation update in the `SCRAM serialization fromat` section
> Separate SALT for each password SCRAM hash

- big_tests/tests/mam_SUITE.erl
- big_tests/tests/mam_helper.erl
- big_tests/tests/muc_SUITE.erl
- big_tests/tests/muc_light_SUITE.erl
- big_tests/tests/muc_light_legacy_SUITE.erl
- src/mam/mod_mam.erl
- src/mam/mod_mam_muc.erl
- src/mam/mod_mam_utils.erl
Add the message retraction feature to service discovery
- For the main XMPP service, register it when enabled for mod_mam
- For the MUC service, register it when enabled for mod_mam_muc
Also:
- Make the MUC test actually check MAM features
(muc service check is left as it can be useful to ensure MUC works)
- Remove stanza printout from the MAM test as we have stanza_log
- Check for both supported MAM namespaces
Notes:
- When message retraction is disabled in MAM, retraction messages are still stored although they do not cause any change to the original messages. The motivation is to allow the clients to handle the retraction message themselves, when they are back online. In this case there seems to be no reason for advertising of message retraction by the server.
> Message retraction: discovery

- big_tests/test.config
- big_tests/tests/sasl_external_SUITE.erl
- rel/files/mongooseim.cfg
- rel/vars.config.in
This PR addresses refactoring of the `auth_opts` list in the config file. `auth_opts` is a list of options usually with few elements. 
Problem example - adding `{{{password_format}}}`
* This should be achieved by e.g. `{password_format, "{password_format, plain},"}` but if it happened that it was the only element of that list, the tailing coma resulted in the syntax error.
* The problem is that some test presets have something in this list while other don't. Either adding this element with tailing coma or without it, was resulting somewhere as a syntax error of the config file.
The changes include:
* Adding `{password_format, plain}` to `auth_opts` - default password_format to be explicitly put as part of configuration
* It will be added as `{password_format, "{password_format, plain}"}.` …
> Refactoring auth_opts in the config file

- big_tests/test.config
- big_tests/tests/accounts_SUITE.erl
- big_tests/tests/ejabberdctl_SUITE.erl
- big_tests/tests/login_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- big_tests/tests/oauth_SUITE.erl
- doc/Advanced-configuration.md
- doc/migrations/3.6.0_3.6.x.md
- rel/files/mongooseim.cfg
- rel/mim1.vars.config
- rel/vars.config.in
- src/auth/ejabberd_auth_riak.erl
- src/mongoose_scram.erl
- test/auth_http_SUITE.erl
This PR addresses changing default password format to SCRAM.
* changing default password format
* refactoring tests that were verifying with plaintext as default
* documentation update
> SCRAM default password format

- rebar.config
This PR addresses "Unable to run pre hooks for 'compile', command 'compile' in namespace 'asn' not found." when calling `rebar3 compile`.
* Old path not found
* Use my fork.
> Fix ASN1 provider not found

- big_tests/tests/login_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- doc/Advanced-configuration.md
- rel/files/mongooseim.cfg
- rel/mim1.vars.config
- src/mongoose_scram.erl
As described in the docs changes, it follows the recommendations from
* https://xmpp.org/extensions/xep-0438.html#pbkdf2
* https://pages.nist.gov/800-63-3/sp800-63b.html#sec5
> SCRAM iteration count default increased to 10k

- doc/Advanced-configuration.md
- src/sasl/cyrsasl.erl
As per the XMPP core RFC, the authentication mechanisms that are advertised to the client `SHOULD be in order of perceived strength to enable the strongest authentication possible.`
[https://tools.ietf.org/html/rfc6120#section-6.3.3](https://tools.ietf.org/html/rfc6120#section-6.3.3)
New order of advertising the authentication mechanisms is the following:
```xml
<mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
<mechanism>SCRAM-SHA-512-PLUS</mechanism>
<mechanism>SCRAM-SHA-512</mechanism>
<mechanism>SCRAM-SHA-384-PLUS</mechanism>
<mechanism>SCRAM-SHA-384</mechanism>
<mechanism>SCRAM-SHA-256-PLUS</mechanism>
<mechanism>SCRAM-SHA-256</mechanism>
<mechanism>SCRAM-SHA-224-PLUS</mechanism>
<mechanism>SCRAM-SHA-224</mechanism>
<mechanism>SCRAM-SHA-1-PLUS</mechanism> …
```
> Order of advertising the auth mechanisms

- big_tests/tests/accounts_SUITE.erl
The aim of this PR it to make sure that authentication backend functionalities are tested similarly for both scram and plain password formats. 
Most of the test SUITEs are running with the default password format. This caused some of the functionalities not to be covered in the tests e.g. it turned out that change_password for riak backend was not working properly when password_format was set to scram (fixed in PR #2737).
Now, as the password format changed to scram, change_password was not testing plain format in the similar manner it was for scram.
This PR adds change_account_details_store_plain test that is changing password format to plain before running tests that are changing the account details.
> Test change_password for both password formats

- big_tests/tests/amp_big_SUITE.erl
- big_tests/tests/multiple_config_cth.erl
AMP test suites check a matrix of conditions, e.g.
- Actions like `notify`, `error`, `drop`
- Delivery conditions like `direct`, `stored`, `none` and their combinations
This increases the number of test cases. To avoid coding every intersection of these conditions, there is a need to generate some of them. Currently this is achieved by nesting test groups, but this prevents them from running in parallel. Long group names need to be generated, what makes the test setup less readable as well.
The proposed solution is to have a new common test hook (see https://erlang.org/doc/man/ct_hooks.html) to set up a list of Config's for each test case. This would speed up the tests significantly by running them in parallel, avoid nesting groups too much and eliminate the need for hardcoding or …
> Improve parallelism of AMP tests

- big_tests/tests/amp_big_SUITE.erl
- doc/modules/mod_amp.md
- include/amp.hrl
- src/amp.erl
- src/amp_resolver.erl
- src/amp_strategy.erl
- src/mam/mod_mam.erl
- src/mod_amp.erl
- test/amp_resolver_SUITE.erl
**Bug fix**
When MongooseIM fails to deliver the message to the recipient and message archive is enabled, there was no notification from AMP for the `stored` delivery condition although the message was stored successfully.
**Motivation**
On failed delivery we need to always trigger AMP delivery conditions: either ‘none’ or ‘stored’. There shouldn't be a case when no condition is triggered.
**Changes**
- Add ‘stored’ as a possible delivery condition on delivery failure.
- If there is an ‘undecided’ delivery rule for a final delivery event, match it (this helps resolve ambiguous cases).
- Only the first rule can be matched for ‘error’ and ‘drop’ actions - this prevents ‘stored’ events from being matched during the initial check if the user is online.
- Detailed docs added, describing the …
> Amp logic fix

- big_tests/tests/amp_big_SUITE.erl
Kill Bob's connection to avoid errors with closing the stream while the session is being resumed after the simulated error.
As the AMP tests don't test session resumption, killing the session is enough.
> Fix closing stream after simulated connection failure

- doc/migrations/3.7.0_3.7.x.md
- src/amp.erl
- src/ejabberd_c2s.erl
- src/ejabberd_sm.erl
- src/mam/mod_mam.erl
- src/mod_amp.erl
- src/mongoose_hooks.erl
- src/offline/mod_offline.erl
This is a **refactoring** PR, there are no intended changes in functionality.
Before:
- AMP stored its intermediate state (undecided rules) in the stanza itself.
- The state was removed with the whole AMP element from the stanza when the processing is finished.
After:
- AMP stores its intermediate state in `mongoose_acc` under the `{amp, rules}` key.
- The AMP element is removed at the `initial_check`.
- The state `{amp, rules}` is left in the acc after the last state for debugging - to know the final AMP state.
> Amp using acc

- big_tests/tests/inbox_SUITE.erl
- big_tests/tests/inbox_helper.erl
- big_tests/tests/mam_helper.erl
- include/ejabberd_c2s.hrl
- src/adhoc.erl
- src/ejabberd_c2s.erl
- src/ejabberd_config.erl
- src/inbox/mod_inbox.erl
- src/jlib.erl
- src/mam/mod_mam.erl
- src/mam/mod_mam_muc.erl
- src/mam/mod_mam_riak_timed_arch_yz.erl
- src/mam/mod_mam_utils.erl
- src/mod_muc_room.erl
- src/mod_time.erl
- src/offline/mod_offline.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/pubsub_form_utils.erl
Replace the custom functions in `jlib` for generating and parsing timestamps according to ISO 8601 with the corresponding function from the `calendar` module in the Erlang standard library.
Also:
- Remove unused time conversion utilities from `mod_mam_utils`
- Get rid of unnecessary conversions to `calendar:datetime()` and back when they happen one after the other
This is a refactoring PR, there are no functionality changes intended.
- The library functions verify the format of the parsed timestamps.
- There might be minor changes related to verification details - IMO it is better to trust the library implementation as it is [tested](https://github.com/erlang/otp/blob/master/lib/stdlib/test/calendar_SUITE.erl#L190) and the custom one had no tests.
> Use calendar for  ISO-8601 / RFC 3339 timestamp processing

- big_tests/tests/mam_SUITE.erl
- big_tests/tests/mam_helper.erl
- big_tests/tests/muc_SUITE.erl
- big_tests/tests/muc_light_SUITE.erl
- big_tests/tests/muc_light_legacy_SUITE.erl
- include/mongoose_ns.hrl
- src/mam/mod_mam_utils.erl
Advertise the namespaces according to XEP-0424 v0.3.0:
- `urn:xmpp:message-retract:0` when MAM is enabled as retraction messages are archived in MAM
- `urn:xmpp:message-retract:0#tombstone` when message retraction is enabled as it uses tombstones
> Update advertised message retraction namespaces

- doc/operation-and-maintenance/Cluster-management-considerations.md
Since the scalability blog posts refers a reader to our documentation, this info should be there first.
> added info about OS settings for high scalability

- big_tests/Makefile
- big_tests/run_common_test.erl
We initialized the JID deps only batch testing, but not for the interactive console.
> Fix 'make console' in big_tests by initializing stringprep

- src/ejabberd_sm.erl
If there is more than one session for the given full JID,
choose the one with the highest session ID.
Motivation:
- Fix a bug during resumption: stanzas were not routed to the user
- Make the function consistent with get_session/1
> Do not return 'none' from get_session_pid if there are many sessions

- rel/files/mongooseim
After this PR change place for the possible `erl_crash.dump` will be explicitly set to `${RUNNER_LOG_DIR}/erl_crash.dump`.
> Set directory for erl_crash.dump

- tools/circle-build-and-push-docker.sh
This PR aims to restore Tide notifications to Github, to be shown there together with Travis and CircleCi status. The fix includes:
* pass full git commit sha (not the short form) to be later used by Tide when posting status to Github
* update the github access token for Tide (this part is to be done in Tide repo)
> Fix tide status in github

- big_tests/tests/connect_SUITE.erl
- big_tests/tests/login_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- big_tests/tests/s2s_helper.erl
This PR replaces some of the places in `big_tests` where config templating and application restart was needed to test some things. Now only relevant parts of MongooseIM are reconfigured and restarted when needed.
> Get rid of conf reload in tests

- .gitignore
- Makefile
- big_tests/run_common_test.erl
- big_tests/test.config
- big_tests/tests/component_SUITE.erl
- big_tests/tests/conf_reload_SUITE.erl
- big_tests/tests/connect_SUITE.erl
- big_tests/tests/ejabberd_node_utils.erl
- big_tests/tests/login_SUITE.erl
- big_tests/tests/reload_helper.erl
- big_tests/tests/sasl_external_SUITE.erl
- rebar.config
- rel/fed1.vars-toml.config
- rel/files/mongooseim.toml
- rel/mim1.vars-toml.config
- rel/mim2.vars-toml.config
- rel/mim3.vars-toml.config
- rel/reg1.vars-toml.config
- rel/vars-toml.config.in
- src/auth/ejabberd_auth.erl
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_reload.erl
- src/ejabberd_config.erl
- test/config_parser_SUITE_data/mongooseim-pgsql.toml
- test/mongoose_config_SUITE.erl
- tools/test_runner/apply_templates.erl
Use the mustache templates for the TOML config file - make it work the same as for the '.cfg' file.
Notes:
- Failures for big tests are expected on CI except `pgsql_mnesia`, which should pass
- There is a fix for getting hosts by auth method. This bug was revealed by the TOML config which provided a list of methods (which should be valid) instead of an atom with one method.
- The templating is a bit inconsistent: sometimes we template only the value and sometimes one or more key-value pairs. It could be more organised, but this might be done as a separate story - not to change too much in one go. This is consistent with how it worked with 'cfg'.
- The templated config file contains a lot of empty lines, maybe this could be improved, but this falls outside of the scope of this story.
- …
> TOML config templating

- big_tests/test.config
- rel/mim1.vars-toml.config
- src/config/mongoose_config_parser_toml.erl
- tools/install
Fix little issues with TOML.
The goal is to make all the tests green.
This does not mean that all config options that are documented in https://mongooseim.readthedocs.io/en/latest/ are working.
That would be another story - and a big one. It has to be done eventually, hopefully before the next release. The best way to do it would be to add relevant tests, especially that we are reducing the amount of config parsing in tests, see https://github.com/esl/MongooseIM/pull/2797
> TOML config fixes

- include/mongoose.hrl
- rel/files/mongooseim
- src/config/mongoose_config_parser.erl
- src/config/mongoose_config_parser_cfg.erl
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_reload.erl
- src/config/mongoose_config_terms.erl
- src/ejabberd_config.erl
- test/config_parser_SUITE.erl
- test/ejabberd_config_SUITE.erl
- test/mongoose_config_SUITE.erl
**Functional changes**
Choose config format (cfg or TOML) by looking at file extension. Previously even though the configured path ended with 'cfg', the '.cfg' file extension was stripped and if there was a '.toml' file with the same root name, it was used instead. This was counter-intuitive and now the config file name is configured explicitly - it is `mongooseim.toml` by default.
There is no implicit fallback to `mongooseim.cfg` anymore.
Having one explicitly configured config path is less error prone.
Right now the way to change it would be to edit the `mongooseim` script. We could make it simpler if we want to support both formats. The goal for now is to keep only TOML after a possible transition period (not decided yet).
**Refactoring**
- Move the parser of the `cfg` format to …
> TOML config split

- big_tests/tests/http_helper.erl
- big_tests/tests/mod_http_notification_SUITE.erl
- big_tests/tests/push_http_SUITE.erl
- test/http_helper.erl
Except for the place where the http pool passes a map instead of a list, this is the state of the big_tests that #2716 should be able to pass. Once this is merged to master, the http2 PR should rebase onto it and pass these tests successfully.
Note that the problem for gun was about pools being initialised before there was an available listener: in the modified test suites, the pools where being initialised earlier in the `init_per_x` hierarchy, hence gun's connection wasn't available.
Note that there's one important test, that in my fork of http2 with these tests gun is not passing, and that is the `mod_http_listener` `simple_message_no_listener` test, where there's precisely no listener. This is failing because the request timeout is of 5 seconds, so the client's process is blocked for …
> Reorganise http related test_suites

- Makefile
- big_tests/default.spec
- big_tests/run_common_test.erl
- big_tests/test.config
- big_tests/tests/config_format_SUITE.erl
- big_tests/tests/ejabberd_node_utils.erl
- rel/files/mongooseim.cfg
- rel/mim1.vars.config
- src/config/mongoose_config_parser_toml.erl
Test that equivalent `toml` and `cfg` config files result in the same contents in the `config`, `local_config` and `acl` ETS tables in MongooseIM.
- Template both config files in big tests.
- Add the test case.
- Fix any inconsistencies discovered by the tests.
See commit messages for more details.
> Config format equivalence tests for all presets

- src/config/mongoose_config_parser_toml.erl
1. Parse TOML structures with two functions: `parse_map` and `parse_list`.
2. Reorder functions according to the order of sections in the TOML config file.
3. Add function specs for input types (TOML sections, keys, values) and output types (config records and options).
4. Annotate each function with the TOML path it is processing.
Planned next steps:
1. Renaming the functions for increased consistency.
2. Research on converting the annotations to code - more details coming soon.
> TOML config parser refactoring

- src/config/mongoose_config_parser_toml.erl
- Call the 'handler' function for each value in a section or list
Motivation: keep the functions separate while passing the path
down the tree and having a common entry point for nodes.
This allows introducing validation and having validation results
tagged with the path where the error is located.
Path annotation becomes redundant now and is left only for better
readability.
> TOML config parser refactoring: paths and handlers

- src/config/mongoose_config_parser_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/s2s_only.cfg
- test/config_parser_SUITE_data/s2s_only.toml
This PR adds support for all s2s options in the TOML config file
* Introduced new variable names in the config file (not documented yet!)
* Updated parser to properly use new options
* Added separate test for s2s options only
> Add support for all s2s options

- src/config/mongoose_config_parser.erl
- src/config/mongoose_config_parser_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/miscellaneous.cfg
- test/config_parser_SUITE_data/miscellaneous.toml
- test/config_parser_SUITE_data/mongooseim-pgsql.cfg
This PR adds support for missing options in the following sections:
* general
* auth
* listen
* services
Additionally, a few changes had to be made in the existing code to accomodate for some of the new options.
> Add support for miscellaneous opts

- big_tests/tests/ejabberdctl_SUITE.erl
Just a quick fix that was missed when the jid module was extracted as a library and integrated into big_tests. We can do `jid:from_binary/1` locally now, no need for RPCs.
> Use local jid module in big_tests

- src/mam/mod_mam_utils.erl
Fix the `start_stringprep` function in the EUnit test code in `mod_mam_utils.erl` so that `rebar3 eunit` doesn't fail.
No changes outside EUnit test code.
Closes #2844.
> Fix EUnit test in mod_mam_utils.erl (Issue esl#2844)

- rel/fed1.vars.config
- rel/mim1.vars.config
- rel/mim2.vars.config
- rel/mim3.vars.config
- rel/reg1.vars.config
- rel/vars.config.in
- tools/configure
Closes #2832
In `mim1.vars.config`, `mim2.vars.config` etc., the `mongooseim_lock_dir` setting is configured as follows:
```
{mongooseim_lock_dir, "$EJABBERD_DIR/var/lock"}.
```
But nothing sets `EJABBERD_DIR` during the build process, so the big tests end up writing the lock file in `/var/lock`, which fails if the big tests are running as a user that doesn't have permission to write to that directory.
I've changed it to:
```
{mongooseim_lock_dir, "$RUNNER_BASE_DIR/var/lock"}.
```
Please let me know if I've missed something and there is some reason that it should be different, or some process that would set `EJABBERD_DIR` for the build.
> Change mongooseim_lock_dir specified for big tests so it's not /var/lock

- src/config/mongoose_config_parser_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/outgoing_pools.cfg
- test/config_parser_SUITE_data/outgoing_pools.toml
This PR addresses [MIM-1110](https://erlangsolutions.atlassian.net/secure/RapidBoard.jspa?rapidView=3&projectKey=MIM&modal=detail&selectedIssue=MIM-1110)
* Added support for new connection types (http, rabbit)
* Added support for missing options for already existing connection types
Note:
There are still pool options that are not parsed. We decided to only add them when needed because most of them are never used anywhere. Full list of these options is [here](https://github.com/inaka/worker_pool#starting-a-pool)
> Added support for all outgoing_pools options

- big_tests/tests/ejabberdctl_SUITE.erl
- src/admin_extra/service_admin_extra_sessions.erl
- src/ejabberd_c2s.erl
- src/ejabberd_sm.erl
- src/mongoose_client_api/mongoose_client_api_sse.erl
- src/mongoose_lib.erl
- src/mongoose_types.erl
- test/ejabberd_c2s_SUITE_mocks.erl
This PR addresses "I don't want to bring back now_to_microseconds/1".
* Shorter byte size for SIDs.
* We don't really need nanoseconds.
* `ejabberd_sm:sid/0` is now defined!
* `ejabberd_sm:clean_session_list/1` spec fixed.
* `mongoose_types` - new file for cool types.
> system_time in sid

- big_tests/tests/sasl_external_SUITE.erl
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
Test and validate auth options.
Also: remove the confusing "cyrsasl_*" prefix.
> TOML config: validate auth options

- big_tests/tests/mod_http_upload_SUITE.erl
Closes #2838
Issue [162](https://github.com/cmullaparthi/ibrowse/issues/162) affecting ibrowse 4.4.1 means that it always resolves `localhost` to the IPv6 address `::1` rather than the IPv4 address `127.0.0.1` (because calls `inet:gethostbyname(Host, inet6)` explicitly).  This causes failures of the big test mod_http_upload_SUITE on IPv4-only systems such as docker with the default settings.
This change bypasses DNS and uploads to minio at `127.0.0.1` explicitly.  Only the big test code is affected.
> Upload to minio at 127.0.0.1 not localhost to avoid IPv6 / DNS issues (#2838)

- .circleci/config.yml
- .gitignore
- .travis.yml
- Makefile
- tools/print-dots.sh
- tools/travis-test.sh
This PR is done in a context of this issue https://github.com/esl/MongooseIM/issues/2844
There is no integration of eunit execution into `test-runner.sh` script (no dedicated options to control it).  to run eunit tests you can use `make eunit` or `./rebar3 eunit` command
However, `test-runner.sh` can be used for quick manual testing of the changes in `travis-test.sh`. For that you have set  `EUNIT_TESTS` env variable. 
```
EUNIT_TESTS=true test-runner.sh --skip-big-tests --skip-small-tests --skip-build-mim --skip-build-tests
```
eunit tests are triggered for `small_tests` CI jobs on Travis and CircrleCI. the summary of execution is printed in the console.
the full log is uploaded to AWS in the `logs` directory (e.g. see `eunit.log` file …
> eunit execution in CI tests

- big_tests/tests/rest_SUITE.erl
- doc/rest-api/Administration-backend_swagger.yml
- src/mod_commands.erl
- src/mongoose_api_common.erl
- src/mongoose_commands.erl
This PR addresses a need for more advanced integrations - current messaging endpoint requires a client to submit a message body and nothing else, while some clients want to use some extensions and want to define the whole contents of a message, or send some other arbitrary stanzas.
* a rest endpoint for admin user which accepts any stanza, provided it has from and to attributes
* updated rest suite
* updated swagger docs
> rest endpoint for sending stanzas

- big_tests/tests/pubsub_s2s_SUITE.erl
- rel/fed1.vars.config
- src/pubsub/mod_pubsub.erl
Closes #2779 
Change the response to a publish stanza that lacks a `node` attribute.  Currently, a node with a random name will be auto-created.  But [XEP-0060](https://xmpp.org/extensions/xep-0060.html#publisher-publish-request) states:
> The element MUST possess a 'node' attribute, specifying the NodeID of the node.
XEP-0060 is not clear on what error should be returned if the node attribute is missing, so I've implemented the same response that it specifies for [retract](https://xmpp.org/extensions/xep-0060.html#publisher-delete-error-nodeid) and [configure](https://xmpp.org/extensions/xep-0060.html#owner-configure-error-nodeid) stanzas that lack NodeIDs:
```
<error type='modify'>
<bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
<nodeid-required …
```
> Reject publish to non-existent pubsub node with nodeid-required

- src/logger/mongoose_log_filter.erl
This PR addresses an issue I noticed with the logfmt logger.
Calling logger macros like this:
```
?LOG_ERROR("Supervisor received unexpected message: ~tp~n",[{'ETS-TRANSFER',mod_global_distrib_bounce_message_store_by_target,self(),testing}],
#{domain=>[otp],
error_logger=>#{tag=>error}}),
```
resulted in crashes like this:
```
2020-09-07T17:46:08.318748+00:00 error: FORMATTER CRASH: {"Supervisor received unexpected message: ~tp~n",[{'ETS-TRANSFER',mod_global_distrib_bounce_message_store_by_target,<0.31591.1>,testing}]}
```
This example is derived from OTP's Supervisor way of logging ([line in source](https://github.com/erlang/otp/blob/62280d6952150805788025fe0da0343a60dd1f69/lib/stdlib/src/supervisor.erl#L587))
Such crashes can be observed for example …
> Fix formatter crashes due to format strings

- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
Parse the 'acl' section in a more structured way,
matching exact rules from the 'acl' module.
> Validate the 'shaper', 'acl' and 'access' sections

- rel/files/mongooseim.toml
- src/config/mongoose_config_parser_cfg.erl
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- src/ejabberd_s2s_out.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/mongooseim-pgsql.toml
- test/config_parser_SUITE_data/s2s_only.toml
Validate and test the `s2s` options.
Some fixes and improvements to this section:
- Make subsections out of the `dns` and `outgoing` option groups
- Clean up the parsing logic, use the `handler` where possible
- Decouple the internal representation of the IP versions (address families) and the connection timeout to improve code structure.
See the individual commits for more details.
Note: the `domain_certfiles` options should be moved out of the s2s section, preferably to `host_config`, as it also affects c2s listeners. This is not urgent, but it would be good to create a story for it.
> TOML: test and validate s2s options

- doc/Advanced-configuration.md
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/miscellaneous.cfg
- test/config_parser_SUITE_data/miscellaneous.toml
Test host config: each allowed option is now validated and tested for both cases: per-host and globally.
Handling of host config was also reworked - see the individual commits for details.
The main motivation was to avoid having two separate clauses in the parser for handling the global and per-host option.
> TOML: validate host config

- src/config/mongoose_config_parser_toml.erl
- test/config_parser_SUITE_data/mongooseim-pgsql.cfg
- test/config_parser_SUITE_data/mongooseim-pgsql.toml
This PR fixes the way we parsed `mongoose_api_client` and `mongoose_api_admin` options. They are moved to `listen.http.handlers` subsection
> fix mongoose_api_admin and mongoose_api_client opts

- big_tests/default.spec
- big_tests/tests/extdisco_SUITE.erl
- include/mongoose_ns.hrl
- rel/files/mongooseim.cfg
- src/mod_extdisco.erl
This PR adds support for [XEP-0215 External Service Discovery](https://xmpp.org/extensions/xep-0215.html). An XMPP client or other entity might need to discover services external to the XMPP network in order to complete certain XMPP-related use cases. One example is the discovery of STUN servers and TURN relays.
Connecting MongooseIM+MongooseICE duet to client applications like `Conversations` or `Movim` and allow for video/voice calling requires support for XEP-0215.
It is implemented as an `iq_handler` for `urn:xmpp:extdisco:2` namespace and returning details of an external service that are specified in the configuration file. 
There are three types of requests that are supported:
* get all services with all their details (host, type, port, transport, username, password)
* get services …
> Exrternal Service Discovery - XEP-0215

- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/outgoing_pools.cfg
- test/config_parser_SUITE_data/outgoing_pools.toml
Follow-up on https://github.com/esl/MongooseIM/pull/2872/ in order to remove configuration related to gun, as we've reverted back to fusco. Custom fusco opts are not allowed.
> Change http_opts config from gun to fusco

- src/ejabberd_cowboy.erl
Fix a small typo that would stop the `num_acceptors` configuration outside `transport_options` from being applied.
> Fix a typo "num_acceptros"

- src/auth/ejabberd_auth_dummy.erl
- src/auth/ejabberd_auth_pki.erl
- src/gen_mod.erl
- src/global_distrib/mod_global_distrib_hosts_refresher.erl
- src/jingle_sip/mod_jingle_sip.erl
- src/mam/mod_mam.erl
- src/mam/mod_mam_muc.erl
- src/mam/mod_mam_params.erl
- src/mod_muc_db.erl
- src/mod_muc_db_mnesia.erl
- src/sasl/cyrsasl_external.erl
I spotted a few places where types that used to be in `ejabberd` but are now only in `jid` were still being referred to as members of the `ejabberd` module.  This means dialyzer is not checking type safety for these functions.  I've done a find/replace on the code.
Once resolved, dialyzer still found no type safety issues.
> Replace ejabberd:server() with jid:server(), also lserver, [l]user and [l]resource

- src/config/mongoose_config_parser_toml.erl
- test/config_parser_SUITE.erl
This PR addresses "consistency for mod_mam_meta" configuration.
> Set pm/muc sections to false by default for TOML in mod_mam_meta

- doc/Advanced-configuration.md
- doc/advanced-configuration/access.md
- doc/advanced-configuration/host_config.md
- mkdocs.yml
- src/config/mongoose_config_parser_toml.erl
- test/config_parser_SUITE.erl
Document the `host_config` section.
Fix the 'scope' definition in the docs as well.
> TOML docs: host_config

- big_tests/tests/extdisco_SUITE.erl
- doc/modules/mod_extdisco.md
- rel/files/mongooseim.cfg
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- src/mod_extdisco.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/modules.cfg
- test/config_parser_SUITE_data/modules.toml
This PR adds `mod_extdisco` in TOML format. The changes include:
* adding module in parser and validator
* modify the config format in cfg
* tests for config_parser_SUITE
* documentation update to TOML format
> add mod_extdisco in TOML format

- doc/advanced-configuration/listen.md
- doc/rest-api/Administration-backend.md
- doc/rest-api/Client-frontend.md
- doc/rest-api/Metrics-backend.md
- doc/rest-api/README.md
This PR updates the documentation of REST API to use the TOML config format.
I also found some typos and deleted a file (`doc/rest-api/README.md`) that seemed to be not needed and was popping up when starting the docs as not included in the site navigation.
> Toml/doc REST API update

- rel/files/app.config
- src/config/mongoose_config_parser_toml.erl
- src/logger/mongoose_log_filter.erl
- test/config_parser_SUITE.erl
Make the TOML errors more readable by the user.
When loading the configuration fails:
- Log all the TOML-related errors, make sure the 'what' and 'text' attributes in the log message contain the proper description of the error
- Exit with a concise error message
For more details, see the individual commit messages.
**Note:** the 'tomerl' library is quite limited:
- it is not possible to print out the faulty lines in the config
- some error messages are unhandled in 'tomerl:format_error' 
- neither this nor any other Erlang library allows formatting/printing TOML
We might consider forking and extending this library.
> TOML: user-friendly errors

- doc/advanced-configuration/Services.md
- doc/advanced-configuration/database-backends-configuration.md
- doc/advanced-configuration/outgoing-connections.md
- doc/modules/mod_shared_roster_ldap.md
- doc/rest-api/Administration-backend_swagger.yml
This PR updates the `doc/advanced-configuration/database-backends-configuration.md `.
I also think there was an error in the listeners docs concerning the path.
I'm not sure if the provided configuration for MS SQL is correct
> Toml/doc db-backends conf update

- doc/modules/mod_muc_light.md
- doc/operation-and-maintenance/Cluster-configuration-and-node-management.md
- doc/operation-and-maintenance/Cluster-management-considerations.md
- doc/operation-and-maintenance/Logging-&-monitoring.md
- doc/operation-and-maintenance/Logging.md
- doc/operation-and-maintenance/Mongoose-metrics.md
- doc/operation-and-maintenance/Reloading-configuration-on-a-running-system.md
- doc/operation-and-maintenance/System-Metrics-Privacy-Policy.md
- doc/operation-and-maintenance/gdpr-considerations.md
- doc/operation-and-maintenance/known-issues.md
- doc/operation-and-maintenance/tls-distribution.md
- rel/files/mongooseimctl
- src/ejabberd_admin.erl
- src/ejabberd_config.erl
This PR updates the Operation and Maintenance part of the documentation to reflect the TOML configuration. It also contains many general fixes, like typos, grammar, etc (sometimes in files located outside the O&A part of the docs).
I did **not** touch the `Reloading-configuration-on-a-running-system.md` file as I'm not sure what to do with it. It seems to not really be reflected in the new TOML config (e.g. no `node_specific_options` in the TOML config). I hesitated from adding something like "This functionality is only available if you are using the older, `cfg` config format" but this may be the best way to deal with this issue for now. I'd be happy to hear reviewers opinions on this topic.
> Toml/doc Operation and Maintenance update

- big_tests/tests/muc_SUITE.erl
It takes about 4s to compile 'mod_muc_room' on CI, so it is likely that long compilation causes random failures like [this one](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/2903/34413/riak_mnesia.23.0.3-1/big/ct_run.test@default-c3abfa5b-16b9-48fe-ab56-a53b143e6468.2020-10-08_07.30.10/big_tests.tests.muc_SUITE.logs/run.2020-10-08_07.41.54/suite.log.html)
> Increase meck timeout to 10s to prevent timeouts

- tools/pkg/scripts/deb/build_package.sh
- tools/pkg/scripts/rpm/mongooseim.spec
Removes `_build` and `asngen` before  `make install` to remove any
locally compiled artifacts before making RPMs and Debian packages.
For local development this prevents compiled artifacts from your
your local operating system sneaking into the packages.
> Clean before install

- big_tests/tests/accounts_SUITE.erl
- doc/modules/mod_offline_stub.md
- src/admin_extra/service_admin_extra_accounts.erl
- src/admin_extra/service_admin_extra_gdpr.erl
- src/admin_extra/service_admin_extra_last.erl
- src/admin_extra/service_admin_extra_private.erl
- src/admin_extra/service_admin_extra_roster.erl
- src/admin_extra/service_admin_extra_vcard.erl
- src/auth/ejabberd_auth.erl
- src/auth/ejabberd_auth_external.erl
- src/auth/extauth.erl
- src/ejabberd_sm.erl
- src/ejabberd_users.erl
- src/mam/mod_mam.erl
- src/mod_disco.erl
- src/mod_register.erl
- src/mod_shared_roster_ldap.erl
- src/mod_vcard_ldap.erl
- src/mongoose_api_users.erl
- src/offline/mod_offline.erl
- src/offline/mod_offline_stub.erl
- src/sasl/cyrsasl_anonymous.erl
- test/auth_http_SUITE.erl
- test/auth_jwt_SUITE.erl
Up to now, in ejabberd_auth, we've had two almost identical functions,
`is_user_exists` and `does_user_exist`. This is redundant and confusing,
so I've just default back to an overloaded `does_user_exist`, where one
takes a full JID, and the other takes a username and server and creates
a JID and calls the first. The goal would be to eventually get rid of
the non-JID one and use only typed data-structures.
> Unify does_user_exist API

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- src/ejabberd_config.erl
- src/system_metrics/mongoose_system_metrics_collector.erl
This PR adds a metric to see what type of configuration file is being used. The aim is to determine the adoption of the new config file format.
> add metric: type of config file

- tools/circle-build-and-push-docker.sh
- Config file updated to 'mongooseim.toml'
- Ubuntu version fixed at 18.04
This PR attempts to fix the issue of building MongooseIM on CircleCI with Ubuntu 16.04 and using the resulting tarball to build a docker image based on Ubuntu 20.04 - these two had incompatible library versions and recent MongooseIM docker images were not starting at all.
The two still don't align completely (16.04 and 18.04), but the image for [this PR](https://hub.docker.com/layers/mongooseim/mongooseim/PR-2926/) does not crash on startup.
Possibilities:
1. Run CircleCI on Ubuntu 20.04, upgrade Docker image to 20.04 - needs fixing multiple issues, see https://github.com/esl/MongooseIM/pull/2925
2. Run CircleCI on Ubuntu 18.04 in Docker (no machine for 18.04) - most likely even more difficult, but we could reduce …
> Use the latest mongooseim-docker

- src/rdbms/mongoose_rdbms_pgsql.erl
This PR addresses slow simple prepared queries:
Before:
```
> load_test(legacy, 100).
{417789,ok}
> load_test(upsert, 100).
{514556,ok}
```
```after
> load_test(legacy, 100).
{417789,ok}
> load_test(upsert, 100).
{417433,ok}
```
Both upsert and update_first versions consume same amount of time.
* One less roundtrip to **postres** on execute.
* Do `epgsql:describe` in the prepare step, not in the execute step, because it goes to the server to get data.
Code for micro-banchmarking:
```erlang
load_test(Method, Times) ->
timer:tc(fun() -> test_xml_times(Method, Times) end).
test_xml_times(_Method, 0) ->
ok;
test_xml_times(Method, Times) ->
mod_private_rdbms:multi_set_data(Method, <<"alice">>, <<"localhost">>,
[{<<"alice:private:ns">>, test_xml(Times)}]), …
```
> Reduce execution time by 20% for simple prepared queries in postgres

- include/mod_roster.hrl
- src/admin_extra/service_admin_extra_roster.erl
- src/auth/ejabberd_auth.erl
- src/mod_commands.erl
- src/mod_roster.erl
- src/mongoose_client_api/mongoose_client_api_contacts.erl
- src/muc_light/mod_muc_light.erl
- test/roster_SUITE.erl
PROBLEM: if we pass forward an “untyped” binary for the user, server, and/or resource of a jid, we don’t know if it has been stringprepped or not, so we are always stringprepping again and again things that probably were stringprepped already, wasting CPU time. This was seen in profiles when working on the ejabberd_sm (#2582) case.
SOLUTION: Rewrite function calls to pass a #jid{} record, which is clear about its pieces, and extract the stringprepped chunks only on the place where it is used.
TO BE DONE: This is not changing any of the hooks, so it still doesn't introduce any incompatibilities. A subsequent work will do so.
> Reduce stringprepping for roster modules

- big_tests/tests/connect_SUITE.erl
- tools/ssl/Makefile
So there are two important fixes here.
The first thing is that the cipher `ECDHE-RSA-AES256-GCM-SHA384` belongs strictly to the tls 1.2 version, so in order to pass the test called `clients_can_connect_with_ECDHE-RSA-AES256-GCM-SHA384_only` needs to request using this version alone, otherwise the client will be able to connect with many more ciphers and this test would fail.
The second thing is that, in ubuntu, Diffie-Hellman keys that are known to be to small are disallowed by default, due to the Logjam vulnerability, so the dh size parameter needed to be incremented in the makefile for the ssl certificates. Why this is not an issue in the latest MacOS, I don't know.
But with this, TLS issues for the latest ubuntu are fixed.
The first two commits are from …
> TLS and Ubuntu

- doc/advanced-configuration/listen.md
- include/ejabberd_config.hrl
- rel/mim3.vars-toml.config
- src/config/mongoose_config_parser.erl
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_spec.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/mongooseim-pgsql.options
- test/config_parser_SUITE_data/mongooseim-pgsql.toml
Declarative specification for the 'listen' configuration section.
See the commit messages for more details.
- Still using `export_all`
- Still no specs, they will come soon
- Record fields will also be documented soon
> TOML config: declarative spec for 'listen'

- Makefile
- big_tests/tests/dynamic_modules.erl
- rebar.config.script
- src/jingle_sip/mod_jingle_sip.erl
The trick is to tell `relx` that certain apps are to be only included in the runtime and their code loaded, but don't need to be started. This is done using the trick
```erlang
LoadApps = [{App, load} || App <- OptionalApps]
```
That is, for example, in the `relx` app list, doing `[..., {nksip, load}, ...]` instead of [..., nksip, ...].
`nksip` is nevertheless loaded in `mod_jingle_sip` doing the typical `application:ensure_all_started/1` and pattern-matching that it returns ok.
Co-authored-by Mikhail Uvarov
> Tag nksip apps as load-only for relx

- big_tests/run_common_test.erl
- big_tests/test.config
- big_tests/tests/ejabberd_node_utils.erl
- big_tests/tests/sasl_external_SUITE.erl
- doc/advanced-configuration/release-options.md
- rel/fed1.vars-toml.config
- rel/files/mongooseim.toml
- rel/mim1.vars-toml.config
- rel/mim2.vars-toml.config
- rel/mim3.vars-toml.config
- rel/reg1.vars-toml.config
- rel/vars-toml.config.in
- tools/test_runner/apply_templates.erl
The main change is to introduce [Mustache sections](http://mustache.github.io/mustache.5.html) to remove whitespaces occuring in the templated config files, including the default `prod` config file.
**Example.** The block below has the following semantics: if `var` is defined and not `false`, render an empty line followed by its contents.
```
{{#var}}     
{{{var}}}
{{/var}}
```
There is one caveat for `bbmustache` - strings are lists and would be treated as Mustache lists, so they need to be binarized in tests (rebar3 does this already when processing the overlays, but tests call bbmustache separately). Alternatively, all template variables could be converted to binaries, but I think it could make them a bit less readable.
> TOML improved config templates

- big_tests/tests/dynamic_modules.erl
- big_tests/tests/jingle_SUITE.erl
> Load nksip in parallel with big timeouts

- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_spec.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/s2s_only.options
- test/config_parser_SUITE_data/s2s_only.toml
Declarative specs for the 'shaper', 'acl', 'access' and 's2s' sections.
See the commit messages for more details.
> TOML: declarative specs for 'shaper', 'acl', 'access', 's2s'

- big_tests/tests/muc_SUITE.erl
- src/mod_muc_room.erl
This PR addresses the situation when a locked MUC room (locked on creation) receives `disco#info`. 
- Previously the room responded with error `The room is locked`. 
- With this PR when the owner of the locked room sends `disco#info` it is receiving supported features. 
- This PR aims to help with corner case situation from XMPP compliance tests.
> Locked MUC room disco#info

- test/auth_external_SUITE_data/sample_external_auth.py
Heh, there was some old usage of python2 in the small tests that was forgotten 😄
> Upgrade helper script in small tests to python3

- mkdocs.yml
This PR addresses [MIM-1238](https://erlangsolutions.atlassian.net/secure/RapidBoard.jspa?rapidView=3&projectKey=MIM&modal=detail&selectedIssue=MIM-1238)
It seems that most of the issues we had with the docs can be solved by finding an appropriate theme and this is the one that best suits our preferences. 
Left to do after merge -> upload new version of the docs to `readthedocs`
> Change readthedocs theme

- .circleci/config.yml
This follows exactly what was done for mongoose-push, hopefully should work here as well.
> Ensure envvar is in the environment for the next job

- doc/modules/mod_bosh.md
- doc/modules/mod_caps.md
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_spec.erl
- src/config/mongoose_config_validator_toml.erl
- src/gen_mod.erl
- src/mod_adhoc.erl
- src/mod_auth_token.erl
- src/mod_bosh.erl
- src/mod_caps.erl
- src/mod_carboncopy.erl
- src/mod_csi.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/modules.toml
Modules covered in this PR:
To be continued in the next PR:
- mod_disco
- mod_event_pusher
Checklist for each module:
- Write the new spec in the module as a callback function: `config_spec/0`. Some cases need reworking the options, e.g. when the same value can be a primitive (e.g. string or atom) or a nested section/list
- Add the module to `mongoose_config_spec:all_modules/0` and `HAS_NO_SPEC`
- Double check with the docs: `https://esl.github.io/MongooseDocs` that the options and their format, validator etc are correct
- Remove `module_opt` and `handler` clauses from `mongoose_config_parser_toml` as well as module-specific functions for nested options
- Remove `validate` clauses from `mongoose_config_validator_toml`
- Make sure this passes locally: `./rebar3 ct …
> TOML declarative modules (1/4)

- .circleci/config.yml
So this should now ensure the history from `MongooseDocs` is fetch ahead of the push, and if there's any conflict, it won't force the push, so we'd rather have CI failing than the docs getting lost.
```
git fetch git@github.com:esl/MongooseDocs.git gh-pages:gh-pages 
```
will basically make a local branch with such name and the contents of an altogether unrelated repo, the docs one.
> Fix duplication of branches and names

- big_tests/test.config
It wasn't finding the node to rpc to, hence the rpc to load the ct logger was failing.
A quick fix for errors like
```erlang
issue="Failed to init ct_mongoose_log_hook", node=undefined, reason={error,
{bad_absname,
{badrpc,
nodedown}}}
```
> Fix harmless ct hook error

- src/logger/mongoose_flatlog_formatter.erl
- src/logger/mongoose_json_formatter.erl
This PR addresses #2967 
Instead of allowing an error during log line formatting to propagate into `formatter_crashed`, which can then lead to a death spiral of formatters crashing as they try to format the `formatter_crashed` error, safely format a log message about the formatter crash.
This avoids the big tests failing at debug log level, and will also be safer for production use - any undiscovered bugs in log formatting won't be able to bring down the MongooseIM process.
Example of formatted log line produced by the modified JSON formatter in case of an error during formatting:
```
{"when":"2020-12-04T09:16:33.003295+00:00","what":"log_format_failed","reason":"badarg","level":"error","formatter_module":"mongoose_json_formatter","class":"error","cause_mfa":"{ejabberd_router,route,4}","ca …
```
> Catch log formatter errors to avoid death spiral of logging (issue #2967)

- include/ejabberd_config.hrl
- include/mongoose_config_spec.hrl
- src/admin_extra/service_admin_extra.erl
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_spec.erl
- src/config/mongoose_config_validator_toml.erl
- src/event_pusher/mod_event_pusher.erl
- src/event_pusher/mod_event_pusher_http.erl
- src/event_pusher/mod_event_pusher_push.erl
- src/event_pusher/mod_event_pusher_rabbit.erl
- src/event_pusher/mod_event_pusher_sns.erl
- src/mod_adhoc.erl
- src/mod_auth_token.erl
- src/mod_bosh.erl
- src/mod_caps.erl
- src/mod_carboncopy.erl
- src/mod_csi.erl
- src/mod_disco.erl
- src/system_metrics/service_mongoose_system_metrics.erl
Reasons:
- avoid record name conflicts in modules
- do not include unnecessary records to modules
> Move config spec records to a separate header file

- tools/setup_minio.sh
This PR addresses "missing nc command in the `minio/mc` container".
* Use `tools/wait_for_service.sh` to ensure the main minio container is started (similar the way we wait for other DB containers).
> Use wait_for_service.sh instead of netcat

- big_tests/tests/mam_SUITE.erl
- src/mam/mod_mam_rdbms_prefs.erl
- src/mam/mod_mam_rdbms_user.erl
- src/rdbms/mongoose_rdbms.erl
This PR addresses "Add prepared queries for the remaining parts of MAM"
* mod_mam_rdbms_user
* mod_mam_rdbms_prefs
> Add prepared queries for the remaining parts of MAM - user & prefs
