esl/MongooseIM

- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/mod_websockets.erl
* Always add xmlns for WS
* Expect acking session result if sm was enabled before session.
> Stanza.io compatibility

- apps/ejabberd/src/mod_carboncopy.erl
> Cleanup mod_carboncopy

- .gitignore
- apps/ejabberd/src/mod_mam_muc_odbc_async_pool_writer.erl
- apps/ejabberd/src/mod_mam_odbc_async_pool_writer.erl
solving this task https://github.com/esl/MongooseIM/issues/395
> mod_mam_odbc_async_pool_writer and mod_mam_muc_odbc_async_pool_writer configurable pool size

- apps/ejabberd/src/ejabberd_sm.erl
- apps/ejabberd/src/ejabberd_sm_redis.erl
- apps/ejabberd/test/ejabberd_sm_SUITE.erl
* Fix cleanup/1
* Clean sessions from prev life
> Redis improvements

- apps/ejabberd/src/mod_mam_con_ca_arch.erl
- apps/ejabberd/src/mod_mam_muc_ca_arch.erl
> mod_mam cassandra: create worker pool per node

- .travis.yml
- apps/ejabberd/src/ejabberd.app.src
- rel/reltool.config.script
- src/mongooseim.app.src
> Bug fix version 1.5.2

- README.md
A better PR?
The section title was misleading. And the packages to expect are named.
> Renamed quickstart section, added platorms

- README.md
- doc/README.md
[skip ci]
Reference from the website: https://www.erlang-solutions.com/sites/all/themes/erlang/img/mongoose/MongooseIM_blue.png
> Logo added

- apps/ejabberd/src/ejabberd_c2s.erl
This should fix esl/ejabberd_tests#130, but I've not been able to test this by myself yet.
According to RFC 6120, section 5.3.1 it's not recommended to send features before the client has finished STARTTLS:
http://xmpp.org/rfcs/rfc6120.html#tls-rules-mtn
I've stumbled on this with Gajim 0.16.3 on Windows but haven't yet able to reproduce this with the very same client on NixOS, Ubuntu and Debian.
While this originally was/is an issue with Gajim, MongooseIM really should implement what is recommended by the RFC, regardless of whether clients out there break because of this (or see it as an open invitation to send cleartext passwords).
> ejabberd_c2s: Omit features on required STARTTLS.

- apps/ejabberd/src/mod_ping.erl
- apps/ejabberd/src/mongoose_metrics_hooks.erl
- doc/modules/mod_ping.md
- mkdocs.yml
- test/ejabberd_tests/default.spec
- test/ejabberd_tests/rebar.config
- test/ejabberd_tests/tests/mod_ping_SUITE.erl
This PR:
* adds test for mod_ping
* makes iq reply timeout configurable in mod_ping
* waits for the ping process to stop before removing it from supervisor
> mod_ping tests

- doc/developers-guide/REST-interface-to-metrics.md
- rel/files/ejabberd.cfg
- rel/reltool_vars/node1_vars.config
- rel/reltool_vars/node2_vars.config
- rel/vars.config
- test/ejabberd_tests/test.config
This PR changes the default HTTP API endpoint so there is no risk that someone accidentally exposes the API to everyone.
> Change http api cfg

- test/ejabberd_tests/tests/mam_SUITE.erl
This should help with strange database connectivity issues on Travis.
Examine more than just the most recently archived message for the text
in the last message addressed to the recipient. Under certain failure
cases, e.g. database connectivity issues, the most recent message from
the archive might not be the last message addressed to the recipient.
> Fix `offline_message' test

- apps/ejabberd/src/mod_bosh.erl
- test/ejabberd_tests/tests/bosh_SUITE.erl
The GET method was implement only for Load Balancer's health checks. For example ELB uses this method.
> Bosh GET method

- apps/ejabberd/src/ejabberd_sm.erl
- apps/ejabberd/test/ejabberd_sm_SUITE.erl
> Metrics - return cached value if unique sessions count crashes

- Makefile
- apps/ejabberd/src/jlib.erl
- apps/ejabberd/test/jid_gen.erl
- apps/ejabberd/test/jlib_SUITE.erl
This PR creates tests for jlib module and cleans the module code a bit.
> Jlib tests and cleaning

- doc/advanced-configuration/HTTP-authentication-module.md
Explains how to avoid problem described in #423
> [skip ci] Add info about Content-Length to auth_http docs

- apps/ejabberd/src/ejabberd_admin.erl
- apps/ejabberd/src/mod_admin_extra_private.erl
- apps/ejabberd/src/mod_offline.erl
- apps/ejabberd/src/mod_offline_mnesia.erl
- apps/ejabberd/src/mod_offline_odbc.erl
- test/ejabberd_tests/tests/cluster_commands_SUITE.erl
- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
- test/ejabberd_tests/tests/ejabberdctl_helper.erl
-fixed `get_loglevel`, `delete_old_messages`, `delete_expired_messages` functions from `ejabberd_admin`
-removed obsolete and useless code
-tests for `ejabberd_admin` module
> Ejabberd admin coverage

- apps/ejabberd/src/mod_roster.erl
- apps/ejabberd/src/mod_roster_mnesia.erl
- apps/ejabberd/src/mod_roster_odbc.erl
- apps/ejabberd/src/mod_roster_riak.erl
- doc/advanced-configuration/database-backends-configuration.md
- doc/modules/mod_roster.md
- test/ejabberd_tests/test.config
- test/ejabberd_tests/tests/mongoose_helper.erl
- tools/setup_riak
> Add mod_roster_riak

- apps/ejabberd/src/mod_mam_muc_ca_arch.erl
- apps/ejabberd/src/mod_mam_muc_ca_sup.erl
- doc/modules/mod_mam.md
> Update Cassandra backend for MAM

- apps/ejabberd/src/acl.erl
- apps/ejabberd/src/ejabberd_config.erl
- apps/ejabberd/test/acl_SUITE.erl
- doc/advanced-configuration/acl.md
- mkdocs.yml
> Add tests and refactor the acl module

- README.md
> [skip ci] Product page

- apps/ejabberd/src/jlib.erl
- apps/ejabberd/src/mongoose_cover_helper.erl
- rel/reltool_vars/node2_vars.config
- test/ejabberd_tests/tests/connect_SUITE.erl
- tools/cipher_suites_test.sh
Fixes #370
These tests are using `openssl s_client` from Erlang VM.
> C2s ciphers tests

- README.md
> [skip ci] client libraries

- .travis.yml
- README.md
- apps/ejabberd/include/ejabberd.hrl
- apps/ejabberd/rebar.config
- apps/ejabberd/src/ejabberd.erl
- apps/ejabberd/src/ejabberd_binary.erl
- apps/ejabberd/src/ejabberd_config.erl
- apps/ejabberd/src/mongoose_metrics.erl
- apps/ejabberd/src/scram.erl
- apps/ejabberd/test/ejabberd_config_SUITE.erl
- apps/ejabberd/test/ejabberd_helper.erl
- apps/ejabberd/test/ejabberd_sm_SUITE.erl
- apps/ejabberd/test/mim_ct_rest.erl
- apps/ejabberd/test/mod_websockets_SUITE.erl
- apps/ejabberd/test/mongooseim_metrics_SUITE.erl
- apps/ejabberd/test/xmpp_route_SUITE.erl
- doc/user-guide/Getting-started.md
- rebar.config
- rebar.config.script
> Ditch support for R15B03 and older

- apps/ejabberd/src/ejabberd_admin.erl
- apps/ejabberd/src/mod_offline.erl
- apps/ejabberd/src/mod_offline_mnesia.erl
- apps/ejabberd/src/mod_offline_odbc.erl
- apps/ejabberd/src/mod_offline_riak.erl
- apps/ejabberd/src/mongoose_riak.erl
- rebar.config
- rel/reltool.config.script
- test/ejabberd_tests/test.config
- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
- test/ejabberd_tests/tests/mongoose_helper.erl
- test/ejabberd_tests/tests/offline_SUITE.erl
- tools/setup_riak
This PR:
* adds Riak backend for offline storage
* extends offline_SUITE
Resolves #586
> Riak offline

- apps/ejabberd/src/mod_privacy_riak.erl
- test/ejabberd_tests/test.config
- tools/setup_riak
> Support riak backend in mod_privacy module

- test/ejabberd_tests/tests/bosh_SUITE.erl
Erlang R15 is not supported anymore
> Remove version check from bosh_SUITE

- apps/ejabberd/src/ejabberd_ctl.erl
- apps/ejabberd/src/ejabberd_listener.erl
- apps/ejabberd/src/ejabberd_tls.erl
- apps/ejabberd/src/odbc_queries.erl
- test/ejabberd_tests/tests/s2s_SUITE.erl
> Remove some workarounds for old Erlang/OTP version

- test/ejabberd_tests/tests/metrics_api_SUITE.erl
Compare values with macros in metrics_api_SUITE
Fixing #648
> Expect nodeUptime to be incremented between two API calls #648

- apps/ejabberd/src/mod_privacy.erl
- apps/ejabberd/src/mod_roster_odbc.erl
- test/ejabberd_tests/tests/privacy_SUITE.erl
- test/ejabberd_tests/tests/privacy_helper.erl
This PR adds more test cases to privacy SUITE testing group and subscription based blocking.
> Improve privacy tests

- apps/ejabberd/src/ejabberd_auth_http.erl
- apps/ejabberd/test/auth_http_SUITE.erl
- apps/ejabberd/test/ejabberd_c2s_SUITE.erl
- apps/ejabberd/test/ejabberd_c2s_SUITE_mocks.erl
- rebar.config
This PR resolves #411.
Also includes #491.
> Improve ejabberd_c2s-related mocks for quick tests

- Makefile
- dialyzer.mk
This PR:
* moves dialyzer targets to dedicated file
* splits the big plt to 3 (for erlang, deps and apps)
> refactor dialyzer section in Makefile

- CHANGELOG.md
I hope it's not too heavy to read...
> [skip ci] Added some links

- rebar.config
Currently we are using version 2.0.2 which is almost 2 years old.
> Update lager to 3.0.2

- .travis.yml
- tools/docker/riak/Dockerfile
- tools/docker/riak/advanced.config
- tools/setup_riak
- tools/travis-build-and-push-docker.sh
- tools/travis-setup-db.sh
- tools/wait-for-it.sh
- tools/wait_for_riak.sh
* dockerhub integration:
* build and upload docker image to https://hub.docker.com/r/mongooseim/mongooseim/
* used Dockerfile from michalwski/mongooseim-docker
* upload tar.gz file to Github's release (when building a tag)
> DockerHub and Github's releases integration

- apps/ejabberd/src/mongoose_metrics.erl
- apps/ejabberd/test/ejabberd_sm_SUITE.erl
- apps/ejabberd/test/mongooseim_metrics_SUITE.erl
- doc/operation-and-maintenance/Logging-&-monitoring.md
- rebar.config
- rel/reltool.config.script
Change to a newer version of exometer. No real change.
> upped exometer to 1.2

- doc/operation-and-maintenance/Logging-&-monitoring.md
- rebar.config
- rel/files/app.config
- rel/reltool.config.script
This PR addresses https://github.com/esl/MongooseIM/issues/604
* Added syslog_backend dependency to _rebar.config_
* Added syslog and lager_syslog apps to _reltool.config.script_
* Added commented syslog_backend config line to _app.config_ file
> Added lager_syslog backend

- CHANGELOG.md
> [skip ci] minor fixes

- .travis.yml
- apps/ejabberd/src/ejabberd_auth_anonymous.erl
- apps/ejabberd/src/ejabberd_auth_external.erl
- apps/ejabberd/src/ejabberd_auth_http.erl
- apps/ejabberd/src/ejabberd_auth_internal.erl
- apps/ejabberd/src/ejabberd_auth_ldap.erl
- apps/ejabberd/src/ejabberd_auth_odbc.erl
- apps/ejabberd/src/ejabberd_auth_riak.erl
- apps/ejabberd/src/ejabberd_gen_auth.erl
- apps/ejabberd/test/auth_external_SUITE.erl
- apps/ejabberd/test/auth_external_SUITE_data/sample_external_auth.py
- rel/files/sample_external_auth.py
- test/ejabberd_tests/test.config
- test/ejabberd_tests/tests/connect_SUITE.erl
- test/ejabberd_tests/tests/ejabberdctl_SUITE.erl
- test/ejabberd_tests/tests/login_SUITE.erl
This PR fixes #694
* move ejabberd_auth_external tests from dedicated job to small tests
* remove not used functions from ejabberd_auth_* modules
> Remove external auth job

- apps/ejabberd/test/xmpp_route_SUITE.erl
> fixed exometer start in xmpp test

- doc/advanced-configuration/Modules.md
- doc/modules/mod_http_notification.md
- mkdocs.yml
> [skip ci] mod_http_notification_doc

- doc/user-guide/Features-and-supported-standards.md
* Instant Messaging and Presence: RFC 3921 & RFC 6121
* HTTP(S) long-polling (BOSH)
* Configurable database backends: Riak KV
> [skip ci] some precisions

- doc/user-guide/Get-to-know-MongooseIM.md
Some precisions on specific features, some phrasing and expressions, also Wombat and megaLOAD.
> [skip ci] Get-to-know-MongooseIM review

- doc/advanced-configuration/database-backends-configuration.md
database-backends-configuration review:
* some wording
* sectionning
> [skip ci] database-backends-configuration review

- doc/advanced-configuration/Listener-modules.md
Changes to the documentation:
* Typos, titles, precisions
> [skip ci] Listener-modules review

- doc/advanced-configuration/Modules.md
Changes to the documentation:
* Intro
* Expanded most module descriptions
> [skip ci] Modules review

- doc/advanced-configuration/acl.md
Changes to the documentation:
* Phrasing
* Punctuation
* Formatting
> [skip ci] ACL doc review

- doc/modules/mod_adhoc.md
Changes to the documentation: just some phrasing
> [skip ci] mod_adhoc review

- doc/modules/mod_admin_extra.md
Changes to the documentation: list review
> [skip ci] mod_admin_extra review

- doc/modules/mod_amp.md
> [skip ci] mod_amp review

- doc/modules/mod_bosh.md
Changes to the documentation: formatting, minor text addition
> [skip ci] mod_bosh review

- doc/modules/mod_carboncopy.md
> [skip ci] mod_carboncopy review

- doc/modules/mod_csi.md
Changes to the documentation: link, formatting
> [skip ci] mod_csi review

- doc/modules/mod_disco.md
> [skip ci] mod_disco review

- doc/modules/mod_http_notification.md
Changes to the documentation: formatting, structure
> [skip ci] mod_http_notification review

- doc/modules/mod_keystore.md
Changes to the documentation: structure, formatting
> [skip ci] mod_keystore review

- doc/modules/mod_last.md
> [skip ci] mod_last review

- doc/modules/mod_muc.md
Changes to the documentation: formatting, some more precisions
> [skip ci] mod_muc review

- doc/modules/mod_muc_log.md
Changes to the documentation: formatting, minor precisions
> [skip ci] mod_muc_log review

- doc/modules/mod_offline.md
> [skip ci] mod_offline review

- doc/modules/mod_ping.md
Changes to the documentation: link fix, formatting, precision
> [skip ci] mod_ping review

- doc/modules/mod_privacy.md
Changes to the documentation: precision, formatting
> [skip ci] mod_privacy review

- doc/modules/mod_private.md
> [skip ci] mod_private review

- doc/modules/mod_register.md
Changes to the documentation: precision, formatting
> [skip ci] mod_register review

- doc/modules/mod_revproxy.md
Changes to the documentation: typo, formatting
> [skip ci] mod_revproxy review

- doc/modules/mod_roster.md
> [skip ci] mod_roster review

- doc/modules/mod_mam.md
Changes to the documentation: structure, formatting
> [skip ci] mod_mam review

- doc/modules/mod_shared_roster_ldap.md
> [skip ci] mod_shared_roster_ldap review

- doc/modules/mod_sic.md
> [skip ci] mod_sic review

- doc/modules/mod_stream_management.md
> [skip ci] mod_stream_management review

- doc/modules/mod_time.md
> [skip ci] mod_time review

- doc/modules/mod_vcard.md
Changes to the documentation: formatting, typo
> [skip ci] mod_vcard review

- doc/modules/mod_version.md
> [skip ci] mod_version review

- doc/modules/mod_websockets.md
Changes to the documentation: punctuation
> [skip ci] mod_websockets review

- doc/operation-and-maintenance/Logging-&-monitoring.md
Changes to the documentation: formatting, sectionning, content, ordering
> [skip ci] Logging-&-monitoring review

- doc/operation-and-maintenance/Reloading-configuration-on-a-running-system.md
> [skip ci] Reloading-configuration-on-a-running-system review

- doc/operation-and-maintenance/Mongoose-metrics.md
Changes to the documentation: formatting, typo
> [skip ci] Mongoose-metrics review

- doc/developers-guide/Testing-MongooseIM.md
Changes to the documentation: formatting, phrasing
> [skip ci] Testing-MongooseIM review

- doc/developers-guide/REST-interface-to-metrics.md
Changes to the documentation: typo
> [skip ci] REST-interface-to-metrics review

- doc/developers-guide/Hooks-and-handlers.md
Changes to the documentation: title, author, naming, and minor things (commas, parenthesis, paragraphs)
> [skip ci] Hooks-and-handlers review

- doc/developers-guide/hooks_description.md
Changes to the documentation: intro, list, uppercase
> [skip ci] hooks_description review

- doc/developers-guide/message_routing.md
Changes to the documentation: structure, typo
> [skip ci] message_routing review

- doc/developers-guide/xep_tool.md
Changes to the documentation: structure, titles, links
> [skip ci] xep_tool review

- doc/developers-guide/OpenSSL-and-FIPS.md
Changes to the documentation: punctuation, upper/lower cases
> [skip ci] OpenSSL-and-FIPS review

- doc/operation-and-maintenance/Cluster-configuration-and-node-management.md
Changes to the documentation: formatting, precisions
> [skip ci] Cluster-configuration-and-node-management review

- doc/user-guide/Getting-started.md
Added install from DMG, reviewed sections, moved command line
> [skip ci] Getting started review

- test/ejabberd_tests/tests/muc_light_SUITE.erl
This PR addresses https://github.com/esl/MongooseIM/pull/841#discussion_r66929343
* removed code duplication in four test cases
> Muc light disco#items test refactored

- apps/ejabberd/src/mod_privacy_odbc.erl
- rel/reltool_vars/node3_vars.config
- test/ejabberd_tests/default.spec
- test/ejabberd_tests/tests/mod_blocking_SUITE.erl
Parallelised, added to default.spec
> Blocking commands - tests

- doc/developers-guide/hooks_description.md
- doc/developers-guide/message_routing.md
- doc/operation-and-maintenance/Logging-&-monitoring.md
> Improved documentation on hooks

- .travis.yml
As for now, the cassandra job on travis doesn't bring any value as the cassandra integretion is not finished yet.
> remove cassandra job on travis

- apps/ejabberd/src/mongoose_api_xml.erl
> fix for issue #852

- doc/advanced-configuration/database-backends-configuration.md
* `Choosing a database for MongooseIM` section in `database-backends-configuration.md`
> docs on databases

- doc/developers-guide/Testing-MongooseIM.md
- test/ejabberd_tests/README.md
This PR updates testing documentation.
* No functional changes
* No new or updated tests
* Changes to documentation:
* Clarify state of ejabberd_tests;
* Delete references to files deleted time ago;
* Detail nodes - node3 and fed1. Without those nodes running, the respective test suites are skipped as the respective init fail.
> Review developers' testing documents

- apps/ejabberd/include/jlib.hrl
- apps/ejabberd/src/ejabberd_c2s.erl
This PR performs some refactoring, addressing no tracked issue.
* No functionality changes
* No new or updated tests
* No changes to the documentation
> Delete bin macros - redundant since all macros became bins (2f3f98c)

- apps/ejabberd/include/mongoose_api.hrl
- apps/ejabberd/src/ejabberd_app.erl
- apps/ejabberd/src/mongoose_admin.erl
- apps/ejabberd/src/mongoose_api_admin.erl
- apps/ejabberd/src/mongoose_api_client.erl
- apps/ejabberd/src/mongoose_api_common.erl
- apps/ejabberd/src/mongoose_commands.erl
- apps/ejabberd/test/commands_SUITE.erl
- apps/ejabberd/test/commands_backend_SUITE.erl
- apps/ejabberd/test/mongoose_api_common_SUITE.erl
- test/ejabberd_tests/tests/rest_SUITE.erl
- test/ejabberd_tests/tests/rest_helper.erl
This PR focuses only on the REST API for backend services. The main change is the URL generator which now creates shorter and nicer URLs.
> REST shorter prettier

- apps/ejabberd/src/mod_muc_light.erl
- apps/ejabberd/src/mod_muc_light_admin.erl
- rel/files/ejabberd.cfg
- test/ejabberd_tests/default.spec
- test/ejabberd_tests/tests/muc_light_http_api_SUITE.erl
This PR introduces source and tests for the MUC Light HTTP Administration API MVP.
> Finalise MUC Light HTTP API

- apps/ejabberd/src/mod_muc_admin.erl
- apps/ejabberd/src/mod_muc_light_admin.erl
- apps/ejabberd/src/mongoose_admin.erl
- apps/ejabberd/src/mongoose_api_admin.erl
- apps/ejabberd/src/mongoose_api_common.erl
- apps/ejabberd/src/mongoose_commands.erl
- apps/ejabberd/test/commands_SUITE.erl
- apps/ejabberd/test/commands_backend_SUITE.erl
- apps/ejabberd/test/mongoose_api_common_SUITE.erl
* mongoose_command's category as binary
* mongoose_command's description as binary
* updated relevant modules and tests affected by the change
> Mongoose commands improvements

- apps/ejabberd/src/mod_mongoose_admin.erl
- apps/ejabberd/src/mod_muc_admin.erl
- apps/ejabberd/src/mod_muc_light_admin.erl
- apps/ejabberd/src/mongoose_admin.erl
- apps/ejabberd/src/mongoose_api_admin.erl
- apps/ejabberd/src/mongoose_api_common.erl
- apps/ejabberd/src/mongoose_commands.erl
- apps/ejabberd/test/commands_SUITE.erl
- apps/ejabberd/test/commands_backend_SUITE.erl
- apps/ejabberd/test/mongoose_api_common_SUITE.erl
- rel/files/ejabberd.cfg
- test/ejabberd_tests/tests/rest_SUITE.erl
This PR goes on top of #927
* rename mongoose_admin to mod_mongoose_admin
* changed names of some commands
* refactoring reducing duplicated code
> Mongoose admin improvements

- test/ejabberd_tests/tests/mod_blocking_SUITE.erl
> Delete fresh users in mod_blocking_SUITE

- test/ejabberd_tests/default.spec
- test/ejabberd_tests/tests/mam_helper.erl
- test/ejabberd_tests/tests/rest_SUITE.erl
- test/ejabberd_tests/tests/rest_client_SUITE.erl
- test/ejabberd_tests/tests/rest_helper.erl
This PR goes on top of #928 
* new rest_client_SUITE testing the REST API for clients
* refactored rest_SUITE to share the same code for both rest related suites
* stability improvements of 2 test cases from rest_SUITE causing random failures on travis-ci
> Rest api client

- README.md
This PR adds social media links in the README
> [skip ci] social media links

- apps/ejabberd/src/mod_mam.erl
- apps/ejabberd/src/mod_mongoose_admin.erl
- apps/ejabberd/src/mongoose_api_admin.erl
- apps/ejabberd/src/mongoose_api_client.erl
- apps/ejabberd/src/mongoose_api_common.erl
- apps/ejabberd/src/mongoose_commands.erl
- apps/ejabberd/test/commands_SUITE.erl
- apps/ejabberd/test/commands_backend_SUITE.erl
- test/ejabberd_tests/tests/mam_helper.erl
- test/ejabberd_tests/tests/rest_SUITE.erl
* introduction of overloading commands (defining multiple commands in the same category and action, but varying arity)
* getting archived messages via REST - latest or prior to a specified date
> Commands overloading

- apps/ejabberd/src/mod_muc_admin.erl
- test/ejabberd_tests/tests/muc_helper.erl
- test/ejabberd_tests/tests/muc_http_api_SUITE.erl
This is rebased off-of a recent `master`.
> Introduce HTTP Administration API for Kicking MUC Users 

- apps/ejabberd/src/mongoose_api_client.erl
- doc/http-api/client_swagger.yml
- rel/files/ejabberd.cfg
- test/ejabberd_tests/tests/rest_SUITE.erl
- test/ejabberd_tests/tests/rest_client_SUITE.erl
- test/ejabberd_tests/tests/rest_helper.erl
* updated swagger spec for client API
* improved rest_client_SUITE to test archive pagination
* enforced use of HTTPS in client API handler
* parallelised rest and rest_client suites
> Update swagger spec for client API

- doc/operation-and-maintenance/Cluster-management-considerations.md
- mkdocs.yml
Proposed changes include new doc around cluster design, architecture and management.
> [skip ci] Cluster management considerations

- doc/operation-and-maintenance/Cluster-management-considerations.md
> fix typo (coul -> could)

- doc/README.md
> [skip ci] fix README

- doc/Contributions.md
- doc/README.md
- mkdocs.yml
Our contributions to the ecosystem, including our pieces, and third-party opensource projects
> Ecosystem contributions

- doc/Contributions.md
Our contributions are not limited to software: we also contribute to open standards
> [skip ci] open standards contributions

- apps/ejabberd/src/ejabberd_auth_http.erl
This PR addresses #962 
* Don't send Authorization header if no basic_auth is configured in auth_http
> Don't send empty Authorization header

- tools/summarise-ct-results
- tools/travis-test.sh
The main goal of this PR is to fail small tests if there are some auto skipped test cases, groups or suites.
> Make summary from small tests

- apps/ejabberd/src/ejabberd_listener.erl
Restarting listeners fail sometimes with eaddrinuse reason.
Retry 10 times before failing
> Retry to bind socket

- apps/ejabberd/src/ejabberd_cowboy.erl
- apps/ejabberd/src/mongoose_client_api_rooms.erl
- apps/ejabberd/src/mongoose_client_api_rooms_messages.erl
- doc/http-api/client_swagger.yml
- rel/files/ejabberd.cfg
- test/ejabberd_tests/tests/rest_client_SUITE.erl
* return status 403 when non-participant tries to invite a user
* return status 403 when non-participant tries to read room's archive
* allow to enable compression (for all cowboy endpoints)
> HTTP client API small improvements

- apps/ejabberd/src/mod_muc_room.erl
- doc/http-api/http-administration-api-documentation.md
This PR addresses #986 
* brief description of modules required to enable HTTP Administration API
> Fix http admin doc #986

- tools/travis-helpers.sh
- tools/travis-test.sh
- tools/travis-upload-to-s3.sh
* test logs are organized in directories containing PREST  
* the S3 URL is printed at the beginning of a test
> Improve s3 test archive

- doc/http-api/backend_swagger.yml
Factored out repeating fragments as $refs; updated return codes (204)
> [skip ci] Cleaned up and updated backend swagger doc

- apps/ejabberd/src/mongoose_client_api_rooms.erl
- doc/http-api/client_swagger.yml
- test/ejabberd_tests/tests/rest_client_SUITE.erl
* implemented REST API method to list all rooms user is connected to
* optimized swagger spec
> REST API list my rooms

- tools/rock_changed.sh
Bug in script, failed if there was more then one modified file
> [skip ci] fixed rock script - failed on multiple files

- tools/travis-build-and-push-docker.sh
> Use esl/mongooseim-docker repo to build the docker image

- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_cowboy.erl
- apps/ejabberd/src/ejabberd_sm_mnesia.erl
- apps/ejabberd/src/jlib.erl
- apps/ejabberd/src/mod_bosh.erl
- apps/ejabberd/src/mod_bosh_socket.erl
- apps/ejabberd/src/mod_carboncopy.erl
- apps/ejabberd/src/mod_mam_riak_timed_arch_yz.erl
- apps/ejabberd/src/mod_muc_commands.erl
- apps/ejabberd/src/mod_muc_room.erl
- apps/ejabberd/src/mod_register.erl
- apps/ejabberd/src/mod_revproxy.erl
- apps/ejabberd/src/mod_vcard_mnesia.erl
- apps/ejabberd/src/mod_vcard_riak.erl
- apps/ejabberd/src/mod_websockets.erl
- apps/ejabberd/src/mongoose_api_admin.erl
- apps/ejabberd/src/mongoose_api_client.erl
- apps/ejabberd/src/mongoose_api_common.erl
- apps/ejabberd/src/mongoose_cassandra_worker.erl
- apps/ejabberd/src/mongoose_cluster.erl
- apps/ejabberd/src/mongoose_commands.erl
- apps/ejabberd/src/p1_fsm_old.erl
- dialyzer.mk
- rebar.config
This PR partially addresses #946
* fixed warning about unknown types
* fixed function specs after fixing unknown types
* stop suppressing `no local return` warning
* stop suppressing `unused calls` warning
* stop suppressing `undefined_callbacks`
> Improve dialyzer checks

- doc/operation-and-maintenance/Cluster-management-considerations.md
This PR addresses the need for number
Summary table
> Summary table

- apps/ejabberd/src/mod_commands.erl
- apps/ejabberd/src/mod_muc_commands.erl
- apps/ejabberd/src/mod_muc_light_commands.erl
- apps/ejabberd/src/mongoose_api_admin.erl
- doc/http-api/backend_swagger.yml
- test/ejabberd_tests/tests/muc_http_api_SUITE.erl
- test/ejabberd_tests/tests/muc_light_http_api_SUITE.erl
- test/ejabberd_tests/tests/rest_SUITE.erl
This PR addresses #1041, #1040, #1022
* use `username` when creating a user via REST API
* update swagger spec
> REST API small fixes

- rel/files/sample_external_auth.py
> use /usr/bin/env python2 in sample_auth script

- apps/ejabberd/src/mongoose_metrics_hooks.erl
> Subscribe on correct hook in mongoose_metrics_hooks

- doc/http-api/backend_swagger.yml
- doc/http-api/client_swagger.yml
> Swagger spec improvements

- CONTRIBUTING.md
- Makefile
- elvis.config
- tools/rock_changed.sh
This PR does two things:
- option to check all files which were modified in a branch (run it before making PR)
- adds another variable name regexp, commented for now, which will be required when we install new version of elvis
> Elvis - check branch, new regexp

- apps/ejabberd/include/pubsub.hrl
- apps/ejabberd/src/gen_pubsub_node.erl
- apps/ejabberd/src/mod_pubsub.erl
- apps/ejabberd/src/node_dag.erl
- apps/ejabberd/src/node_flat.erl
- apps/ejabberd/src/node_hometree.erl
- apps/ejabberd/src/node_pep.erl
add boolean config option item_publisher
if set to true publishers of items will be stored with event and
broadcasted along according to
https://xmpp.org/extensions/xep-0060.html#publisher-publish-success-publisher
> Pubsub item publisher

- doc/Contributions.md
This PR updates our contribs page:
* Smack: ISR and BoB
> Contribs update

- doc/user-guide/Features-and-supported-standards.md
* Reorganised XEPs table to XEP-per-row format
* Added PubSub, PEP, Blocking Commands
* Removed irrelevant (i.e. client-side) XEPs
* Updated Compliance Suites entries
> Updated XEP list in docs

- apps/ejabberd/src/mongoose_client_api.erl
- apps/ejabberd/src/mongoose_client_api_messages.erl
- apps/ejabberd/src/mongoose_client_api_rooms.erl
- apps/ejabberd/src/mongoose_client_api_rooms_messages.erl
- apps/ejabberd/src/mongoose_client_api_rooms_users.erl
- apps/ejabberd/src/mongoose_client_api_sse.erl
- doc/http-api/client_swagger.yml
- rebar.config
- rel/files/ejabberd.cfg
- rel/reltool.config.script
- test/ejabberd_tests/rebar.config
- test/ejabberd_tests/tests/rest_client_SUITE.erl
This PR is a PoC for Server Sent Events (SSE).
- sending one-to-one messages over SSE
> SSE for REST API clients

- apps/ejabberd/src/ejabberd_c2s.erl
- test/ejabberd_tests/tests/pep_SUITE.erl
Events sent using PEP should be included in the last stanza handled
counts.
The problem occurs when attempting to connect to mongooseim with
mod_caps/mod_pubsub enabled using the Conversations XMPP client.
The connection fails with a "Policy Violation" error. MongooseIM logs
a policy violation stanza with "h attribute too big".
> XEP-0198: ack pep messages

- apps/ejabberd/src/mongoose_client_api_rooms_messages.erl
- apps/ejabberd/src/mongoose_client_api_sse.erl
- doc/http-api/client_swagger.yml
- test/ejabberd_tests/tests/rest_client_SUITE.erl
Adding group messages to the SSE connection
> Adding SSE for groupchats

- doc/developers-guide/mod_muc_light_developers_guide.md
Distinct ETS table with options has been removed.
> [skip ci] Update MUC Light developer guide

- apps/ejabberd/src/mod_mam_cassandra_arch.erl
- apps/ejabberd/src/mod_mam_muc_cassandra_arch.erl
- apps/ejabberd/src/mongoose_client_api_rooms_messages.erl
- rebar.config
This PR fixes dialyzer warnings introduced to master branch
* uses cqerl from @rslota (there is PR to mainstream, hopefully it will be merged soon)
* removes most warnings re unknown types
> Fix dialyzer warnings

- doc/modules/mod_muc.md
This PR addresses no tracked issue.
* no functionality changes
* no new or updated tests
* a minor fix to the documentation
> Fix link in muc hibernation doc

- .gitignore
- .travis.yml
- apps/ejabberd/include/eldap.hrl
- apps/ejabberd/include/jlib.hrl
- apps/ejabberd/src/adhoc.erl
- apps/ejabberd/src/cyrsasl.erl
- apps/ejabberd/src/cyrsasl_digest.erl
- apps/ejabberd/src/ejabberd_auth_ldap.erl
- apps/ejabberd/src/ejabberd_c2s.erl
- apps/ejabberd/src/ejabberd_c2s.hrl
- apps/ejabberd/src/ejabberd_odbc.erl
- apps/ejabberd/src/ejabberd_s2s_in.erl
- apps/ejabberd/src/ejabberd_service.erl
- apps/ejabberd/src/eldap.erl
- apps/ejabberd/src/mod_adhoc.erl
- apps/ejabberd/src/mod_admin_extra_vcard.erl
- apps/ejabberd/src/mod_bosh_socket.erl
- apps/ejabberd/src/mod_mam_cassandra_arch.erl
- apps/ejabberd/src/mod_mam_muc_cassandra_arch.erl
- apps/ejabberd/src/mod_mam_muc_odbc_async_pool_writer.erl
- apps/ejabberd/src/mod_muc_light_codec_modern.erl
- apps/ejabberd/src/mod_pubsub.erl
- apps/ejabberd/src/mod_revproxy.erl
- apps/ejabberd/src/mod_websockets.erl
- apps/ejabberd/src/mongoose_commands.erl
- apps/ejabberd/src/shaper_srv.erl
- tools/travis-build-and-push-docker.sh
- tools/travis-upload-to-s3.sh
This PR fix some initial bugs related to switch from rebar2 to rebar3.
> Post rebar3 fixes

- doc/Roadmap.md
* detail on push
* Bind 2.0
* SASL 2.0
* Mangostas
* Servers in Elixir
> Slightly updated the roadmap

- .travis.yml
Travis YML file still pointed to old dev nodes paths.
> Fix config and log print in Travis after rebar3-fication

- apps/ejabberd/src/mam_jid.erl
- apps/ejabberd/src/mam_message.erl
- apps/ejabberd/src/mod_bosh.erl
- apps/ejabberd/src/mod_disco.erl
- apps/ejabberd/src/mod_http_notification.erl
- apps/ejabberd/src/mod_http_notification_default.erl
- apps/ejabberd/src/mod_keystore.erl
- apps/ejabberd/src/mod_last.erl
- apps/ejabberd/src/mod_mam.erl
- apps/ejabberd/src/mod_mam_cache_user.erl
- apps/ejabberd/src/mod_mam_meta.erl
- apps/ejabberd/src/mod_mam_muc_cache_user.erl
- apps/ejabberd/src/mod_mam_muc_odbc_arch.erl
- apps/ejabberd/src/mod_mam_odbc_arch.erl
- apps/ejabberd/src/mod_mam_riak_timed_arch_yz.erl
- apps/ejabberd/src/mod_mam_utils.erl
- apps/ejabberd/test/mod_mam_meta_SUITE.erl
This is a second part of rocking `mod_*` with Elvis.
Only one issue will become unresolved for now: `mod_mam_utils` being a god module. I don't think decomposing a module with 50+ functions into smaller ones with ~20 functions is in scope of this PR.
> Rock mod_* - part 2 - mod_disco..mod_mam

- doc/Roadmap.md
> [skip ci] fix bullet points

- .travis.yml
This PR addresses integration with Tide and adds webhook.
> Add test integration with Tide

- apps/ejabberd/src/mod_muc_log.erl
- apps/ejabberd/src/mod_muc_room.erl
mod_muc_room might be calling mod_muc_log:check_access_log at the
same time mod_muc_log process called mod_muc_room:get_room_users.
This commit changes the communication between processes to be
unidirectional.
> Fix deadlock between mod_muc_{room,log}.

- doc/user-guide/Get-to-know-MongooseIM.md
repetition in one sily line of documentation
> [skip ci] removed repetition

- doc/user-guide/release_config.md
> [skip ci] minor fixes to the wording

- doc/user-guide/Getting-started.md
> [skip ci] fix minor typos

- apps/ejabberd/src/mod_offline.erl
- apps/ejabberd/src/mod_offline_mnesia.erl
- apps/ejabberd/src/mod_offline_riak.erl
- apps/ejabberd/src/mod_ping.erl
- apps/ejabberd/src/mod_privacy.erl
- apps/ejabberd/src/mod_privacy_mnesia.erl
- apps/ejabberd/src/mod_privacy_odbc.erl
- apps/ejabberd/src/mod_privacy_riak.erl
- apps/ejabberd/src/mod_private.erl
Elvisification of mods from `mod_offline` to `mod_private` (incl. backends).
> Rock mod_offline..mod_private

- apps/ejabberd/include/mod_muc_light.hrl
- apps/ejabberd/include/mod_muc_room.hrl
- apps/ejabberd/src/mod_muc.erl
- apps/ejabberd/src/mod_muc_iq.erl
- apps/ejabberd/src/mod_muc_light.erl
- apps/ejabberd/src/mod_muc_light_db.erl
- apps/ejabberd/src/mod_muc_light_db_mnesia.erl
- apps/ejabberd/src/mod_muc_light_room.erl
- apps/ejabberd/src/mod_muc_light_utils.erl
- apps/ejabberd/src/mod_muc_log.erl
- apps/ejabberd/src/mod_muc_room.erl
Any comments needed? :) Enjoy reading the diff! :D
> Rock mod_muc*.erl

- apps/ejabberd/src/node_push.erl
This PR is a rebased copy of #1222.
> node_push: ignore cdata content in publish_item/8

- doc/Roadmap.md
Now that we have a clearer vision of 2.1.x because we released 2.1.0-beta1, we can add/remove items with much more confidence
> Honesty update

- apps/ejabberd/src/mod_register.erl
- apps/ejabberd/src/mod_roster.erl
- apps/ejabberd/src/mod_roster_mnesia.erl
- apps/ejabberd/src/mod_roster_odbc.erl
- apps/ejabberd/src/mod_shared_roster_ldap.erl
- apps/ejabberd/src/mod_time.erl
- apps/ejabberd/src/mod_vcard.erl
- apps/ejabberd/src/mod_vcard_ldap.erl
- apps/ejabberd/src/mod_vcard_mnesia.erl
- apps/ejabberd/src/mod_vcard_odbc.erl
- apps/ejabberd/src/mod_version.erl
- apps/ejabberd/src/mod_websockets.erl
- test.disabled/ejabberd_tests/tests/vcard_SUITE.erl
Another song written together with our King of Rock.
> Rock mod_register..mod_websockets

- doc/user-guide/Get-to-know-MongooseIM.md
* Adding REST libs
* Re-org in a table
> Client side

- doc/Differentiators.md
[skip ci]
Just a global review
[skip ci]
> [skip ci] A small update on the differentiators

- apps/ejabberd/src/gen_pubsub_node.erl
- apps/ejabberd/src/gen_pubsub_nodetree.erl
- apps/ejabberd/src/mod_pubsub.erl
- apps/ejabberd/src/node_flat.erl
- apps/ejabberd/src/node_hometree.erl
- apps/ejabberd/src/node_pep.erl
- apps/ejabberd/src/nodetree_dag.erl
- apps/ejabberd/src/nodetree_tree.erl
Publishing Elvis songs and subscribing to Elvis news.
> Rock PubSub

- tools/travis-build-and-push-docker.sh
This PR only updates ref to esl/mongooseim-docker
> Use mongooseim-docker with support for Erlang dist over TLS

- doc/user-guide/Features-and-supported-standards.md
> Add XEP-0357 to Features-and-supported-standards.md

- doc/operation-and-maintenance/Logging-&-monitoring.md
- doc/operation-and-maintenance/Mongoose-metrics.md
- doc/operation-and-maintenance/tls-distribution.md
> [skip ci] operations-and-maintenance

- doc/developers-guide/REST-interface-to-metrics.md
- doc/developers-guide/Testing-MongooseIM.md
> [skip ci] Dev guide review

- doc/developers-guide/Hooks-and-handlers.md
- doc/developers-guide/OpenSSL-and-FIPS.md
- doc/developers-guide/hooks_description.md
- doc/developers-guide/message_routing.md
- doc/developers-guide/mod_amp_developers_guide.md
- doc/developers-guide/mod_muc_light_developers_guide.md
- doc/developers-guide/xep_tool.md
> [skip ci] Dev guide

- doc/user-guide/Getting-started.md
> [skip ci] correct download link

- tools/travis-build-and-push-docker.sh
The new Dockerfile includes installing some standars network
diagnostics tools.
> Update mongooseim-docker reference.

- doc/Roadmap.md
* More friendly text
* More content, some precisions
* Some structure
> [skip ci] simple review

- doc/user-guide/Push-notifications.md
> [skip ci] Hotfix push notifications tutorial doc

- doc/Contributions.md
* Shorter titles so that they fit in readthedocs side menu
* Link to MongoosePush
> [skip ci] Push and titles

- doc/developers-guide/message_routing.md
> [skip ci] stanza routing - formatting

- doc/http-api/backend_swagger.yml
- doc/http-api/client_swagger.yml
- doc/http-api/http-administration-api-documentation.md
> http api doc

- doc/Contributions.md
> [skip ci] MongooseICE/Fennec

- CHANGELOG.md
> Spelling correction.

- doc/Roadmap.md
> [skip ci] re-ordering, links, typos

- test.disabled/ejabberd_tests/rebar.config
- test.disabled/ejabberd_tests/tests/amp_big_SUITE.erl
- test.disabled/ejabberd_tests/tests/bosh_SUITE.erl
- test.disabled/ejabberd_tests/tests/bosh_interleave_reqs.erl
- test.disabled/ejabberd_tests/tests/carboncopy_SUITE.erl
- test.disabled/ejabberd_tests/tests/component_SUITE.erl
- test.disabled/ejabberd_tests/tests/conf_reload_SUITE.erl
- test.disabled/ejabberd_tests/tests/connect_SUITE.erl
- test.disabled/ejabberd_tests/tests/disco_and_caps_SUITE.erl
- test.disabled/ejabberd_tests/tests/ejabberdctl_SUITE.erl
- test.disabled/ejabberd_tests/tests/last_SUITE.erl
- test.disabled/ejabberd_tests/tests/legacy_stream_helper.erl
- test.disabled/ejabberd_tests/tests/login_SUITE.erl
- test.disabled/ejabberd_tests/tests/mam_SUITE.erl
- test.disabled/ejabberd_tests/tests/metrics_c2s_SUITE.erl
- test.disabled/ejabberd_tests/tests/metrics_register_SUITE.erl
- test.disabled/ejabberd_tests/tests/metrics_session_SUITE.erl
- test.disabled/ejabberd_tests/tests/mod_http_notification_SUITE.erl
- test.disabled/ejabberd_tests/tests/mod_ping_SUITE.erl
- test.disabled/ejabberd_tests/tests/muc_SUITE.erl
- test.disabled/ejabberd_tests/tests/oauth_SUITE.erl
- test.disabled/ejabberd_tests/tests/offline_SUITE.erl
- test.disabled/ejabberd_tests/tests/pep_SUITE.erl
- test.disabled/ejabberd_tests/tests/presence_SUITE.erl
- test.disabled/ejabberd_tests/tests/privacy_SUITE.erl
- test.disabled/ejabberd_tests/tests/pubsub_SUITE.erl
- test.disabled/ejabberd_tests/tests/sasl_SUITE.erl
- test.disabled/ejabberd_tests/tests/shared_roster_SUITE.erl
- test.disabled/ejabberd_tests/tests/sm_SUITE.erl
- test.disabled/ejabberd_tests/tests/xep_0352_csi_SUITE.erl
See https://github.com/esl/escalus/pull/145
> Use the 'clean_disconnect' branch of escalus

- doc/developers-guide/Testing-MongooseIM.md
> Fix a typo in docs [skip-ci]

- doc/History.md
Fork, fully independant project, pivot to fullstack messaging platform, platform expansion, IoT and chabots
> [skip ci] Creation of the History file

- apps/ejabberd/include/jlib.hrl
- apps/ejabberd/src/foreign_event/mod_foreign.erl
- apps/ejabberd/src/foreign_event/mod_foreign_http.erl
- snippets.erl
- snippets.sh
- test.disabled/ejabberd_tests/tests/mod_foreign_SUITE.erl
> Foreign event publish pubsub

- apps/ejabberd/src/foreign_event/mod_foreign.erl
- apps/ejabberd/src/foreign_event/mod_foreign_http.erl
- apps/ejabberd/test/mod_foreign_http_SUITE.erl
- test.disabled/ejabberd_tests/tests/mod_foreign_SUITE.erl
> Foreign event improve http

- apps/ejabberd/test/mod_foreign_http_SUITE.erl
Without this commit the tests would fail because of configuration.
> Adjust the Foreign-Event HTTP unit tests to metrics

- apps/ejabberd/src/foreign_event/mod_foreign_http.erl
- apps/ejabberd/test/mod_foreign_http_SUITE.erl
- test.disabled/ejabberd_tests/tests/mod_foreign_SUITE.erl
This commit also introduces some log messages.
> Make the mod_foreign timeout configurable

- doc/Advanced-configuration.md
* Add LDAP documentation section to Advanced Configuration
> Fill LDAP documentation

- mkdocs.yml
The "history" did not appear in the menu...
> [skip ci] forgot menu entry

- doc/Roadmap.md
* intro text review
* In-chat forms = "quick replies"
* IoT details
* Mangosta Laptop
* forgotten components
> [skip ci] Broken formatting

- doc/Roadmap.md
* most feedback integrated
* logical, time-based reordering
* call to action
> [skip ci] forgotten feedback

- apps/ejabberd/src/acl.erl
- apps/ejabberd/src/cyrsasl_oauth.erl
- apps/ejabberd/src/ejabberd_listener.erl
- apps/ejabberd/src/http_upload/mod_http_upload.erl
- apps/ejabberd/src/mod_muc_light_commands.erl
- apps/ejabberd/src/mongoose_api_common.erl
- apps/ejabberd/src/mongoose_client_api_rooms.erl
- doc/http-api/backend_swagger.yml
- doc/http-api/client_swagger.yml
- test.disabled/ejabberd_tests/tests/muc_http_api_SUITE.erl
- test.disabled/ejabberd_tests/tests/muc_light_http_api_SUITE.erl
- test.disabled/ejabberd_tests/tests/rest_client_SUITE.erl
Introduce + test MUC Light room creation w/ what becomes the leading part of a room JID.
Swagger update coming.
> Identifier for create room command

- doc/README.md
- doc/custom.css
- mkdocs.yml
Introduce a custom CSS stylesheet for ReadTheDocs / mkdocs.
> Fine tune MongooseIM logo position

- apps/ejabberd/src/rdbms/mongoose_rdbms.erl
> Fix backoff calculation for RDBMS reconnection.

- doc/modules/mod_push_service_mongoosepush.md
- doc/user-guide/Push-notifications.md
As in the title - minor doc fix.
> Update API version in mod_push related docs

- test.disabled/ejabberd_tests/tests/presence_SUITE.erl
This PR adds new tests to `presence_SUITE` which ensure that unavailable presences are broadcasted to all contacts which user sent directed presences to.
See https://tools.ietf.org/html/rfc6121#section-4.6
> Add tests for directed presence behaviour

- rel/files/ejabberd.cfg
> move {odbc_keepalive_interval, undefined}. in DB section.

- README.md
- doc/README.md
> [skip ci] Wiola's edit

- apps/ejabberd/src/cyrsasl_plain.erl
- test.disabled/ejabberd_tests/tests/login_SUITE.erl
> Fix #1313 issue

- README.md
- doc/README.md
> [skip ci] readme consistency

- apps/ejabberd/src/mod_muc_light.erl
This PR just uses the new ejabberd_hooks functions to add and remove hooks from list.
> reorganise mod_muc_light hooks subscription

- apps/ejabberd/src/ejabberd_auth.erl
- apps/ejabberd/src/ejabberd_auth_external.erl
- apps/ejabberd/src/ejabberd_auth_http.erl
- apps/ejabberd/src/ejabberd_auth_internal.erl
- apps/ejabberd/src/ejabberd_auth_ldap.erl
- apps/ejabberd/src/ejabberd_auth_odbc.erl
- apps/ejabberd/src/ejabberd_auth_riak.erl
This PR addresses 
* Refactoring of ejabberd_auth*.erl modules to allow them to comply with elvis.config specifications.
> Fix the code style issues reported by elvis.

- doc/Roadmap.md
[skip ci] roadmap update with planetary architecture
This PR addresses our roadmap adaptation
* moved 3.0 to 4.0
* moved 3.1 to 4.1
* 3.0 is now RT planetary scale
* 3.1 is now DB planetary scale
* some items moved
* one sentence per line
> [skip ci] planetary architecture

- doc/advanced-configuration/HTTP-authentication-module.md
fix missing underscore in http authentication configuration
> doc: fix missing underscore

- doc/History.md
> Make timeline more obvious with dates

- doc/advanced-configuration/Modules.md
- doc/http-api/backend_swagger.yml
- doc/http-api/http-administration-api-documentation.md
- doc/modules/mod_commands.md
- doc/modules/mod_http_notification.md
Doc for mod_commands, some minor fixes and updates.
> [skip ci] doc updates: mod_commands

- README.md
This PR  is intended to show new feature of Tide - generating load test history.
Questions to be answered:
- is chart looking okay?
- where it should be placed?
- is it clear for both non-technical and technical users?
> [skip ci] [WIP] Add load test history chart to README

- doc/http-api/backend_swagger.yml
> [skip ci] test Swagger

- doc/Roadmap.md
* components headers for better visualisation
* major releases headers by theme, for diagonal readability
* some better phrasings
> [skip ci] readability/visualisation

- apps/ejabberd/src/mod_muc_light_commands.erl
- doc/modules/mod_muc_commands.md
- doc/modules/mod_muc_light_commands.md
Introduce docs for mod_muc_commands and mod_muc_light_commands
> Muc commands docs

- doc/advanced-configuration/Listener-modules.md
> [skip ci] mod cowboy

- doc/modules/mod_push.md
Just the typespecs of callback functions need to be updated, I think
> Update docs for mod_push

- doc/modules/mod_caps.md
This PR creates docs for mod_caps
> Create doc for mod_caps

- doc/modules/mod_aws_sns.md
One of the config options needs to be changed:
token_muc_messages_topic --> muc_messages_topic
because that's how it's fetched module itself
> Update docs for mod_aws_sns

- README.md
- doc/README.md
- mkdocs.yml
How to:
    Build from source code
    Set up MongoosePush
    Set up MongooseICE
> [skip ci] "How to" menu

- doc/modules/mod_carboncopy.md
There was a missing config option
> Update mod_carbon docs

- doc/swagger/index.html
Changed:
* paths
* HTML title element
> [skip ci] Swagger path and title

- README.md
- doc/README.md
* lacked keywords such as "im" or chat" (and "load testing" and "metrics")
* still mentioned Inaka
> [skip ci] intro review

- doc/user-guide/Getting-started.md
> [skip ci] Review and modernize Getting Started doc.

- apps/ejabberd/src/mod_roster.erl
- doc/modules/mod_csi.md
- doc/modules/mod_http_notification.md
- doc/modules/mod_http_upload.md
- doc/modules/mod_last.md
- doc/modules/mod_mam.md
- doc/modules/mod_muc.md
- doc/modules/mod_muc_light.md
- doc/modules/mod_offline.md
- doc/modules/mod_privacy.md
- doc/modules/mod_private.md
- doc/modules/mod_register.md
- doc/modules/mod_roster.md
- doc/modules/mod_vcard.md
- doc/operation-and-maintenance/Mongoose-metrics.md
- doc/rest-api/Metrics-backend.md
> Metrics docs improvement

- doc/user-guide/Push-notifications.md
> [skip ci] Fix typo in mod_push tutorial

- README.md
- doc/README.md
Improved logo CSS and fixed link to platform schema.
> Last-minute README.md fixes for 2.1.0 final

- README.md
- doc/README.md
Time to reveal Tide to the world
> [skip ci] Pointing to Tide

- README.md
This PR addresses no issue.
Proposed changes include fixing references to Tide from README.md
> Update Tide references to https://

- apps/ejabberd/test/mongoose_rdbms_SUITE.erl
To do:
* does_backoff_exceed - check why the time is so big
* does_backoff_increase - why end_per_testcase does not unload everything?
> Implement regression tests

- doc/user-guide/Getting-started.md
- doc/user-guide/How-to-build.md
Added information about ubuntu and CentOS installation
> Updates to getting started guide

- doc/developers-guide/Hooks-and-handlers.md
Changed the example to reflect most recent MongooseIM version.
> [skip ci] Updated hooks and handlers example

- doc/rest-api/Administration-backend_swagger.yml
* unify Swagger page title with markdown page title
* uppercases for initial letter on section headers
> [skip ci] title and uppercases

- doc/developers-guide/Testing-MongooseIM.md
Added a bit more explanation, described small tests, fixed grammar and punctuation.
> reviewed doc about testing

- doc/modules/mod_mam.md
> Add missing comma

- doc/user-guide/How-to-build.md
> Add docs on building from source on macOS (once again)

- doc/advanced-configuration/database-backends-configuration.md
- doc/developers-guide/mod_muc_light_developers_guide.md
- doc/modules/mod_vcard.md
This PR fixes some of the issues noticed in https://github.com/esl/MongooseIM/pull/1580. 
Please take a look at https://github.com/esl/MongooseIM/pull/1586/files#diff-c1b026b7e739fc85db663e958a01a367R40 when reviewing.
> Small documentation fixes

- doc/Advanced-configuration.md
This PR adds documentation on how to configure ODBC connection with TLS.
> ODBC+TLS configuration

- doc/Advanced-configuration.md
- doc/advanced-configuration/database-backends-configuration.md
Only documentation for self signed certificate
> [skip ci] Add Cassandra SSL documentation

- doc/user-guide/Push-notifications.md
> Fix docs missing comma

- src/jid.erl
- src/jlib.erl
Refactor jlib, jid to solve elvis warnings.
> Refactor jlib, jid

- doc/modules/mod_event_pusher_http.md
- doc/modules/mod_event_pusher_sns.md
Add information about keys in url-encoded form for HTTP notifications
Add information about JSON schema for Amazon SNS notifications
> Http sns doc update

- doc/advanced-configuration/database-backends-configuration.md
- priv/mysql.sql
utf8mb4 support for all MySQL tables
Documentation update about required minimum version
> Mysql utf8mb4

- test.disabled/ejabberd_tests/rebar.config
- test.disabled/ejabberd_tests/test.config
- test.disabled/ejabberd_tests/tests/carboncopy_SUITE.erl
- test.disabled/ejabberd_tests/tests/rest_SUITE.erl
Test Escalus story-with-clients-as-list branch i.e. Escalus PR https://github.com/esl/escalus/pull/162
> Use Escalus with new story_with_client_list/3 and removed apply_w_arity_check magic

- .travis.yml
- tools/docker-compose.sh
- tools/travis-test.sh
This PR includes:
- docker-compose inside docker
- printing docker-composing execution time
> Docker compose in docker

- test.disabled/ejabberd_tests/tests/mongoose_helper.erl
- test.disabled/ejabberd_tests/tests/muc_SUITE.erl
This PR addresses #1648 #1646
* New function mongoose_helper:successful_rpc/3
* Calls fixed
> Fix undefined functions

- tools/travis-build-tests.sh
This PR addresses #1674
* Хорошо
> Allow unicode in commit description ¯\_(ツ)_/¯ #1674

- test.disabled/ejabberd_tests/run_common_test.erl
This PR addresses #1677 #1668
* Waiting time is increased
* Travis log prettifying
> Increase cover timeout

- tools/compile_riak_pb.sh
This PR addresses usused and confusing script removal.
Something related to rebar2.
> Remove unused tools/compile_riak_pb.sh

- test.disabled/ejabberd_tests/tests/mod_global_distrib_SUITE.erl
It should be asia_node instead of second time europe_node1
> Change the node name test connects to

- src/bin_to_hex.erl
- src/mod_mam_muc_odbc_arch.erl
- src/mod_mam_odbc_arch.erl
- src/rdbms/mongoose_rdbms.erl
- src/rdbms/mongoose_rdbms_mysql.erl
- src/rdbms/mongoose_rdbms_odbc.erl
- src/rdbms/mongoose_rdbms_pgsql.erl
> Add hex escaping of binaries to MySQL backend.

- src/global_distrib/mod_global_distrib_disco.erl
- src/global_distrib/mod_global_distrib_mapping.erl
- src/global_distrib/mod_global_distrib_outgoing_conns_sup.erl
- src/global_distrib/mod_global_distrib_utils.erl
This PR combines several changes that should eliminate the problem with routing problems between components in Global Distribution setup.
> Fix missing disco replies between components in GD

- src/ejabberd_service.erl
- src/global_distrib/mod_global_distrib_bounce.erl
- src/mod_websockets.erl
This PR introduces more debug logs that will hopefully allow to debug one of heisenbugs in DG.
> Extend debug logs in ejd_service and mod_websockets

- doc/modules/mod_event_pusher_push.md
> Fix mod_event_pusher_push docs #1704 [skip-ci]

- include/ejabberd_c2s.hrl
- rel/fed1.vars.config
- rel/files/ejabberd.cfg
- rel/mim1.vars.config
- rel/mim2.vars.config
- rel/mim3.vars.config
- rel/vars.config.in
- src/cert_utils.erl
- src/cyrsasl.erl
- src/cyrsasl_external.erl
- src/ejabberd.erl
- src/ejabberd_auth_pki.erl
- src/ejabberd_c2s.erl
- src/ejabberd_receiver.erl
- src/ejabberd_s2s_in.erl
- src/ejabberd_socket.erl
- src/ejabberd_tls.erl
- src/just_tls.erl
- test.disabled/ejabberd_tests/tests/connect_SUITE.erl
- test/auth_jwt_SUITE.erl
initial implementation of SASL EXTERNAL
> Initial implementation

- tools/start-nodes.sh
- tools/travis-common-vars.sh
- tools/travis-test.sh
Split start and started steps when in travis-test
> Put node starting code into a separate script

- .travis.yml
- doc/developers-guide/Testing-MongooseIM.md
- tools/travis-build-and-push-docker.sh
- tools/travis-helpers.sh
- tools/travis-prepare-log-dir.sh
- tools/travis-secure-erase.sh
- tools/travis-test.sh
- tools/travis-upload-to-gdrive.sh
- tools/travis-upload-to-s3.sh
Refactoring also allows uploading to own S3 bucket.
> Allow uploading test reports to Google Drive.

- src/mod_auth_token.erl
The hook was not adjusted after hooks refactoring.
> Fix token cleanup on remove_user hook.

- test.disabled/ejabberd_tests/rebar.config
~~This PR is to only check if esl/escalus#168 works with current tests.~~
This PR updates escalus version to `aa77ba506fd46cf2bf9a0ac3639bc2ed6e1a8173` (most recent master version with timeout PR merged)
Waiting for final Travis build.
> Try escalus with 5s stanza wait timeout

- src/mam_iq.erl
- src/mod_mam.erl
- src/mod_mam_muc.erl
- src/mod_mam_utils.erl
- test.disabled/ejabberd_tests/test.config
- test.disabled/ejabberd_tests/tests/mam_SUITE.erl
- test.disabled/ejabberd_tests/tests/mam_helper.erl
- test.disabled/ejabberd_tests/tests/mam_helper.hrl
> Fix complete attribute calculation for backward pagination in MAM

- doc/rest-api/Administration-backend_swagger.yml
- test.disabled/ejabberd_tests/tests/muc_light_http_api_SUITE.erl
This PR addresses https://github.com/esl/MongooseIM/issues/1741
It wasn't tested before so lets see what might fail.
If so, all the fixes will be introduced in this PR
> Test http admin + muc light odbc backend

- rebar.config
- rebar.lock
The latest release includes useful changes, like support for recent MariaDB versions.
> Bump MySQL database driver version

- big_tests/tests/oauth_SUITE.erl
- rebar.config
- rebar.lock
- src/mongoose_api_format.erl
- test/acc_SUITE.erl
> Update exml to rapidxml based version.

- doc/advanced-configuration/Modules.md
- doc/modules/mod_jingle_sip.md
- src/jingle_sip/jingle_sip_callbacks.erl
- src/jingle_sip/jingle_sip_helper.erl
- src/jingle_sip/jingle_to_sdp.erl
- src/jingle_sip/mod_jingle_sip.erl
- src/jingle_sip/mod_jingle_sip_backend.erl
- src/jingle_sip/sip_to_jingle.erl
Also:
Add module into a module list
Remove Erlang/OTP 20 from prerequisites
> Add copyright and author notices for mod_jingle_sip

- doc/user-guide/How-to-build.md
This PR addresses updates this page with current dependencies.
> [skip ci] Update "How to build" page

- src/mongoose_rabbit_worker.erl
> [clt-rabbit] Fix closing Rabbit connection

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
- src/event_pusher/mod_event_pusher_rabbit.erl
- src/mongoose_rabbit_worker.erl
> [clt-rabbit] Fix presence handling

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
- src/mongoose_rabbit_worker.erl
> [clt-rabbit] Fix routing key

- doc/advanced-configuration/Listener-modules.md
- src/ejabberd_listener.erl
- src/mongoose_tcp_listener.erl
- src/mongoose_udp_listener.erl
- test/ejabberd_listener_SUITE.erl
> Add configurable number of acceptors for listeners.

- big_tests/tests/mam_SUITE.erl
- big_tests/tests/mam_helper.erl
- doc/modules/mod_mam.md
- include/mongoose_ns.hrl
- rel/files/ejabberd.cfg
- src/ejabberd_gen_mam_archive.erl
- src/mam_iq.erl
- src/mod_mam.erl
- src/mod_mam_cassandra_arch.erl
- src/mod_mam_meta.erl
- src/mod_mam_muc.erl
- src/mod_mam_odbc_arch.erl
- src/mod_mam_odbc_async_pool_writer.erl
- src/mod_mam_params.erl
- src/mod_mam_riak_timed_arch_yz.erl
- src/mod_mam_utils.erl
- src/mongoose_metrics.erl
- src/mongoose_metrics_mam_hooks.erl
- test/mod_mam_meta_SUITE.erl
This PR removes support for MAM 0.2. For now only obvious cases has been removed, non-obvious ones still needs to be found and removed.
> [WIP] Remove MAM 0.2

- src/mongoose_rabbit_worker.erl
Closes the first point from esl/tide#418.
> [clt-rabbit] Connect to Rabbit asynchronously

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
- src/event_pusher/mod_event_pusher_rabbit.erl
- src/mongoose_rabbit_worker.erl
> [clt-rabbit] Handle chat messages

- tools/travis-upload-to-s3.sh
aws-s3-sync: 180 seconds
aws-s3-copy: 100 seconds
s3-parallel-put: 27 seconds
> Use s3-parallel-put instead of aws-s3-sync

- .travis.yml
This PR addresses "Travis takes forever"
- skipping some steps
- upload logs only on error - reverted for now
> Skip install steps for pkg preset

- src/mongoose_rabbit_worker.erl
Closes the last point from esl/tide#418.
> [clt-rabbit] Clear docs

- tools/db_configs/cassandra/proxy/zazkia-routes.json
- tools/db_configs/mysql/mysql.cnf
- tools/travis-setup-db.sh
This PR should improve disk IO for our databases on Travis.
* Data outside of a container
* Relax ACID for MySQL on Travis
> Data on volume

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
- src/event_pusher/mod_event_pusher_rabbit.erl
- src/mongoose_rabbit_worker.erl
> [clt-rabbit] Handle group chat messages

- src/event_pusher/mod_event_pusher_rabbit.erl
> [clt-rabbit] Fix a typo

- src/mod_mam_odbc_prefs.erl
The old way of matching abortion type is error-prone.
Basically, we changed `{aborted, Reason}` to `{aborted, #{reason=>Reason, sql_query => ....}` and it broke the logic.
So, let's not much on Reason.
> Fix database deadlock handling in mod_mam_odbc_prefs

- doc/advanced-configuration/Modules.md
- doc/modules/mod_event_pusher_rabbit.md
> [clt-rabbit] Add documentation for mod_event_pusher Rabbit backend

- src/eldap_pool.erl
This PR addresses failing ldap builds
> Fix ldap with port changed

- big_tests/rebar.config
- big_tests/rebar.lock
- Log more detailed error in escalus_fresh:clean
- This PR https://github.com/esl/escalus/pull/180
> Use escalus c761b6068c4cbda18b58deaa87748df24c16c576

- .travis.yml
- Makefile
> remove 'make dev' as duplication of 'make devrel'

- big_tests/run_common_test.erl
- tools/travis-publish-github-comment.sh
Write /tmp/ct_stats_vars in run_common_test
Handle nothing-to-remove case in remove_ct_log_links
This PR extends #1916 with test stats counters
> Add stats into github comment

- big_tests/tests/metrics_helper.erl
- big_tests/tests/metrics_register_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- src/mod_register.erl
This test has been failing randomly. We now wait longer after each checking of metric value.
> Increase wait time continuously

- big_tests/tests/sm_SUITE.erl
Ack presence from previous session
This PR addresses https://github.com/esl/MongooseIM/pull/1874
* seems that the additional presence was an unacked stanza from previous session.
> stabilise sm_SUITE

- src/mongoose_rabbit_worker.erl
> [clt-rabbit] Change metrics names

- load_test/amoc_scenarios/xmpp_amqp.erl
> Clt rabbit update amqp scenario

- doc/modules/mod_mam.md
This PR improves the explanation around MAM async workers.
> Language refactor of MAM async worker description

- big_tests/rebar.config
- big_tests/rebar.lock
This PR uses new escalus version. https://github.com/esl/escalus/pull/182
> Use escalus with new cleanup system

- test/ejabberd_loglevel_SUITE.erl
This reverts commit 53cb243fbd7e234c536ddc3acb7a634b16a144a1 and fixes the suite for Erlang/OTP 21 in other way.
The current fix sets the default loglevel for Erlang's built-in logger to `info` where progress reports are visible.
> Revert "fix ejabberd_logleverl_SUITE"

- test/async_helper.erl
- test/ejabberd_listener_SUITE.erl
* retries in waiting for listeners to be closed in ejabberd_listeners_SUITE
> Fix randomly failing ejabberd_listeners_SUITE

- big_tests/tests/accounts_SUITE.erl
- big_tests/tests/bosh_SUITE.erl
- big_tests/tests/carboncopy_SUITE.erl
- big_tests/tests/mam_SUITE.erl
- big_tests/tests/mam_helper.erl
- big_tests/tests/metrics_c2s_SUITE.erl
- big_tests/tests/metrics_helper.erl
- big_tests/tests/metrics_session_SUITE.erl
- big_tests/tests/mod_global_distrib_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- big_tests/tests/oauth_SUITE.erl
- big_tests/tests/sm_SUITE.erl
replace as many as possible `timer:sleep` with busy waiting in `big_tests`
> Incremental sleep redundancy

- src/ejabberd_router.erl
- src/gen_iq_handler.erl
This PR lowers the log level and improves the message in 2 places which are related mainly to development process. This is based on https://github.com/esl/MongooseIM/pull/1981#issuecomment-405240100
> Improve loglevel and log message for parts related to dev process

- big_tests/tests/mongoose_helper.erl
> Use the same machanism as for other backends to check state after SUITE

- doc/developers-guide/Basic-iq-handler.md
- mkdocs.yml
> [skip ci] Add basic IQ handler tutorial

- big_tests/tests/inbox_SUITE.erl
- big_tests/tests/inbox_helper.erl
- doc/modules/mod_inbox.md
- src/inbox/mod_inbox.erl
- src/inbox/mod_inbox_odbc.erl
> Inbox conversation hidden read

- big_tests/tests/muc_light_SUITE.erl
- big_tests/tests/muc_light_helper.erl
- big_tests/tests/muc_light_legacy_SUITE.erl
- big_tests/tests/rest_client_SUITE.erl
- doc/rest-api/Client-frontend_swagger.yml
- rel/files/ejabberd.cfg
- src/mongoose_client_api_rooms.erl
- src/mongoose_client_api_rooms_config.erl
- src/muc_light/mod_muc_light.erl
- src/muc_light/mod_muc_light_commands.erl
- src/muc_light/mod_muc_light_room.erl
Add possibility of changing muc light room configuration through REST API
> Rest api muc light config

- doc/Basic-configuration.md
- doc/Differentiators.md
- doc/user-guide/How-to-build.md
- doc/user-guide/release_config.md
> Technical documentation content review

- doc/Advanced-configuration.md
- doc/user-guide/release_config.md
This PR addresses #2012 and #2019
> Update ODBC and release config examples in docs

- big_tests/tests/inbox_SUITE.erl
- big_tests/tests/inbox_helper.erl
- doc/modules/mod_inbox.md
- include/mod_inbox.hrl
- src/inbox/mod_inbox.erl
Each IQ result stanza in conversation will provide total unread count and active conversation count
> Inbox total count unread

- rebar.config
- rebar.lock
This PR addresses #2040
Once the tests pass, I'll tag exml with 3.0.2 and update this PR.
> Update exml with security fix

- doc/modules/mod_inbox.md
Update documentation with explanation of exact meaning of new elements in IQ result.
> [skip ci] Update information of new elements in result IQ

- big_tests/tests/inbox_SUITE.erl
- big_tests/tests/inbox_helper.erl
- doc/modules/mod_inbox.md
- src/inbox/mod_inbox.erl
Add proper error description when invalid inbox form field (value) is sent
> Inbox error description

- big_tests/tests/mod_global_distrib_SUITE.erl
- src/auth/ejabberd_auth_http.erl
- src/event_pusher/mod_event_pusher_push.erl
- src/event_pusher/mod_event_pusher_sns.erl
- src/global_distrib/mod_global_distrib_mapping_redis.erl
- src/mod_push_service_mongoosepush.erl
- src/mongoose_http_client.erl
- src/mongoose_redis.erl
- src/mongoose_riak.erl
- src/mongoose_wpool.erl
- test/auth_external_SUITE.erl
- test/auth_http_SUITE.erl
- test/mod_aws_sns_SUITE.erl
- test/mongoose_wpool_SUITE.erl
> Mongoose wpool abstraction

- big_tests/test.config
- big_tests/tests/mongoose_elasticsearch_SUITE.erl
- doc/advanced-configuration/outgoing-connections.md
- doc/migrations/3.1.1_3.1.1++.md
- src/elasticsearch/mongoose_elasticsearch.erl
- src/mongoose_wpool_elastic.erl
This PR addresses review comment by @fenek https://github.com/esl/MongooseIM/pull/2079#pullrequestreview-157352574
> Make elastic pool more generic :ok_hand:

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
> [clt-rabbit] Improve mod_event_pusher_rabbit test suite

- test/cowboy_SUITE.erl
I started observing some random failures in cowboy_SUITE around checking how many times a handler's function was called. I refactored the code to retry the check if the first attempt fails.
> Stabilise cowboy_SUITE 

- Makefile
- rebar.config
> Add Elvis, and update Makefile for Elvis

- big_tests/tests/mongoose_push_mock.erl
- big_tests/tests/muc_light_helper.erl
- big_tests/tests/push_helper.erl
- big_tests/tests/push_integration_SUITE.erl
- src/event_pusher/mod_event_pusher.erl
- src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
- src/inbox/mod_inbox.erl
- src/inbox/mod_inbox_one2one.erl
- src/inbox/mod_inbox_rdbms.erl
- src/inbox/mod_inbox_rdbms_pgsql.erl
- src/inbox/mod_inbox_utils.erl
- src/rdbms/mongoose_rdbms_pgsql.erl
Show `unread_count` value in push notification (fetch it from inbox and add it to accumulator)
> Inbox push notifications

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
- doc/modules/mod_event_pusher_rabbit.md
- src/event_pusher/mod_event_pusher_rabbit.erl
- src/mongoose_rabbit_worker.erl
Closes esl/tide#490, esl/tide#451.
> [clt-rabbit] Extend mod_event_pusher_rabbit configuration

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
- src/event_pusher/mod_event_pusher_rabbit.erl
- src/mongoose_amqp.erl
- src/mongoose_rabbit_worker.erl
Implements https://github.com/esl/tide/issues/418#issuecomment-432707318.
> [clt-rabbit] Refactor RabbitMQ event pusher backend

- src/auth/ejabberd_auth_external.erl
- src/gen_mod.erl
This PR removes unnecessary TODOs from code
> Remove unnecessary TODOs

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
- doc/advanced-configuration/outgoing-connections.md
- doc/modules/mod_event_pusher_rabbit.md
- mkdocs.yml
- src/event_pusher/mod_event_pusher_rabbit.erl
- src/mongoose_rabbit_worker.erl
- src/wpool/mongoose_wpool_rabbit.erl
- test/mongoose_rabbit_worker_SUITE.erl
Closes the last point from: https://github.com/esl/tide/issues/418#issuecomment-432707318.
> [clt-rabbit] Switch mod_event_pusher_rabbit to mongoose_wpool

- .travis.yml
- src/auth/ejabberd_auth_external.erl
- src/ejabberd_c2s.erl
- src/ejabberd_ctl.erl
- src/jlib.erl
- src/mod_amp.erl
- src/mod_blocking.erl
- src/mod_last.erl
- src/mod_muc.erl
- src/mod_muc_room.erl
- src/mongoose_cluster.erl
- src/muc_light/mod_muc_light.erl
- src/muc_light/mod_muc_light_commands.erl
- src/muc_light/mod_muc_light_room.erl
- src/muc_light/mod_muc_light_utils.erl
- src/rdbms/mongoose_rdbms.erl
- src/sasl/cyrsasl.erl
This PR fixes dialyzer errors on Erlang/OTP 21 and runs the dialyzer job on travis with Erlang/OTP 21.
> Dialyzer 21 fixes

- src/mongoose_rabbit_worker.erl
- src/wpool/mongoose_wpool_rabbit.erl
- test/mongoose_rabbit_worker_SUITE.erl
Closes https://github.com/esl/tide/issues/418#issuecomment-433099338.
> [clt-rabbit] Add overflow prevention mechanism to RMQ worker

- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/mod_pubsub_db_rdbms.erl
- src/pubsub/mod_pubsub_db_rdbms_sql.erl
- src/pubsub/nodetree_tree.erl
This PR adds RDBMS backend for `pubsub_node` table.
> Pubsub node RDBMS backend

- doc/modules/mod_pubsub.md
This PR updates `mod_pubsub`s documentation.
> update mod_pubsub docs to reflect current state [skip ci]

- doc/modules/mod_pubsub.md
This PR updates PubSub RDBMS docs and nodetree_tree's description.
> Post-pubsub-subscription docs update

- test/ejabberd_c2s_SUITE.erl
This PR tests if the `max_fsm_queue` option takes effect and kills the process if its queue is longer then the configured length.
> Add test for max_fsm_queue option of the c2s process

- src/backend_module.erl
Before only function execution time was measured,
there was no information about number of given function calls
which is often as important as the execution time.
> Extend tracked backend functions with count metric

- tools/snippets
This PR updates snippet to register users.
> Update try register user snippets

- doc/modules/mod_pubsub.md
- src/pubsub/mod_pubsub.erl
This PR adds generic metrics measuring count, erros and execution time for different pubsub actions based on sent IQs.
> Introduce overall pubsub metrics

- include/mod_inbox.hrl
- src/inbox/mod_inbox.erl
- src/inbox/mod_inbox_rdbms.erl
- src/inbox/mod_inbox_rdbms_mssql.erl
- src/inbox/mod_inbox_rdbms_mysql.erl
- src/inbox/mod_inbox_rdbms_pgsql.erl
- src/inbox/mod_inbox_utils.erl
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_cache.erl
- src/pubsub/mod_pubsub_cache_mnesia.erl
- src/pubsub/mod_pubsub_cache_rdbms.erl
- src/pubsub/mod_pubsub_db_rdbms.erl
- src/pubsub/mod_pubsub_db_rdbms_sql.erl
- src/rdbms/mongoose_rdbms.erl
- src/rdbms/mongoose_rdbms_odbc.erl
- src/rdbms/rdbms_queries.erl
This PR introduces an upsert helper. It consists of 2 functions:
* prepare_upsert which creates the prepared statement
* execute_upsert which executes the statement with given parameters
> Upsert helper

- src/backend_module.erl
- src/pubsub/mod_pubsub.erl
This PR:
- adds 'mod_pubsub_db_backend:add_item` to tracked functions
- changes tha name of metric responsible for the number of backend function calls
> Pubsub rdbms issues

- big_tests/tests/pubsub_SUITE.erl
- big_tests/tests/pubsub_tools.erl
- doc/modules/mod_pubsub.md
- include/pubsub.hrl
- src/pubsub/mod_pubsub.erl
- src/pubsub/mod_pubsub_db_mnesia.erl
- src/pubsub/nodetree_dag.erl
- src/pubsub/pubsub_index.erl
- test/pubsub_backend_SUITE.erl
This PR addresses "MIM-243 Change Implementation to version 3 - Spawn processes dynamically to perform broadcast."
> Spawn a new process in mod_pubsub:broadcast_stanza/9

- doc/authentication-backends/HTTP-authentication-module.md
> [skip ci] updated http auth documentation

- doc/authentication-backends/PKI-authentication-module.md
- doc/authentication-methods/client-certificate.md
- doc/developers-guide/hooks_description.md
- doc/developers-guide/mod_muc_light_developers_guide.md
- doc/modules/mod_http_upload.md
- doc/modules/mod_last.md
- doc/modules/mod_mam.md
- doc/modules/mod_muc_light.md
- doc/modules/mod_offline.md
- doc/modules/mod_privacy.md
- doc/modules/mod_private.md
- doc/modules/mod_pubsub.md
- doc/modules/mod_roster.md
- doc/modules/mod_vcard.md
- doc/operation-and-maintenance/Mongoose-metrics.md
This PR updates parts of the documentation that has been somehow omitted since 3.2.0 release.
> [skip ci] Update docs for 3.3.0

- big_tests/rebar.config
> Use new Escalus

- doc/developers-guide/hooks_description.md
This PR addresses # 2245
Proposed changes include an update to the documentation on the `user_send_packet` hook.
> [skip ci] Improve user_send_packet hook documentation.

- big_tests/tests/muc_SUITE.erl
- src/mod_muc.erl
This PR fixes the following issue: only online rooms where are listed but offline should be listed too.
> Disco items offline rooms fix

- doc/Erlang-cookie-security.md
- mkdocs.yml
This PR adds a guide on securing a MongooseIM deployment.
> Add cookie security guide

- src/admin_extra/service_admin_extra_gdpr.erl
> Fix string:prefix/2 for OTP < 20

- big_tests/tests/gdpr_SUITE.erl
- src/mam/mod_mam_muc_rdbms_arch.erl
to test changes run:
```
tools/test-runner.sh --preset pgsql_mnesia --one-node --skip-small-tests --skip-cover --skip-stop-nodes  -- gdpr:retrieve_personal_data_mam
```
> MAM MUC GDPR retrieve for RDBMS backend

- big_tests/tests/gdpr_SUITE.erl
- big_tests/tests/mam_helper.erl
- big_tests/tests/mongoose_helper.erl
- src/mam/mod_mam_riak_timed_arch_yz.erl
GDPR retrieval for MAM MUC and MAM PM with riak backend
> Gdpr retrieve mam riak

- big_tests/tests/gdpr_SUITE.erl
- src/mam/ejabberd_gen_mam_archive.erl
- src/mam/mod_mam.erl
- src/mam/mod_mam_cassandra_arch.erl
- src/mam/mod_mam_elasticsearch_arch.erl
- src/mam/mod_mam_meta.erl
- src/mam/mod_mam_muc_cassandra_arch.erl
- src/mam/mod_mam_muc_rdbms_arch.erl
- src/mam/mod_mam_rdbms_arch.erl
- src/mam/mod_mam_riak_timed_arch_yz.erl
- src/mam/mod_mam_utils.erl
- test/mam_jid_mini_SUITE.erl
> Gdpr retrieve mam pm

- big_tests/tests/gdpr_SUITE.erl
- big_tests/tests/mam_SUITE.erl
- big_tests/tests/muc_SUITE.erl
- big_tests/tests/rest_helper.erl
- priv/cassandra.cql
- src/mam/mod_mam_meta.erl
- src/mam/mod_mam_muc_cassandra_arch.erl
- src/mam/mod_mam_rdbms_arch.erl
- test/mod_mam_meta_SUITE.erl
> cassandra schema update

- doc/migrations/3.3.0_3.3.0plus.md
to attach to the test env cassandra you can use the next command:
```
docker run -it --rm -e SSL_CERTFILE=/cacert.pem -v "${PWD}/tools/ssl/ca/cacert.pem:/cacert.pem:ro" --link mongooseim-cassandra:cassandra cassandra:3.9 sh -c 'exec cqlsh "$CASSANDRA_PORT_9042_TCP_ADDR" --ssl'
```
> Cassandra GDPR migration guide.

- doc/advanced-configuration/database-backends-configuration.md
- doc/advanced-configuration/outgoing-connections.md
- doc/developers-guide/Testing-MongooseIM.md
- doc/operation-and-maintenance/known-issues.md
- mkdocs.yml
This PR updates docs with known issues as of release 3.4.0.
> Add known issues for rel 3.4.0 to docs

- big_tests/tests/metrics_api_SUITE.erl
- doc/operation-and-maintenance/Mongoose-metrics.md
- src/mongoose_metrics.erl
- src/mongoose_metrics_definitions.hrl
- test/mongooseim_metrics_SUITE.erl
This PR adds a metric to see the number of TCP connections, together with some small tests and big tests
> New metric: open connections

- doc/advanced-configuration/database-backends-configuration.md
- doc/developers-guide/Testing-MongooseIM.md
- doc/operation-and-maintenance/known-issues.md
- doc/user-guide/How-to-build.md
This PR adds extra details about building MIM from source, testing it and connecting to MSSQL.
> Update "How to build" and MSSQL instructions

- .circleci/config.yml
There is a problem with CircleCI `apt-get` that fails randomly.
This PR introduces the fix for the issue
> Stabilise CircleCI builds

- test/cowboy_SUITE.erl
This is fix for the issue in cowboy described in https://github.com/aleklisi/cowboy_termiante_exit
The cowboy issue created in https://github.com/ninenines/cowboy/issues/1397
> Remove disconnect from client side

- .circleci/config.yml
- .travis.yml
- Makefile
- rebar.config
- tools/build-releases.sh
- tools/test_runner/apply_templates.erl
- tools/test_runner/apply_templates.sh
Before: make devrel 255 secs
After: ./tools/build-releases.sh 52 secs
> Use rsync and template generation to make other dev releases

- doc/advanced-configuration/database-backends-configuration.md
Note sure this is very helpful, as it is repeating:
* Added a list of possible RDBMS
* Added Cassandra and ElasricSearch in persistent data
* Added user data
This PR addresses a way to find relevant info
> Storage backends update

- big_tests/test.config
- big_tests/tests/ldap_helper.erl
- big_tests/tests/sasl_external_SUITE.erl
- big_tests/tests/vcard_SUITE.erl
- doc/Advanced-configuration.md
- doc/advanced-configuration/outgoing-connections.md
- doc/authentication-backends/LDAP-authentication-module.md
- doc/authentication-methods/client-certificate.md
- doc/modules/mod_shared_roster_ldap.md
- doc/modules/mod_vcard.md
- include/eldap.hrl
- rel/files/mongooseim.cfg
- src/auth/ejabberd_auth_ldap.erl
- src/eldap_pool.erl
- src/eldap_utils.erl
- src/mod_shared_roster_ldap.erl
- src/mod_vcard_ldap.erl
- src/mongoose_ldap_worker.erl
- src/sasl/cyrsasl_external.erl
- src/wpool/mongoose_wpool.erl
- src/wpool/mongoose_wpool_ldap.erl
- tools/travis-setup-ldap.sh
- Support SASL EXTERNAL with checking if the user exists in LDAP.
- Configure and maintain LDAP connections like other outgoing connections.
- Support TLS in LDAP connections.
- Allow anonymous authentication for LDAP connections.
> Improve LDAP connections

- .circleci/config.yml
This PR addresses small fix for CircleCI introduced in this PR:
https://github.com/esl/MongooseIM/pull/2417
> Don't compile tests twice [fix for CircleCI]

- big_tests/tests/sm_SUITE.erl
- src/ejabberd_c2s.erl
This PR addresses CI failure.
* prototype for ejabberd_c2s:get_info/1 function (would be something similar to erlang:process_info/2, but would return maps)
* currently, ejabberd_c2s:get_info/1 is very simple
* Wait for SM buffer to drop from 2 to 1 in our test.
That CI error with two initial presences instead of one:
```erlang
{{assertion_failed,assert_many,true,
[is_presence,#Fun<sm_SUITE.16.84098895>],
[{xmlel,<<"presence">>,
[{<<"from">>,
<<"alicE54.96561@localhost/escalus-default-resource">>},
{<<"to">>,
<<"alice54.96561@localhost/escalus-default-resource">>},
{<<"xml:lang">>,<<"en">>}],
[]},
{xmlel,<<"presence">>,
[{<<"from">>,
<<"alicE54.96561@localhost/escalus-default-resource">>},
{<<"to">>,
<<"alice54.96561@localhost/escalus-default-resource">>}, …
```
> Fix case when two initial presences are received after reconnection in sm:resume_session_state_stop_c2s

- big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
Simple quickfix, seems to be receiving something related to the users entering the room.
> mod_event_pusher_rabbit quickfix

- tools/travis-setup-db.sh
This PR addresses "riak job fails with `closed, disconnected` reason.
And we see in riak logs something about waiting for solr timeout.
* configure riak with longer solr waiting time
* check solr healthcheck
Riak writes in it's crash.log when error:
```erlang
** Generic server yz_solr_proc terminating 
** Last message in was {check_solr,0}
** When Server state == {state,"/var/lib/riak/yz",#Port<0.7609>,8093,8985}
** Reason for termination == 
** "solr didn't start in alloted time"
2019-09-19 13:37:35 =CRASH REPORT====
crasher:
initial call: yz_solr_proc:init/1
pid: <0.521.0>
registered_name: yz_solr_proc
exception exit: {"solr didn't start in alloted time",[{gen_server,terminate,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.e …
```
> Wait for solr to be up

- big_tests/tests/cluster_commands_SUITE.erl
- big_tests/tests/distributed_helper.erl
- src/mongoose_cluster.erl
This PR addresses some errors in cluster command tests.
* we use global transaction for node clustering operations, to ensure that the operations would be serialized (i.e. no two running at the same time).
> Use transactions for mongoose_cluster operations

- big_tests/tests/ejabberdctl_SUITE.erl
Add logging into ejabberdctl_SUITE:dump_and_load
This PR addresses "empty Mnesia (i.e. no tables) would break ejabberdctl_SUITE".
* create passwd table
Similar to https://github.com/esl/MongooseIM/pull/2458 (i.e. another PR with missing passwd table, but expected to exist).
How to reproduce:
- default dev nodes (i.e. loaded before applying preset) would create some tables (i.e. that passwd table because of default internal_mnesia auth module). But if you start nodes with preset ALREADY applied manually, then the case would always failing, assuming you run that suite first (i.e. other suites don't have a chance to create some tables).
> Ensure that Mnesia table exist in ejabberdctl_SUITE before starting test

- .travis.yml
> Stop sending webhook from Travis to Tide

- doc/Advanced-configuration.md
- doc/authentication-backends/Riak-authentication-module.md
- doc/modules/mod_last.md
- doc/modules/mod_mam.md
- doc/modules/mod_offline.md
- doc/modules/mod_privacy.md
- doc/modules/mod_private.md
- doc/modules/mod_roster.md
- doc/modules/mod_vcard.md
- mkdocs.yml
- src/auth/ejabberd_auth_riak.erl
- src/mam/mod_mam_meta.erl
- src/mam/mod_mam_riak_timed_arch_yz.erl
- src/mod_last_riak.erl
- src/mod_offline_riak.erl
- src/mod_privacy_riak.erl
- src/mod_private_riak.erl
- src/mod_roster_riak.erl
- src/mod_vcard_riak.erl
This PR allows to configure bucket names.
* configurations options
* docs
> Configurable riak buckets

- rel/files/mongooseim.cfg
- rel/files/mongooseim.cfg.token-support
- src/mam/ejabberd_gen_mam_archive.erl
- src/mam/mod_mam_muc_cassandra_arch.erl
- src/mam/mod_mam_muc_rdbms_arch.erl
- src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
- test/cowboy_SUITE_data/mongooseim.onlyhttp.cfg
- test/cowboy_SUITE_data/mongooseim.onlyws.cfg
- test/ejabberd_config_SUITE_data/mongooseim.default.cfg
- test/ejabberd_config_SUITE_data/mongooseim.no_listeners.cfg
- test/ejabberd_config_SUITE_data/mongooseim.no_listeners.loglevel_err.cfg
- test/ejabberd_config_SUITE_data/mongooseim.no_listeners.node_specific_module_node1_v1.cfg
- test/ejabberd_config_SUITE_data/mongooseim.no_listeners.node_specific_module_node2_v1.cfg
- test/ejabberd_config_SUITE_data/mongooseim.no_listeners.node_specific_node1_v1.cfg
- test/ejabberd_config_SUITE_data/mongooseim.no_listeners.node_specific_node1_v2.cfg
- test/ejabberd_config_SUITE_data/mongooseim.no_listeners.node_specific_node2_v1.cfg
- test/ejabberd_config_SUITE_data/mongooseim.no_listeners.node_specific_node2_v2.cfg
- test/ejabberd_config_SUITE_data/mongooseim.split.cfg
- test/ejabberd_config_SUITE_data/mongooseim.with_mod_offline.cfg
- test/ejabberd_config_SUITE_data/mongooseim.with_mod_offline.different_opts.cfg
- test/ejabberd_listener_SUITE_data/mongooseim.alt.cfg
- test/ejabberd_listener_SUITE_data/mongooseim.basic.cfg
- test/revproxy_SUITE_data/mongooseim.norules.cfg
- test/revproxy_SUITE_data/mongooseim.onerule.cfg
> Remove all of the mam_*_purge occurences

- big_tests/tests/login_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- big_tests/tests/sasl_SUITE.erl
- big_tests/tests/sasl_external_SUITE.erl
- src/auth/ejabberd_auth.erl
- src/auth/ejabberd_auth_anonymous.erl
- src/auth/ejabberd_auth_dummy.erl
- src/auth/ejabberd_auth_external.erl
- src/auth/ejabberd_auth_http.erl
- src/auth/ejabberd_auth_internal.erl
- src/auth/ejabberd_auth_jwt.erl
- src/auth/ejabberd_auth_ldap.erl
- src/auth/ejabberd_auth_pki.erl
- src/auth/ejabberd_auth_rdbms.erl
- src/auth/ejabberd_auth_riak.erl
- src/auth/ejabberd_gen_auth.erl
- src/ejabberd_app.erl
- src/mongoose_fips.erl
- src/sasl/cyrsasl.erl
- src/sasl/cyrsasl_anonymous.erl
- src/sasl/cyrsasl_digest.erl
- src/sasl/cyrsasl_external.erl
- src/sasl/cyrsasl_oauth.erl
- src/sasl/cyrsasl_plain.erl
- src/sasl/cyrsasl_scram.erl
- test/auth_external_SUITE.erl
- test/auth_http_SUITE.erl
- test/auth_jwt_SUITE.erl
- Support different configuration SASL mechanisms for each hosts.
- Simplify the implementation of listing supported SASL mechanisms.
> Simplify management of SASL mechanisms

- src/ejabberd_c2s.erl
In current implementation, `ejabberd_c2s:send_element/3` receives an accumulator, but it never is the original one. The old one is dropped in `ejabberd_c2s:send_and_maybe_buffer_stanza/3`, and a while later a new one is created in `ejabberd_c2s:send_element_from_server_jid/2`. Trying to trace or profile from `ejabberd_c2s:send_element/3` gives rather unexpected results. This PR fixed the issue by passing the original accumulator on.
> Do not recreate accumulator when sending out a stanza

- big_tests/tests/push_SUITE.erl
- big_tests/tests/push_helper.hrl
- big_tests/tests/push_integration_SUITE.erl
- doc/modules/mod_event_pusher_push.md
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- src/event_pusher/mod_event_pusher_push.erl
- src/event_pusher/mod_event_pusher_push_rdbms.erl
This PR adds RDBMS backend for mod_evet_pusher_push
* Postgres, MySQL and MSSQL schemas
* RDBMS backend implementatino
* Updated tests to use RDBMS backed for push if possible
> Event pusher push RDBMS backend

- big_tests/tests/mod_ping_SUITE.erl
- doc/developers-guide/Hooks-and-handlers.md
- doc/developers-guide/hooks_description.md
- doc/modules/mod_ping.md
- src/metrics/mongoose_metrics_hooks.erl
- src/mod_ping.erl
This is the continuation of https://github.com/esl/MongooseIM/pull/2230.
> Mod ping response metric

- src/jlib.erl
We have our own implementation of base64 coding and encoding in MIM:
`jlib:decode_base64/1` -> https://github.com/esl/MongooseIM/blob/21fa934f9e26bf5107e1b939ba071009d87932f5/src/jlib.erl#L690
`jlib:encode_base64/1` -> https://github.com/esl/MongooseIM/blob/21fa934f9e26bf5107e1b939ba071009d87932f5/src/jlib.erl#L745
But they’re in fact implemented in the standard OTP library in http://erlang.org/doc/man/base64.html.
To add more, I get the implementations as equivalent using proper and several million runs, using properties like these:
```
original_is_inversed() ->
?FORALL(L, binary(), decode_base64(encode_base64(L)) =:= L).
equiv_encode() ->
?FORALL(L, binary(), encode_base64(L) =:= base64:encode(L)).
equiv_decodes_from_test() ->
?FORALL(L, binary(),
decode_base64(encode_base64(L)) =:= …
```
> Resort to standard otp base64 module in jlib

- src/mongoose_client_api_rooms_config.erl
- src/mongoose_client_api_rooms_messages.erl
- src/mongoose_client_api_rooms_users.erl
- src/swagger_docs/mongoose_client_api_rooms_config_doc.erl
- src/swagger_docs/mongoose_client_api_rooms_messages_doc.erl
- src/swagger_docs/mongoose_client_api_rooms_users_doc.erl
Added Swagger for:
```sh
/api/rooms/[:id]/config
/api/rooms/:id/users/[:user]
/api/rooms/[:id]/messages
```
> Added Swagger for rest of rooms REST APIs

- .circleci/config.yml
> Use Erlang/OTP 22.1.8 on CircleCI

- tools/circle-build-and-push-docker.sh
> Use newest mongooseim-docker repo to create docker image

- tools/circle-build-and-push-docker.sh
This PR uses mongooseim-docker which builds docker image where config files are sym-linked from the `/member`
> use esl/mongooseim-docker@77f825a

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- rel/mim1.vars.config
- rel/mim2.vars.config
- rel/mim3.vars.config
- src/system_metrics/mongoose_system_metrics_sender.erl
- src/system_metrics/service_mongoose_system_metrics.erl
This PR provides additional feature to system metrics module.
* CI builds report metrics to separate TrackingID in GA
* CI builds have different default reporting intervals
> CI System Metrics TrackingID

- src/rdbms/mongoose_rdbms.erl
- src/wpool/mongoose_wpool_mgr.erl
This PR addresses issue #2596 by removing logging the connection options.
> Remove logging connection options

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- src/system_metrics/mongoose_system_metrics_collector.erl
> Add statistics collectors

- rebar.config
- rebar.lock
Here we go :smiley: 
Btw, some info about these, for example for GCC: https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html
> Enable optimisations

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- src/ejabberd_loglevel.erl
- src/system_metrics/mongoose_system_metrics_collector.erl
- src/system_metrics/mongoose_system_metrics_file.erl
- src/system_metrics/mongoose_system_metrics_sender.erl
- src/system_metrics/service_mongoose_system_metrics.erl
This PR stores the last sent report to a JSON file.
> Metrics report stored locally

- doc/migrations/3.5.0_3.5.0plus.md
> [skip ci] add cluster ID to migration script

- tools/pkg/platforms/centos7/Dockerfile
- tools/pkg/platforms/centos7/files/build/mongooseim.spec
- tools/pkg/platforms/debian_stretch/Dockerfile
> Use Erlang/OTP 22.1.8 in Docker container building .deb and .rpm

- doc/user-guide/How-to-build.md
> Add openssl dev package to deps install command

- rel/files/mongooseim
- rel/files/mongooseimctl
Bug found and fixed by @DenysGonchar
> Pass args as one parameter to runuser command

- big_tests/tests/mongoose_helper.erl
- big_tests/tests/muc_SUITE.erl
- big_tests/tests/muc_helper.erl
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- src/mod_muc.erl
- src/mod_muc_db_rdbms.erl
This PR continues @janciesla8818's work on the RDBMS backend for muc. His WIP commits were rewritten to reflect a cleaner history, and then my bunch of commits finishing the job follow.
> Muc rdbms backend

- big_tests/tests/mongoose_helper.erl
- big_tests/tests/offline_SUITE.erl
- src/offline/mod_offline.erl
added `store_groupchat_messages` option for mod_offline
> Offline groupchat

- doc/modules/mod_muc.md
Tiny thing that was forgotten 😐
> [skip ci] add rdbms backend to muc docs

- big_tests/tests/push_integration_SUITE.erl
- src/mod_push_service_mongoosepush.erl
> ensure all optional parameters passed properly to MongoosePUSH

- src/mam/mod_mam.erl
- src/mam/mod_mam_elasticsearch_arch.erl
- src/mam/mod_mam_muc.erl
- src/mam/mod_mam_muc_cache_user.erl
- src/mam/mod_mam_muc_elasticsearch_arch.erl
- src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
- src/mam/mod_mam_rdbms_async_pool_writer.erl
- src/mam/mod_mam_riak_timed_arch_yz.erl
- src/mam/mod_mam_utils.erl
- src/metrics/mongoose_metrics_mam_hooks.erl
- src/mongoose_hooks.erl
> Move hook calls from `mod_mam*` modules to mongoose_hooks

- tools/travis-setup-db.sh
> use mysql 8.0.18

- doc/user-guide/How-to-build.md
@janciesla8818 please look into :)
> Update exported flags in How to compile MIM docs

- big_tests/tests/connect_SUITE.erl
- doc/advanced-configuration/Listener-modules.md
- include/ejabberd_c2s.hrl
- src/ejabberd_c2s.erl
- src/ejabberd_receiver.erl
- src/ejabberd_s2s_out.erl
- src/ejabberd_socket.erl
- src/mongoose_tcp_listener.erl
- test/ejabberd_listener_SUITE.erl
This PR addresses #2630
Proxy protocol is described in [1]
* read the [proxy protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) header if the listener is configured to do so
> Proxy protocol support

- big_tests/tests/mod_ping_SUITE.erl
- include/ejabberd_c2s.hrl
- src/ejabberd_c2s.erl
- src/ejabberd_c2s_info_handler.erl
- src/ejabberd_c2s_state.erl
- src/mod_ping.erl
- src/mongoose_hooks.erl
> Rewrite mod_ping to execute logic in C2S context

- src/sasl/cyrsasl_scram.erl
Code refactoring for the cyrsasl_scram module to improve code quality and reduce amount of nested case statements.
> Refactoring of nested case statements

- src/mongoose_scram.erl
The original way does a lot of list_to_binary(binary_to_list(X)), which
is slow and suffers from allocations. By simply masking on the binary
size, we get some ~5-10% performance improvement in microbenchmarking.
Not a lot, but still a good number. And specially, way more readable.
With `Pass = <<"123456">>, Salt = crypto:strong_rand_bytes(16).` we get:
Old:
()> timer:tc(fun() -> lists:foreach(fun(_) -> scram:hi(Pass, Salt, 4096), ok end, lists:seq(1,1000)), ok end).
{26145858,ok}
New
()> timer:tc(fun() -> lists:foreach(fun(_) -> scram:hi(sha, Pass, Salt, 4096), ok end, lists:seq(1,1000)), ok end).
{22379493,ok}
> SCRAM - Reimplement the masking to a more efficient way

- src/auth/ejabberd_auth.erl
- src/auth/ejabberd_auth_rdbms.erl
Adding multi scram support for rdbms backend.
> Extend scram sha rdbms

- doc/user-guide/Getting-started.md
This PR addresses typo fix in docs.
> Typo fixed.

- doc/user-guide/Bootstrap-Scripts.md
- doc/user-guide/Getting-started.md
- mkdocs.yml
- rebar.config
- rel/files/mongooseimctl
- rel/files/scripts/bootstrap01-hello.sh
- tools/pkg/scripts/smoke_test.sh
* ejabberdctl command and docs
> Add mongooseimctl bootstrap command

- big_tests/test.config
> Disable stanza_log

- doc/user-guide/push-notifications/With-MongoosePush.md
This PR addresses updating MongoosePush guide in MongooseIM documentation.
> Update MongoosePush guide

- src/amp_strategy.erl
Do not call 'ejabberd_sm' twice for the user's sessions as they can change between the calls.
Steps to reproduce:
- enable erlang doctor for all the functions in MongooseIM.
- run a modified `amp_big_SUITE` with each test repeated 50 times in parallel.
Result: `function_clause` in `mod_mam`
Also: fixed and unified indentation.
> Fix a race condition in AMP strategy

- tools/pkg/Dockerfile_deb
- tools/pkg/Dockerfile_rpm
- tools/pkg/scripts/rpm/mongooseim.spec
This PR allows current build scripts to be used for Ubuntu Focal and Centos 8.
> Fix package build scripts

- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
Validate the 'general' options, fix bugs and add missing validators discovered by the tests.
> Test validation for 'general' section

- src/config/mongoose_config_parser_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/mongooseim-pgsql.cfg
- test/config_parser_SUITE_data/mongooseim-pgsql.toml
* Fixed mod_websockets options parsing
> Fix mod_websockets

- big_tests/tests/sasl_external_SUITE.erl
- rel/fed1.vars-toml.config
- rel/files/mongooseim.toml
- rel/mim1.vars-toml.config
- rel/mim2.vars-toml.config
- rel/mim3.vars-toml.config
- rel/reg1.vars-toml.config
- rel/vars-toml.config.in
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- src/ejabberd_cowboy.erl
- src/ejabberd_service.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/miscellaneous.toml
- test/config_parser_SUITE_data/mongooseim-pgsql.toml
Validation of the `listen` section, along with tests.
When testing it became necessary to amend and polish some listener options.
This is the reason for the first commit.
For details, see the commit messages.
> TOML config options validation and testing: listeners

- src/auth/ejabberd_auth_rdbms.erl
This PR fixes scram_passwords functionality for RDBMS backend. Main fix is in line 457 and it's just escaping Username string before writing new password to the database. I was thinking about adding tests for this functionality but it would get non-trivial quite quickly and out way the benefits as it would require adding dirty read to the databases or some other hack. To avoid some of the bugs in the future I improved the specs of the scramming functions.
I tested the functionality locally and was able to scram the passwords properly.
> fix scram_passwords for rdbms

- src/config/mongoose_config_parser_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/modules.cfg
- test/config_parser_SUITE_data/modules.toml
This PR addresses [MIM-1112](https://erlangsolutions.atlassian.net/secure/RapidBoard.jspa?rapidView=3&projectKey=MIM&modal=detail&selectedIssue=MIM-1112).
* Added parsing for all the modules and their options
* Added equivalence test for module options between TOML and CFG
> TOML modules parsing

- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
- Pool scope: make 'global' the default one
- Server options: rework them for more fine-grained validation
> TOML: Validate and test rdbms pool config

- big_tests/test.config
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/miscellaneous.cfg
- test/config_parser_SUITE_data/miscellaneous.toml
- test/config_parser_SUITE_data/mongooseim-pgsql.cfg
- test/config_parser_SUITE_data/mongooseim-pgsql.toml
This PR addresses [MIM-1146](https://erlangsolutions.atlassian.net/secure/RapidBoard.jspa?rapidView=3&projectKey=MIM&modal=detail&selectedIssue=MIM-1146)
> TOML - Add support for last batch of options

- doc/Advanced-configuration.md
- doc/advanced-configuration/general.md
- mkdocs.yml
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- src/ejabberd_sm.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/miscellaneous.cfg
- test/config_parser_SUITE_data/miscellaneous.toml
Document the 'general' section
Functional changes either fixing bugs or simplifying the configuration.
See commit messages for more details and proposed documentation guidelines.
> TOML config documentation: general

- src/ejabberd_s2s_out.erl
- src/logger/mongoose_log_filter.erl
I've been trying out the new structured logging approach and spotted what seem to be some typos in the code, which I've corrected.
> Fix some typos in new structured logging code

- doc/advanced-configuration/Modules.md
- doc/modules/mod_extdisco.md
- doc/user-guide/Features-and-supported-standards.md
- mkdocs.yml
This PR adds documentation for mod_extdisco that is implementing XEP-0215. #2870
> Documentation for mod_extdisco XEP-0215

- src/config/mongoose_config_parser_toml.erl
- test/config_parser_SUITE.erl
Hot-fix for https://app.circleci.com/pipelines/github/esl/MongooseIM/2997/workflows/dc5ba177-30e1-4791-977f-ddd733c2a476/jobs/31517
> Fix parsing of mod_pubsub.max_subscriptions_node

- doc/Advanced-configuration.md
- doc/advanced-configuration/general.md
- doc/advanced-configuration/s2s.md
- mkdocs.yml
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
Document the s2s options.
See the commit messages for details.
> TOML docs: s2s

- doc/operation-and-maintenance/Logging-&-monitoring.md
- doc/operation-and-maintenance/Logging.md
- mkdocs.yml
- priv/filebeat.mongooseim.yml
- rel/files/app.config
- src/ejabberd_admin.erl
- src/logger/mongoose_log_filter.erl
- src/logger/mongoose_logs.erl
> Add "Configuring logging" docs

- doc/advanced-configuration/outgoing-connections.md
- src/config/mongoose_config_parser_toml.erl
> Toml config outgoing pools - reviewed

- doc/Advanced-configuration.md
- doc/advanced-configuration/host_config.md
- doc/migrations/3.7.0_3.7.x.md
- doc/modules/mod_shared_roster_ldap.md
- rel/files/mongooseim
- Make it actually possible to use the 'cfg' format
- Document the new format
- Minor doc cleanup
> TOML config fixes

- doc/Advanced-configuration.md
- doc/developers-guide/logging.md
- doc/modules/mod_global_distrib.md
- doc/user-guide/Getting-started.md
- doc/user-guide/Jingle-SIP-setup.md
Low-hanging fruits for the cfg-to-toml transition in docs
> Minor cfg-to-toml fixes

- doc/developers-guide/logging.md
- doc/operation-and-maintenance/Logging-fields.md
- mkdocs.yml
> [skip ci] Fix logging-fields documentation

- doc/modules/mod_mam.md
Fix for small typos in mod_mam docs.
> fix typos in mod_mam doc

- mkdocs.yml
> Update migration link

- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_spec.erl
- src/config/mongoose_config_utils.erl
- src/config/mongoose_config_validator_toml.erl
This PR adds the declarative spec for the `auth` config section.
See the commit messages for more information.
> TOML declarative config: 'auth' section

- big_tests/test.config
- doc/advanced-configuration/outgoing-connections.md
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_spec.erl
- src/config/mongoose_config_validator_toml.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/mongooseim-pgsql.toml
- test/config_parser_SUITE_data/outgoing_pools.options
- test/config_parser_SUITE_data/outgoing_pools.toml
Declarative spec for the TOML config of the 'outgoing_pools' section.
See the commit messages for details.
> TOML declarative config spec: pools

- doc/custom.css
- mkdocs.yml
> Revert material theme

- src/admin_extra/service_admin_extra.erl
- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_spec.erl
- src/config/mongoose_config_validator_toml.erl
- src/mongoose_service.erl
- src/system_metrics/service_mongoose_system_metrics.erl
- test/config_parser_SUITE.erl
New callback for services:
config_spec/0
> TOML declarative spec for services

- test/json_formatter_SUITE.erl
This PR adds a testcase for fix from #2968  checking if a large log message would crash log formatter. 
[`jiffy:encode`](https://github.com/esl/MongooseIM/blob/master/src/logger/mongoose_json_formatter.erl#L54) return value is `iodata()` which usually is a binary but for large input it's a list of binaries. This resulted in a formatter crash leading to:  #2967
> add testcase: large_event_dont_crash_formatter

- src/config/mongoose_config_parser_toml.erl
- src/config/mongoose_config_spec.erl
- src/config/mongoose_config_validator_toml.erl
- src/mod_sic.erl
- src/mod_time.erl
- test/config_parser_SUITE.erl
> TOML declarative config for `mod_sic` and `mod_time`

- priv/mysql.sql
- src/mam/mod_mam_utils.erl
- src/mod_roster_rdbms.erl
- src/rdbms/mongoose_rdbms.erl
- src/rdbms/rdbms_queries.erl
This PR addresses "prepared queries for mod_roster".
> Prepared queries for mod_roster

- README.md
- doc/advanced-configuration/Modules.md
- doc/index.md
- doc/modules/mod_inbox.md
- doc/modules/mod_mam.md
Add github actions and circleci badges, correct a typo, and a link to the muc_light xep.
> Documentation improvements

- src/mod_last_rdbms.erl
- src/rdbms/rdbms_queries.erl
This PR addresses prepared queries for mod_last.
* Prepared queries
> Prepared queries for mod_last

- src/mod_muc_db_rdbms.erl
> Use prepared queries for MUC legacy - version 2

- src/pubsub/mod_pubsub_cache_rdbms.erl
- src/pubsub/mod_pubsub_db_rdbms.erl
- src/pubsub/mod_pubsub_db_rdbms_sql.erl
- src/rdbms/mongoose_rdbms.erl
My part of work related to `mod_pubsub` and what have I done so far. Once everything is done, I think I'll squash into 1 commit for better readability.
> prepared queries pubsub

- tools/travis-test.sh
This PR addresses "We print reports for the last **successful** run. But not the last executed run".
* Pass to summarise-ct-results directories actually created since the start of the test
> Don't print test summary if CT reports directory is not created

- rebar.config
Very quick update to use the hex package, now that it has been updated :)
> Update rebar3_codecov to use the latest hex package

- README.md
- big_tests/tests/metrics_roster_SUITE.erl
- big_tests/tests/mod_blocking_SUITE.erl
- big_tests/tests/presence_SUITE.erl
- big_tests/tests/privacy_SUITE.erl
- doc/developers-guide/Hooks-and-handlers.md
- src/mam/mod_mam.erl
- src/mam/mod_mam_muc.erl
- src/mongoose_deprecations.erl
I didn't want to make my other PR less readable, but fixed many typos while working on it. Here they are.
> Fix some typos

- tools/travis-setup-db.sh
See https://hub.docker.com/_/microsoft-mssql-server
> Use the new official MSSQL docker image

- .circleci/config.yml
- rel/files/scripts/bootstrap20-template.escript
Test all in OTP 24
Only small_tests, pgsql and ldap in OTP 22 and 23.
> Configure CircleCI matrix

- src/mam/mod_mam.erl
- src/mam/mod_mam_muc.erl
- src/mam/mod_mam_utils.erl
In #3191 I did not correctly passed around the parameters I needed, in order to know how to extend the iq correctly. Sorry, this PR fixes that 😅
> Correctly pass mam_iq parameters to know what to extend

- big_tests/dynamic_domains.spec
- big_tests/tests/domain_removal_SUITE.erl
- big_tests/tests/private_SUITE.erl
- doc/migrations/4.2.0_4.3.0.md
- priv/mssql2012.sql
- priv/mysql.sql
- priv/pg.sql
- rel/files/mongooseimctl
- src/admin_extra/service_admin_extra_private.erl
- src/mod_private.erl
- src/mod_private_mnesia.erl
- src/mod_private_rdbms.erl
- src/mod_private_riak.erl
- src/rdbms/mongoose_rdbms.erl
- tools/open-test-database-shell.sh
- Use HostTypes in mod_private
- introduce server column into rdbms schema
- remove_domain
> Hostypify mod_private

- big_tests/dynamic_domains.spec
- big_tests/tests/accounts_SUITE.erl
- big_tests/tests/mongoose_helper.erl
- rel/mim1.vars-toml.config
- src/mod_register.erl
- src/mongoose_hooks.erl
This PR adds support for dynamic domains in mod_register and adapts the tests.
> Add support for dynamic domains in mod_register

- big_tests/dynamic_domains.spec
- big_tests/tests/xep_0352_csi_SUITE.erl
- src/mod_csi.erl
This PR adds support for dynamic domains in mod_csi and adapts tests.
> Support dynamic domains in mod_csi

- big_tests/tests/domain_removal_SUITE.erl
- src/mod_last.erl
- src/mod_last_mnesia.erl
- src/mod_last_rdbms.erl
- src/mod_last_riak.erl
* Added `remove_domain` callbacks for `mod_last` and `mod_last_rdbms`
* Added test case for `mod_last`
> Implement domain removal in mod_last

- doc/developers-guide/domain_management.md
Document removing domains with RDBMS.
> Add domain removal RDBMS info

- big_tests/test.config
This PR addresses [MIM-1546](https://erlangsolutions.atlassian.net/browse/MIM-1546)
> Revert scope to global for all global distrib redis presets

- Makefile
- tools/ssl/Makefile
> Do not delete dh_params when certs are expired

- doc/modules/mod_mam.md
> Fix list in `mod_mam.md` for mkdocs

- big_tests/tests/domain_removal_SUITE.erl
Fix expecting IQ, but received presence unavailable instead.
That presence is from make_everyone_friends story.
This PR addresses https://circleci-mim-results.s3.eu-central-1.amazonaws.com/branch/master/90803/mysql_redis.24.0.5/big/ct_run.test@724c891523be.2021-11-29_15.45.45/big_tests.tests.domain_removal_SUITE.logs/run.2021-11-29_16.00.22/domain_removal_suite.last_removal.html
* Rewrite code to use one story only
* Fix indention, common, how could it pass code review?
> Fix domain_removal_SUITE:last_removal

- big_tests/tests/carboncopy_SUITE.erl
This PR addresses failing https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3354/91894/odbc_mssql_mnesia.24.0.5/big/ct_run.test%402d6ff89b34ab.2021-12-03_07.47.22/big_tests.tests.carboncopy_SUITE.logs/run.2021-12-03_07.48.10/carboncopy_suite.unavailable_resources_dont_get_carbons.17922.html
probably because of half a second not enough to receive a stanza (we usually use 5 seconds).
* Use double routing to confirm that a stanza not received
> Remove wait from unavailable_resources_dont_get_carbons

- big_tests/tests/mam_helper.erl
Helps with with race conditions when async writer is used
This PR addresses https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3442/93835/odbc_mssql_mnesia.24.0.5/big/ct_run.test@413ae0d0195b.2021-12-10_08.53.16/big_tests.tests.mam_SUITE.logs/run.2021-12-10_08.56.42/mam_suite.init_per_group.82306.html
```
mam_SUITE:init_per_group failed
Reason: {test_case_failed,Respond size is 3, 15 is expected.}
```
* wait for archive size
* check for size of the result from wait_for_stanzas just in case (it could return less than the requested number of messages)
> Use wait_for_archive_size inside send_rsm_messages helper

- big_tests/tests/inbox_SUITE.erl
- big_tests/tests/inbox_extensions_SUITE.erl
- big_tests/tests/inbox_helper.erl
- src/inbox/mod_inbox.erl
- src/inbox/mod_inbox_entries.erl
Issue https://github.com/esl/MongooseIM/issues/3423 solved.
> Adding queryId to archived inbox messages

- doc/modules/mod_muc_light.md
Documenting https://github.com/esl/MongooseIM/pull/3493
> Add documentation for muclight cache affiliations

- big_tests/tests/mod_global_distrib_SUITE.erl
- big_tests/tests/push_integration_SUITE.erl
- big_tests/tests/sm_SUITE.erl
- doc/modules/mod_stream_management.md
- include/ejabberd_c2s.hrl
- src/ejabberd_c2s.erl
- src/stream_management/mod_stream_management.erl
- src/stream_management/mod_stream_management_mnesia.erl
- test/common/config_parser_helper.erl
- test/config_parser_SUITE.erl
- test/config_parser_SUITE_data/modules.toml
- test/mongoose_cleanup_SUITE.erl
Stream management options in a map with defaults.
> Put mod_stream_management config opts in a map

- big_tests/tests/auth_methods_for_c2s_SUITE.erl
- big_tests/tests/mongooseimctl_SUITE.erl
- src/auth/ejabberd_auth.erl
The title says it all. To test the metrics I chose two suites somewhat related.
> Fix metrics for auth backend not being reported

- doc/configuration/acl.md
- doc/migrations/4.2.0_5.0.0.md
> Fix formatting

- src/mam/mod_mam_muc.erl
This same metric exists for 1:1 chats, but not for groupchats, and it is quite useful for devops.
> Add metric parallel to the one for 1:1 chats

- src/auth/ejabberd_auth_jwt.erl
- test/common/config_parser_helper.erl
- test/config_parser_SUITE.erl
This PR addresses #3690
The secret was parsed as a string, but should be a binary instead.
Also: add file check
> Fix the format of JWT secret

- priv/graphql/schemas/admin/domain.gql
- priv/graphql/schemas/admin/gdpr.gql
- priv/graphql/schemas/admin/http_upload.gql
- priv/graphql/schemas/admin/metric.gql
- priv/graphql/schemas/admin/muc.gql
- priv/graphql/schemas/admin/muc_light.gql
- priv/graphql/schemas/admin/private.gql
- priv/graphql/schemas/admin/token.gql
- priv/graphql/schemas/admin/vcard.gql
Check for incorrect or missing admin annotations in GraphQL schemas
> Verified domain admin annotations

- rebar.lock
> Update ref for jwerl

- src/mod_carboncopy.erl
This PR changes all hook handlers in `mod_carboncopy` module to `gen_hook` format.
> Refactored hook handlers in mod_carboncopy

- src/auth/ejabberd_auth.erl
- src/domain/mongoose_domain_api.erl
- src/inbox/mod_inbox.erl
- src/mam/mod_mam_muc_rdbms_arch.erl
- src/mam/mod_mam_rdbms_arch.erl
- src/mongoose_hooks.erl
- src/muc_light/mod_muc_light.erl
- src/muc_light/mod_muc_light_cache.erl
Convert mod_muc_light_cache to gen_hook.
> Convert mod_muc_light_cache to gen_hook

- src/mongoose_hooks.erl
- src/offline/mod_offline.erl
- src/offline/mod_offline_chatmarkers.erl
- src/offline/mod_offline_stub.erl
Convert mod_offline modules to gen_hook
> Convert mod_offline modules to gen_hook

- src/mod_csi.erl
This PR changes all hook handlers in `mod_csi` module to `gen_hook` format.
> Refactored hook handlers in mod_csi

- src/mod_domain_isolation.erl
This PR changes all hook handlers in `mod_domain_isolation` module to `gen_hook` format. Also, I introduced a minor refactor and added missing `spec` for private functions.
> Refactored hook handlers in mod_domain_isolation

- src/mod_muc.erl
This PR changes all hook handlers in `mod_muc` module to `gen_hook` format.
> Refactored hook handlers in mod_muc

- big_tests/tests/graphql_muc_SUITE.erl
- big_tests/tests/graphql_private_SUITE.erl
- big_tests/tests/graphql_token_SUITE.erl
- big_tests/tests/graphql_vcard_SUITE.erl
- big_tests/tests/oauth_SUITE.erl
- src/graphql/admin/mongoose_graphql_token_admin_mutation.erl
- src/graphql/mongoose_graphql_scalar.erl
- src/graphql/user/mongoose_graphql_last_user_mutation.erl
- src/graphql/user/mongoose_graphql_last_user_query.erl
- src/graphql/user/mongoose_graphql_token_user_mutation.erl
- src/mod_auth_token.erl
- src/mod_auth_token_api.erl
- src/vcard/mod_vcard_api.erl
Improve error handling in token
> Improve error handling in token

- doc/developers-guide/Hooks-and-handlers.md
- doc/developers-guide/hooks_description.md
- doc/migrations/5.1.0_6.0.0.md
This PR updates hooks and handlers documentation.
> Document hooks refactor

- big_tests/src/cth_surefire.erl
Handle the case when `end_per_testcase` is not called because the process died.
The bug showed up when testing the `otp-25.2` branch, which failed because OpenSSL was also updated. The failures are expected, but `cth_surefire` crashed, making all subsequent suites fail: https://app.circleci.com/pipelines/github/esl/MongooseIM/9902/workflows/1b0b4209-5168-404b-b7cb-b6703cbb25d3/jobs/158894/steps
The `otp-25.2` branch was rebased onto this PR, and only the expected tests failed, showing that `cth_surefire` is fixed now: https://app.circleci.com/pipelines/github/esl/MongooseIM/9906/workflows/d7feb619-838a-4b9a-b37d-7dba96301f80/jobs/158953/steps
> Fix common test error handling in cth_surefire

- big_tests/Makefile
- big_tests/test.config
- rebar.config
- rel/files/vm.args
The default cookie should be the same as the app name.
> Set cookie to mongooseim

- src/metrics/mongoose_metrics_hooks.erl
Deleting double hooks addition.
> Fixing bug in mongoose_metrics_hooks

- .circleci/template.yml
- rel/files/scripts/bootstrap20-template.escript
- tools/circle-build-and-push-docker.sh
This PR addresses "Some missing features good to have for real-life deploy though Helm."
* See https://github.com/esl/mongooseim-docker/pull/47 to review changes
> Test updated mongooseim-docker repo (better usability and smoke testing)

- big_tests/tests/mim_c2s_SUITE.erl
- src/c2s/mongoose_c2s.erl
Adding the check to ensure correctness of "to" jid.
> Adding function checking the "to" jid

- big_tests/tests/rest_SUITE.erl
This PR addresses [a broken test](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3629/171910/internal_cets.25.3-amd64/big/ct_run.test%409f772c79d7f8.2023-03-31_07.47.48/big_tests.tests.rest_SUITE.logs/run.2023-03-31_07.59.11/rest_suite.session_can_be_kicked.66819.html)
* Because the check operation is async, we need an async way to check. i.e. wait_until or waiting for the c2s pid to die.
> Use eventually check in rest_SUITE:session_can_be_kicked

- README.md
- doc/index.md
Changing status icons at `doc/index.md`
https://github.com/esl/MongooseIM/blob/fix-readme-project-status-rel-6.0/doc/index.md
https://github.com/esl/MongooseIM/blob/fix-readme-project-status-rel-6.0/README.md
> unifying status icons at README.md and doc/index.md

- doc/configuration/database-backends-configuration.md
- doc/configuration/listen.md
Minor updates to docs, see commit messages.
> Require MySQL 8.0 in docs

- big_tests/default.spec
- big_tests/dynamic_domains.spec
- big_tests/tests/graphql_cets_SUITE.erl
- priv/graphql/schemas/admin/admin_schema.gql
- priv/graphql/schemas/admin/cets.gql
- src/ejabberd_sm_cets.erl
- src/graphql/admin/mongoose_graphql_admin_query.erl
- src/graphql/admin/mongoose_graphql_cets_admin_query.erl
- src/graphql/mongoose_graphql.erl
This PR addresses MIM-1881
* Graphql handler
* Tests
> Add GraphQL handler for CETS info

- big_tests/tests/service_mongoose_system_metrics_SUITE.erl
- src/system_metrics/service_mongoose_system_metrics.erl
Adding new Google Analytics 4 instance IDs and secrets.
> Adding new production and CI instance id

- .circleci/config.yml
- .circleci/template.yml
This PR fixes CI workflow for tags. Here's a link to a correctly executed workflow (without docs publishing) for a temporary tag: https://app.circleci.com/pipelines/github/esl/MongooseIM/10770/workflows/5ec395c1-49a5-43d2-9757-fcb27a62c320
> Fix build for tags

- doc/tutorials/Docker-build.md
- doc/tutorials/How-to-build.md
- mkdocs.yml
Adding a tutorial on how to build and run the docker image using the newly added script.
> Adding information about the docker building script to the documentation

- big_tests/tests/mod_http_upload_SUITE.erl
- src/http_upload/mod_http_upload.erl
Updating the version of mod_http_upload
Adding the test to ensure, that filenames with unicode characters are supported.
> Updating mod_http_upload

- .github/workflows/ci.yml
- README.md
- doc/index.md
this PR introduces the following changes:
- Update of badges
- fix for constantly failing package building action.
> Readme update rel 6.1

- src/mod_bosh.erl
- src/mod_caps.erl
- src/mod_disco.erl
- src/mod_ping.erl
- src/mod_time.erl
- src/offline/mod_offline.erl
- src/offline/mod_offline_chatmarkers.erl
- src/pubsub/mod_pubsub.erl
Updating xeps that don't require code change.
> Updating XEPs

- .circleci/template.yml
- rebar.config
> Use rebar3_codecov 0.6.0

- tools/xep_tool/mongooseim.doap.mustache
> Fix typo in link to the repo

- rebar.lock
This PR uprades exometer_report_graphite to the newest version after recent channge: https://github.com/esl/exometer_report_graphite/pull/2
> Upgrade exometer_report_graphite

- big_tests/tests/auth_methods_for_c2s_SUITE.erl
- big_tests/tests/mod_global_distrib_SUITE.erl
- src/mongoose_internal_databases.erl
This PR addresses MIM-2067.
* stop mnesia before running tests
> Fully disable mnesia in tests

- big_tests/tests/mam_SUITE.erl
- src/mam/mod_mam_utils.erl
> Mim 2165 mam bug

- README.md
- doc/index.md
> Fix github actions status badge

- big_tests/default.spec
- big_tests/dynamic_domains.spec
- big_tests/tests/cets_disco_SUITE.erl
- big_tests/tests/graphql_metric_SUITE.erl
- big_tests/tests/instrument_cets_SUITE.erl
- priv/graphql/schemas/admin/metric.gql
- src/graphql/mongoose_graphql_union.erl
- src/metrics/mongoose_metrics_api.erl
- src/metrics/mongoose_metrics_probe_cets.erl
- src/mongoose_cets_discovery.erl
- src/mongoose_instrument_probe_cets.erl
> Add tests for cets instrument

- big_tests/dynamic_domains.config
- big_tests/tests/accounts_SUITE.erl
- big_tests/tests/auth_helper.erl
- big_tests/tests/auth_methods_for_c2s_SUITE.erl
- big_tests/tests/instrument_helper.erl
- src/auth/ejabberd_auth.erl
- test/auth_dummy_SUITE.erl
> Add instrumentation for other auth events

- big_tests/tests/muc_SUITE.erl
This PR addresses some performance issues in muc_SUITE.
- Use meck:new ones in muc_SUITE. Reduces the amount of time waiting for compilation 
- Use 120 seconds timeout to meck/unmeck
> Use meck:new ones in muc_SUITE

- rel/prod.vars-toml.config
Adding instrumentation and prometheus to MongooseIM prod configuration.
> Adding instrumentation and prometheus to prod configuration

- doc/configuration/instrumentation.md
- doc/migrations/6.2.1_x.x.x.md
- src/config/mongoose_config_validator.erl
- src/instrument/mongoose_instrument_log.erl
- test/config_parser_SUITE.erl
Updating instrumentation configuration documentation.
Modifying valid instrumentation log level values, disabling 'none' value.
> Updating documentation

- big_tests/run_common_test.erl
This PR addresses "Fix test-runner coverage report MIM-2340":
* Print the number of ok, skipped and failed to analyse modules 
* Fix paths (use absolute paths when writing html file report) 
* Do not run make_html on CI
> Fix test-runner coverage report MIM-2340

- src/just_tls.erl
Also, don't set `[{fail_if_no_peer_cert, false}]` for client, because this is not a client option.
> Distinguish between client and server opts in just_tls

- include/external_component.hrl
- src/component/mongoose_component.erl
- src/component/mongoose_component_cets.erl
- src/component/mongoose_component_connection.erl
- src/component/mongoose_component_mnesia.erl
- src/domain/mongoose_domain_api.erl
- test/component_reg_SUITE.erl
- test/mongoose_cleanup_SUITE.erl
Addresses the comment at https://github.com/esl/MongooseIM/pull/4452#discussion_r1907184353
> Reimplement adding dynamic domains to components

- priv/graphql/schemas/user/account.gql
- priv/graphql/schemas/user/user_schema.gql
- priv/graphql/wsite/index.html
- src/graphql/mongoose_graphql.erl
- src/graphql/user/mongoose_graphql_account_user_query.erl
* updated graphiql
* removed dummy account query from the user schema.
> Graphql cleanup

- doc/migrations/6.3.1_6.x.y.md
> MIM-2384 Prepare migration proposals after the exml changes from 4.0.0

- src/stream_management/mod_stream_management.erl
This PR includes minor improvements to `mod_stream_management`:
- Improve separation of concerns between functions.
- Remove broken and unnecessary guard.
- Prevent stanzas from being sent to a closed socket in the `resume` state, because they would fail anyway.
- Blocking the stanza looks safe as there are no handlers (or further hooks) executed afterwards.
- It looks better to skip such stanzas in the outgoing c2s instrumentation events, because they are not actually sent anywhere.
> Minor refactoring of mod_stream_management

- big_tests/tests/sm_SUITE.erl
- src/stream_management/mod_stream_management.erl
exclude non-stanza elements from counting.
> Fix SM counting

- big_tests/tests/s2s_SUITE.erl
- src/s2s/mongoose_s2s_in.erl
This PR ensures that an erroneous stream opening tag received during s2s negotiation does not cause a `function_clause` error - both before and after authentication.
There are two main changes, described in detail in the corresponding commits:
- Handle missed error cases during s2s stream negotiation.
- Add tests checking the error conditions.
> Prevent function_clause error in s2s

- big_tests/tests/component_helper.erl
- big_tests/tests/fast_auth_token_SUITE.erl
- doc/configuration/TLS-hardening.md
- doc/configuration/general.md
- doc/configuration/listen.md
- doc/listeners/listen-c2s.md
- doc/listeners/listen-components.md
- doc/listeners/listen-http.md
- doc/listeners/listen-s2s.md
- doc/modules/mod_global_distrib.md
- src/fast_auth_token/mod_fast_auth_token_generic_mech.erl
- src/fast_auth_token/mod_fast_auth_token_rdbms.erl
- src/global_distrib/mod_global_distrib_connection.erl
- src/global_distrib/mod_global_distrib_receiver.erl
- src/global_distrib/mod_global_distrib_transport.erl
- src/mod_websockets.erl
This PR corrects multiple minor issues found during the review of `feature/listeners`:
- Improve documentation.
- Refactor code.
See the commit messages for more information.
> Listeners: minor fixes in docs and refactoring

- big_tests/tests/bosh_SUITE.erl
The instrumentation event `xmpp_element_in` checked in `create_and_terminate_session` was actually NOT emitted in this test, but in the previous ones. This is why the test has become extremely flaky. It wasn't flaky before reworking the XMPP element events, because they used to be emitted by stream opening/ending tags as well.
Solution:
- Simplify event assertions - check them once in `interleave_requests`, where they are all emitted indeed.
- Make sure the asserted events are emitted in the same test by using timestamps.
> Fix flaky test in bosh_SUITE
